.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Provide pull requests and issue templates to standardize project contribution standards.
[#150](https://github.com/dragonflyoss/Dragonfly2/issues/150#issue-867323425)
Standardize project pull request and issue standards.
N/A

Add pull request and issue templates

---

CONTRIBUTING.md
Dragonfly2.iml

- Add `CONTRIBUTING.md`
#158 
Describe the contribution document

Add CONTRIBUTING.md

---

.github/ISSUE_TEMPLATE/custom.md

Create custom issue template.
#167 
N/A

Create custom issue template

---

.github/CODEOWNERS

- Change codeowners from dragonfly team to dragonfly2 team
N/A
N/A

Change codeowners to dragonfly2's maintainers and reviewers

---

manager/apis/v2/main.go
manager/server/router.go

Change manager docs path.
#192 
N/A

Fix manager docs path

---

client/daemon/peer/peertask_base.go
client/daemon/peer/peertask_file.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_stream.go
client/daemon/service/manager.go
client/daemon/transport/transport.go

1. Update tiny peer task span.
2. Add peer id for some logs.
fix #204

daemon: add add additional peer id for some logs

---

pkg/dynconfig/dynconfig_test.go
pkg/idgen/task_id.go
pkg/idgen/task_id_test.go
pkg/util/digestutils/digest.go
scheduler/scheduler/evaluator_factory.go
scheduler/server/scheduler_server.go
scheduler/service/service.go

- Generate sha256 from slice.
- Standardized naming.
#210 
N/A

Refactor idgen pkg

---

Makefile

Detailed test information display

---

cdnsystem/config/cdn.yaml
cdnsystem/config/config.go
cdnsystem/config/constants.go
pkg/rpc/scheduler/client/client.go
scheduler/config/config.go

feature: remove redundant configurations

---

scheduler/manager/cdn_manager.go
scheduler/manager/task_manager.go
scheduler/manager/task_manager_test.go
scheduler/server/scheduler_server.go
scheduler/service/service.go

- Rewrite task manager's functions.
#218 
N/A

Refactor task manager

---

.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yml

- `ci.yaml` remove main-rc branch
- `codeql-analysis.yml` remove main-rc branch
#220

Workflows remove main-rc branch

---

client/clientutil/types.go
client/config/peerhost.go
client/config/peerhost_test.go
client/daemon/storage/storage_manager.go
docs/en/config/dfget-daemon.yaml
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/scheduler/client/client.go

Feature: add disk quota gc for daemon

---

cmd/common/common.go

app start fail due to config file string address is nil
#222

Fix config file nil error

---

cdnsystem/daemon/mgr/task/manager.go

The CDN encountered a deadlock while doing disk garbage collection
#225

Fix deadlock of CDN GC storage 

---

cdnsystem/cdnerrors/errors_test.go
cdnsystem/cdnutil/cdn_util.go
cdnsystem/daemon/mgr/cdn/cache_data_mgr.go
cdnsystem/daemon/mgr/cdn/cache_detector.go
cdnsystem/daemon/mgr/cdn/cache_detector_util.go
cdnsystem/daemon/mgr/cdn/cache_writer.go
cdnsystem/daemon/mgr/cdn/cache_writer_test.go
cdnsystem/daemon/mgr/cdn/cache_writer_util.go
cdnsystem/daemon/mgr/cdn/downloader.go
cdnsystem/daemon/mgr/cdn/manager.go
cdnsystem/daemon/mgr/cdn/reporter.go
cdnsystem/daemon/mgr/cdn/storage/hybrid/shm_switch.go
cdnsystem/daemon/mgr/cdn/storage/path_util.go
cdnsystem/daemon/mgr/cdn_mgr.go
cdnsystem/daemon/mgr/progress/manager.go
cdnsystem/daemon/mgr/progress/manager_util.go
cdnsystem/daemon/mgr/progress_mgr.go
cdnsystem/daemon/mgr/task/manager.go
cdnsystem/daemon/mgr/task/manager_util.go
cdnsystem/daemon/mgr/task_mgr.go
cdnsystem/plugins/plugin_manager.go
cdnsystem/plugins/plugins.go
cdnsystem/plugins/plugins_test.go
cdnsystem/server/server.go
cdnsystem/server/service/cdn_seed_server.go
cdnsystem/source/ossprotocol/oss_source_client.go
cdnsystem/source/source_client_util.go
cdnsystem/storedriver/store.go
cdnsystem/storedriver/store_mgr.go
cdnsystem/storedriver/store_mgr_test.go

refactor CDN subsystem imports more formatter.
#229

Refactor CDN subsystem imports more formatter.

---

pkg/idgen/task_id_test.go

- Change the meta parameter `Md5` to `Digest`.
#242 
N/A

Fix idgen test

---

pkg/cache/cache.go

Fix scheduler test

---

client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_test.go
client/daemon/storage/storage_manager.go

Feature: remove unsafe code in client/daemon/storage

---

docs/en/user-guide/proxy/containerd.md
docs/en/user-guide/proxy/docker.md
docs/en/user-guide/registry/cri-containerd.md
docs/en/user-guide/registry/cri-o.md
pkg/dflog/logcore/init.go
pkg/dflog/logcore/logcore.go

- Fix `cri-containerd.md` and `cri-o.md` document.
- Add `containerd.md` document.
#284

Fix client document

---

go.mod
go.sum
manager/apis/v2/handler/scheduler_cluster.go
manager/apis/v2/types/schema.go
manager/server/server_test.go
manager/server/service/manager_server.go
manager/store/orm/cdn_cluster.go
manager/store/orm/cdn_instance.go
manager/store/orm/orm_store.go
manager/store/orm/scheduler_cluster.go
manager/store/orm/scheduler_instance.go
manager/store/orm/security_domain.go

Signed-off-by: hanson.yj <hanson.yj@alibaba-inc.com>
Refactor mysql table schema, orm json tag.
#282 
- [Y] New feature (non-breaking change which adds functionality)
- [Y] Code compiles correctly.
- [Y] My code follows the code style of this project.
- [Y] I have added tests to cover my changes.
- [Y] All new and existing tests passed.

Refactor mysql table schema, orm json tag.

---

client/dfget/dfget.go

small PR for code optimization.
nil
nil

small PR for code optimization.

---

client/dfget/dfget.go

small PR for code optimization. (#294)

---

client/dfget/dfget.go

Unified error handling style
nil

Unified error handling style

---

deploy/charts/dragonfly/templates/cdn-configmap.yaml
deploy/charts/dragonfly/templates/cdn-deploy.yaml
deploy/charts/dragonfly/templates/cdn-svc.yaml
deploy/charts/dragonfly/templates/dfdaemon-configmap.yaml
deploy/charts/dragonfly/templates/dfdaemon-daemonset.yaml
deploy/charts/dragonfly/templates/scheduler-configmap.yaml
deploy/charts/dragonfly/templates/scheduler-deploy.yaml
deploy/charts/dragonfly/templates/scheduler-svc.yaml
deploy/charts/dragonfly/values.yaml

add installation.namespace config for helm chart
https://github.com/dragonflyoss/Dragonfly2/issues/296
support custom namespace when helm install.

Add installation.namespace config for helm chart

---

Makefile
hack/build.sh

1. Add missing manager build script
2. Update some wrong variant in build.sh
#308

Fix build script

---

.goreleaser.yml
Makefile
build/package/nfpm/dfget.yaml

- Use `NFPM` to publish build packages.
Fixes #312 
Automatically build the release package。

Add goreleaser NFPM

---

api/v2/manager/docs.go
api/v2/manager/swagger.json
api/v2/manager/swagger.yaml

Signed-off-by: hanson.yj <hanson.yj@alibaba-inc.com>

Fix manager api to config from scheduler_config in swagger yaml

---

client/daemon/peer/peertask_base.go
cmd/scheduler/cmd/root.go
pkg/rpc/scheduler/client/client.go

Optimize log and fix some typo

Optimize log and fix some typo

---

.github/workflows/docker.yml

- Add docker image workflow.
Fixes #322 
Automated image building.

Add docker building workflow

---

hack/build.sh

- Remove the git operation in the build script.
Fixes #320 
N/A

Optimize build script

---

cmd/manager/cmd/root.go

Don't ignore any errors. Do you think of. Thanks very much.

Improve error handling

---

CONTRIBUTING.md
Makefile

- Improve `CONTRIBUTING.md`
- Improve `makefile`
Fixes #305 
N/A

Improve CONTRIBUTING.md and makefile

---

.github/workflows/ci.yml

- Increase CI timeout.
Fixes #327 
N/A

Increase CI timeout

---

manager/apis/v2/main.go
manager/server/server.go
manager/server/service/manager_server.go

return error in NewManagerServer func
Tips for more error details when call NewManagerServer func.

return error in NewManagerServer func

---

scheduler/manager/cdn_manager.go

Fix: scheduler panic

---

Makefile
client/config/dfget.go
client/config/dfget_test.go

Fix: infinite recursion in MkDirAll

---

pkg/gc/gc_test.go

Fix GC test

---

client/config/peerhost.go
client/daemon/peerhost.go
client/daemon/peerhost_linux.go
client/daemon/peerhost_stub.go
docs/en/config/dfget.yaml

Feature: support setns in client

---

.goreleaser.yml

Goreleaser added mockgen

---

hack/start-cdn.sh

Change cdn start script

---

scheduler/config/config.go

Fix: update DynconfigOptions typo

---

manager/config/config.go
manager/config/config_test.go
manager/config/testdata/manager.yaml
manager/database/database.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml

- Add scheduler config' `CDNDirPath` attribute test.
- Add manager config test.
Fix #391
N/A

test: manager and scheduler config

---

build/package/nfpm/config/dfget.yaml
client/config/peerhost.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.yaml
cmd/dependency/dependency.go

Update mapsturcture decode and remove unused config

Update mapsturcture decode and remove unused config

---

deploy/kustomize/single-cluster-native/bases/cdn/statefulset.yaml
deploy/kustomize/single-cluster-native/bases/kustomization.yaml
deploy/kustomize/single-cluster-native/bases/namespace.yaml
deploy/kustomize/single-cluster-native/overlays/sample/kustomization.yaml
deploy/kustomize/single-cluster-openkruise/bases/kustomization.yaml
deploy/kustomize/single-cluster-openkruise/bases/namespace.yaml
deploy/kustomize/single-cluster-openkruise/overlays/sample/kustomization.yaml

Update kustomize default namespace and images

Update kustomize default namespace and images

---

deploy/charts/dragonfly/README.md
deploy/charts/dragonfly/templates/cdn/cdn-rabc.yaml
deploy/charts/dragonfly/templates/cdn/cdn-svc.yaml
deploy/charts/dragonfly/templates/namespace.yaml
deploy/charts/dragonfly/templates/scheduler/scheduler-svc.yaml
deploy/charts/dragonfly/values.yaml

Update helm chart images tag to v0.1.0.beta

Update helm chart images tag to v0.1.0.beta

---

deploy/charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
deploy/kustomize/single-cluster-native/bases/kustomization.yaml

Fix wrong daemon config and kubectl image tag

Fix wrong daemon config and kubectl image tag

---

deploy/charts/dragonfly/templates/cdn/cdn-statefulset.yaml
deploy/kustomize/single-cluster-native/bases/cdn/statefulset.yaml
deploy/kustomize/single-cluster-openkruise/bases/cdn/statefulset.yaml

Update cdn init container template

Update cdn init container template

---

deploy/charts/dragonfly/templates/cdn/cdn-statefulset.yaml
deploy/charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
deploy/charts/dragonfly/values.yaml

1. Update dfdaemon proxy port comment.
2. Update static cdn config.

Update helm charts

---

.github/workflows/ci.yml

chore: remove macos ci

---

.github/workflows/docker.yml
deploy/charts/dragonfly/values.yaml
deploy/kustomize/single-cluster-native/bases/dfdaemon/daemonset.yaml
deploy/kustomize/single-cluster-native/bases/kustomization.yaml
deploy/kustomize/single-cluster-native/overlays/sample/kustomization.yaml
deploy/kustomize/single-cluster-openkruise/bases/dfdaemon/daemonset.yaml
deploy/kustomize/single-cluster-openkruise/bases/kustomization.yaml
deploy/kustomize/single-cluster-openkruise/overlays/sample/kustomization.yaml

- Rename docker image dfdaemon.

chore: rename docker image dfdaemon

---

.goreleaser.yml

- remove goreleaser go generate

chore: remove goreleaser go generate

---

deploy/charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
deploy/charts/dragonfly/values.yaml
deploy/kustomize/single-cluster-native/bases/dfdaemon/dfget.yaml
deploy/kustomize/single-cluster-openkruise/bases/dfdaemon/dfget.yaml
docs/en/config/dfget.yaml

Add default filter in proxy for deployment and docs

Add default filter in proxy for deployment and docs

---

client/daemon/peerhost_linux.go

Fix close net namespace fd

---

cdnsystem/daemon/task/manager_util.go
pkg/source/httpprotocol/http_source_client.go
pkg/source/source_client.go

Fix wrong cache task header

---

deploy/charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
deploy/charts/dragonfly/values.yaml

Minimize daemon runtime capabilities.

Feature: minimize daemon runtime capabilities

---

client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_stream_callback.go
client/daemon/proxy/proxy.go
client/daemon/storage/metadata.go

Support reuse tiny peer task

---

client/daemon/peer/peertask_stream.go
client/daemon/proxy/proxy.go
client/daemon/transport/transport.go

Optimize error message for proxy

---

client/daemon/peerhost.go

Export peer.TaskManager for embedding dragonfly in custom binary

---

go.mod
go.sum
pkg/rpc/scheduler/client/client.go

Report peer result when failed to register
#429

Report peer result when failed to register

---

deploy/charts/dragonfly/templates/cdn/cdn-statefulset.yaml
deploy/charts/dragonfly/templates/dfdaemon/dfdaemon-daemonset.yaml
deploy/charts/dragonfly/templates/scheduler/scheduler-statefulset.yaml
deploy/charts/dragonfly/values.yaml

Add pod labels in helm chart

---

.github/workflows/e2e.yml
Makefile
deploy/charts/dragonfly/values.yaml
test/README.md
test/e2e/containerd_test.go
test/e2e/util/exec.go
test/testdata/containerd/config.toml
test/testdata/crictl/config.yaml
test/testdata/kind/config.yaml

Add local e2e kind environment

---

test/e2e/containerd_test.go
test/e2e/dfget_test.go
test/e2e/e2eutil/exec.go
test/testdata/k8s/file-server.yaml

Add e2e dfget test cases

---

manager/model/user.go
manager/service/user.go
manager/types/user.go

fix: manager user typo

---

client/daemon/proxy/proxy_manager.go

Disable proxy when config is empty

Disable proxy when config is empty

---

hack/build.sh
hack/docker-build.sh

Set GOPROXY with default value
Fix:
```
docker-build.sh: line 14: GOPROXY: unbound variable
```

chore: set GOPROXY with default value

---

manager/handlers/user.go
manager/middlewares/jwt.go
manager/model/user.go
manager/server/router.go
manager/service/service.go
manager/service/user.go
manager/types/user.go

feat: optimize jwt

---

deploy/docker-compose/README.md
deploy/docker-compose/config/.gitignore
deploy/docker-compose/config/nginx.conf
deploy/docker-compose/config/scheduler.yaml
deploy/docker-compose/docker-compose.yaml
deploy/docker-compose/run.sh
deploy/docker-compose/template/cdn.template.json
deploy/docker-compose/template/cdn.template.yaml
deploy/docker-compose/template/dfget.template.yaml

Add docker compose for deploying

---

client/config/headers.go
client/config/peerhost.go
client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_test.go
client/daemon/proxy/reverse_proxy.go

Add multiple registry mirrors support

---

scheduler/config/config.go
scheduler/core/events.go
scheduler/core/scheduler_service.go
scheduler/daemon/peer/manager.go
scheduler/server/service/scheduler_server.go

feat: Extract peer event processing function

---

internal/tasks/tasks.go
internal/tasks/tasks_test.go

Add a function SendTask to struct Tasks, which packs the parameters of server.sendTask.

feat: add func to convert args

---

internal/tasks/tasks.go
internal/tasks/tasks_test.go

add test cases for marshal and unmarshal

Add test cases for marshal and unmarshal

---

hack/docker-build.sh

fix: docker-build.sh not GOPROXY var.
issuse: https://github.com/dragonflyoss/Dragonfly2/issues/486

fix:GOPROXY var

---

internal/dflog/logger.go
pkg/rpc/dfdaemon/client/down_result_stream.go
pkg/rpc/scheduler/client/client.go
scheduler/core/evaluator/basic/basic_evaluator.go
scheduler/core/monitor.go
scheduler/core/scheduler/basic/basic_scheduler.go

Add schedule execute detail log
fix #494

Schedule Log

---

scheduler/config/config.go
scheduler/core/events.go
scheduler/core/monitor.go
scheduler/types/peer.go

Fix scheduler pick candidate and associate child  encounter  dead lock
fix #500

Fix scheduler pick candidate and associate child  encounter  dead lock

---

go.mod
go.sum

fix security vulnerabilities 
https://github.com/dragonflyoss/Dragonfly2/security/dependabot/go.mod/github.com%2Fgin-gonic%2Fgin/open

Fix gin potential security vulnerabilities

---

scheduler/core/evaluator/evaluator.go

- [ x My code follows the code style of this project.

fix: scheduler get evaluator lock

---

go.mod
scheduler/daemon/host/manager.go
scheduler/daemon/host_mgr.go

Update CDN host info

---

test/e2e/e2e_test.go
test/e2e/e2eutil/exec.go

test: compare image commit

---

build/images/base/README.md
client/daemon/daemon.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/rpcserver_test.go
hack/build.sh

Optimize client rpc package name and other docs

---

internal/job/constants.go
internal/job/job.go
internal/job/job_test.go
internal/job/queue.go
internal/job/queue_test.go
internal/job/types.go
manager/job/job.go
manager/job/preheat.go
manager/manager.go
manager/service/preheat.go
manager/service/service.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml
scheduler/job/job.go
scheduler/scheduler.go

feat: rename task to job

---

client/daemon/peer/peertask_stream.go

Fix wrong content length in proxy

---

cdnsystem/cdn.go
cdnsystem/rpcserver/rpcserver.go
cdnsystem/rpcserver/rpcserver_test.go

Rename cdn server package to rpcserver

---

manager/permission/rbac/rbac.go
manager/permission/rbac/rbac_test.go

- Optimize get permission name.

feat: optimize get permission name

---

.gitmodules

feat: add console submodule

---

client/daemon/peer/peertask_base.go

Fix wait available peer packet panic

---

hack/docker-build.sh

feat: update git submodule

---

.github/workflows/docker.yml

- Update helm charts submodule.
- Docker push workflow with submodule.

Feature: update helm charts submodule

---

manager/handlers/permission.go
manager/handlers/user.go
manager/manager.go
manager/middlewares/jwt.go
manager/middlewares/rbac.go
manager/permission/rbac/rbac.go
manager/permission/rbac/rbac_test.go
manager/router/router.go
manager/service/permission.go
manager/service/service.go
manager/service/user.go
manager/types/permission.go
manager/types/user.go

https://github.com/dragonflyoss/Dragonfly2/issues/546

change rabc code struct

---

manager/manager.go
manager/router/router.go

feat: gin log to file

---

client/daemon/peer/peertask_stream.go

Add time out when client register to scheduler

---

manager/types/scheduler.go

- Update scheduler cluster query params.

feat: update scheduler cluster query params

---

manager/model/cdn_cluster.go
manager/model/scheduler_cluster.go
manager/service/scheduler_cluster.go
manager/types/scheduler.go

- Change scheduler query params.

feat: change scheduler query params

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml
Makefile
hack/install-e2e-test.sh
test/e2e/e2e_test.go
test/testdata/charts/compatibility-config.yaml

- Add compatibility test cases.

chore: add compatibility test workflow

---

cdnsystem/supervisor/cdn/storage/disk/disk.go
cdnsystem/supervisor/cdn/storage/hybrid/hybrid.go

Signed-off-by: santong <244372610@qq.com>

Optimize CDN free space check

---

cdnsystem/config/constants_otel.go
cdnsystem/rpcserver/rpcserver.go
cdnsystem/supervisor/cdn/cache_detector.go
cmd/dependency/dependency.go
pkg/rpc/client.go
pkg/rpc/client_util.go
scheduler/config/constants_otel.go
scheduler/core/events.go
scheduler/core/scheduler/basic/basic_scheduler.go
scheduler/core/service.go
scheduler/rpcserver/rpcserver.go
scheduler/supervisor/cdn/manager.go
scheduler/supervisor/peer/manager.go
scheduler/supervisor/task.go
scheduler/supervisor/task/manager.go

Signed-off-by: santong <244372610@qq.com>

Optimize app and tracer log

---

client/daemon/peer/peertask_base.go

fix: return failed piece

---

client/daemon/proxy/proxy_sni.go
scheduler/core/events.go
scheduler/core/scheduler/basic/basic_scheduler.go
scheduler/core/scheduler/scheduler.go
scheduler/core/service.go

Signed-off-by: santong <244372610@qq.com>

If peer reschedule parent reach max times notice client back source

---

docs/en/ecosystem/Kubernetes-with-Dragonfly.md

docs: update runtime guide in helm deploy

---

CHANGELOG.md
Makefile

chore: update changelog

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml

chore: skip workflows

---

test/e2e/manager/preheat.go

test: change preheat e2e timeout

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml

chore: skip e2e

---

docs/en/README.md
docs/zh-CN/README.md

docs: test guide link

---

MAINTAINERS.md

docs: maintainers

---

.github/workflows/compatibility-e2e.yml

chore: compatibility with v2.0.0 test

---

MAINTAINERS.md

chore: update maintainers

---

pkg/util/net/iputils/ip_utils.go

Normally, we can get host ip by `hostname -i`.
In dragonfly, it lists  all interfaces and select the first, it's so random.
Example:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft forever
inet6 ::1/128 scope host
valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
link/ether 00:16:3e:16:73:b5 brd ff:ff:ff:ff:ff:ff
inet 172.19.167.234/20 brd 172.19.175.255 scope global dynamic eth0
valid_lft 309909041sec preferred_lft 309909041sec
inet6 fe80::216:3eff:fe16:73b5/64 scope link
valid_lft forever …
```

chore: optimize advertise ip

---

docs/en/config/scheduler.yaml

docs: scheduler config

---

.gitignore
pkg/log/log.go

chore: export set log level

---

client/daemon/storage/local_storage.go
client/daemon/storage/storage_manager.go

- Release fd.
- Update submodule.

feat: release fd

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml

- Update skip-duplicate-actions version. 
Fixes https://github.com/fkirc/skip-duplicate-actions/issues/140

chore: update skip-duplicate-actions version

---

client/daemon/peer/peertask_base.go

fix: skip check DisableAutoBackSource option when scheduler says back source

---

docs/en/ecosystem/Kubernetes-with-Dragonfly.md
docs/zh-CN/ecosystem/Kubernetes-with-Dragonfly.md

docs: update kubernetes docs

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lint.yml

chore: workflows ignore paths

---

.github/workflows/docker.yml

- Release image to `docker.pkg.github.com`.

chore: release image to docker.pkg.github.com

---

build/images/base/Dockerfile
pkg/rpc/scheduler/server/server.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/core/service.go
scheduler/metrics/metrics.go
scheduler/rpcserver/rpcserver.go
scheduler/scheduler.go

feat: support traffic metrics by peer host

---

cdn/cdn.go

fix: cdn AdvertiseIP not used

---

manager/job/preheat.go

- Manager preheat image skip certificate validation
Fixes #785

feat: preheat skip certificate validation

---

test/e2e/manager/preheat.go

feat: preheat test

---

pkg/rpc/scheduler/server/server.go

- Optimize scheduler peer stat log

feat: optimize scheduler peer stat log

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
docs/en/api-reference/api-reference.md
docs/zh-CN/api-reference/api-reference.md
manager/handlers/user.go

- Generate manager `application` apis document

docs: manager apis

---

cdn/cdn.go
cdn/config/config.go
cdn/rpcserver/rpcserver.go
client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
cmd/dependency/dependency.go
cmd/dfget/cmd/root.go
go.mod
go.sum
internal/idgen/host_id.go
internal/idgen/host_id_test.go
internal/idgen/peer_id_test.go
pkg/rpc/cdnsystem/server/server.go
pkg/rpc/manager/manager.pb.go
pkg/rpc/scheduler/server/server.go
pkg/util/hostutils/host_utils.go
pkg/util/hostutils/host_utils_test.go
pkg/util/net/iputils/ip_utils.go
pkg/util/net/iputils/ip_utils_test.go
scheduler/config/config.go
scheduler/config/dynconfig.go
scheduler/config/dynconfig_test.go
scheduler/scheduler.go
scheduler/supervisor/cdn.go
test/tools/stress/main.go

- Scheduler and cdn report fqdn to manager.
- Generate `fqdn` with `github.com/Showmax/go-fqdn`.
- Refactor `idgen.CDN` to `idgen.CDNHostID`.
- Refactor `iputils.HostIP` to `iputils.IPv4`.

feat: scheduler and cdn report fqdn to manager

---

pkg/util/net/iputils/ip_utils.go
pkg/util/net/iputils/ip_utils_test.go

Signed-off-by: 孙伟鹏 <weipeng.swp@alibaba-inc.com>
Place the list of IP addresses retrieved by hostname first
fix #820

Place the list of IP addresses retrieved by hostname first

---

client/config/dynconfig.go
client/daemon/daemon.go
client/daemon/daemon_test.go
pkg/reachable/reachable.go
pkg/reachable/reachable_test.go

- Add package `reachable`
- Dfdaemon filters unavailable scheduler addresses.

feat: add package reachable

---

.github/workflows/compatibility-e2e.yml

feat: update helm charts version

---

build/images/cdn/Dockerfile
deploy/kustomize/single-cluster-native/bases/cdn/statefulset.yaml
deploy/kustomize/single-cluster-openkruise/bases/cdn/statefulset.yaml
hack/env.sh
hack/install.sh
hack/start-cdn.sh

chore: unify binary directory

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
docs/en/api-reference/api-reference.md
docs/zh-CN/api-reference/api-reference.md
manager/service/preheat.go
manager/types/preheat.go

- Preheat compatible with harbor.
Fixes #834

feat: preheat compatible with harbor

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
docs/en/api-reference/api-reference.md
docs/zh-CN/api-reference/api-reference.md
manager/model/application.go
manager/service/application.go

- Add application CDN clusters field.

feat: add application cdn clusters field

---

manager/searcher/searcher.go

- Export search `evaluate` func.

feat: export searcher evaluate func

---

internal/dflog/logger.go
manager/searcher/searcher.go
manager/service/service_grpc.go

feat: add plugin log

---

client/config/dynconfig.go

- Dfdaemon get scheduler list with `AdvertiseIP`.

feat: get scheduler list with advertise ip

---

client/daemon/peer/piece_manager.go

Fix: file peer task back source digest not match

---

docs/en/quick-start.md
docs/zh-CN/quick-start.md

docs: update quick-start.md format

---

cdn/config/constants.go
cdn/supervisor/task/manager_util.go
client/daemon/peer/peertask_file_test.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_stream_test.go
client/daemon/peer/piece_manager.go
internal/dfutils/dfutils.go
internal/dfutils/dfutils_test.go

unify piece size

---

manager/router/router.go

- Remove oauth interface auth.

feat: remove oauth interface auth

---

pkg/rpc/manager/client/client.go

fix: error log

---

client/config/peerhost.go
client/daemon/daemon.go
client/daemon/peer/piece_manager.go
client/daemon/upload/upload_manager.go
docs/en/deployment/configuration/dfget.yaml

feat: support customize transport in daemon

---

manager/auth/oauth/oauth.go

feat: add oauth timeout

---

client/daemon/peer/piece_manager.go
docs/en/deployment/configuration/dfget.yaml

docs: keep alive

---

docs/en/developer-guide/plugin.md
docs/zh-CN/developer-guide/plugin.md

docs: add plugin guide

---

.github/workflows/lint.yml
.markdownlint.yml
Makefile
hack/markdownlint.sh

feat: add lint makefile

---

client/daemon/daemon.go
manager/service/service_grpc.go

fix: searcher log

---

cdn/rpcserver/rpcserver.go
cdn/supervisor/cdn/cache_detector.go
cdn/supervisor/cdn/cache_detector_test.go
cdn/supervisor/cdn/storage/mock/mock_storage_mgr.go
cdn/supervisor/cdn/storage/storage.go
cdn/supervisor/mock/mock_task_mgr.go
cdn/supervisor/task/manager.go
cdn/supervisor/task/manager_util.go
cdn/supervisor/task_mgr.go
cdn/types/seed_task_info.go

task manager

---

client/daemon/peer/peertask_base.go
client/daemon/peer/piece_manager.go

fix: small size task failed due to digest error

---

manager/service/cdn_cluster.go

- Add cdn cluster to scheduler cluster.

fix: add cdn cluster to scheduler cluster

---

cdn/supervisor/task/manager.go

Reslove scheduler obtain seeds cancel result in CDN task download cancel

Reslove scheduler obtain seeds cancel result in CDN task download cancel

---

scheduler/core/events.go

- Fix scheduler success event.

fix: scheduler success event

---

client/daemon/peer/peertask_base.go

- Dfdaemon update content length.

feat: dfdaemon update content length

---

pkg/source/hdfsprotocol/hdfs_source_client_test.go

Fix hdfs test

---

cmd/dfget/cmd/root.go

fix: dfget dfpath

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml
Makefile
client/daemon/peer/peertask_stream.go
hack/install-e2e-test.sh
hack/kind-load.sh
test/e2e/dfget_test.go
test/e2e/e2e_test.go
test/e2e/e2eutil/file_server.go
test/e2e/manager/preheat.go
test/testdata/k8s/file-server.yaml
test/testdata/k8s/proxy.yaml
test/tools/no-content-length/Dockerfile
test/tools/no-content-length/build.sh
test/tools/no-content-length/main.go

chore: support multi daemons e2e test

---

client/daemon/storage/local_storage.go

fix: mismatch digest peer task did not mark invalid

---

docs/en/deployment/configuration/cdn.yaml
docs/en/deployment/configuration/dfget.yaml
docs/en/deployment/configuration/scheduler.yaml
test/testdata/k8s/proxy.yaml

docs: dir path

---

client/daemon/daemon.go

feat: add data storage directory

---

internal/idgen/peer_id_test.go

test: idgen peer id

---

manager/searcher/searcher.go
manager/searcher/searcher_test.go

- Dfdaemon list scheduler cluster with multi idc

feat: dfdaemon list scheduler cluster with multi idc

---

scheduler/supervisor/peer.go

fix: peer gc

---

docs/en/developer-guide/plugin.md
pkg/source/testdata/plugin/dfs.go

docs: update plugin docs

---

cdn/config/config.go
client/daemon/daemon.go
cmd/cdn/cmd/root.go
cmd/dfget/cmd/daemon.go
cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go
pkg/source/source_client.go

fix: plugin dir is empty

---

internal/idgen/task_id.go
pkg/util/net/urlutils/url_utils.go
scheduler/core/service.go
scheduler/rpcserver/rpcserver.go
scheduler/supervisor/task.go

- Refactor scheduler register task.

refactor: scheduler register task

---

cdn/supervisor/cdn/cache_writer_test.go
cdn/supervisor/cdn/manager_test.go

Fix Multiple test downloads failed

---

cdn/rpcserver/rpcserver.go
cdn/supervisor/service.go
cdn/supervisor/task/manager.go
internal/util/util.go

Set totalPieceCount when the file length is available

---

pkg/sync/kmutex.go
pkg/sync/kmutex_test.go
pkg/sync/krwmutex.go
pkg/sync/krwmutex_test.go
scheduler/core/service.go

feat: add kmutex and krwmutex

---

test/README.md

fix typos for test/readme

---

client/daemon/peer/peertask_base.go

fix: not handle base.Code_SchedTaskStatusError in client

---

pkg/rpc/scheduler/server/server.go

fix: size scope empty

---

client/config/dfget.go
client/config/dfget_darwin.go
client/config/dfget_linux.go
client/dfget/dfget.go
client/dfget/dfget_test.go
cmd/dfget/cmd/root.go
pkg/source/source_client.go

feat: support recursive download in dfget

---

internal/dflog/logcore/init.go
internal/dflog/logcore/logcore.go
internal/dflog/logger.go
pkg/rpc/scheduler/server/server.go

- Remove stat log from scheduler.

feat: remove stat log from scheduler

---

go.mod
pkg/source/hdfsprotocol/hdfs_source_client.go

Fix HDFS File reader

---

cdn/supervisor/cdn/downloader.go
cdn/supervisor/cdn/manager_test.go
client/daemon/peer/peertask_file_test.go
client/daemon/peer/peertask_stream_backsource_partial_test.go
client/daemon/peer/peertask_stream_test.go
client/daemon/peer/piece_manager.go
client/dfget/dfget.go
client/dfget/dfget_test.go
pkg/source/hdfsprotocol/hdfs_source_client.go
pkg/source/hdfsprotocol/hdfs_source_client_test.go
pkg/source/httpprotocol/http_source_client.go
pkg/source/httpprotocol/http_source_client_test.go
pkg/source/mock/mock_source_client.go
pkg/source/ossprotocol/oss_source_client.go
pkg/source/response.go
pkg/source/source_client.go
pkg/source/testdata/main.go
pkg/source/testdata/plugin/dfs.go

feat: update source.Response and source client interface

---

client/daemon/peer/piece_manager.go
client/daemon/storage/local_storage.go

chore: optimize back source update digest logic

---

docs/en/developer-guide/plugin.md

docs: update plugin doc

---

test/e2e/dfget_test.go
test/testdata/k8s/proxy.yaml

chore: copy e2e proxy log to artifact

---

cdn/config/old_config.go
cdn/metrics/config.go

- Change metrics service listen port to `8000`.

feat: change metrics service port to 8000

---

scheduler/rpcserver/rpcserver.go
test/testdata/k8s/proxy.yaml

fix: schedulers send invalid direct piece

---

client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/storage/storage_manager.go

feat: add default DiskGCThresholdPercent and ignore it when is 0

---

.github/workflows/docker.yml

- Change `docker.pkg.github.com` to `ghcr.io`.

chore: change docker.pkg.github.com to ghcr.io

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml
pkg/idgen/host_id_test.go
scheduler/core/events.go
scheduler/core/service.go
scheduler/supervisor/cdn.go
scheduler/supervisor/host.go
test/e2e/constants.go
test/e2e/dfget_test.go
test/e2e/e2e_test.go
test/e2e/e2eutil/artifact.go
test/testdata/charts/config.yaml
test/testdata/k8s/file-server.yaml
test/testdata/kind/config.yaml

- If cdn is deleted, clear cdn related information.
#949

feat: if cdn is deleted, clear cdn related information

---

CHANGELOG.md

modify a simple spelling mistake.
nothing
Make a contribution to the commity from small things.

spelling error, just a little mistake

---

docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml
scheduler/config/config.go

fix: scheduler config typo

---

hack/markdownlint.sh

fix markdownlint.sh error
fix markdownlint.sh error, $(PWD) -- > $(pwd)

fix markdownlint.sh error

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_mock_test.go
client/daemon/peer/piece_downloader.go
client/daemon/peer/piece_manager.go
client/daemon/peer/piece_manager_test.go
pkg/rpc/base/base.pb.go
pkg/rpc/base/base.proto

- Send piece result error not handled.
- Add error code `ClientConnectionError` and `ClientPieceNotFound`.

fix: send piece result error not handled

---

client/daemon/storage/local_storage.go
client/daemon/storage/storage_manager.go

Update typo in local_storage.go

---

docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml
scheduler/resource/host_manager.go
scheduler/resource/host_manager_mock.go
scheduler/resource/host_manager_test.go
scheduler/resource/resource.go
scheduler/resource/resource_test.go

feat: add scheduler host GC

---

client/config/constants_otel.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_test.go
client/daemon/proxy/proxy.go
client/daemon/transport/transport.go

1. Trace https proxy request
2. Add Trace ID into log if tracing is enabled.

feat: trace https proxy request

---

deploy/docker-compose/config/scheduler.yaml

The latest scheduler config has changed, we need update the config in docker-compose.

chore: sync docker-compose scheduler config

---

cmd/dependency/dependency.go
docs/en/deployment/configuration/cdn.yaml
docs/en/deployment/configuration/dfget.yaml
docs/en/deployment/configuration/manager.yaml
docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/cdn.yaml
docs/zh-CN/deployment/configuration/dfget.yaml
docs/zh-CN/deployment/configuration/manager.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml

feat: update submodule charts

---

.github/workflows/ci.yml
.github/workflows/compatibility-e2e.yml
.github/workflows/docker.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/release.yml

feat: add actions job timout

---

.github/workflows/ci.yml

- change workflow test timeout.

chore: change workflow test timeout

---

client/daemon/peer/peertask_piecetask_poller.go

add client obtain from cdn totalpieces

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_file.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_stream.go
client/daemon/storage/storage_manager.go

1. Optimize defer in `peerTaskConductor.Done` and `peerTaskConductor.Fail`.
2. Fix concurrent test failed in `runPeerTaskConductor`

chore: optimize defer and test

---

.github/workflows/compatibility-e2e.yml

- Change compatibility version to `v2.0.2-rc.0`

feat: change compatibility version to v2.0.2-rc.0

---

client/daemon/metrics/metrics.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/proxy/proxy.go
client/daemon/transport/transport.go

chore: optimize metrics and trace in daemon

---

manager/types/config.go

- manager config model add `is_boot` key

feat: manager config model add is_boot key

---

cmd/dependency/dependency.go
docs/en/troubleshooting/README.md
docs/zh-CN/troubleshooting/README.md
internal/dflog/logcore/init.go
internal/dflog/logcore/logcore.go
internal/dflog/logcore/signal.go
pkg/log/log.go

1. Support change log level in-flight.
2. Update change log level guide.

Feature: change log level in-flight

---

client/daemon/metrics/metrics.go
client/daemon/peer/peertask_conductor.go

chore: add piece task metrics in daemon

---

cdn/rpcserver/rpcserver.go

Add CDN get piece tasks result logs

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml
Makefile
go.mod
go.sum
hack/install-e2e-test.sh
test/e2e/concurrency_test.go
test/e2e/containerd_test.go
test/e2e/dfget_test.go
test/e2e/e2e_test.go
test/e2e/manager/preheat.go

chore: upgrade to ginkgo v2

---

scheduler/service/callback.go

fix: retrigger cdn panic

---

test/testdata/charts/config.yaml

chore: add missing pod log in e2e

---

.github/workflows/docker.yml

refactor: docker workflows

---

.github/workflows/docker.yml

fix: docker actions typo

---

cmd/dfget/cmd/root.go

Update root.go: add flock lock failed log

---

manager/manager.go
manager/rpcserver/rpcserver.go
pkg/rpc/manager/server/server.go

- Refactor manager GRPC server.
Fixes #1049

refactor: manager grpc server

---

client/daemon/proxy/proxy.go

1. Fix `read on closed conn` error,
2. Comment for http2 support.

chore: optimize https pass through

---

.golangci.yml
cmd/cdn/cmd/root.go
cmd/dependency/dependency.go
cmd/dfget/cmd/daemon.go
cmd/dfget/cmd/root.go
cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go
internal/dflog/logcore.go
internal/dflog/logger.go
internal/dflog/loginit.go
internal/dflog/signal.go
pkg/log/log.go

1. Argument `--console` and option `console: true` will now display info log by default and support debug log by argument `--verbose` and option `verbose: true`.
2. Use `logger.SetLevel(zapcore.DebugLevel)` to update all log level.

feat: support change console log level

---

client/daemon/peer/peertask_stream.go

chore: add content length for fast stream peer task

---

docs/en/deployment/installation/docker/standalone/manager.md

docs: manager installation

---

.github/workflows/e2e.yml
Makefile
test/e2e/dfget_test.go
test/e2e/e2eutil/exec.go
test/tools/no-content-length/main.go

chore: enable range feature gate in e2e

---

scheduler/scheduler/scheduler.go

fix: evaluate peer's parent

---

manager/searcher/plugin.go
scheduler/scheduler/evaluator/plugin.go

Correct plugin typo

---

client/daemon/peer/peertask_conductor.go

- Optimize client request logy

feat: optimize client request log

---

docs/en/runtime-integration/containerd/mirror.md

- Add containerd private registry configuration.
Fixes #1065

docs: add containerd private registry configuration

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Fixed some typos in docs.
Fixes: #1070 
This change improves the documentation.

Fix typos in docs

---

scheduler/job/job.go
scheduler/scheduler.go
scheduler/service/service.go
scheduler/service/service_test.go

- Job trigger cdn by resource interface
- Fix dragonfly range without `bytes=`

feat: job trigger cdn by resource interface

---

docs/en/deployment/configuration/cdn.yaml
docs/en/deployment/configuration/dfget.yaml
docs/en/deployment/configuration/manager.yaml
docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/cdn.yaml
docs/zh-CN/deployment/configuration/dfget.yaml
docs/zh-CN/deployment/configuration/manager.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml
scheduler/job/job.go
scheduler/service/service.go
scheduler/service/service_test.go

- Format config yaml.
- Scheduler blocks cdn.
Fixes #1077

feat: scheduler blocks cdn

---

.github/PULL_REQUEST_TEMPLATE.md

- Fix pull request template typo.

fix: pull request template typo

---

docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml
scheduler/resource/resource.go
scheduler/resource/resource_test.go
scheduler/scheduler.go

- When scheduler blocks cdn, resource does not initialize cdn.

feat: when scheduler blocks cdn, resource does not initialize cdn

---

.goreleaser.yml
hack/update-version-gorelease.sh

Currently, the release binary did not contain git commit info. This PR will fix this problem.

chore: update gorelease ldflags

---

deploy/docker-compose/config/.gitignore
deploy/docker-compose/docker-compose.yaml
deploy/docker-compose/run.sh
deploy/docker-compose/template/cdn.template.yaml
deploy/docker-compose/template/dfget.template.yaml
deploy/docker-compose/template/manager.template.yaml
deploy/docker-compose/template/scheduler.template.yaml

upgrade to v2.0.2-rc.9
added depends on(redis and mysql)
added healthcheck
Signed-off-by: 赵安家 <anjia0532@gmail.com>

feat: fix docker-compose

---

manager/types/scheduler_cluster.go
scheduler/scheduler.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

feat: add dynamic parallel count

---

cdn/supervisor/progress/manager.go

Fix multi task seeds lead to panic concurrent map writes

---

scheduler/scheduler/scheduler_test.go

test: FilterParentCount 

---

scheduler/resource/host.go
scheduler/resource/host_manager.go
scheduler/resource/host_test.go
scheduler/resource/peer.go
scheduler/resource/peer_manager.go
scheduler/resource/peer_test.go
scheduler/resource/task.go
scheduler/resource/task_manager.go
scheduler/resource/task_test.go
scheduler/scheduler/evaluator/evaluator_base.go
scheduler/service/service.go

- Optimizing counters to use atomic operations.

feat: optimizing counters to use atomic operations

---

manager/types/cdn_cluster.go
manager/types/scheduler_cluster.go

- Update dfdaemon and cdn load limit.

feat: update dfdaemon and cdn load limit

---

client/daemon/peer/peertask_conductor.go
client/daemon/rpcserver/rpcserver.go

chore: init url meta in rpc server

---

manager/database/mysql.go

- Change client default load limit.

feat: change client default load limit

---

client/daemon/peer/peertask_file.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_reuse.go
client/daemon/peer/peertask_stream.go
client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_test.go
client/daemon/storage/storage_manager.go
client/daemon/test/mock/storage/manager.go

feat: reuse partial completed task

---

deploy/docker-compose/template/scheduler.template.yaml
docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml
manager/types/scheduler_cluster.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml
scheduler/resource/peer.go
scheduler/scheduler.go
scheduler/scheduler/evaluator/evaluator_base.go
scheduler/scheduler/evaluator/evaluator_base_test.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go
scheduler/service/service.go
scheduler/service/service_test.go

- Add `filterParentLimit` for filter parents.
- Set normal distribution len to 30.
- When scheduler get `Code_ClientPieceDownloadFail` code, it reschedules peers.
- Update helm charts version.
- Scheduler remove listenLimit.

feat: optimize scheduler

---

pkg/source/source_client.go

- Change back-to-source timeout.

feat: change back-to-source timeout

---

internal/dflog/logger.go

Grpc logger verbosity level

---

pkg/source/httpprotocol/http_source_client.go
pkg/source/source_client.go

- Change source client net dialer context config, refer to [moby/registry.go http client](https://github.com/moby/moby/blob/7b9275c0da707b030e62c96b679a976f31f929d3/plugin/registry.go#L50).

feat: change source client dialer config

---

scheduler/resource/peer.go

- When peer downloads finished, peer deletes parent

feat: when peer downloads finished, peer deletes parent

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/config/peerhost_test.go
client/daemon/daemon.go
client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_test.go

1. Support health probe in daemon
2. Clarify ProxyRule in config

feat: support health probe in daemon

---

pkg/util/timeutils/time_utils.go
pkg/util/timeutils/time_utils_test.go
scheduler/resource/cdn.go
scheduler/service/service.go
scheduler/service/service_test.go

- Scheduler change piece cost from nanosecond to millisecond.

feat: scheduler change piece cost from nanosecond to millisecond

---

pkg/util/fileutils/file_utils.go

Use os.stat replace custom stat function

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_poller.go

chore: fast back source when get pieces task failed

---

pkg/rpc/client.go
pkg/rpc/server.go

- Change grpc client keepalive config.

feat: change grpc client keepalive config

---

cdn/rpcserver/rpcserver.go
cdn/supervisor/progress/manager.go
cdn/supervisor/task/manager.go

fix: wrong md5 sign in cdn

---

scheduler/service/service.go
scheduler/service/service_test.go

- Change task state for register.

feat: change task state for register

---

scheduler/resource/cdn.go
scheduler/resource/cdn_test.go
scheduler/resource/host_manager.go
scheduler/resource/host_manager_test.go

- Scheduler remove inactive host.

feat: scheduler remove inactive host

---

cdn/supervisor/service.go

Resolve forget unlock resource lack lock

---

docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml

docs: change scheduler config

---

scheduler/metrics/metrics.go
scheduler/service/service.go
scheduler/service/service_test.go

- Add scheduler traffic metrics.

feat: add scheduler traffic metrics

---

cdn/supervisor/cdn/storage/disk/config.go
cdn/supervisor/cdn/storage/hybrid/config.go

Lower cdn fullGC threshould

---

scheduler/service/service_test.go

- Fix scheduler service handlePieceFail test.

test: scheduler service handlePieceFail

---

scheduler/service/service.go

feat: scheduler trace trigger cdn

---

Makefile
go.sum

Remove residues left by E2E tests

Remove residues left by E2E tests

---

manager/manager.go
scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

- Add scheduler `constructSuccessPeerPacket` test case.

test: add scheduler constructSuccessPeerPacket case

---

scheduler/config/config.go

- Change reschedule default config

feat: change reschedule default config

---

internal/dflog/logcore.go

Reduce default RotateMaxBackups count

Reduce default RotateMaxBackups count

---

scheduler/resource/peer.go
scheduler/service/service.go
scheduler/service/service_test.go

- Scheduler peer add default biz tag.

feat: scheduler peer add default biz tag

---

pkg/rpc/cdnsystem/client/client.go

fix: rpc cdn sync piece tasks

---

manager/rpcserver/rpcserver.go
manager/searcher/searcher.go
manager/searcher/searcher_test.go
manager/searcher/testdata/main.go
manager/searcher/testdata/plugin/searcher.go

- Searcher returns multiple scheduler clusters.

feat: seacher returns multiple scheduler clusters

---

client/config/deprecated.go
client/config/dfget.go
client/config/dfget_test.go
internal/dferrors/error.go

add header check for ClientOption
add header check for ClientOption

add header check for ClientOption

---

client/daemon/daemon.go

fix deamon not exit after keepalive duration

Fix Deamon keep alive

---

client/daemon/peer/peertask_piecetask_synchronizer.go

chore: always fallback to legacy get pieces

---

client/daemon/daemon.go

Fix client initialization trivial things

---

.golangci.yml

- Change olangci-lint min-complexity to 42

chore: change golangci-lint min-complexity to 42

---

client/daemon/peer/peertask_stream.go

fix: client break error

---

client/daemon/rpcserver/rpcserver.go
client/daemon/upload/upload_manager.go
manager/router/router.go
manager/rpcserver/rpcserver.go
pkg/rpc/cdnsystem/server/server.go
scheduler/rpcserver/rpcserver.go

feat: add grpc health interface

---

client/config/dfget_test.go

fix TestCheckHeader

---

scheduler/resource/peer.go
scheduler/service/service.go
scheduler/service/service_test.go

- Scheduler add block peers set.

feat: scheduler add block peers set

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
MAINTAINERS.md
README.md
SECURITY.md

- Add slack and google groups.

docs: add slack and google groups

---

scheduler/service/service.go
scheduler/service/service_test.go

feat: get available task

---

client/daemon/peer/peertask_piecetask_poller.go
client/daemon/peer/peertask_stream.go

chore: print client stream task error log

---

scheduler/metrics/metrics.go
scheduler/service/service.go

- Add type to `DownloadFailureCount` metrics

feat: add type to DownloadFailureCount metrics

---

client/daemon/metrics/metrics.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/piece_downloader.go

feat: add back source fail metric in client

---

manager/types/cdn_cluster.go
manager/types/scheduler_cluster.go

- Change manager validate with config.

feat: change manager validate with config

---

pkg/container/set/safe_set.go
pkg/container/set/safe_set_test.go
pkg/container/set/set.go
pkg/container/set/set_test.go
scheduler/resource/peer.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

- Scheduler blocks steal peers.

feat: scheduler blocks steal peers

---

.github/workflows/lint.yml
cmd/dfget/main.go

Upgrade golang lint version

---

scheduler/resource/host.go
scheduler/resource/host_manager.go
scheduler/resource/host_manager_test.go
scheduler/resource/host_test.go
scheduler/resource/peer.go
scheduler/scheduler/scheduler.go

fix: calculate FreeUploadLoad

---

build/images/cdn/Dockerfile

upgrade nginx version of CDN image to fix issue #1150
fix #1150

Fix Image Vulnerabilities

---

deploy/docker-compose/docker-compose.yaml

- Update docker compose verison.

feat: update docker compose version

---

deploy/docker-compose/docker-compose.yaml
deploy/docker-compose/template/cdn.template.yaml
deploy/docker-compose/template/dfget.template.yaml
deploy/docker-compose/template/manager.template.yaml
deploy/docker-compose/template/scheduler.template.yaml

Signed-off-by: AnJia <anjia0532@gmail.com>

feat: docker-compose write log to file

---

client/daemon/storage/storage_manager.go

fix: client superfluous usage gc

---

scheduler/metrics/metrics.go
scheduler/rpcserver/rpcserver.go
scheduler/service/service.go

- Add `AnnounceTask` and `StatTask` metrics.

feat: add AnnounceTask and StatTask metrics

---

scheduler/storage/storage_test.go

- Fix scheduler storage tests.

test: scheduler storage

---

scheduler/resource/peer.go

- Prevent traversal tree from infinite loop.

fix: prevent traversal tree from infinite loop

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_synchronizer.go

fix: acquire empty dst pid

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_synchronizer.go

chore: optimize create synchronizer logic

---

scheduler/resource/peer.go
scheduler/resource/peer_test.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go
scheduler/service/service.go
scheduler/service/service_test.go

- Fix tree infinite loop.
- When there is no CDN, the peer back-to-source immediately.

fix: tree infinite loop

---

deploy/docker-compose/run.sh

Signed-off-by: AnJia <anjia0532@gmail.com>

fix: run.sh threw error on mac

---

scheduler/config/config.go

- Fix scheduler config validation.

fix: scheduler config validation

---

cmd/dfget/cmd/daemon.go

fix: dfget daemon console log invalid

---

client/daemon/peer/peertask_piecetask_synchronizer.go

chore: add target peer id in sync piece trace

---

deploy/docker-compose/README.md
deploy/docker-compose/run.sh

- Fix docker compose `run.sh`.

fix: docker compose run.sh

---

build/images/cdn/Dockerfile
cdn/cdn.go
cdn/fileserver/fileserver.go
cdn/supervisor/cdn/storage/disk/disk.go
cdn/supervisor/cdn/storage/hybrid/hybrid.go
cdn/supervisor/cdn/storage/mock/mock_storage_manager.go
cdn/supervisor/cdn/storage/storage.go
hack/start-cdn.sh

Feature: use a golang native file server to replace nginx

---

pkg/rpc/scheduler/scheduler.pb.go
pkg/rpc/scheduler/scheduler.proto

- Fix grpc `total_piece_count` comment.

fix: grpc total_piece_count comment

---

scheduler/config/config.go
scheduler/config/constants.go
scheduler/config/dynconfig.go
scheduler/job/job.go
scheduler/metrics/metrics.go
scheduler/resource/cdn.go
scheduler/resource/host.go
scheduler/resource/host_manager.go
scheduler/resource/peer.go
scheduler/resource/peer_manager.go
scheduler/resource/resource.go
scheduler/resource/task.go
scheduler/resource/task_manager.go
scheduler/rpcserver/rpcserver.go
scheduler/scheduler.go
scheduler/scheduler/evaluator/evaluator.go
scheduler/scheduler/evaluator/evaluator_base.go
scheduler/scheduler/scheduler.go
scheduler/service/service.go
scheduler/storage/storage.go

fix: scheduler typo

---

pkg/rpc/client_util.go

In case we don't want to GC client connections in some special
circumstances.

feat: don't gc client rpc connection if ExpireTime is 0

---

client/daemon/peer/piece_downloader.go
client/daemon/peer/piece_manager.go
pkg/util/digestutils/digest_reader.go
pkg/util/digestutils/digest_reader_test.go

feat: support more digest methods like sha256 in client

---

pkg/util/digestutils/digest_reader.go
pkg/util/digestutils/digest_reader_test.go

fix: digest reader and unit tests

---

client/daemon/peer/peertask_manager.go
client/daemon/rpcserver/rpcserver.go

feat: back source when receive seed request

---

client/daemon/daemon.go
scheduler/resource/seed_peer_client.go

feat: reduce dynconfig logs

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/cache/cache.go
manager/handlers/peer.go
manager/metrics/metrics.go
manager/rpcserver/rpcserver.go
manager/service/peer.go
manager/service/service.go
manager/types/peer.go

feat: get active peer count

---

test/e2e/dfget_test.go

- Dfget disabled back-to-source.

test: dfget disabled back-to-souce

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_poller.go
client/daemon/peer/piece_manager.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/seeder.go
client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_subtask.go
client/daemon/storage/local_storage_test.go
client/daemon/storage/metadata.go

1. fix: seed peer did not send done seed result
2. fix: unknown length back source seed did not send content length to other peers

fix: seed peer did not send done seed result

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.yaml
client/daemon/daemon.go

- Client add tls verify config.

feat: client add tls verify config

---

client/daemon/peer/peertask_reuse.go
client/daemon/peer/peertask_seed.go
client/daemon/rpcserver/seeder.go

fix: reuse seed peer id is not exist

---

.github/workflows/docker.yml

- Docker build with multi platforms.

feat: docker build with multi platforms

---

manager/model/models.go
manager/rpcserver/rpcserver.go

fix: create_at timestamp

---

client/daemon/metrics/metrics.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_mock_test.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_seed.go
client/daemon/rpcserver/seeder.go
client/daemon/rpcserver/seeder_test.go
client/daemon/test/mock/peer/peertask_manager.go

feat: add seed peer metrics

---

README.md

- Update readme system features.

docs: update readme system features

---

hack/gen-containerd-hosts.sh

Fix https://github.com/dragonflyoss/d7y.io/issues/85

chore: add hack/gen-containerd-hosts.sh

---

internal/job/types.go
manager/job/preheat.go

- Remove preheat tag required validation.

feat: remove preheat tag required validation

---

client/daemon/proxy/proxy.go
client/daemon/rpcserver/seeder.go
hack/gen-containerd-hosts.sh
manager/job/preheat.go
test/e2e/manager/constants.go
test/e2e/manager/preheat.go
test/testdata/containerd/config.toml

- Remove default digest value.
- Add end time to seed piece.

fix: preheat tack id

---

pkg/rpc/client_util.go

feat: remove connection gc

---

build/package/nfpm/config/dfget.yaml
deploy/docker-compose/template/dfget.template.yaml
test/testdata/charts/config.yaml
test/testdata/k8s/proxy.yaml

feat: dfdaemon add ns filter

---

manager/config/config.go
manager/config/config_test.go
manager/config/testdata/manager.yaml
manager/manager.go
manager/rpcserver/rpcserver.go

- Add `EnablePeerGauge` config to manager.

feat: add EnablePeerGauge config to manager

---

manager/handlers/handlers.go
manager/service/application.go
manager/service/config.go
manager/service/job.go
manager/service/oauth.go
manager/service/scheduler.go
manager/service/scheduler_cluster.go
manager/service/security_group.go
manager/service/security_rule.go
manager/service/seed_peer.go
manager/service/seed_peer_cluster.go
manager/service/user.go

Signed-off-by: LetFu <letfu@outlook.com>
Reset offset before calculating count;
Fix the totalpage calculation error.
#1373
I looked at the code and I found that the error should be here:
https://github.com/dragonflyoss/Dragonfly2/blob/main/manager/service/job.go#L180-L184
```go
if err := s.db.WithContext(ctx).Scopes(model.Paginate(q.Page, q.PerPage)).Where(&model.Job{
Type:   q.Type,
State:  q.State,
UserID: q.UserID,
}).Find(&jobs).Count(&count).Error; err != nil {
```
When page is not 1, the offset calculated by the following code will not be 0
https://github.com/dragonflyoss/Dragonfly2/blob/main/manager/model/models.go#L40
```go
offset := (page - 1) * perPage
```
At this time, the SQL statement generated by the above SQL code is as follows:
```sql
{"elapsed": "2.223839ms", "rows": 2, …
```

fix: count error & totalPage error (#1373)

---

cdn/cdn.go
client/daemon/daemon.go
client/daemon/peer/piece_downloader.go
client/daemon/peer/piece_downloader_test.go
client/daemon/upload/types.go
client/daemon/upload/upload_manager.go
client/daemon/upload/upload_manager_test.go

- Replace gin-gonic/gin with gorilla/mux.
Fixes #1386

feat: replace gin-gonic/gin with gorilla/mux

---

manager/rpcserver/rpcserver.go

- Add seed peer for list scheduler grpc interface.

feat: add seed peer for list scheduler grpc interface

---

deploy/docker-compose/run.sh

Signed-off-by: Letfu <letfu@outlook.com>
Dragonfly2 starts with dependencies on mysql and redis, but they do not exist
in the script. and the default mirror repository d7yio does not exist.
Also some of the containers that depend on it when starting may not be ready
yet, so I added --restart=always.
In my use of `. /run.sh container` I found some problems.

fix: default repository does not exist and missing dependency containers

---

cmd/dfget/cmd/daemon.go
cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go
internal/dflog/logger.go

- Redirect stdout and stderr to file.

feat: redirect stdout and stderr to file

---

test/testdata/k8s/file-server.yaml
test/testdata/k8s/proxy.yaml

Signed-off-by: jiasirui <jiasirui3@163.com>

ymal file start with ---

---

client/daemon/objectstorage/objectstorage.go
client/daemon/objectstorage/types.go

- Dfdaemon add destroyObject rest api.
#1249

feat: dfdaemon add destroyObject rest api

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.yaml
client/daemon/objectstorage/objectstorage.go
client/daemon/objectstorage/types.go
pkg/strings/strings.go
pkg/strings/strings_test.go

- Import object to seed peer with max replicas.
#1249

feat: import object to seed peer with max replicas

---

scheduler/resource/peer.go
scheduler/resource/peer_test.go

- Refactor scheduler http response status code.

refactor: scheduler http response status code

---

client/dfstore/dfstore.go

- GetObjectInput add range field.

feat: GetObjectInput add range field

---

client/daemon/objectstorage/objectstorage.go
client/daemon/objectstorage/types.go
client/dfstore/dfstore.go
client/dfstore/mocks/dfstore_mock.go
pkg/objectstorage/mocks/objectstorage_mock.go
pkg/objectstorage/objectstorage.go
pkg/objectstorage/oss.go
pkg/objectstorage/s3.go

feat: used put object action

---

client/config/dynconfig.go
client/config/dynconfig_test.go
client/config/mocks/dynconfig_mock.go
client/dfstore/dfstore.go

- Dfstore closes writer.
- Dynconfig removes list bucket.
#1249

feat: dfstore closes writer

---

client/daemon/rpcserver/seeder.go

fix: seed task metric panic

---

.github/workflows/codeql-analysis.yml

chore: update codeql version

---

client/daemon/peer/piece_manager.go

chore: exit when receive context done

---

deploy/docker-compose/docker-compose.yaml
deploy/docker-compose/run.sh
deploy/docker-compose/template/dfget.template.yaml

chore: update docker compose

---

test/testdata/kind/config.yaml

chore: upgrade kind node version

---

go.mod
pkg/source/clients/httpprotocol/http_source_client.go

feat: remove errors package

---

client/config/peerhost.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.yaml
manager/config/config_test.go
manager/config/testdata/manager.yaml
scheduler/config/config_test.go

Signed-off-by: ljx373327 <ljx373327@alibaba-inc.com>
fix Spelling errors

fix Spelling errors

---

scheduler/scheduler/scheduler.go

fix: depth limit

---

cmd/scheduler/cmd/root.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml

feat: scheduler add data dir

---

client/daemon/objectstorage/objectstorage.go
client/daemon/upload/upload_manager.go
manager/router/router.go

- Metrics reduces labels, refer to https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels.
Fixes #1454

fix: metrics reduces labels

---

client/config/dfget.go

fix dfget disable-back-source flag config error

---

client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_subtask.go

#Signed-off-by: ljx373327 <ljx373327@alibaba-inc.com>
In the case of p2p first and then back to the source to download the pieces, although going back to the source will re-download the pieces, but when t.pieces has piece information, it will skip GenMetadata resulting in downloadedPieceCount.Load() ! = pieceCount finally cannot GenMetadata return to false cannot generate PieceMd5Sign
#1464

fix [4000] digest not set error

---

pkg/dag/dag.go
pkg/dag/dag_test.go
pkg/dag/vertex.go
pkg/dag/vertex_test.go

- Add directed acyclic graph package.

feat: add directed acyclic graph package

---

pkg/dag/dag.go
pkg/dag/dag_test.go
pkg/dag/mocks/dag_mock.go

- DAG adds LenVertex and RangeVertex func.

feat: dag adds LenVertex and RangeVertex func

---

client/daemon/upload/upload_manager.go

Signed-off-by: bigerous <bigerous@qq.com>

fix: upload_manager write header in time

---

client/config/constants.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go

- Dfdaemon add default healthy config.

feat: dfdaemon add default healthy config

---

cmd/dfcache/cmd/root.go
cmd/dfget/cmd/daemon.go
cmd/dfget/cmd/root.go
cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go

Adjust the configuration check sequence.
Before the service starts to initialize, verify the configuration content first, which can ensure a smoother subsequent process.

fix: adjust the configuration check sequence

---

client/daemon/rpcserver/seeder.go
scheduler/resource/seed_peer.go

- Scheduler merge end of piece and piece from seed peer.

feat: scheduler merge end of piece and piece from seed peer

---

pkg/dag/dag.go
pkg/dag/dag_test.go
pkg/dag/mocks/dag_mock.go
pkg/dag/vertex_test.go

add dag interface, for find all start of vertex and all end of vertex

feat: add dag interface

---

scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/testdata/scheduler.yaml

add config for machine learning

feat: scheduler add training config

---

scheduler/scheduler/scheduler_test.go

- Find parent with ancestor testing.

test: find parent with ancestor

---

client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
deploy/docker-compose/template/dfget.template.yaml
deploy/docker-compose/template/seed-peer.template.yaml
test/testdata/k8s/proxy.yaml

fix: dfdaemon unix socket

---

pkg/source/clients/ossprotocol/oss_source_client.go

Signed-off-by: bigerous <bigerous@qq.com>

fix oss client judge directory bug

---

cmd/scheduler/cmd/root.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml

feat: scheduler sets workhome

---

pkg/dag/dag.go
pkg/dag/dag_test.go
pkg/dag/mocks/dag_mock.go

fix: random vertices

---

client/daemon/peer/peertask_conductor.go

Signed-off-by: bigerous <bigerous@qq.com>

fix one piece task sometimes backsource after succeed

---

client/daemon/peer/peertask_conductor.go

fix: wait first peer packet fail

---

client/daemon/peer/piece_manager.go

fix: auto switch to concurrent back source

---

pkg/source/clients/httpprotocol/header.go

- Dfdaemon add `Authorization` and `WWWAuthenticate` headers.

feat: dfdaemon add Authorization and WWWAuthenticate headers

---

internal/dflog/logger.go
internal/job/constants.go
internal/job/job.go
manager/job/job.go
manager/service/job.go

feat: store preheat result

---

build/package/docs/dfget.1
build/package/docs/dfget.1.md

- Add daemon-socket for daemon docs.

docs: add daemon-socket for daemon docs

---

client/daemon/daemon.go
client/daemon/rpcserver/rpcserver.go

fix: check same peer id for sync pieces

---

client/daemon/daemon.go

fix daemon socket remove error

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/cache/cache.go
manager/config/config.go
manager/config/config_test.go
manager/config/constants.go
manager/config/testdata/manager.yaml
manager/database/redis.go
manager/handlers/application.go
manager/handlers/bucket.go
manager/handlers/config.go
manager/handlers/job.go
manager/handlers/model.go
manager/handlers/oauth.go
manager/handlers/preheat.go
manager/handlers/scheduler.go
manager/handlers/scheduler_cluster.go
manager/handlers/security_group.go
manager/handlers/security_rule.go
manager/handlers/seed_peer.go
manager/handlers/seed_peer_cluster.go
manager/middlewares/error.go
manager/router/router.go
manager/service/mocks/service_mock.go
manager/service/model.go
manager/service/service.go
manager/types/model.go

- Manager adds model and model version api.

feat: manager adds model and model version api

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/types/model.go

feat: change update model api

---

scheduler/resource/peer.go
scheduler/resource/peer_test.go
scheduler/resource/seed_peer.go
scheduler/scheduler/evaluator/evaluator_base.go
scheduler/scheduler/evaluator/evaluator_base_test.go
scheduler/scheduler/scheduler_test.go
scheduler/service/service.go
scheduler/service/service_test.go

- Schedulers create main peer record.

feat: schedulers create main peer record

---

manager/manager.go
scheduler/scheduler.go

- Scheduler and manager change graceful stop timeout.

feat: scheduler and manager change graceful stop timeout

---

scheduler/config/dynconfig.go
scheduler/config/dynconfig_test.go
scheduler/resource/peer_test.go

- Scheduler dynconfig returns more info.
#1329

feat: scheduler dynconfig returns more info

---

go.mod
internal/job/logger.go
pkg/gc/gc.go
pkg/gc/logger.go

feat: gc removes logrus

---

client/daemon/daemon.go
client/daemon/peer/piece_downloader.go

feat: add seed trace

---

scheduler/resource/peer.go
scheduler/resource/peer_test.go

- Fix scheduler's `MainParent` func.

fix: scheduler's MainParent func

---

client/daemon/daemon.go
manager/rpcserver/rpcserver.go
pkg/rpc/manager/client/client.go
scheduler/scheduler.go
scheduler/service/service.go

- Fix scheduler and manager tracing.

fix: scheduler and manager tracing

---

manager/router/router.go

- Model and model version api removes auth.

feat: model and model version api removes auth

---

manager/manager.go
scheduler/scheduler.go
scheduler/storage/mocks/storage_mock.go
scheduler/storage/storage.go
scheduler/storage/storage_test.go

- Storage calculate the count of records.

feat: storage calculate the count of records

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/service/model.go
manager/types/model.go

- Model version add training result.

feat: model version add training result

---

client/config/dynconfig_manager.go
client/config/dynconfig_manager_test.go
client/config/dynconfig_test.go
client/daemon/daemon.go
pkg/rpc/manager/client/client.go
pkg/rpc/manager/client/mocks/client_mock.go
scheduler/config/dynconfig.go
scheduler/config/dynconfig_test.go
scheduler/scheduler.go

feat: manager client add context

---

client/config/dynconfig.go
client/config/dynconfig_local.go
client/config/dynconfig_manager.go
client/config/mocks/dynconfig_mock.go
scheduler/config/dynconfig.go
scheduler/config/mocks/dynconfig_mock.go

feat: dynconfig add refresh func

---

scheduler/job/job.go

fix: scheduler can not exit gracefully due to machinery fatal log

---

pkg/reachable/reachable.go
pkg/resolver/scheduler_resolver.go
pkg/resolver/seed_peer_resolver.go
pkg/rpc/cdnsystem/server/server.go
pkg/rpc/dfdaemon/server/server.go
pkg/rpc/manager/server/server.go
pkg/rpc/scheduler/server/server.go

- GRPC removes MaxConnectionIdle.

feat: grpc removes MaxConnectionIdle

---

pkg/rpc/cdnsystem/client/client.go
pkg/rpc/client.go
pkg/rpc/client_util.go
pkg/rpc/interceptor.go
pkg/rpc/scheduler/client/client.go

- Add grpc client error interceptor.

feat: add grpc client error interceptor

---

client/config/dynconfig_manager.go
scheduler/config/dynconfig.go

- Dynconfig refresh and notify listeners.

feat: dynconfig refresh and notify listeners

---

client/daemon/daemon.go

- Fix dfdaemon can not shutdown.

fix: dfdaemon can not shutdown

---

pkg/rpc/dfdaemon/client/client.go

- Dfdaemon add convert interceptor.

feat: dfdaemon add convert interceptor

---

go.mod
go.sum
manager/manager.go
manager/rpcserver/cert.go
manager/rpcserver/cert_test.go
manager/rpcserver/rpcserver.go
pkg/rpc/manager/server/server.go

feat: manager implements issue certificate grpc

---

manager/config/config.go
manager/config/config_test.go
manager/config/testdata/manager.yaml
manager/manager.go
manager/rpcserver/cert.go
manager/rpcserver/cert_test.go
manager/rpcserver/rpcserver.go

- Manager add certificate config.

feat: manager add certificate config

---

client/config/dfget_darwin.go
client/config/dfget_linux.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon_linux.go
client/daemon/daemon_stub.go
pkg/dfpath/dfpath_darwin.go
pkg/dfpath/dfpath_linux.go

feat: remove golang +build tag

---

pkg/balancer/consistent_hashing.go
pkg/resolver/scheduler_resolver.go
pkg/resolver/seed_peer_resolver.go

- Consistent hashing add picker log.

feat: consistent hashing add picker log

---

client/daemon/daemon.go
client/daemon/peer/peertask_piecetask_poller.go
client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/rpcserver/rpcserver_test.go
client/daemon/rpcserver/seeder_test.go
cmd/dfcache/cmd/root.go
cmd/dfget/cmd/daemon.go
cmd/dfget/cmd/root.go
pkg/rpc/cdnsystem/client/client.go
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/manager/client/client.go
pkg/rpc/scheduler/client/client.go
scheduler/resource/seed_peer_client.go
scheduler/scheduler.go

feat: grpc dial adds context

---

manager/config/config.go
manager/config/constants.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go

- Add default metrics address.

feat: add default metrics address

---

go.mod
go.sum
manager/metrics/metrics.go
manager/rpcserver/rpcserver.go

- PeerGauge adds version and commit labels.

feat: PeerGauge adds version and commit labels

---

client/config/peerhost.go
client/daemon/daemon.go
pkg/cache/certify.go

feat: support multiple certify cache

---

manager/rpcserver/rpcserver.go
pkg/rpc/manager/server/server.go

chore: update new manager

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/peer/peertask_reuse_test.go
client/daemon/peer/peertask_stream_backsource_partial_test.go

feat: add client grpc dial timeout

---

client/config/peerhost.go
client/config/peerhost_test.go
cmd/dependency/dependency.go
manager/config/config.go
manager/manager.go
pkg/serialize/pemcontent.go

feat: add common serialize package

---

client/daemon/daemon.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_file.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/peer/peertask_reuse.go
client/daemon/peer/peertask_reuse_test.go
client/daemon/peer/peertask_stream.go
client/daemon/peer/peertask_stream_backsource_partial_test.go
client/daemon/peer/piece_manager.go

feat: refactor peertask option

---

client/daemon/daemon.go
manager/config/config.go
manager/manager.go
manager/rpcserver/cert.go
manager/rpcserver/cert_test.go
manager/rpcserver/rpcserver.go
pkg/cache/certify.go
pkg/issuer/dragonfly_manager.go
pkg/rpc/credential.go

- manager init cert for grpc server.

feat: manager init cert for grpc server

---

client/config/fixme.go
client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
client/daemon/peer/piece_manager.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/seeder.go
internal/dflog/logger.go
pkg/rpc/mux.go
pkg/rpc/mux_test.go

Support both of tls and non-tls grpc server

feat: add grpc mux transport

---

scheduler/metrics/metrics.go
scheduler/service/service.go

chore: add source error metrics

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
pkg/rpc/credential.go
pkg/serialize/pemcontent.go

feat: add tls policy constants

---

.github/workflows/ci.yml
client/config/peerhost_darwin.go

Docker installs in macos-latest refer to https://github.com/actions/runner-images/issues/17.

chore: fix macos build

---

.github/workflows/ci.yml

fix: ci actions with docker

---

manager/config/config.go
manager/config/config_test.go
manager/config/testdata/manager.yaml
manager/manager.go
pkg/rpc/credential.go
pkg/rpc/mux.go

- Add tls policy to manager grpc server.

feat: add tls policy to manager grpc server

---

client/config/dynconfig_local.go
client/config/dynconfig_local_test.go
client/config/dynconfig_manager.go
client/config/dynconfig_manager_test.go
scheduler/config/dynconfig.go

- Resolver addr add ServerName.

feat: resolver addr add ServerName

---

pkg/issuer/dragonfly.go
pkg/issuer/dragonfly_manager.go

feat: set tls cert leaf

---

manager/config/config.go
manager/config/config_test.go
manager/config/constants.go
manager/config/testdata/manager.yaml
manager/manager.go
pkg/issuer/dragonfly.go
pkg/issuer/dragonfly_manager.go

feat: manager add cert spec

---

client/config/dynconfig_local.go
client/config/dynconfig_manager.go
scheduler/config/dynconfig.go

- Check whether scheduler is in the same cluster.

feat: check whether scheduler is in the same cluster

---

client/daemon/rpcserver/rpcserver.go

chore: update debug info

---

.github/workflows/check-size.yml
.github/workflows/e2e.yml
test/testdata/charts/config-tls.yaml

chore: workflows add tls e2e

---

.github/dependabot.yml

- dependabot add github-actions.

chore: dependabot add github-actions

---

cmd/dfstore/cmd/copy.go
cmd/dfstore/cmd/root.go

- Fix dfstore flags invalid.
Fixes #1640

fix: dfstore flags invalid

---

hack/build.sh

fix: manager embed assets

---

client/config/dynconfig_manager.go

feat: add missing client version for ListSchedulers

---

build/package/nfpm/config/dfget.yaml
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
deploy/docker-compose/template/dfget.template.yaml
deploy/docker-compose/template/seed-peer.template.yaml

- Change storage strategy to sample.

feat: change storage strategy to simple

---

manager/cache/cache.go
manager/rpcserver/rpcserver.go

- Stat peer metrics with memory cache.

feat: stat peer metrics with memory cache

---

build/package/nfpm/config/dfget.yaml
client/config/constants.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.yaml
deploy/docker-compose/template/dfget.template.yaml
test/testdata/k8s/proxy.yaml

feat: change dfdaemon rate limit

---

pkg/source/clients/httpprotocol/http_source_client.go

- Source changes ResponseHeaderTimeout and ExpectContinueTimeout.

feat: source changes ResponseHeaderTimeout and ExpectContinueTimeout

---

scheduler/resource/task.go
scheduler/resource/task_test.go
scheduler/scheduler/scheduler_test.go

fix: task CanBackToSource func

---

.github/workflows/e2e.yml
client/daemon/peer/piece_manager.go
client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_subtask.go
test/e2e/dfget_test.go
test/testdata/charts/config-disable-seed-peer.yaml
test/testdata/charts/config-tls.yaml
test/testdata/charts/config.yaml

- Disable seed peer in standalone action.
- Fix concurrent back source not work.

chore: actions disable seed peer

---

cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go
deploy/docker-compose/template/manager.template.yaml
deploy/docker-compose/template/scheduler.template.yaml
internal/job/job.go
manager/config/config.go
manager/config/config_test.go
manager/config/testdata/manager.yaml
manager/database/database.go
manager/database/redis.go
manager/job/job.go
manager/rpcserver/rpcserver.go
manager/service/job.go
manager/service/service.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/testdata/scheduler.yaml
scheduler/job/job.go

- Support redis cluster.
Fixes #1656

feat: support redis cluster

---

cmd/dfget/cmd/root.go

- Dfget supports config file.
Fixes #1665

feat: dfget supports config file

---

cmd/dfget/cmd/root.go
manager/config/config.go
scheduler/config/config.go

- Update helm-charts submodule version to support redis cluster.

chore: update helm-charts submodule version

---

manager/config/config.go
scheduler/config/config.go

fix: manager redis config convert

---

client/daemon/peer/peertask_manager_test.go
client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_subtask.go

feat: support download empty file

---

client/daemon/rpcserver/rpcserver.go

chore: update download rpc check

---

.golangci.yml
manager/config/config.go
manager/config/config_test.go
manager/config/testdata/manager.yaml

feat: manager add advertiseIP

---

deploy/docker-compose/docker-compose.yaml

feat: update docker compose image

---

client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_mock.go
client/daemon/peer/peertask_manager_test.go
client/daemon/rpcserver/rpcserver.go

* Fix: grpc download a new tidy file error

fix: grpc download tidy file error

---

.github/workflows/ci.yml

feat: enable ipv6 in unit test

---

go.mod
go.sum

chore: update api pkg

---

cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go
manager/cache/cache.go
manager/config/config.go
manager/config/config_test.go
manager/database/database.go
manager/database/mysql.go
manager/database/postgres.go
manager/manager.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/dynconfig_test.go
scheduler/resource/resource.go
scheduler/resource/resource_test.go
scheduler/rpcserver/rpcserver_test.go
scheduler/scheduler.go
scheduler/service/service.go
scheduler/service/service_test.go

- Refactor manager and scheduler config.

refactor: manager and scheduler config

---

pkg/source/clients/hdfsprotocol/hdfs_source_client.go
pkg/source/loader/hdfs.go

fix: hdfs not registered

---

scheduler/service/service.go

feat: optimize storage log

---

client/daemon/rpcserver/rpcserver_test.go
client/daemon/storage/local_storage_test.go
client/daemon/transport/transport_test.go
client/daemon/upload/upload_manager_test.go

test: remove test main

---

scheduler/service/service.go

feat: async create a record

---

.gitignore
client/config/dynconfig_local.go
client/daemon/daemon.go
deploy/docker-compose/docker-compose.yaml
deploy/docker-compose/template/dfget.template.yaml
deploy/docker-compose/template/manager.template.yaml
deploy/docker-compose/template/scheduler.template.yaml
deploy/docker-compose/template/seed-peer.template.yaml

fix: docker compose config

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/rpcserver_test.go

feat: support concurrent recursive download

---

pkg/source/clients/ossprotocol/oss_source_client.go
pkg/source/source_client.go

feat: oss get metadata

---

client/daemon/storage/storage_manager.go

chore: change disk usage debug log format to decimal

---

manager/searcher/searcher.go
manager/searcher/searcher_test.go
pkg/types/constants.go
scheduler/scheduler/evaluator/evaluator_base.go
scheduler/scheduler/evaluator/evaluator_base_test.go

- searcher calculates cluster type.

feat: searcher calculates cluster type

---

client/config/peerhost_darwin.go
scheduler/resource/task.go
scheduler/resource/task_manager.go
scheduler/resource/task_manager_test.go
scheduler/resource/task_test.go
scheduler/service/service.go
scheduler/service/service_test.go

- add `TaskStateLeave` to task.

feat: add TaskStateLeave to task

---

client/daemon/peer/piece_manager.go
pkg/source/clients/httpprotocol/http_source_client.go
pkg/source/clients/ossprotocol/oss_source_client.go
pkg/source/response.go

fix: backsource temporary error judgement

---

deploy/docker-compose/template/scheduler.template.yaml
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/testdata/scheduler.yaml
scheduler/resource/host_manager.go
scheduler/resource/host_manager_test.go
scheduler/resource/peer_manager.go
scheduler/resource/peer_manager_test.go
scheduler/resource/resource_test.go
scheduler/resource/task.go
scheduler/resource/task_manager.go
scheduler/resource/task_manager_test.go
scheduler/resource/task_test.go
scheduler/scheduler/evaluator/evaluator_base.go
scheduler/service/service.go
scheduler/service/service_test.go

- Remove task and host gc ttl.

feat: remove task and host gc ttl

---

pkg/source/clients/httpprotocol/http_source_client.go

- Add http request content log.

feat: http request content log

---

scheduler/resource/seed_peer.go

feat: add seed peer back source traffic

---

client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_sni.go

chore: make lru cache safe

---

scheduler/service/service.go
scheduler/service/service_test.go

- Overwrite task url and url meta.

feat: overwrite task url and url meta

---

deploy/docker-compose/template/scheduler.template.yaml

- Change docker compose task ttl.

chore: change docker compose task ttl

---

client/daemon/upload/upload_manager.go
go.mod
go.sum
internal/dflog/logcore.go
internal/dflog/logger.go
internal/dflog/loginit.go
manager/router/router.go

feat: gin logger rotation

---

client/daemon/transport/transport.go

chore: update roundtrip log

---

scheduler/resource/task.go
scheduler/service/service.go
scheduler/service/service_test.go

- Task state is`TaskStateRunning` can be registered.

feat: task state is TaskStateRunning can be registered

---

manager/types/scheduler_cluster.go
scheduler/rpcserver/rpcserver.go
scheduler/service/service.go

- Change FilterParentRangeLimit validation.

feat: change FilterParentRangeLimit validation

---

scheduler/resource/task.go
scheduler/resource/task_test.go
scheduler/service/service.go
scheduler/service/service_test.go

- Available peer includes state is PeerStatePending.

feat: available peer includes state is PeerStatePending

---

ADOPTERS.md

docs: add adopters.md

---

go.mod
go.sum
manager/config/config.go
pkg/objectstorage/constants.go
pkg/objectstorage/objectstorage.go
pkg/objectstorage/obs.go
pkg/objectstorage/oss.go
pkg/objectstorage/s3.go

feat: obs object storage support

---

client/daemon/peer/peertask_manager_mock.go
pkg/objectstorage/mocks/objectstorage_mock.go
pkg/objectstorage/objectstorage.go
pkg/objectstorage/obs.go
pkg/objectstorage/s3.go

- Refactor obs of objectstorage pkg.

refactor: obs of objectstorage pkg

---

pkg/rpc/cdnsystem/client/client.go
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/manager/client/client.go
pkg/rpc/scheduler/client/client.go

- grpc_retry removes WithPerRetryTimeout.

feat: grpc_retry removes WithPerRetryTimeout

---

client/daemon/peer/peertask_reuse.go
client/daemon/peer/peertask_reuse_test.go

chore: check reuse file

---

scheduler/resource/task.go
scheduler/resource/task_test.go
scheduler/service/service.go
scheduler/service/service_test.go

- Refactor scheduler registers task.

refactor: scheduler registers task

---

hack/gen-containerd-hosts.sh

add fallback registry mirror in gen-containerd-host.sh

fix: add fallback registry mirror in gen-containerd-host.sh

---

build/plugin-builder/Dockerfile
build/plugin-builder/build.sh

fix: plugin builder

---

ADOPTERS.md

chore: add intel to ADOPTERS.md

---

go.mod
go.sum

- Update grpc api proto verison.

chore: update grpc api proto verison

---

client/daemon/storage/local_storage.go
client/daemon/storage/storage_manager.go

fix: did not call scheduler leave tasks in forceGC

---

internal/dflog/logger.go

chore: add timestamp to stdout&stderr

---

client/daemon/daemon.go
client/daemon/storage/local_storage.go
pkg/rpc/scheduler/client/client.go

feat: daemon call leaveHost when exit

---

pkg/rpc/scheduler/client/client.go

feat: grpc scheduler client dial options

---

client/daemon/transport/transport.go

feat: add download header log

---

.github/workflows/e2e.yml
client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_mock.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/rpcserver_test.go
client/daemon/transport/transport.go
test/testdata/charts/config-split-running-tasks.yaml

feat: support split running tasks

---

scheduler/service/service.go

feat: add leave host logger

---

scheduler/resource/peer.go

fix: leave host

---

client/daemon/rpcserver/rpcserver.go

chore: add list log in rpc download

---

client/config/constants.go
client/config/constants_otel.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_reuse.go
client/daemon/rpcserver/rpcserver.go
client/daemon/transport/transport.go
cmd/dependency/dependency.go

feat: add otel trace in log

---

client/daemon/rpcserver/rpcserver.go

In gRPC, SendMsg method is not concurrency safe, we need fix it.
SendMsg Method Not-Concurrency Safe: https://github.com/grpc/grpc-go/issues/2094

chore: make SendMsg in doRecursiveDownload safe

---

client/daemon/peer/peertask_conductor.go

the otelgrpc need cancel the context manully, otherwise the goroutine will leak.
```
goroutine 276077 [chan receive, 82 minutes]:
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamClientInterceptor.func1.1()
/home/admin/159_20221017150236344_419598893_code/rpm_workspace/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.1/interceptor.go:295 +0x53
created by go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.StreamClientInterceptor.func1
/home/admin/159_20221017150236344_419598893_code/rpm_workspace/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.1/interceptor.go:294 +0x8b3
```

fix: otel goroutine leak

---

go.mod
go.sum
scheduler/resource/seed_peer.go

- Statistical the traffic of reused peer.

feat: statistical the traffic of reused peer

---

client/daemon/peer/peertask_piecetask_synchronizer.go

chore: close out of use client grpc conn

---

scheduler/resource/seed_peer.go
scheduler/service/service.go

- `peer.UpdateAt` needs to be updated during download process.

feat: peer.UpdateAt needs to be updated during download process

---

scheduler/resource/peer_manager.go

feat: optimize peer gc

---

client/daemon/peer/peertask_manager_mock.go
manager/job/preheat.go
scheduler/job/job.go

feat: optimize preheat

---

client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_test.go
client/daemon/storage/storage_manager.go

chore: daemon avoid alway open metadata files

---

client/daemon/rpcserver/seeder.go

feat: seed peer reuses traffic

---

internal/dflog/logger.go
internal/job/job.go
manager/job/preheat.go
manager/service/job.go

feat: optimize preheat log

---

.github/workflows/e2e.yml
Makefile
client/dfget/dfget.go
hack/install-e2e-test.sh
pkg/source/clients/s3protocol/s3_source_client.go
pkg/source/loader/s3.go
test/e2e/concurrency_test.go
test/e2e/containerd_test.go
test/e2e/dfget_test.go
test/e2e/e2e_test.go
test/e2e/manager/preheat.go
test/testdata/charts/config-cache-list-metadata.yaml
test/testdata/k8s/minio.yaml
test/tools/download-grpc-test/main.go

feat: add s3 resource client

---

internal/dflog/logger.go
scheduler/job/job.go
scheduler/resource/host.go
scheduler/resource/peer.go
scheduler/resource/peer_manager.go
scheduler/resource/task.go
scheduler/service/service.go

feat: optimize peer log

---

client/config/dynconfig_local.go
client/config/dynconfig_local_test.go
client/config/dynconfig_manager.go
client/config/dynconfig_manager_test.go
manager/job/preheat.go
pkg/rpc/cdnsystem/client/client.go
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/manager/client/client.go
pkg/rpc/scheduler/client/client.go
scheduler/config/constants.go
scheduler/config/dynconfig.go
scheduler/job/job.go
scheduler/resource/resource.go
scheduler/resource/seed_peer.go
scheduler/resource/seed_peer_mock.go
scheduler/scheduler.go

- Add timeout to grpc and job.

feat: add timeout grpc and job

---

scheduler/service/service.go

- Optimize scope size is error.

feat: optimize scope size is error

---

.github/workflows/lint.yml
client/util/types.go
go.mod
go.sum
manager/handlers/bucket.go
manager/handlers/model.go
pkg/dag/dag.go
pkg/rpc/server_listen.go

- Update `concurrent-map` version.
- Update `golangci-lint` and fix lint error.

feat: update concurrent-map version

---

pkg/source/clients/httpprotocol/http_source_client.go
pkg/source/clients/ossprotocol/oss_source_client.go
pkg/source/clients/s3protocol/s3_source_client.go
pkg/source/header.go
pkg/source/response.go

chore: remove unused code

---

test/e2e/dfget_test.go

chore: update e2e test

---

client/daemon/rpcserver/rpcserver.go

fix: recursive download always return none error

---

client/daemon/peer/peertask_conductor.go

chore: update dst peer log

---

client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/config/peerhost_test.go
client/daemon/daemon.go
client/daemon/peer/peertask_dummy.go
go.mod
go.sum
manager/model/seed_peer.go
pkg/balancer/consistent_hashing.go
pkg/rpc/scheduler/client/client.go
pkg/rpc/scheduler/client/mocks/client_mock.go
pkg/types/types.go
scheduler/config/dynconfig_test.go
scheduler/metrics/metrics.go
scheduler/resource/host.go
scheduler/resource/host_manager.go
scheduler/resource/host_manager_test.go
scheduler/resource/host_test.go
scheduler/resource/peer_test.go
scheduler/resource/seed_peer_client.go
scheduler/resource/seed_peer_client_test.go
scheduler/resource/task.go
scheduler/resource/task_test.go
scheduler/rpcserver/rpcserver.go
scheduler/scheduler/evaluator/evaluator_base.go
scheduler/scheduler/evaluator/evaluator_base_test.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go
scheduler/service/service.go
scheduler/service/service_test.go

feat: scheduler adds announce host handler

---

manager/rpcserver/rpcserver.go

feat: optimize manager log

---

client/config/dynconfig_local.go
client/config/dynconfig_manager.go
pkg/gc/gc.go
scheduler/config/dynconfig.go

feat: optimize gc package

---

manager/types/scheduler_cluster.go

- Manager changes `filterParentLimit` value.

feat: manager changes filterParentLimit value

---

scheduler/config/config.go
scheduler/config/constants.go
scheduler/scheduler.go
scheduler/storage/storage.go
scheduler/storage/storage_test.go

- Scheduler supports storage config.

feat: scheduler supports storage config

---

scheduler/service/service.go

-  destPeer keepalive when downloaded by other peer
- remove redundant scheduling when failed peer is already be blocked

Fix: [scheduler]  destPeer keepalive when downloaded by other peer

---

ADOPTERS.md

- Add `Kuaishou` to `ADOPTERS.md`.

chore: add Kuaishou to ADOPTERS.md
