dragonflyoss/dragonfly

.github/CODEOWNERS

- fix `CODEOWNERS` function
#178 
N/A

Fix CODEOWNERS team function

---

client/config/dfget.go
client/daemon/service/manager.go
cmd/dfget/cmd/root.go

When output parent directory is not exist, dfget should create the directory.
#187

Create output parent directory if not exists

---

client/config/peerhost.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.json
client/config/testdata/config/daemon.yaml
client/daemon/proxy/proxy.go
client/daemon/transport/transport.go
client/daemon/transport/transport_test.go
go.mod
go.sum

- Fix assert.EqualValues is useless for CertPool
- Add CertPool custom Unmarshal
- Refactor transport
#206 
N/A

Fix config test

---

README.md
docs/README.md
docs/en/README.md
docs/en/config/dfget.yaml
docs/en/ecosystem/Harbor-with-Dragonfly.md
docs/en/ecosystem/Kubernetes-with-Dragonfly.md
docs/en/user-guide/quick-start.md

Feature: update docs

---

internal/dynconfig/dynconfig.go
scheduler/config/dynconfig.go

When there is some directories in `cdnDir`, `ioutil.ReadFile(filepath.Join(d.cdnDirPath, file.Name()))` will always fail.

Fix: when load config from cdn directory in dynconfig, skip sub directories

---

pkg/rpc/client.go

Currently, we didn't use resolver server config in grpc.
Disable resolver server config to fix #315 
#315

Feature: disable resolver server config

---

client/dfget/dfget.go
cmd/dfget/cmd/root.go

1. Use for loop with buffered channel and time.After to control timeout
2. refactor some redundant log and variable
https://github.com/dragonflyoss/Dragonfly2/issues/343
1. When dfdaemon is unavailable, dfget will stuck in health checking for a long time. This will slow downloading task. 
Now timeout works.

fix: check health too long when dfdaemon is unavailable

---

scheduler/manager/cdn_manager.go

Due to the incorrect identification of the CDN by Schuler, the same CDN corresponds to multiple hosts in the scheduler
fix #354

Correct CDN UUID in scheduler

---

deploy/charts/dragonfly/README.md
deploy/charts/dragonfly/templates/NOTES.txt
deploy/charts/dragonfly/templates/dfdaemon/dfdaemon-configmap.yaml
deploy/charts/dragonfly/templates/jaeger.yaml
deploy/charts/dragonfly/values.yaml

Add jaeger for helm deployment.

Add jaeger for helm deployment

---

go.mod
scheduler/service/worker/woker.go
scheduler/types/peer_task.go
scheduler/types/peer_task_test.go

scheduler only processes one peer task status at the same time, and will discard others. it is wrong.
we should set status diffrent priority level, while status with higher  level should not be discarded.

Fix: add process level for scheduler peer task status

---

cdnsystem/config/config.go
cdnsystem/server/server.go
scheduler/config/config.go
scheduler/config/config_darwin.go
scheduler/config/config_linux.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml
scheduler/server/server.go

feat: host info

---

manager/database/database.go
manager/model/scheduler_cluster.go
manager/service/scheduler_cluster.go
manager/types/scheduler_cluster.go

- Add `is_default` to `SchedulerCluster` table
Fixes #456

feat: add is_default to SchedulerCluster table

---

manager/server/server.go
manager/service/service.go
manager/service/service_grpc.go

- refactor manager server new params.

refactor: manager server new params

---

client/daemon/service/manager.go
pkg/rpc/cdnsystem/client/client.go
pkg/rpc/client.go
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/dfdaemon/client/peer.go

fix the address (addr) typo and improvement a comment.

Fix address typo

---

deploy/charts/dragonfly/values.yaml
docs/en/config/dfget.yaml
docs/en/ecosystem/Kubernetes-with-Dragonfly.md
docs/en/user-guide/registry-mirror/cri-containerd.md

Update multiple registries support docs

---

cdnsystem/daemon/cdn/cache_writer.go

Fix cdn back source range size overflow

---

manager/manager.go
manager/proxy/proxy.go
scheduler/scheduler.go

Signed-off-by: baimo.qwb@antfin.com <baimo.qwb@antfin.com>
- Optimize manager startup process.

feat: optimize manager startup process

---

client/dfget/dfget.go
cmd/dfget/cmd/root.go

Signed-off-by: zuozheng.hzz <zuozheng.hzz@alibaba-inc.com>
#563

fix: adjust dfget download log

---

scheduler/scheduler.go

feat: empty scheduler job

---

cdnsystem/supervisor/cdn/storage/disk/disk.go
cdnsystem/supervisor/mock/mock_task_mgr.go
cdnsystem/supervisor/task/manager.go
cdnsystem/supervisor/task_mgr.go

When cdn check task existence in gc, it will call taskMgr.Get which will update the accessTimeMap in manager. I add a Exist method to replace the Get in gc.

Add a function to check task existence in cdn

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/router/router.go
manager/service/scheduler_cluster.go
manager/types/scheduler_cluster.go

- Add cdn cluster id for scheduler cluster.

feat: add cdn cluster id for scheduler cluster

---

client/daemon/peer/peertask_base.go
client/daemon/peer/peertask_file.go
client/daemon/peer/peertask_file_callback.go
client/daemon/peer/peertask_stream.go
client/daemon/peer/peertask_stream_callback.go

Optimize backsource logic and report peer result

---

pkg/rpc/cdnsystem/client/client.go
pkg/rpc/cdnsystem/client/piece_seed_stream.go
pkg/rpc/cdnsystem/server/server.go
pkg/rpc/client.go
pkg/rpc/client_util.go
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/dfdaemon/client/down_result_stream.go
pkg/rpc/scheduler/client/client.go
pkg/rpc/scheduler/client/peer_packet_stream.go
scheduler/core/scheduler/basic/basic_scheduler.go
scheduler/core/service.go

refactor communication framework.

Framework refactor

---

go.mod
go.sum
manager/job/preheat.go

Replaces our current usage of docker/distribution with a more up-to-date release.

switch to distribution v3

---

client/config/peerhost.go
client/daemon/daemon.go
client/daemon/peer/peertask_base.go
client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_manager.go
client/daemon/proxy/proxy_sni.go

Add sni proxy support

---

manager/handlers/user.go
manager/middlewares/jwt.go
manager/middlewares/rbac.go
manager/model/user.go
manager/router/router.go
manager/service/cdn.go
manager/service/cdn_cluster.go
manager/service/oauth.go
manager/service/scheduler.go
manager/service/scheduler_cluster.go
manager/service/security_group.go
manager/service/service.go
manager/service/user.go

- Enable jwt.
- Enable rbac.
- Add user's display interface.
- Fix the resource not found destroy report 404.
- Fix frontend router conflict.

feat: enable manager user's features

---

cmd/dfget/cmd/root.go

When I added two or more headers in dfget, it will meet error like `net/http: invalid header field name "[Accept"` with an unexpected "[", I find that it is because of viper.
We can notice that the type StringArray is treat as String(default) in the following codes in viper, and the ValueString method of StringArray will add the "[" and "]".
So I suppose that we should use StringSlice instead of StringArray.

fix: use string slice for header

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.yaml
client/daemon/daemon.go
client/daemon/peer/piece_downloader.go
client/daemon/peer/piece_downloader_test.go
client/daemon/peer/piece_manager.go
client/daemon/peer/piece_manager_test.go
docs/en/config/dfget.yaml

feat: add piece download timeout

---

docs/zh-CN/config/dfget.yaml

docs: update docs/zh-CN/config/dfget.yaml

---

cdnsystem/supervisor/cdn/cache_detector.go
cdnsystem/supervisor/cdn/downloader.go
cdnsystem/supervisor/cdn/manager.go
cdnsystem/supervisor/cdn/storage/hybrid/hybrid.go
cdnsystem/supervisor/task/manager.go
cdnsystem/supervisor/task/manager_util.go
cdnsystem/types/seed_task_info.go
pkg/source/httpprotocol/http_source_client.go
scheduler/core/events.go
scheduler/core/scheduler/basic/basic_scheduler.go
scheduler/core/service.go
scheduler/supervisor/host.go
scheduler/supervisor/peer.go
scheduler/supervisor/peer/manager.go
scheduler/supervisor/task.go
scheduler/supervisor/task/manager.go

Beautify scheduler/CDN log

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml
docs/en/user-guide/install/README.md
docs/zh-CN/user-guide/install/README.md

docs: install

---

MAINTAINERS.md

chore: add lucy-cl maintainer

---

build/package/nfpm/config/dfget.yaml
build/package/nfpm/dfget-postinstall.sh
build/package/nfpm/dfget-postremove.sh
build/package/nfpm/dfget-preremove.sh
build/package/nfpm/dfget.yaml

chore: update build package config

---

client/config/peerhost_darwin.go
client/config/peerhost_linux.go
docs/en/config/dfget.yaml
docs/zh-CN/config/dfget.yaml

chore: enable calculate digest

---

.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml

- E2E workflows remove goproxy.

chore: e2e workflows remove goproxy

---

pkg/rpc/manager/client/client.go
scheduler/config/mocks/manager_client_mock.go

- Add manager client list scheduler interface.

feat: add manager client list scheduler interface

---

docs/en/ecosystem/Kubernetes-with-Dragonfly.md
docs/zh-CN/ecosystem/Kubernetes-with-Dragonfly.md

docs: update kubernetes docs

---

client/daemon/storage/local_storage.go
client/daemon/storage/storage_manager.go

chore: optimize client storage gc log

---

scheduler/core/evaluator/basic/basic_evaluator.go
scheduler/supervisor/peer.go

if peer's host is CDN, peer has the lowest priority among all peers with the same number of pieces. This prevents clients from downloading data from the CDN preferentially, which may occupy the BANDWIDTH of the CDN
fix #788

Avoid using up the bandwidth of the CDN

---

cmd/dependency/dependency.go
cmd/dependency/plugin_cmd.go
internal/dfplugin/dfplugin.go

feat: support list plugin

---

docs/en/deployment/configuration/cdn.yaml
docs/en/deployment/configuration/manager.yaml
docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/cdn.yaml
docs/zh-CN/deployment/configuration/manager.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml

- Add metrics configuration document.

docs: metrics configuration

---

build/images/manager/Dockerfile

feat: update manager image

---

manager/searcher/searcher.go
manager/searcher/searcher_test.go
manager/searcher/testdata/main.go
manager/searcher/testdata/plugin/searcher.go
manager/service/service_grpc.go

- Add context for FindSchedulerCluster.

feat: add context for FindSchedulerCluster

---

manager/searcher/searcher.go
manager/searcher/searcher_test.go
manager/searcher/testdata/main.go
manager/searcher/testdata/plugin/searcher.go
manager/service/service_grpc.go

- searcher plugin change return params.

feat: searcher plugin change return params

---

cdn/supervisor/cdn/cache_data_mgr.go
cdn/supervisor/cdn/cache_detector.go
cdn/supervisor/cdn/cache_detector_test.go
cdn/supervisor/cdn/cache_writer.go
cdn/supervisor/cdn/cache_writer_test.go
cdn/supervisor/cdn/manager.go
cdn/supervisor/cdn/storage/disk/disk.go
cdn/supervisor/cdn/storage/hybrid/hybrid.go
cdn/supervisor/cdn/storage/mock/mock_storage_mgr.go
cdn/supervisor/cdn/storage/path_util.go
cdn/supervisor/cdn/storage/storage.go
cdn/supervisor/cdn/storage/storage_gc.go
cdn/supervisor/progress/manager.go
client/daemon/peer/peertask_file_callback.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_reuse.go
client/daemon/peer/peertask_stream.go
client/daemon/peer/peertask_stream_callback.go
client/daemon/peer/piece_manager.go
client/daemon/storage/const.go
client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_test.go
client/daemon/storage/metadata.go
client/daemon/storage/storage_manager.go
client/daemon/test/mock/storage/manager.go
client/daemon/upload/upload_manager.go

correct metadata spell

---

cdn/supervisor/task/manager.go
cdn/types/seed_task_info.go
client/daemon/peer/piece_manager.go
pkg/source/hdfsprotocol/hdfs_source_client.go
pkg/source/hdfsprotocol/hdfs_source_client_test.go
pkg/source/httpprotocol/http_source_client.go
pkg/source/ossprotocol/oss_source_client.go
pkg/source/source_client.go

chore: update UnknownSourceFileLen

---

pkg/source/source_client.go

Fix load source plugins

---

client/daemon/peer/piece_manager.go
client/daemon/peer/piece_manager_test.go

fix: total pieces not set when back source

---

.gitignore
deploy/docker-compose/README.md
deploy/docker-compose/run.sh

feat: support create container without docker-compose

---

Makefile
build/package/nfpm/config/dfget.yaml
build/package/nfpm/dfget-postinstall.sh
build/package/nfpm/dfget-postremove.sh
build/package/nfpm/dfget-preinstall.sh
build/package/nfpm/dfget-preremove.sh
build/package/nfpm/dfget.yaml
build/package/nfpm/systemd/fix.dfget-daemon.cpuset.sh

feat: optmize dfget package upgrade support

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
client/daemon/peer/peertask_base.go
client/daemon/peer/peertask_file.go
client/daemon/peer/peertask_file_test.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_stream.go
client/daemon/peer/peertask_stream_backsource_partial_test.go
client/daemon/peer/peertask_stream_test.go
client/daemon/rpcserver/rpcserver.go
client/daemon/storage/local_storage.go

fix: infinitely get pieces when piece num is invalid

---

version/version.go

chore: add version metric

---

scheduler/core/events.go

We've removed 'peer' from current tree, and ScheduleChildren() set
'parent' as parent of peers in 'children', so we should inform children
that 'parent' is the destination peer, not the removed 'peer'.
Fixes: #956

fix: use 'parent' as mainPeer in PeerPacket in removePeerFromCurrentTree()

---

client/config/peerhost.go
client/daemon/daemon.go
client/daemon/metrics/metrics.go
client/daemon/peer/peertask_file.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_stream.go
client/daemon/proxy/proxy.go
client/daemon/transport/transport.go

feat: add daemon metrics support

---

client/config/peerhost.go
client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_test.go
docs/en/deployment/configuration/dfget.yaml
docs/zh-CN/deployment/configuration/dfget.yaml

Add a new field in registryMirror, allowing to use proxies list to decide whether to use dragonfly.
By doing this, it is now possible to cache more than only blobs/sha256 urls, allowing to use dragonfly2 for other usage thatn docker registries, like yum repositories.
Also fix the whiteList test which is tested on direct request, although host is empty and canno tbe tested.
Please update the documentation in Chinese, I just can't do it.
#959 
This PR now allows to use dragonfly to mirror yum repositories, at least.

Add useProxies to registryMirror allowing to mirror more anything

---

client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_test.go
docs/en/deployment/configuration/dfget.yaml
docs/zh-CN/deployment/configuration/dfget.yaml

Signed-off-by: momiji <teq1uila-free01@yahoo.fr>
Improve redirect usage to allow rewriting url in direct and proxy mode.
When redirect contains a `/`, it is considered as an rewrite url instead of a hostname replacement.
Rewrite is similar to apache ProxyPass directive everybody is used to.
#959 
With full url rewrite, it is now possible to completely change url and not only hostname.
It also applies to direct mode when useProxies is set, allowing to serve multiple (registry) mirrors based on the url.

feat: improve redirect to allow url rewrite

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/proxy/proxy.go
test/e2e/constants.go
test/e2e/dfget_test.go
test/e2e/e2e_test.go
test/e2e/e2eutil/artifact.go
test/testdata/charts/config.yaml
test/testdata/k8s/proxy.yaml

test: dump goroutine in e2e

---

client/config/constants.go
docs/en/deployment/configuration/dfget.yaml
docs/en/deployment/configuration/scheduler.yaml
docs/zh-CN/deployment/configuration/dfget.yaml
docs/zh-CN/deployment/configuration/scheduler.yaml
scheduler/config/config.go

feat: change task and peer ttl

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_file_test.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_stream_backsource_partial_test.go
client/daemon/peer/peertask_stream_test.go
client/daemon/peer/piece_manager.go
client/daemon/storage/local_storage.go
client/daemon/storage/metadata.go

When back source in daemon, if total pieces count is not settled, piece md5 is missed.

fix: total pieces count not set cause digest invalid

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_dummy.go
client/daemon/peer/peertask_manager_test.go

When scheduler is not available, replace the scheduler client in single peer task is okay.
We should not replace the scheduler client in peer task manager.

fix: when scheduler is not available, replace the scheduler client

---

deploy/docker-compose/config/scheduler.yaml
scheduler/resource/peer.go
scheduler/rpcserver/rpcserver.go
scheduler/rpcserver/rpcserver_test.go
scheduler/service/callback.go
scheduler/service/callback_test.go

- Set peer state to running when scope size is SizeScope_TINY.

feat: set peer state to running when scope size is SizeScope_TINY

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_test.go

When multiple same tasks come, we should register to schedulers only one.
So we need move registering after updated running tasks.

chore: register to scheduler after updated running tasks

---

scheduler/resource/peer.go
scheduler/resource/peer_test.go

- Scheduler download tiny file with range header and handle http error code.

feat: scheduler download tiny file with range header

---

client/daemon/peer/peertask_conductor.go

chore: update outdated log

---

test/testdata/charts/config.yaml

chore: add missing pod log in e2e

---

scheduler/resource/cdn.go
scheduler/resource/host.go
scheduler/resource/peer.go
scheduler/resource/peer_test.go
scheduler/service/callback.go

- When peers create a tree, no need to add peers to host and task.
Fixes #1043

feat: when peers create a tree, no need to add peers to host and task

---

scheduler/resource/peer.go
scheduler/resource/peer_test.go

1. Fix wrong range when download tiny file.
2. Fix wrong peer id when download tiny file from dfget daemon.
3. Update unit tests.

fix: scheduler download tiny file error

---

scheduler/resource/cdn.go

- Fixed not setting peer state to `PeerStateFailed` when cdn peer download failed.
Fixes #1065

fix: when cdn download failed, scheduler should set cdn peer state PeerStateFailed

---

scheduler/resource/peer.go

When a peer leaves, it calls scheduler's LeaveTask() interface to
notify scheduler that it's leaving. And LeaveTask() will re-schedule
all its children to find a new parent by calling ScheduleParent().
But some of this peer's children might be in PeerStateSucceeded
state, as they have finished downloading tasks from parent. So
ScheduleParent() on such children is pointless.
Let's delete peer's parent on PeerEventDownloadSucceeded event, so
its parent won't call ScheduleParent() on it again, when its parent
is leaving.

fix: delete peer's parent on PeerEventDownloadSucceeded event

---

manager/types/scheduler_cluster.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

- Scheduler add limit count of filter parent func.
- Default number of filter count is `5`.
- User can config `filter_parent_count` in manager console.
Fixes #1089

feat: scheduler add limit count of filter parent func

---

scheduler/resource/peer.go
scheduler/resource/peer_test.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

- Scheduler limit tree depth.
Fixes #1100

feat: scheduler limit tree depth

---

scheduler/service/service.go
scheduler/service/service_test.go

- When peer state is PeerStateSucceeded, return size scope is small.

fix: when peer state is PeerStateSucceeded, return size scope is small

---

client/daemon/peer/peertask_reuse.go
client/daemon/peer/peertask_reuse_test.go

1. rename `rg` to `reuseRange` to clarify purpose.
2. add missing `Content-Range` header for reusing subtasks.

chore: optimize reuse logic

---

cdn/rpcserver/rpcserver.go

Optimize get piece tasks log

---

scheduler/resource/cdn.go
scheduler/resource/peer.go

- Scheduler metrics add default value of biz tag.

feat: scheduler metrics add default value of biz tag

---

client/config/peerhost.go

fix daemon scheduler option validate bug

Fix daemon scheduler option validate bug

---

Makefile

chore: add makefile note

---

pkg/cache/cache_test.go

- Fix https://github.com/dragonflyoss/Dragonfly2/runs/5534319344?check_suite_focus=true

test: cache expire interval

---

manager/database/mysql.go
scheduler/config/dynconfig.go
scheduler/resource/cdn.go
scheduler/resource/cdn_test.go
scheduler/resource/host.go
scheduler/resource/host_test.go
scheduler/resource/peer.go
scheduler/scheduler/evaluator/evaluator_base_test.go
scheduler/scheduler/scheduler.go
scheduler/service/service.go

- When peer downloads finished, host remove peer.
- Since ReportPeerResult and ReportPieceResult are called in no order, the result may be reported after the register is successful. Fix state machine switching problem.

feat: when peer downloads finished, host remove peer and compatible with ReportPeerResult and ReportPieceResult are called in no order

---

cdn/supervisor/cdn/storage/disk/disk.go
cdn/supervisor/cdn/storage/disk/disk_test.go
cdn/supervisor/cdn/storage/hybrid/hybrid.go
cdn/supervisor/cdn/storage/path_util.go
cdn/supervisor/cdn/storage/storage_gc.go

Optimize CDN GC Debug log

---

client/clientutil/keepalive.go
client/daemon/daemon.go
client/daemon/peer/peerid_generator.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_stream_backsource_partial_test.go
client/daemon/peer/piece_downloader.go
client/daemon/peer/piece_manager.go
client/daemon/peer/piece_manager_test.go
client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_manager.go
client/daemon/storage/local_storage.go
client/daemon/transport/peerid_generator.go
client/daemon/transport/transport.go
client/daemon/transport/transport_test.go
pkg/source/httpprotocol/http_source_client.go

1. optimize back source trace and logic
2. fix keepalive performance
3. optimize generate peer id and transport performance
4. fix io.Copy call superfluous sendfile, then increase network latency

optimize proxy performance

---

client/config/dfget.go

If the client output parameter is not specified, the client cannot automatically obtain the target file path

Fix empty client output path

---

manager/database/mysql.go
scheduler/config/constants.go
scheduler/resource/cdn_test.go
scheduler/resource/host.go
scheduler/resource/host_test.go
scheduler/rpcserver/rpcserver.go
scheduler/scheduler/scheduler.go

- Change `DefaultSchedulerFilterParentLimit` value.
- Add default tag value for metrics.

feat: change default scheduler filter parent limit

---

test/e2e/manager/preheat.go

test: fix e2e preheat case

---

client/daemon/rpcserver/rpcserver_test.go
client/daemon/rpcserver/subscriber.go

fix: subscriber data race

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_reuse.go
client/daemon/storage/storage_manager.go
client/dfget/dfget.go
cmd/dfget/cmd/root.go
go.mod

replace time.Now().Sub by time.Since

replace time.Now().Sub by time.Since

---

client/daemon/daemon.go
client/daemon/daemon_test.go

- Dfdaemon get avaliable scheduler addresses in the same cluster

feat: dfdaemon get available scheduler addresses in the same cluster

---

manager/router/router.go

- Add RBAC to manager config interface.

feat: add rbac to manager config interface

---

manager/searcher/searcher.go
manager/searcher/searcher_test.go

- Dfdaemon match scheduler with case insensitive

feat: dfdaemon match scheduler with case insensitive

---

client/daemon/peer/peertask_stream.go
client/daemon/peer/piece_broker.go
client/daemon/peer/piece_broker_test.go

chore: optimize stream peer task

---

client/daemon/peer/peertask_conductor.go

In `waitFailedPiece` we receive a failed piece, then `pullPiecesFromPeers` loop go on and wait the `failedPieceCh` again,
if two failed piece sent to `failedPieceCh`, the first piece is missed.

fix: client miss failed piece

---

cdn/config/config_test.go
cdn/config/old_config.go
cdn/rpcserver/config.go
cdn/rpcserver/rpcserver.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/testdata/scheduler.yaml
scheduler/scheduler.go

- Update grpc listen address on scheduler and cdn.

feat: update grpc listen address on scheduler and cdn

---

manager/rpcserver/rpcserver.go
scheduler/resource/peer.go
scheduler/resource/task.go
scheduler/resource/task_test.go
scheduler/service/service.go
scheduler/service/service_test.go

if the number of failed peers in the task is greater than FailedPeerCountLimit, then scheduler notifies running peers of failure.
- If the number of failed peers in the task is greater than FailedPeerCountLimit, then scheduler notifies running peers of failure.

feat: if the number of failed peers in the task is greater than FailedPeerCountLimit, then scheduler notifies running peers of failure

---

manager/middlewares/error.go
manager/service/cdn_cluster.go
manager/service/scheduler_cluster.go

- Cannot delete a cluster with existing instances.

feat: cannot delete a cluster with existing instances

---

client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/subscriber.go

For legacy peers, when call SyncPieceTasks, we must receive at least one piece tasks.
If scheduler :
1. send to peer A with peer packet, main peer: peer x, steal peers: B
2. send to peer B with peer packet, main peer: peer x, steal peers: A
Both of peer A and peer B do not have any pieces, they will hang at receiving the first piece tasks.
So we need send an empty piece tasks to each others to avoid this hang bug.
Fix #1220

fix: sync pieces hang

---

client/daemon/peer/peertask_conductor.go

When all peers are using `SyncPieceTasks` GRPC,  `waitAvailablePeerPacket` will always timeout.
We need remove timeout check in `waitAvailablePeerPacket`.

fix: client unexpected timeout

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_poller.go
client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/rpcserver/subscriber.go

It is not safe to call SendMsg on the same stream in different goroutines at the same time.
Refer: https://github.com/grpc/grpc-go/blob/master/stream.go#L1405

fix: client sync send unsafe call

---

scheduler/service/service.go
scheduler/service/service_test.go

- `registerTask` returns to the task in time.

feat: registerTask returns to the task in time

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/rpcserver/subscriber.go
client/daemon/storage/local_storage.go
client/daemon/storage/storage_manager.go
internal/dflog/logger.go
pkg/safe/safe.go

1. https://github.com/dragonflyoss/Dragonfly2/blob/v2.0.2/client/daemon/rpcserver/subscriber.go#L100
When `err != ni`l, `request == nil`, and `stat.Code() != codes.Canceled`, `s.getPieces` will panic.
2. https://github.com/dragonflyoss/Dragonfly2/blob/v2.0.2/client/daemon/peer/peertask_conductor.go#L267
When register fail, `pt.cancel` will report peer result with `pt.schedulerClient`, while `pt.schedulerClient` is nil.

fix: client sync piece panic

---

cmd/dfget/cmd/daemon.go
manager/rpcserver/rpcserver.go
pkg/rpc/cdnsystem/server/server.go
pkg/rpc/dfdaemon/server/server.go
pkg/rpc/server.go
scheduler/rpcserver/rpcserver.go

1. The dfget daemon will be launched by dfget command in backgroud, the stdout and stderr will be lost.
So we need redirect them to log files.
2. Fix zap grpc log is always wrote to stderr.

feat: redirect daemon stdout stderr to file

---

scheduler/rpcserver/rpcserver.go
scheduler/service/service.go
scheduler/service/service_test.go

- Add `AnnounceTask` and `StatTask` tests.
- Refactor dferror message.

Add AnnounceTask and StatTask tests

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/subscriber.go

1. Cancel sync pieces when need back source.
2. Fix panic for inconsistently typed value for `pieceTaskSynchronizer.err`.
3. Fix cleanStaleWorker did not remove unused peers.

chore: optimize sync pieces

---

.github/workflows/ci.yml
.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml

- Add schedule cron with e2e testing.

chore: add schedule cron with e2e testing

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_piecetask_poller.go
client/daemon/peer/peertask_piecetask_synchronizer.go
pkg/rpc/cdnsystem/client/client.go
pkg/rpc/client.go
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/manager/client/client.go
test/e2e/dfget_test.go

1. Cancel the peer task in background when encounter report to scheduler err in sync manager
2. Remove superfluous retry to sync and get pieces from other peers to make sync pieces quickly.

fix: client synchronizer report error lock and dial grpc timeout

---

build/package/nfpm/systemd/dfget-daemon.service
build/package/nfpm/systemd/fix.dfget-daemon.cpuset.sh

fix: skip unsupported kernel in systemd service

---

scheduler/storage/storage_test.go

test: fix storage backups

---

scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

- When peer state is `PeerStateSucceeded`, it can be a parent.

feat: when peer state is PeerStateSucceeded, it can be a parent

---

scheduler/service/service.go
scheduler/service/service_test.go

- If cdn server's task has left and did not notify the schduler to leave the task, scheduler sets cdn peer state to `PeerStateLeave`.

fix: legacy cdn peer

---

cmd/dfget/cmd/daemon.go
cmd/dfget/cmd/daemon_dup2.go
cmd/dfget/cmd/daemon_dup3.go

feat: support build arm&&arm64 dfget

---

deploy/docker-compose/README.md
deploy/docker-compose/run.sh

Signed-off-by: AnJia <anjia0532@gmail.com>

fix: run.sh threw error on mac

---

client/daemon/transport/transport.go

`Accept` header should not be removed, issue: https://github.com/dragonflyoss/Dragonfly2/issues/1290
Fix #1290

fix: keep accept header

---

hack/protoc.sh

Add '--rm' option to docker command, so container will be removed
automatically. Otherwise we'll have many exited but not removed
containers as we run 'make protoc'.

fix: remove container after generating protoc

---

go.mod
go.sum
pkg/dfnet/dfnet.go
pkg/rpc/dfdaemon/client/client.go
pkg/rpc/vsock.go

So we support connecting dfdaemon running on host outside of VM via
virtio-vsock device.

feat: add vsock network type support

---

client/daemon/peer/peertask_reuse.go
client/daemon/rpcserver/seeder.go
client/daemon/storage/metadata.go
client/daemon/storage/storage_manager.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xd2ebae]
goroutine 447 [running]:
d7y.io/dragonfly/v2/client/daemon/rpcserver.(*seedSynchronizer).sendRemindingPieceSeeds(0xc000a41730, 0x1094bd9)
/go/src/d7y.io/dragonfly/v2/client/daemon/rpcserver/seeder.go:178 +0x8e
d7y.io/dragonfly/v2/client/daemon/rpcserver.(*seedSynchronizer).sendPieceSeeds(0xc000a41730)
/go/src/d7y.io/dragonfly/v2/client/daemon/rpcserver/seeder.go:146 +0x78c
d7y.io/dragonfly/v2/client/daemon/rpcserver.(*seeder).ObtainSeeds(0xc00000e528, 0xc000c52500, {0x12d6c10, 0xc0006a4380})
/go/src/d7y.io/dragonfly/v2/client/daemon/rpcserver/seeder.go:119 +0x753
```

fix: reuse seed panic

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/job/job.go
manager/job/preheat.go
manager/types/job.go
test/e2e/manager/preheat.go

- Custom preheat tag parameters.

feat: custom preheat tag parameters

---

scheduler/resource/seed_peer.go
scheduler/resource/task.go
scheduler/resource/task_test.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go
scheduler/service/service.go

- Scheduler handles seed peer failed.

feat: scheduler handles seed peer failed

---

build/images/cdn/Dockerfile
build/images/dfdaemon/Dockerfile
build/images/manager/Dockerfile
build/images/scheduler/Dockerfile

- GRPC health probe support arm64

feat: grpc health probe support arm64

---

client/daemon/metrics/metrics.go

- Fix dfdaemon seed peer metrics namespace.

fix: dfdaemon seed peer metrics namespace

---

client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_test.go

For range like: bytes=1024-, func `computePiecePosition` will return a negative end due to overflow, we need check the content length first.

fix: find partial completed overflow

---

.github/workflows/check-size.yml

chore: add check size action

---

pkg/util/net/iputils/ip_utils.go

Since commit 0bc0d3b7ead8 ("feat: add vsock network type support
(#1303)") we have vsock support, which means we could run dfget in a
constrained VM env that only has loopback net interface, and connect to
dfdaemon on host via vsock connection. So it's a valid setup to have no
external IPv4 addr.
Don't panic in this case and use "127.0.0.1" as IPv4.

feat: use 127.0.0.1 as IPv4 if there's no external IPv4 addr

---

.github/workflows/check-size.yml

chore: add check size workflows

---

manager/middlewares/jwt.go
manager/router/router.go

- Fix manager router middlewares order.

fix: manager router middlewares order

---

client/config/dfget.go
client/config/dfget_darwin.go
client/config/dfget_linux.go
client/dfget/dfget.go
cmd/dfget/cmd/root.go

Signed-off-by: ljx373327 <ljx373327@alibaba-inc.com>
fix dfget limit flag err
limit flag can't  use because deserialization failed
#1377
- fix failed to deserialize because of rate limit type error, replace with rate limit wrapper class
- fix flag limit and the keyword ratelimit do not match

fix ratelimit

---

cmd/dfget/cmd/root.go

Signed-off-by: ljx373327 <ljx373327@alibaba-inc.com>
dfget config fix
When dfget goes to start the daemon, the daemon can not be affected by the config flag
#1380
add config flag when dfget run daemon

dfget config fix

---

client/daemon/daemon.go
client/daemon/objectstorage/objectstorage.go
pkg/objectstorage/constants.go
pkg/objectstorage/objectstorage.go
pkg/objectstorage/oss.go
pkg/objectstorage/s3.go

- Dfdaemon add `GetObject` rest api.

feat: dfdaemon add GetObject rest api

---

client/dfget/dfget.go

In dragonfly v2.0.3, `func (client *httpSourceClient) Download(request *source.Request)` is rewrited, now when status code is not 200/206, it will not directly return error, instead, a status code validation function is assigned to `response.Validate()`.
https://github.com/dragonflyoss/Dragonfly2/blob/b705780a3340fd2f4a15b06483ea77ff7539be77/pkg/source/clients/httpprotocol/http_source_client.go#L185-L198
However, `downloadFromSource()` doesn't call `response.Validate()` to validate, so it will still copy response to target file and report success.
I added validation in `downloadFromSource()`, now it works well (see screenshot below).
https://github.com/dragonflyoss/Dragonfly2/issues/1397

fix: downloadFromSource() doesn't validate response

---

manager/config/config.go
manager/config/config_test.go
manager/config/testdata/manager.yaml
manager/database/mysql.go

Enable configuration of the tls parameter for the mysql connection. An example would be setting tls to "preferred", or "true". This is separate from the tlsConfig (renamed from tls) parameter in manager.yaml, which is used to setup a custom tls config, where tls key/certs are specified. This will fix the case where the manager cannot connect to a server that requires TLS.
See the tls parameter section in the below link:
https://pkg.go.dev/github.com/go-sql-driver/mysql#section-readme
https://github.com/dragonflyoss/Dragonfly2/issues/1299
Currently Manager cannot connect to a MySQL database that requires TLS, without fully configuring certs/keys (functionality added in https://github.com/dragonflyoss/Dragonfly2/pull/1015). By making this configurable, TLS can be used (even with only …

feat: enable configuration of the tls parameter for the mysql connection. i.e. tls=preferred

---

pkg/net/fqdn/fqdn.go

- If service can not found fqdn, replace fqdn with hostname.

feat: if service can not found fqdn, replace fqdn with hostname

---

client/daemon/upload/upload_manager.go

Signed-off-by: bigerous <bigerous@qq.com>
uploader should write header immediately, prevent client disconnecting after limiter.Wait() due to response header timeout

fix:upload_manager write header immediately when it is ready

---

pkg/slices/slices.go
pkg/slices/slices_test.go
scheduler/resource/peer.go
scheduler/resource/peer_test.go

Fix infinite loop in `peer.Ancestors()`.

fix: infinite loop in peer.Ancestors()

---

cmd/dfstore/cmd/root.go

- Fix dfstore command-line tool name.

fix: dfstore command-line tool name

---

client/config/peerhost.go
client/config/peerhost_test.go
client/config/testdata/config/daemon.yaml
client/daemon/peer/piece_manager.go
client/daemon/peer/piece_manager_test.go
deploy/docker-compose/template/dfget.template.yaml
test/testdata/charts/config.yaml
test/testdata/k8s/proxy.yaml

Signed-off-by: greenhandatsjtu <sunhengke@sjtu.edu.cn>
If the download speed of back source is slower than the threshold, dfdaemon wil automatically switch from single thread download to concurrent download.
Related PR: https://github.com/dragonflyoss/Dragonfly2/pull/1426

feat: auto switch to concurrent back source based on download speed

---

scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

- Can not return peer with the same host.
- Candidate parent host is not allowed to be the same as the peer host, because dfdaemon cannot handle the situation where two tasks are downloading and downloading each other.

feat: can not return peer with the same host

---

client/config/dfget.go
client/daemon/metrics/metrics.go
client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager.go
client/daemon/rpcserver/mocks/rpcserver_mock.go
client/daemon/rpcserver/rpcserver.go
pkg/rpc/dfdaemon/server/mocks/server_mock.go
pkg/rpc/dfdaemon/server/server.go

feat: support grpc recursive download

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.gitignore
.goreleaser.yml
Makefile
build/images/manager/Dockerfile
build/plugin-builder/images/manager/Dockerfile
client/daemon/daemon.go
client/daemon/rpcserver/rpcserver.go
deploy/docker-compose/template/manager.template.yaml
hack/build.sh
hack/gen-buildx.sh
manager/config/config.go
manager/config/config_test.go
manager/config/constants.go
manager/config/testdata/manager.yaml
manager/manager.go
manager/router/router.go
scheduler/scheduler/scheduler.go
scheduler/scheduler/scheduler_test.go

hotfix: peer with same host and manager embed assets

---

client/daemon/objectstorage/objectstorage.go

…to calculate md5
- When the request has a range header, object storage is no need to  to calculate md5.

feat: when the request has a range header, object storage is no need to  to calculate md5

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/piece_manager.go
scheduler/service/service.go

chore: optimize source error log

---

client/daemon/daemon.go
pkg/rpc/interceptor.go
scheduler/scheduler.go

- Refresh dynconfig addresses when grpc requests unavailable.

feat: refresh dynconfig addresses when grpc requests unavailable

---

pkg/rpc/cdnsystem/server/server.go
pkg/rpc/dfdaemon/server/server.go
pkg/rpc/manager/server/server.go
pkg/rpc/scheduler/server/server.go

- Add `MaxConnectionIdle`, `MaxConnectionAge` and `MaxConnectionAgeGrace` to grpc keepalive.

feat: add MaxConnectionIdle to grpc keepalive

---

manager/model/models.go

- Set created_at and updated_at type to timestamp, refer to https://dev.mysql.com/doc/refman/8.0/en/datetime.html.

feat: set created_at and updated_at to timestamp

---

client/daemon/peer/peertask_conductor.go
client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_subtask.go
client/daemon/storage/mocks/stroage_manager_mock.go
client/daemon/storage/storage_manager.go

The gc did not known which task is failed and mark it reclaim, we need unregister failed task storage first.

feat: unregister failed task storage

---

manager/service/scheduler_cluster.go
manager/service/seed_peer_cluster.go

- Fix gorm can not update `is_default` field, refer to https://stackoverflow.com/questions/56653423/gorm-doesnt-update-boolean-field-to-false.

fix: gorm can not update is_default field

---

pkg/source/clients/httpprotocol/http_source_client.go

feat: add http request log

---

scheduler/service/service.go
scheduler/service/service_test.go

- Peer will back-to-source when task switch state failed.

feat: peer will back-to-source when task switch state failed

---

.github/workflows/e2e.yml
client/daemon/objectstorage/objectstorage.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_reuse.go
client/daemon/peer/piece_manager.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/seeder.go
client/daemon/transport/transport.go
client/util/range.go
test/e2e/dfget_test.go
test/e2e/e2e_test.go

In open end range in concurrent back source like: `bytes=1-`, `parsedRange.Length` is not updated after got metadata.
This PR will fix it.

fix: open end range in concurrent back source

---

client/daemon/daemon.go

daemon don't leaveHost when keepStorage=true

fix: daemon don't leaveHost when keepStorage=true

---

client/daemon/rpcserver/rpcserver.go
pkg/source/header.go

The Expire header target format is GMT time, need convert local time to UTC time first before format.

fix: expire header timezone

---

client/config/dynconfig_manager.go
client/config/dynconfig_manager_test.go
client/config/dynconfig_test.go
manager/rpcserver/rpcserver.go

- when dfdaemon disable object storage, dynconfig can't fetch manager.

feat: when dfdaemon disable object storage, dynconfig can't fetch manager

---

scheduler/job/job.go

add username when create redis client

---

go.mod
go.sum
scheduler/service/service.go
scheduler/service/service_test.go

- If the scheduler cannot find the peer, then return `Code_SchedReregister` to dfdaemon.

feat: if the scheduler cannot find the peer, then return Code_SchedReregister to dfdaemon

---

test/testdata/charts/config-cache-list-metadata.yaml
test/testdata/charts/config-concurent-back-source.yaml
test/testdata/charts/config-disable-seed-peer.yaml
test/testdata/charts/config-grpc-tls-ipv6.yaml
test/testdata/charts/config-grpc-tls.yaml
test/testdata/charts/config-ipv6.yaml
test/testdata/charts/config-split-running-tasks.yaml
test/testdata/charts/config.yaml
test/testdata/k8s/proxy.yaml

- Remove `advertiseIP` config in e2e.

fix: remove advertiseIP config in e2e

---

client/daemon/peer/peertask_conductor.go

feat: corrupt data check

---

client/config/dynconfig_manager.go
scheduler/config/dynconfig.go

health client not close will cause go routines leak:

fix:scheduler's health client not close

---

manager/metrics/metrics.go
manager/rpcserver/rpcserver.go

- Searcher can not found candidate scheduler clusters, return all scheduler clusters.

feat: searcher can not found candidate scheduler clusters, return all scheduler clusters

---

client/daemon/peer/peertask_conductor.go
internal/dferrors/error.go
pkg/rpc/interceptor.go

The function `convertClientError ` is only invoked for initializing stream, not `Send` or `Recv`, for parsing `dferrors.DfError`, only call it manually.

fix: dferror not convert

---

.github/workflows/compatibility-e2e.yml
client/daemon/peer/piece_dispatcher_test.go
scheduler/announcer/announcer.go
scheduler/announcer/announcer_test.go
scheduler/config/dynconfig.go
scheduler/config/dynconfig_test.go
scheduler/config/mocks/dynconfig_mock.go
scheduler/resource/peer.go
scheduler/resource/peer_test.go
scheduler/resource/resource_test.go
scheduler/resource/seed_peer_client.go
scheduler/resource/seed_peer_client_test.go
scheduler/scheduler.go
scheduler/service/service_v1.go
scheduler/service/service_v1_test.go

- Refactor announcer and dynconfig with v2 verison of the manager grpc.

refactor: announcer and dynconfig with v2 verison of the manager grpc

---

scheduler/resource/peer_manager.go
scheduler/resource/peer_manager_test.go

- Fix peer GC clear all peers when peer's count large than PeerCountLimitForTask, refer to https://github.com/dragonflyoss/Dragonfly2/pull/2060.

fix: peer GC clear all peers when peer's count large than PeerCountLimitForTask

---

scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/testdata/scheduler.yaml

Signed-off-by: XZ <834756128@qq.com>
Add default networkTopology configuration.
Struct networkTopology includes parameters: Enable, SyncInterval, CollectInterval, Probe. 
Enable networkTopology services, including probe, network topology collection and synchronization service.
SyncInterval is the interval of synchronizing network topology between schedulers.
CollectInterval is the interval of collecting network topology.
Probe is the configuration of probe.
Struct Probe includes parameters: QueueLength, SyncInterval, SyncCount.
QueueLength is the length of probe queue in directed graph.
SyncInterval is the interval of synchronizing host's probes.
SyncCount is the number of probing hosts.

feat: add default networkTopology configuration

---

client/daemon/peer/peertask_conductor.go

When there is no seed peer cluster in a scheduler cluster, the first peers will back source, if the source is slow and reach schedule timeout, will cause first piece timeout error.

fix: backsource first piece timeout

---

pkg/cache/cache.go

So we can save a syscall stat(2) thus reducing a little overhead. The function MkdirAll will do nothing it the target dir is already existed.
Besides, Close() can only fail if it is ever called. We can safely simplify the code by `defer Close()`

cache: avoid checking dir existence before MkdirAll

---

client/daemon/storage/storage_manager.go

On graceful shutdown we will call forceGC() to delete all cached tasks if 'keepStorage' is false. And we rely on deleteTask() to delete the given task from both local storage and scheduler.
But commit 86a6030c8f10 ("feat: unregister failed task storage (#1717)") changed MarkReclaim() to MarkInvalid() in deleteTask(), and resulted in task leak in scheduler.
Fix it by calling MarkReclaim() in deleteTask().
Fixes: 86a6030c8f10 ("feat: unregister failed task storage (#1717)")

fix: unregister task from scheduler in storage.deleteTask

---

pkg/source/clients/ossprotocol/oss_source_client.go

Oss source client for now only supports accessKeyID+accessKeySecret access. To support STS access, one needs to provides security token to init oss Client. 
To perform sts access, user can set "securityToken" in DfgetConfig.Header in form of "SecurityToken: ******". getClient function of struct ossSourceClient will parsing this header and get "SecurityToken" item. Blank SecurityToken is allowed.

feat: oss client supports STS access (set security token in header)

---

client/config/dynconfig.go
client/config/dynconfig_local.go
client/config/dynconfig_local_test.go
client/config/dynconfig_manager.go
client/daemon/daemon.go

Dynconfig only supports refresh new configs from manager, but local dynconfig is unable to reload scheduler addresses when local config file is updated.
Now we introduce new Dynconfig method 'SetConfig()', which sets the given DaemonOption to struct dynconfigLocal, and register it as a watcher of WatchConfig(), which will reload config file periodically. So that dynconfigLocal.GetResolveSchedulerAddrs() will get new scheduler addresses.

feat: support reload scheduler addresses for local Dynconfig

---

client/config/dynconfig.go
client/config/dynconfig_local.go
client/config/dynconfig_local_test.go
client/config/dynconfig_manager.go
client/daemon/daemon.go

- Add OnNotify to client dynconfig, it will listen changes of the local configuration.

refactor: support reload scheduler addresses for local Dynconfig in client

---

pkg/source/clients/ossprotocol/oss_source_client.go

Make oss source downloads oss object concurrently by setting the "ContentLength" value of Source.Response.
df2 struct pieceManager calls DownloadSource() to download source objects. DownloadSource() firstly connect to source and get the response from source. Then, DownloadSource() checks the "ContentLength" value of the response. If it larger than 0, pieceManager will download the object by multiple threads. Unfortunately, oss client doesn't set ContentLength value, even thought ContentLength can be set by the oss.GetObjectResult.Response.Headers. So this patch add a line to set response a ContentLength value.

feat: enable oss client download object concurrently.

---

manager/rpcserver/manager_server_v1.go
manager/rpcserver/manager_server_v2.go
scheduler/metrics/metrics.go
scheduler/rpcserver/scheduler_server_v2.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

Correct grpc error from codes.Unknow to codes.Internal in gorm operation. Implement StatPeer and LeavePeer interface in v2 version of grpc.
- Correct grpc error code and implement StatPeer and LeavePeer.

feat: correct grpc error code and implement StatPeer and LeavePeer

---

client/config/peerhost.go

If gcInterval is set to 0s or negative value, dfdaemon will panic as
panic: non-positive interval for NewTicker
goroutine 132 [running]:
time.NewTicker(0x0?)
Fix it by validating it as well.

fix: validate daemon gcInterval config

---

client/daemon/peer/peertask_manager_mock.go
client/daemon/peer/piece_manager_mock.go
pkg/types/types.go
scheduler/metrics/metrics.go
scheduler/resource/seed_peer_mock.go
scheduler/rpcserver/scheduler_server_v1.go
scheduler/rpcserver/scheduler_server_v2.go
scheduler/service/service_v1.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

- Implement StatTask, AnnounceHost and LeaveHost api in scheduler service v2.

feat: implement v2 version of scheduler service

---

manager/permission/rbac/rbac.go

As API group regexp is reused when loading routes and the expression itself doesn't change, should make sense to compile it only once.
--
--
Improvement.

Compile API group regexp only once

---

go.mod
go.sum
manager/rpcserver/manager_server_v1.go
manager/rpcserver/manager_server_v2.go
scheduler/metrics/metrics.go
scheduler/resource/seed_peer.go
scheduler/rpcserver/scheduler_server_v1.go
scheduler/rpcserver/scheduler_server_v2.go
scheduler/service/service_v1.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

feat: add metrics to service v2

---

deploy/docker-compose/template/manager.template.yaml
manager/config/config.go
manager/config/config_test.go
manager/config/constants.go
manager/config/testdata/manager.yaml
manager/middlewares/jwt.go
manager/router/router.go
test/testdata/charts/config-nydus.yaml

Fix https://github.com/dragonflyoss/Dragonfly2/security/advisories/GHSA-hpc8-7wpm-889w.
- Add auth config to manager.
https://github.com/dragonflyoss/Dragonfly2/security/advisories/GHSA-hpc8-7wpm-889w

feat: add auth config to manager

---

scheduler/metrics/metrics.go
scheduler/service/service_v2.go

- Fix DownloadPeerCount and DownloadPieceCount metrics.

fix: stat DownloadPeerCount and DownloadPieceCount

---

hack/docker-build.sh

- add default build param GOOS GOARCH

feat:add default build param GOOS GOARCH

---

test/testdata/containerd/config.toml

Kubernetes is migrating its image registry from [[k8s.gcr.io](http://k8s.gcr.io/)](http://k8s.gcr.io/) to [[registry.k8s.io](http://registry.k8s.io/)](http://registry.k8s.io/).
Part of kubernetes/k8s.io#4780.
It's just changing some testing/fixture data so it's a benign change but I made it anyways.

chore: migrate from k8s.gcr.io to registry.k8s.io

---

scheduler/networktopology/probes.go
scheduler/networktopology/probes_test.go

CreatedAt is the function to get creation time of probes.

feat: add CreatedAt function

---

manager/rpcserver/manager_server_v1.go
manager/rpcserver/manager_server_v2.go
scheduler/networktopology/mocks/probes_mock.go

- Fix ip and hostname params in FindSchedulerClusters.

fix: ip and hostname params in FindSchedulerClusters

---

client/dfget/dfget.go
pkg/source/clients/orasprotocol/oras_source_client.go
pkg/source/source_client_builder.go

1. Rename AuthInfoInject to Director
2. Update oras resource logic
Fix #2215

feat: update resource director

---

scheduler/networktopology/probes.go
scheduler/networktopology/probes_test.go

Modify the traversal condition for Items.

fix: modify the traversal condition for Items

---

client/config/dynconfig_local.go

Dfdaemon will fail the health check if there is no available scheduler address. So in the case of local dynconfig, the address of scheduler should be passed. For dfdaemon health check, please refer to https://github.com/dragonflyoss/Dragonfly2/pull/2130.
Dfdaemon will fail the health check if there is no available scheduler address. So in the case of local dynconfig, the address of scheduler should be passed. For dfdaemon health check, please refer to https://github.com/dragonflyoss/Dragonfly2/pull/2130.

feat: local dynconfig notifies data in client

---

.github/workflows/docker.yml

Add multiple arch container images resolves #2269 
Manager cannot run on arm64 machine due to non supported architecture.
```
NotFound desc = failed to pull and unpack image "ghcr.io/dragonflyoss/dragonfly2/manager:v2.0.9": no match for platform in manifest: not found
```
Multi-arch capability

Add multi-arch container images to workflow

---

.github/workflows/docker.yml

Docker build job breaks due to workflow timeout limit at [Line24](https://github.com/dragonflyoss/Dragonfly2/blob/920e348f6d5e047d981996a3b9a556eb5a39cc6c/.github/workflows/docker.yml#L24)
```
crane config ghcr.io/dragonflyoss/dragonfly2/manager:latest@sha256:f896f04f90f8ccacf007f26c7513b3ff6068e96abddf2899982e90af89e6509d | jq
{
"architecture": "unknown",
"os": "unknown",
"config": {},
"rootfs": {
"type": "layers",
"diff_ids": [
"sha256:53247f5000d7fa895af6d05686da234ab9fad161739489c070b1ca6d2fa0cb37"
]
}
}
```
Increase timeout limit on the pipeline. 
Issue: #2271 
Arm64 architecture images released except Manager image.

Github docker workflow timeouts while building manager image

---

scheduler/config/config.go
scheduler/config/config_test.go

- When Redis is in cluster mode, only DB 0 can be used.

fix: redis validation in scheduler config

---

client/daemon/peer/piece_manager.go

When apply `SyncPieceViaHTTPS`, `pieceDownloader` is already initialized, this PR will fix this issue.
Fix #1980

fix: SyncPieceViaHTTPS not work

---

trainer/config/config_test.go
trainer/config/constants.go
trainer/config/testdata/trainer.yaml

- Change DefaultServerPort to 9090 in trainer.

feat: change DefaultServerPort to 9090 in trainer

---

scheduler/metrics/metrics.go
scheduler/service/service_v1.go
scheduler/service/service_v2.go

feat: add traffic type of peer task download duration

feat: add traffic type of peer task download duration

---

scheduler/metrics/metrics.go
scheduler/service/service_v1.go
scheduler/service/service_v2.go

- Remove traffic_type in DownloadPeerDuration metric.

feat: remove traffic_type in DownloadPeerDuration metric

---

pkg/rpc/manager/client/client_v1.go
pkg/rpc/manager/client/client_v2.go
pkg/rpc/security/client/client_v1.go

Replace net dial with grpc health check in manager grpc client and security grpc client. Make grpc health check consistent.
- Replace net dial with grpc health check in client.
#2360

feat: replace net dial with grpc health check in client

---

scheduler/storage/storage.go
scheduler/storage/storage_test.go

- When bufferSize is zero, createDownload and createNetworkTopology can not write data to file, because buffer is empty.

fix: when bufferSize is zero, storage can not write data to file

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/database/database.go
manager/types/scheduler_cluster.go
scheduler/config/constants.go
scheduler/scheduling/scheduling.go
scheduler/scheduling/scheduling_test.go

Since the final length of the filter is the candidateParentLimit used, the parents after the filter is the returned parents.

fix: evaluate after filter

---

scheduler/announcer/announcer.go
scheduler/announcer/announcer_test.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/testdata/scheduler.yaml
scheduler/scheduler.go

- Add announceToTrainer in scheduler.

feat: add announceToTrainer in scheduler

---

scheduler/networktopology/mocks/network_topology_mock.go
scheduler/networktopology/network_topology.go
scheduler/networktopology/probes.go
scheduler/scheduler.go

- Refactor network topology package in scheduler.

refactor: network topology package in scheduler

---

pkg/redis/redis.go

It should call MakeNamespaceKeyInScheduler() function in MakeKeyInScheduler() function, instead of MakeNamespaceKeyInManager() function.

fix: call MakeNamespaceKeyInScheduler function error

---

client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/rpcserver_test.go

Only allow download call from unix domain socket.

chore: check grpc peer info for download service

---

.github/workflows/lint.yml

- Fix `couldn't expand $gostd` error in lint actions, refer to https://github.com/OpenPeeDeeP/depguard/issues/46 and specify the version of golangci-lint as 1.52.2.

feat: specify the version of golangci-lint as v1.52.2

---

pkg/redis/redis.go
pkg/redis/redis_test.go
scheduler/networktopology/network_topology.go
scheduler/networktopology/network_topology_test.go
scheduler/networktopology/probes_test.go
scheduler/resource/host_test.go
scheduler/scheduling/evaluator/evaluator_base_test.go
scheduler/scheduling/scheduling_test.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2_test.go
scheduler/storage/storage_test.go

- Add ParseProbedCountKeyInScheduler and Snapshot tests.
https://github.com/dragonflyoss/Dragonfly2/pull/2438

test: add ParseProbedCountKeyInScheduler and Snapshot tests

---

pkg/source/clients/s3protocol/s3_source_client.go
test/e2e/dfget_test.go
test/e2e/e2e_test.go
test/testdata/k8s/minio.yaml

fix: e2e test dfget recursive

---

scheduler/networktopology/network_topology.go
scheduler/networktopology/network_topology_test.go
scheduler/networktopology/probes_test.go

It's not recommended to use the KEYS prefix:* command to get all the keys in a Redis instance, especially in production environments, because it can be a slow and resource-intensive operation that can impact the performance of the Redis instance.
Instead, you can iterate over Redis keys that match some pattern using the SCAN command, refer to https://redis.uptrace.dev/guide/get-all-keys.html.

feat: replace keys with scan in redis client

---

scheduler/networktopology/network_topology_test.go
scheduler/networktopology/probes_test.go

Fix network topology unit tests, by replacing keys with scan in redis client.

test: replace keys with scan in redis client

---

pkg/digest/digest_test.go

Improve the digest test by adding various hash file encode pattern.

test: improve hash file encode test case in digest test

---

pkg/slices/slices.go
pkg/slices/slices_test.go
scheduler/networktopology/mocks/network_topology_mock.go
scheduler/networktopology/network_topology.go
scheduler/networktopology/network_topology_test.go
scheduler/resource/host_manager.go
scheduler/resource/host_manager_mock.go
scheduler/resource/host_manager_test.go
scheduler/service/service_v1.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

feat: implement FindProbedHosts and add LoadRandomHosts to host manager

---

client/daemon/daemon.go
client/daemon/peer/piece_downloader.go
pkg/rpc/credential.go

add caCert to `RootCAs` in  tlsconfig of Go,not only ClientCAs.
https://github.com/dragonflyoss/Dragonfly2/issues/2506

fix: also add ca to RootCAs

---

pkg/redis/redis.go
pkg/redis/redis_test.go
scheduler/networktopology/mocks/network_topology_mock.go
scheduler/networktopology/network_topology.go
scheduler/networktopology/network_topology_test.go
scheduler/networktopology/probes.go
scheduler/networktopology/probes_test.go

Remove ProbedAt function in network topology.

feat: remove ProbedAt function in network topology

---

go.mod
go.sum
manager/rpcserver/manager_server_v2.go
pkg/rpc/manager/client/client_v2.go
pkg/rpc/manager/client/mocks/client_v2_mock.go

feat: implement DeleteSeedPeer api in manager

---

client/daemon/objectstorage/objectstorage.go
client/daemon/peer/peertask_manager_test.go
client/daemon/transport/transport.go
client/dfget/dfget.go
scheduler/job/job.go

fix: improper use strings.TrimLeft

---

manager/rpcserver/security_server_v1.go
manager/rpcserver/security_server_v1_test.go

fix: manager generates mTLS certificates for arbitrary IP addresses

---

client/config/deprecated.go
client/config/dynconfig_manager.go
client/config/flags.go
client/daemon/objectstorage/objectstorage.go
client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_piecetask_synchronizer.go
client/daemon/proxy/proxy_sni.go
client/daemon/rpcserver/rpcserver.go
manager/config/config.go
manager/database/mysql.go
pkg/rpc/server_listen.go
scheduler/config/config.go
scheduler/config/dynconfig.go
scheduler/resource/peer.go
scheduler/resource/seed_peer_client.go
scheduler/scheduler.go
scheduler/service/service_v1.go
test/tools/stress/main.go
trainer/trainer.go

Reverts dragonflyoss/Dragonfly2#2642

Revert "feat: replace fmt.Sprintf with net.JoinHostPort"

---

client/daemon/objectstorage/objectstorage.go

feat: initialize object storage client in the New func

---

client/daemon/objectstorage/objectstorage.go
client/dfstore/dfstore.go
pkg/objectstorage/objectstorage.go
pkg/objectstorage/obs.go
pkg/objectstorage/oss.go
pkg/objectstorage/s3.go

"Fixing issues in the object storage based on JuiceFS use cases. Mainly includes:
1. Route path of createbucket.
2. Unable to properly pass objectkey when calling copyobject.
3. Oss GetObjectMeta return not found error.
4. getObjectMetadatas does not include directories.
#2176 
To provide support for JuiceFS objectStorage implementation.

Fix issues in the objectstorage based on JuiceFS use cases.

---

pkg/graph/dag/dag.go
pkg/graph/dag/dag_test.go
pkg/graph/dag/mocks/dag_mock.go
pkg/graph/dag/vertex.go
pkg/graph/dag/vertex_test.go
pkg/graph/dg/dg.go
pkg/graph/dg/dg_test.go
pkg/graph/dg/mocks/dg_mock.go
pkg/graph/dg/vertex.go
pkg/graph/dg/vertex_test.go
pkg/objectstorage/mocks/objectstorage_mock.go
scheduler/resource/task.go

fix: Vertex.DeleteInEdges and Vertex.DeleteOutEdges functions are not thread safe

---

.github/workflows/ci.yml
.github/workflows/compatibility-e2e.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/release.yml

use go-version-file: go.mod for go version detecting

feat: use go-version-file: go.mod for go version detecting

---

pkg/source/clients/s3protocol/s3_source_client.go

Something exception raised when using `dfget` to download a s3 directory.
Below is my usage:
```
dfget --recursive  --url "s3://my-bucket/my-dir" \
--header "awsEndpoint: xxx" \
--header ... \
--output local_dir
```
I find the bug is that:
When download a s3 directory, client will call a s3 API `ListObjectsV2`, to check whether the url is a directory. And the API need a parameter `prefix` (used as prefix filter for s3 object ids, should not start with leading slash "/"). In dragonfly's s3 client code, the url will be parsed as `request.URL` and `request.URL.path` will be used as `prefix`(after add a trailing slash). Such `path` always have leading slash "/", e.g. '/', '/my-dir/', make `ListObjectsV2` API response wrong result.

fix: dfget couldn't download s3 directory correctly

---

pkg/objectstorage/s3.go

Fix the issue of improper initialization of return commonPrefixes slice in the S3 list interface when using delimiter.
#2176

Fix s3 commonPrefix initial issue.

---

scheduler/networktopology/network_topology.go

A snapshot should be represented by one network topology id in network topology record.

fix: snapshot network topology id

---

manager/config/config.go
manager/config/config_test.go
manager/config/constants.go
manager/database/postgres.go

Add option to disable prepared statement for postgres.
This option is required for use with PgBouncer. PgBouncer does not support prepared statements.
To disable prepared statements, pass gorm PreferSimpleProtocol: true.
https://github.com/dragonflyoss/Dragonfly2/issues/2767
Solves problems when working with pgbouncer.

fix: add option to disable prepared statement for postgres

---

client/config/dynconfig_manager.go

chore: optimize dynconfig error log

---

pkg/rpc/cdnsystem/client/client.go
pkg/rpc/dfdaemon/client/client_v1.go
pkg/rpc/dfdaemon/client/client_v2.go
pkg/rpc/health/client/client.go
pkg/rpc/inference/client/client_v1.go
pkg/rpc/interceptor.go
pkg/rpc/manager/client/client_v1.go
pkg/rpc/manager/client/client_v2.go
pkg/rpc/scheduler/client/client_v1.go
pkg/rpc/scheduler/client/client_v2.go
pkg/rpc/security/client/client_v1.go
pkg/rpc/trainer/client/client_v1.go

Fix refer to PR https://github.com/argoproj/argo-cd/pull/15174, See https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4226 for more information.

fix: otelgrpc.UnaryClientInterceptor memory leak

---

client/daemon/daemon.go

Cleanup, and add noTLSConfig instead nil for better readable

chore(client/daemon): cleanup, and add noTLSConfig

---

manager/job/preheat.go
manager/job/sync_peers.go

chore(manager/job): cleanup and fix typo

---

client/daemon/daemon.go
client/daemon/proxy/proxy.go
client/daemon/proxy/proxy_manager.go
client/daemon/proxy/proxy_sni.go

When shutdown, we must wait the flying proxy request completed, this PR does:
* Add sync.WaitGroup to proxy - Done
* Add graceful shutdown timeout - WIP
Fix #2761

feat: proxy graceful shutdown

---

scheduler/job/job.go

filter Authorization header from preheat log
https://github.com/dragonflyoss/Dragonfly2/issues/2816
Authorization tokens are included in the log

fix: filter Authorization header from preheat log

---

client/config/dynconfig.go
client/config/dynconfig_local.go
client/config/dynconfig_manager.go
client/config/dynconfig_manager_test.go
client/config/mocks/dynconfig_mock.go
pkg/rpc/manager/client/client_v1.go
pkg/rpc/manager/client/client_v2.go
pkg/rpc/manager/client/mocks/client_v1_mock.go
pkg/rpc/manager/client/mocks/client_v2_mock.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/dynconfig.go
scheduler/config/testdata/scheduler.yaml
scheduler/resource/peer.go
scheduler/scheduling/scheduling.go
scheduler/scheduling/scheduling_test.go

- Add GetSeedPeers to dfdaemon dynconfig.
- Add MaxScheduleCount to scheduler. When peer schedule count exceeded the MaxScheduleCount, scheduler will notify peer back-to-source.

feat: add MaxScheduleCount and GetSeedPeers

---

build/images/manager/Dockerfile

chore: update node version to 20-alpine in Dockerfile

---

client/config/dynconfig_manager.go
internal/dynconfig/dynconfig.go
pkg/resolver/scheduler_resolver.go
pkg/resolver/seed_peer_resolver.go
pkg/rpc/health/client/client.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/dynconfig.go
scheduler/config/testdata/scheduler.yaml
scheduler/service/service_v1.go
scheduler/service/service_v1_test.go

feat: avoid hot resolve in grpc

---

go.mod
go.sum
scheduler/service/service_v2.go

feat: remove handleSyncPiecesFailedRequest when sync piece failed

---

go.mod
go.sum
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

feat: optimize AnnouncePeer log and update api verison

---

go.mod
go.sum

downgrade gorm.io/driver/postgres to 1.5.2
downgrade gorm.io/driver/postgres to 1.5.2
https://github.com/dragonflyoss/Dragonfly2/issues/2907
Fix error: table name "scheduler" specified more than once.

fix: downgrade gorm.io/driver/postgres to 1.5.2

---

client/daemon/peer/peertask_conductor.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_piecetask_synchronizer.go
internal/dferrors/error.go

chore: optimize sync pieces error report

---

go.mod
go.sum
pkg/rpc/dfdaemon/client/client_v2.go
pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go
scheduler/resource/seed_peer.go
scheduler/resource/seed_peer_mock.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

feat: optimize parameters in seed peer DownloadTask

---

client/daemon/peer/piece_manager.go
client/daemon/peer/piece_manager_test.go
client/daemon/storage/local_storage.go
client/daemon/storage/local_storage_subtask.go
go.mod
go.sum

Currently, for multiple pieces tasks, we download them by one piece for one request, download them by multiple pieces(piece group) is a better solution. This PR implements it.

feat: back to source with piece group

---

client/daemon/peer/peertask_manager.go
client/daemon/peer/peertask_manager_test.go
client/daemon/peer/peertask_reuse.go
client/daemon/peer/peertask_reuse_test.go
client/daemon/peer/peertask_stream.go
client/daemon/peer/peertask_stream_backsource_partial_test.go
client/daemon/peer/peertask_stream_resume_test.go

Optimize superfluous `idgen.TaskIDV1` in stream task.

chore: optimize stream task id

---

pkg/slices/slices.go
pkg/slices/slices_test.go
scheduler/networktopology/network_topology.go

feat: add difference function for slices

---

client/daemon/daemon.go

The `cd.networkTopology` is not be checked before calling the `Stop` method, a nil pointer panic will happen during the peer stop procedure.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14d2c1b]
goroutine 321 [running]:
panic({0x169f5a0?, 0x2d44570?})
/usr/local/go/src/runtime/panic.go:1017 +0x3ac fp=0xc000439cc8 sp=0xc000439c18 pc=0x43b2ec
runtime.panicmem(...)
/usr/local/go/src/runtime/panic.go:261
runtime.sigpanic()
/usr/local/go/src/runtime/signal_unix.go:861 +0x378 fp=0xc000439d28 sp=0xc000439cc8 pc=0x4526d8
d7y.io/dragonfly/v2/client/daemon.(*clientDaemon).Stop.func1()
/var/run/dragonfly2-seed-peer/client/daemon/daemon.go:865 +0x57b fp=0xc000439e80 sp=0xc000439d28 pc=0x14d2c1b …
```

only stop networkTopology when it is not nil

---

client/daemon/peer/peertask_conductor.go

When one scheduler goes away, the daemon will print `receive peer packet failed: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: "graceful_stop"` and marks peer task failed.
The daemon should re-register to other schedulers instead of failed immediately.

feat: re-register when scheduler go away

---

pkg/rpc/cdnsystem/client/client.go
pkg/rpc/dfdaemon/client/client_v1.go
pkg/rpc/dfdaemon/client/client_v2.go
pkg/rpc/health/client/client.go
pkg/rpc/inference/client/client_v1.go
pkg/rpc/manager/client/client_v1.go
pkg/rpc/manager/client/client_v2.go
pkg/rpc/scheduler/client/client_v1.go
pkg/rpc/scheduler/client/client_v2.go
pkg/rpc/security/client/client_v1.go
pkg/rpc/trainer/client/client_v1.go

This is a quite easy patch to fix potential grpc connection resolve deadlock with `dynconfig` resolver.
- https://github.com/dragonflyoss/Dragonfly2/issues/2968
- https://github.com/dragonflyoss/Dragonfly2/issues/3022
- https://github.com/grpc/grpc-go/issues/6858
The grpc-go introduce the `WithIdleTimeout` feature in v1.56.0, and the default `idleTimeout` set as `30 * time.Minute` in v1.59.0. This may be a potential cause of many reporting of preheat failed with `DeadlineExceeded`.
It seems that grpc with gc the idle connection after 30 minutes. And scheduler doesn't health check the seed peer, so when we create a preheat task, the last idle connection may be already closed by grpc, but when new connection is created, the connection is waiting for the resolver state to be done.
Here is …

fix potential deadlock in dynconfig resolver

---

cmd/dfget/cmd/root.go

chore: optimize dfget log

---

client/daemon/daemon.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/rpcserver_test.go
go.mod
go.sum
pkg/cache/cache_mock.go
pkg/rpc/dfdaemon/client/client_v1.go
pkg/rpc/dfdaemon/client/mocks/client_v1_mock.go
scheduler/networktopology/mocks/network_topology_mock.go

feat: add leave host to dfdaemon

---

scheduler/config/constants.go

feat: change scheduling params

---

.github/workflows/check-size.yml
.gitmodules

chore: add client-rs submodule to main

---

test/e2e/concurrency_test.go
test/e2e/containerd_test.go
test/e2e/dfget_test.go
test/e2e/e2e_test.go
test/e2e/manager/preheat.go
test/e2e/util/artifact.go
test/e2e/util/exec.go
test/e2e/util/feature_gate.go
test/e2e/util/file_server.go

feat: rename e2eutil to util

---

cmd/trainer/cmd/root.go
scheduler/config/config.go
scheduler/config/config_test.go

Fix buffer size limit: 
The parameter bufferSize in scheduler storage can not be set to 0.

fix: scheduler storage buffer size limit

---

pkg/container/set/safe_set.go
pkg/container/set/set.go
pkg/graph/dag/dag.go
pkg/graph/dag/dag_test.go
pkg/graph/dag/mocks/dag_mock.go
pkg/graph/dag/vertex.go
pkg/graph/dg/dg.go
pkg/graph/dg/dg_test.go
pkg/graph/dg/mocks/dg_mock.go
pkg/graph/dg/vertex.go
scheduler/resource/task.go

`dag.GetVertices` calls `concurrent-map.fanIn`.
`dag.GetRandomVertices` calls `concurrent-map.Keys`.
`sync.Map`
```shell
goos: darwin
goarch: amd64
pkg: d7y.io/dragonfly/v2/pkg/graph/dag
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkDAG_AddVertex-12                     	     100	       943.1 ns/op	     379 B/op	       8 allocs/op
BenchmarkDAG_DeleteVertex-12                  	     100	       221.3 ns/op	       0 B/op	       0 allocs/op
BenchmarkDAG_GetVertices-12                   	     100	     13220 ns/op	    8280 B/op	       4 allocs/op
BenchmarkDAG_GetRandomVertices-12             	     100	      3158 ns/op	     429 B/op	       1 allocs/op
BenchmarkDAG_DeleteVertexWithMultiEdges-12    	     100	       372.3 ns/op	      30 B/op	       0 allocs/op
BenchmarkDAG_AddEdge-12 …
```

feat: optimize graph based on sync.Map

---

client/daemon/proxy/proxy.go

fix: tunnel https

---

client/daemon/storage/storage_manager.go

for one of the taskID in `indexTask2PeerTask map[string][]*localTaskStore`, if the first localTaskStore of `[]*localTaskStore` lost the `xxx.cache.xxx` file, then cache for reuse will miss every time, until the first one removed by GC;
in the worst-case, disk will be full filled;
to avoid it, change to `reverse search order` for `[]*localTaskStore` in `FindXXXTask`;
in this case, cache will be hit again after it miss once;

Improve the search order for localTaskStore array

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/storage/local_storage_test.go
client/daemon/storage/storage_manager.go

Optimize reload storage for a large number of files.

feat: optimize reload storage

---

test/e2e/constants.go
test/e2e/network_topology_test.go
test/testdata/charts/config-cache-list-metadata.yaml
test/testdata/charts/config-compatibility.yaml
test/testdata/charts/config-concurent-back-source.yaml
test/testdata/charts/config-disable-seed-peer.yaml
test/testdata/charts/config-grpc-tls-ipv6.yaml
test/testdata/charts/config-grpc-tls.yaml
test/testdata/charts/config-ipv6.yaml
test/testdata/charts/config-split-running-tasks.yaml
test/testdata/charts/config-write-buffer-size.yaml
test/testdata/charts/config.yaml

fix: fix network topology e2e test

---

manager/database/database.go
manager/database/mysql.go

The newMysql() method in manager/database/ was misspelled as newMyqsl().

fix: typo in manager database

---

test/e2e/v2/dfget_test.go
test/e2e/v2/util/file_server.go
test/e2e/v2/util/task.go

test: add download with dfget e2e test for API v2(Rust Client)

---

manager/handlers/application_test.go
manager/handlers/bucket_test.go
manager/handlers/cluster_test.go
manager/handlers/config_test.go
manager/handlers/health_test.go
manager/handlers/job_test.go
manager/handlers/model_test.go
manager/handlers/oauth_test.go
manager/handlers/peer_test.go
manager/handlers/permission_test.go
manager/handlers/personal_access_token_test.go
manager/handlers/preheat_test.go
manager/handlers/role_test.go
manager/handlers/scheduler_cluster_test.go
manager/handlers/scheduler_test.go
manager/handlers/seed_peer_cluster_test.go
manager/handlers/seed_peer_test.go
manager/handlers/user_test.go

Add unit tests for manager handlers.
fix https://github.com/dragonflyoss/Dragonfly2/issues/2705

feat: add unit tests for manager handlers

---

client/daemon/rpcserver/subscriber.go

1. One remote peer come with `StartNum > 0`, eg: StartNum = 1
2. Local peer run `sendRemainingPieceTasks` and `s.totalPieces` is -1
3. Local peer start to back source or download from other peers with piece 0
4. For piece 0 from local peer, due to `s.totalPieces` is -1, the following check will be skipped and will be sent to remote peer: `if s.totalPieces > -1 && uint32(info.Num) < nextPieceNum`, then `len(s.sentMap)++`
5. `s.totalPieces` will be updated
6. because the piece 0 which should not be sent in step 4, will hit the following logic to break loop
```
if s.totalPieces > -1 && len(s.sentMap)+int(s.skipPieceCount) == int(s.totalPieces) {
s.Unlock()
break loop
}
```
7. The subscriber will hang until other peers send more pieces.
Solution:
We should not check completeness via fuzzy …

fix: client rpcserver subscriber hang

---

manager/job/preheat.go

Background:
Harbor utilizes the V1 preheat job, which includes the auth token issued by Harbor in the request body. However, Dragonfly 2.x's auth logic relies on the username and password to exchange tokens, following the v2 auth flow. As a result, when Harbor attempts to preheat to Dragonfly 2.x, it encounters a 401 unauthorized error as Dragonfly tries to pull the manifest from the private project. To maintain backward compatibility, the auth logic should be aligned to be compatible with 1.x.

fix: pass through the headers specified by user to preheat job

---

client/daemon/networktopology/network_topology.go
pkg/net/ping/ping.go

Use safe set in client daemon network_topology.go.

fix: use safe set in client daemon network_topology.go

---

client/daemon/peer/traffic_shaper.go

Using `Swap` to keep the `usingBandWidth` swap into `lastSecondBandwidth` atomically;
otherwise, between `Load()` and `Store(0)`, `usingBandWidth` may be added, that will be dropped unexpectedly;

fix traffic swap

---

client/config/peerhost.go
client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/daemon.go
client/daemon/pex/peer_exchange.go

chore: update pex replica clean logic

---

client/config/peerhost_darwin.go
client/config/peerhost_linux.go
client/daemon/peer/peertask_conductor.go

1. Skip to validate PieceMd5Sign, per piece digest is sufficient.
2. Enable calculate piece digest by default for data integrality.

chore: optimize calculate digest

---

client/daemon/storage/local_storage.go

Optimized the pieceDigests slice initialization in the genMetadata function by preallocating space based on t.TotalPieces. This change avoids dynamic slice resizing during runtime, which enhances the performance especially when handling large data sets.

refactor: Preallocate pieceDigests slice in genMetadata for improved

---

client/daemon/rpcserver/rpcserver.go

We should update uid and gid before send the last result.

fix: file task uid gid

---

scheduler/resource/host_manager.go
scheduler/resource/host_manager_test.go

During host manager `RunGC()`, reclaim the host directly after host leave peers, as host's `ConcurrentUploadCount` may not be 0 when the host exits abnormally.
#3350

feat: delete the host after host leave peers during host manager gc

---

manager/service/model.go
pkg/objectstorage/mocks/objectstorage_mock.go
pkg/objectstorage/objectstorage.go
pkg/objectstorage/obs.go
pkg/objectstorage/oss.go
pkg/objectstorage/s3.go

fix spelling of all occurrences of the getObject() method which was originally misspelled as getOject().
no related issue
Ensures accuracy and clarity in the codebase.

refractor: fix typo in object storage.go 

---

go.mod
go.sum
scheduler/rpcserver/scheduler_server_v2.go

1. Update api version.
2. Add methods for scheduler rpcserver.
Commands:
```bash
go get -u d7y.io/api/v2
go mod tidy
```

chore: update api verison to v2.0.141

---

client/daemon/proxy/proxy.go

chore: optimize tls cert expire check

---

client/daemon/peer/peertask_reuse.go
client/daemon/transport/transport.go

Fix range with "bytes=0-" always back source in none-prefetch env.

fix: start with zero half-open interval range

---

client/daemon/peer/peertask_manager.go

Fixes a null pointer dereference issue by moving the logging before setting parent to nil in case of storage registration failure. This change prevents accessing properties of a nil parent object, thereby avoiding runtime errors.

fix: fix null pointer dereference issue when parent task storage registration fails 

---

internal/job/job.go
manager/cache/cache.go
manager/config/config.go
manager/database/database.go
manager/job/job.go
pkg/redis/redis.go
scheduler/config/config.go
scheduler/job/job.go
scheduler/scheduler.go

Added sentinel authentication settings
After upgrading redis-go, sentinel authentication broke

fix: add sentinel authentication settings

---

.github/workflows/check-size.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/compatibility-e2e-v1.yml
.github/workflows/compatibility-e2e-v2.yml
.github/workflows/docker.yml
.github/workflows/e2e-v1-nydus.yml
.github/workflows/e2e-v1.yml
.github/workflows/e2e-v2-nydus.yml
.github/workflows/e2e-v2.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/scorecards.yml

chore: fixed Pinned-Dependencies for actions

---

client/config/peerhost.go
client/daemon/daemon.go
client/daemon/rpcserver/rpcserver.go
client/daemon/rpcserver/rpcserver_test.go
client/daemon/rpcserver/seeder.go
client/daemon/rpcserver/seeder_test.go

feat: seed max concurrent

---

.github/workflows/compatibility-e2e-v2.yml
manager/job/task_test.go
test/e2e/v2/manager/task.go

This PR focuses on improving the unit tests for the `manager/job/task.go` and rewriting the e2e tests. The key changes are:
Unit Test Rewrite (`manager/job/task.go`):
1. The unit tests for CreateGetTask and CreateDeleteTask have been completely rewritten.
2. The new tests provide more comprehensive coverage, including handling both success and failure cases.
3. Mocking and assertions have been added to verify internal logic, ensuring the robustness of task creation and deletion workflows.
End-to-End (e2e) Tests:
1. New e2e tests have been added, following the structure of existing preheat tests.
2. The e2e tests now include proper assertions on return values to validate task creation and deletion scenarios.
3. These tests aim to cover the complete flow from request to response, ensuring …

fix: update get and delete task unit test and e2e test.

---

hack/install-e2e-test.sh

Fix: `make e2e-test` error
`Error from server (NotFound): pods "file-server-no-content-length-0" not found`

fix: make e2e test 

---

manager/job/sync_peers.go

old sql only select one item
the old sql only select one item.
Then the peer deleted can not clean in time.The data displaayed in the console(Insight--peer) will be wrong

select all peers in one scheduler_cluster

---

go.mod
go.sum
scheduler/rpcserver/scheduler_server_v2.go

1. Update api version.
2. Add methods for scheduler rpcserver.
3. Update helm chart.
Commands:
```bash
go get -u d7y.io/api/v2
go mod tidy
```
https://github.com/dragonflyoss/Dragonfly2/issues/3523

chore: update api version to v2.0.158 and update helm chart

---

go.mod
go.sum
pkg/rpc/dfdaemon/client/client_v2.go
pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go
pkg/types/types.go
scheduler/job/job.go
scheduler/metrics/metrics.go
scheduler/resource/host_manager_test.go
scheduler/resource/host_test.go
scheduler/resource/peer_manager_test.go
scheduler/resource/peer_test.go
scheduler/resource/seed_peer_client_mock.go
scheduler/resource/seed_peer_test.go
scheduler/resource/task.go
scheduler/resource/task_manager_test.go
scheduler/resource/task_test.go
scheduler/rpcserver/scheduler_server_v2.go
scheduler/scheduling/evaluator/evaluator_base_test.go
scheduler/scheduling/evaluator/evaluator_network_topology_test.go
scheduler/scheduling/scheduling_test.go
scheduler/service/service_v1.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

feat: update new task type(TaskType_STANDARD, TaskType_PERSISTENT, TaskType_PERSISTENT_CACHE)

---

.github/workflows/compatibility-e2e-v2.yml
scheduler/resource/persistentcache/peer.go
scheduler/resource/standard/peer.go

feat: add fsm for persistent cache peer

---

deploy/docker-compose/docker-compose.yaml

chore: update rust client and console submodule

---

.github/workflows/compatibility-e2e-v2.yml
deploy/docker-compose/template/client.template.yaml
deploy/docker-compose/template/manager.template.yaml
deploy/docker-compose/template/scheduler.template.yaml
deploy/docker-compose/template/seed-client.template.yaml
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/testdata/scheduler.yaml
scheduler/resource/standard/host_manager_test.go
scheduler/resource/standard/host_test.go
scheduler/resource/standard/peer.go
scheduler/resource/standard/peer_manager_test.go
scheduler/resource/standard/peer_test.go
scheduler/resource/standard/resource.go
scheduler/resource/standard/seed_peer.go
scheduler/resource/standard/seed_peer_test.go
scheduler/resource/standard/task_manager_test.go
scheduler/resource/standard/task_test.go
scheduler/scheduling/evaluator/evaluator_base_test.go
scheduler/scheduling/scheduling_test.go
scheduler/service/service_v1.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

feat: add self-signed certs for mTLS

---

.github/workflows/docker.yml

chore: generate sbom for release artifacts

---

manager/handlers/job.go
manager/metrics/metrics.go
manager/service/job.go

feat: add CreateJobCount and CreateJobSuccessCount metrics

---

.github/workflows/compatibility-e2e-v2.yml
.github/workflows/e2e-v2-nydus.yml
client/daemon/daemon.go
deploy/docker-compose/template/scheduler.template.yaml
manager/job/sync_peers.go
pkg/idgen/host_id.go
pkg/idgen/host_id_test.go
pkg/rpc/scheduler/client/client_v1.go
pkg/rpc/scheduler/client/client_v2.go
pkg/rpc/scheduler/client/mocks/client_v2_mock.go
scheduler/metrics/metrics.go
scheduler/resource/standard/host.go
scheduler/resource/standard/host_test.go
scheduler/resource/standard/seed_peer_client.go
scheduler/rpcserver/scheduler_server_v2.go
scheduler/scheduling/evaluator/evaluator_base_test.go
scheduler/scheduling/scheduling_test.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go
test/e2e/v2/containerd_test.go
test/e2e/v2/e2e_test.go
test/e2e/v2/leave_host_test.go
test/e2e/v2/util/constants.go
test/e2e/v2/util/exec.go
test/testdata/charts/config-v2.yaml
test/testdata/kind/config-v2.yaml

Verifies that Scheduler can clear offline peer metadata when the host exits normally/abnormally by following steps:
1. Get the number of all hosts in the scheduler.
2. After a normal exit of a host, verify that the number of hosts in the scheduler decreases by 1.
3. After an abnormal exit of a host, verify that the number of hosts in the scheduler decreases by 1 after twice the announce host interval.
close https://github.com/dragonflyoss/Dragonfly2/issues/3523
Earlier we have added functionality so that hosts send `LeaveHost()` requests to the Scheduler on normal exit and hosts on abnormal exit are also sensed by the Scheduler GC after a set amount of time and the metadata is cleared. Now, we are going to add E2E tests to verify that this functionality is correct.

feat: add E2E tests for cases that peers going offline

---

internal/dflog/logger.go
pkg/redis/redis.go
scheduler/resource/persistentcache/host_manager.go
scheduler/resource/persistentcache/peer.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/task.go
scheduler/resource/persistentcache/task_manager.go

feat: add peer manager for persistent cache task

---

scheduler/resource/persistentcache/host.go
scheduler/resource/persistentcache/peer.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/rpcserver/rpcserver.go
scheduler/rpcserver/rpcserver_test.go
scheduler/rpcserver/scheduler_server_v2.go
scheduler/scheduler.go
scheduler/service/service_v1.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

feat: implement StatPersistentCachePeerRequest and StatPersistentCacheTaskRequest for persistent cache

---

scheduler/service/service_v2_test.go
test/e2e/v2/host_test.go

Replaces unit tests that were previously removed.

Add tests for ListHosts() and DeleteHost()

---

.github/workflows/compatibility-e2e-v2.yml
internal/job/types.go
manager/handlers/job.go
manager/handlers/job_test.go
manager/job/task.go
manager/types/job.go
pkg/idgen/task_id.go
pkg/idgen/task_id_test.go
scheduler/job/job.go
scheduler/resource/standard/task_test.go
scheduler/scheduling/evaluator/evaluator_base_test.go
scheduler/scheduling/scheduling_test.go
scheduler/service/service_v1_test.go
test/e2e/v2/concurrency_test.go
test/e2e/v2/containerd_test.go
test/e2e/v2/dfget_test.go
test/e2e/v2/manager/preheat.go
test/e2e/v2/manager/task.go
test/e2e/v2/proxy_test.go
test/testdata/charts/config-v2.yaml

feat: support searching task by url for GetTask and DeleteTask

---

.github/workflows/lint.yml
build/images/base/Dockerfile
build/images/dfdaemon/Dockerfile
build/images/manager/Dockerfile
build/images/scheduler/Dockerfile
build/plugin-builder/Dockerfile
go.mod
hack/build.sh
hack/docker-build.sh
test/tools/no-content-length/Dockerfile

chore: update golang version to v1.23.0

---

pkg/net/http/header.go

This pull request includes changes to the `pkg/net/http/header.go` file to enhance the handling of query parameters for generating task IDs. The most important changes include adding a new set of filtered query parameters for `containerd` and updating the default filtered query parameters to include these new parameters.
Enhancements to query parameter handling:
* [`pkg/net/http/header.go`](diffhunk://#diff-0ae93eed228c1b5586b56da501ed24f84ef016f038402cd4f42f1a6b45ce20f1R77-R83): Added `ContainerdQueryParams` to handle `containerd` specific query parameters. (`[pkg/net/http/header.goR77-R83](diffhunk://#diff-0ae93eed228c1b5586b56da501ed24f84ef016f038402cd4f42f1a6b45ce20f1R77-R83)`)
* [`pkg/net/http/header.go`](diffhunk://#diff-0ae93eed228c1b5586b56da501ed24f84ef016f038402cd4f42f1a6b45ce20f …

feat: add filtered query params of the containerd

---

manager/middlewares/error.go
manager/service/job.go

This pull request focuses on improving error handling in the `manager` package by providing more detailed error messages. The most important changes include updating error messages in the `Error` middleware and enhancing error context in the `findSchedulers` and `findCandidateSchedulers` service methods.
Error handling improvements:
* [`manager/middlewares/error.go`](diffhunk://#diff-0622b1805aec98e46bded0c515e7cf953f84ce5b49f2ab6900bba511b29ef01aL90-R90): Updated the error message in the GORM error handler to use `err.Error()` instead of a generic HTTP status text.
* [`manager/service/job.go`](diffhunk://#diff-32eba326fa80fbb1d566d606bb6bf6d24c19b9dd24687c2a361c69d9f2c56aeaL189-R197): Enhanced error context in the `findSchedulers` method by including the scheduler cluster ID in the error …

feat: optimize error message of preheating

---

go.mod
go.sum
pkg/redis/redis.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/task.go
scheduler/resource/persistentcache/task_manager.go
scheduler/service/service_v2.go

This pull request includes several changes to improve the handling and management of persistent cache tasks and peers in the project. The most significant changes involve the addition of new methods for managing persistent peers, the removal of the `ReplicaCount` field from tasks, and updates to various functions to handle the new structure.
* [`pkg/redis/redis.go`](diffhunk://#diff-62a192412b31ee11bcbde71447ebec0a32a59f31e3e720e4dd62ee39a577cd33R52-R54): Added `PersistentPeersNamespace` constant and the `MakePersistentPeersOfPersistentCacheTaskInScheduler` function to handle persistent peers. [[1]](diffhunk://#diff-62a192412b31ee11bcbde71447ebec0a32a59f31e3e720e4dd62ee39a577cd33R52-R54) [[2]](diffhunk://#diff-62a192412b31ee11bcbde71447ebec0a32a59f31e3e720e4dd62ee39a577cd33R152-R156)
* …

feat: implement delete peer and task in persistent cache

---

scheduler/resource/persistentcache/host.go
scheduler/resource/persistentcache/host_manager.go
scheduler/resource/persistentcache/task_manager_mock.go
scheduler/service/service_v1_test.go
scheduler/service/service_v2.go
scheduler/service/service_v2_test.go

This pull request enhances the `AnnounceHost` function in `scheduler/service/service_v2.go` to handle both standard and persistent cache hosts. The most significant changes are the addition of logic to manage the persistent cache hosts, including their creation, updating, and storage.
* Added handling for persistent cache hosts, including loading, creating, and updating host properties.
* Implemented detailed property setting for persistent cache hosts, covering CPU, memory, network, disk, and build information.
* Added logging for the creation and updating of persistent cache hosts to provide better traceability.
These changes ensure that the system can now manage persistent cache hosts effectively, alongside the existing standard hosts.

feat: store persistent cache host by announce host api

---

go.mod
go.sum
scheduler/resource/persistentcache/host_manager.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/task_manager.go

This pull request includes several changes to improve the handling of time fields and update dependencies. The most important changes involve converting integer parsing functions to their unsigned counterparts and updating the `d7y.io/api/v2` module version.
Dependency update:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L6-R6): Updated `d7y.io/api/v2` module version from `v2.0.171` to `v2.0.173`.
Time field parsing improvements:
* [`scheduler/resource/persistentcache/host_manager.go`](diffhunk://#diff-cab2c0c5532854f2dd2b4557cc339dd396bccb1ea3a66af3ffc13821da7e3a8dL416-R416): Changed `strconv.ParseInt` to `strconv.ParseUint` for parsing `announce_interval` and adjusted the conversion to `time.Duration`. …

feat: optimize api for shceduling

---

go.mod
go.sum
pkg/digest/digest.go

This pull request includes updates to dependencies and a bug fix to the `pkg/digest/digest.go` file. The most important changes are:
Dependency updates:
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L6-R6): Updated the `d7y.io/api/v2` dependency from version `v2.0.173` to `v2.0.175`.
Bug fixes:
* [`pkg/digest/digest.go`](diffhunk://#diff-bca0eaeee6a484251e01596b85c75fde1f90dc8400c5f28c8ce6c28f29700c9fL126-R126): Modified the `Parse` function to handle an additional valid length for the `AlgorithmCRC32` encoded string, allowing lengths of 8 and 10.

feat: support CRC-32-Castagnoli algorithm

---

manager/config/config.go
manager/config/config_test.go
manager/config/constants.go
manager/config/testdata/manager.yaml
manager/job/gc.go

This pull request introduces the concept of batch processing for garbage collection (GC) jobs in the `manager/config` package. The most important changes include adding a batch size parameter to the GC configuration, updating the validation logic to require this parameter, and implementing the batch deletion logic in the GC job.
Configuration updates:
* [`manager/config/config.go`](diffhunk://#diff-38f5db6313cbf867355d056890ad5ca0f1b952eebef92eb70abbafeb1b655c15R324-R326): Added `BatchSize` parameter to `GCConfig` struct and set its default value in the `New` function. Updated the `Validate` function to check for the presence of the `BatchSize` parameter. [[1]](diffhunk://#diff-38f5db6313cbf867355d056890ad5ca0f1b952eebef92eb70abbafeb1b655c15R324-R326) …

feat: delete jobs in batches

---

.github/workflows/compatibility-e2e-v2.yml
manager/job/preheat.go

This pull request introduces several improvements to the `manager/job/preheat.go` file, primarily focusing on enhancing the HTTP client configuration and refactoring the code for better maintainability.
* Introduced a new `defaultHTTPTransport` variable to define the default HTTP transport settings, including maximum idle connections, maximum connections per host, and idle connection timeout.
* Modified the `preheat` struct to include an `httpClient` field, and updated the `newPreheat` function to initialize this client with the `defaultHTTPTransport` settings.
* Updated the `getImageLayers` method to use the `httpClient` from the `preheat` struct instead of creating a new HTTP client each time.
* Refactored the `newImageAuthClient` function to use the `defaultHTTPTransport` for its HTTP …

feat: reuse connections and limit the number of connections for preheating

---

scheduler/resource/persistentcache/host_manager.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/task_manager.go

feat: load empty return false in persistentcache

---

manager/service/job.go
manager/types/job.go
scheduler/job/job.go
scheduler/resource/standard/seed_peer_client.go
scheduler/resource/standard/seed_peer_client_mock.go

This pull request introduces changes to the preheating job functionality, specifically adding support for preheating with seed peers and refactoring related constants and methods. The most important changes include updating the scope constants, modifying the `PreheatArgs` struct, and implementing the `preheatAllSeedPeers` method.
Updates to preheating job functionality:
* [`manager/types/job.go`](diffhunk://#diff-d878064c028a450c53f765d31dff1bea45dc8d3346201e65989d98b2fb976d62L22-R26): Updated scope constants to include `SingleSeedPeerScope` and `AllSeedPeersScope`, and modified the `PreheatArgs` struct to remove the `oneof` constraint for the `Scope` field. [[1]](diffhunk://#diff-d878064c028a450c53f765d31dff1bea45dc8d3346201e65989d98b2fb976d62L22-R26) …

feat: add AllSeedPeersScope for preheating

---

manager/rpcserver/manager_server_v1.go
manager/rpcserver/manager_server_v2.go
pkg/redis/redis.go
pkg/redis/redis_test.go

This pull request includes changes to the `manager/rpcserver` and `pkg/redis` files to improve the caching mechanism by incorporating the `version` parameter into the cache key generation. This ensures that different versions of the same peer can be cached and retrieved correctly.
Changes to cache key generation:
* [`manager/rpcserver/manager_server_v1.go`](diffhunk://#diff-a487908dde55011dac11580dbde0d5753af67553c8d71caeef2c04d2f72872d9L538-R538): Updated the `cacheKey` in the `ListSchedulers` function to include the `version` parameter.
* [`manager/rpcserver/manager_server_v2.go`](diffhunk://#diff-d6cc9560b22b902b815a8aabd758bb6f6127891f1ddb666f462088228a6a860cL558-R558): Updated the `cacheKey` in the `ListSchedulers` function to include the `version` parameter.
* …

feat: add client version for MakeSchedulersKeyForPeerInManager

---

scheduler/scheduler.go
scheduler/service/service_v2.go

This pull request introduces several changes to ensure that the persistent cache feature is only used when Redis is enabled. The changes include adding checks for the presence of the `persistentCacheResource` before performing operations related to the persistent cache.
* Added a check to initialize the persistent cache resource only if `rdb` is not nil in `func New` in `scheduler/scheduler.go`.
* Updated `AnnounceHost` to return early if `persistentCacheResource` is nil, indicating that Redis is not enabled, in `scheduler/service/service_v2.go`.
* Modified various methods to return an error if `persistentCacheResource` is nil, ensuring operations are skipped when Redis is not enabled, in `scheduler/service/service_v2.go`:
* `AnnouncePersistentCachePeer`
* `StatPersistentCachePeer`
* …

feat: when the redis is disabled, AnnounceHost need to skip store redis

---

ADOPTERS.md
CONTRIBUTING.md
README.md
build/images/base/README.md
build/package/docs/dfcache/dfcache.1
build/package/docs/dfcache/dfcache.md
build/package/docs/dfget.1
build/package/docs/dfget.1.md
build/package/docs/dfstore/dfstore.1
build/package/docs/dfstore/dfstore.md
client/daemon/transport/transport.go
pkg/net/ip/ipv4.go

This pull request includes several changes to update references from `Dragonfly2` to `dragonfly` across multiple documentation files and code comments. The changes ensure consistency and accuracy in the project references.
Documentation updates:
* [`ADOPTERS.md`](diffhunk://#diff-12e0a48d6c5f2a58f4caa284b0546243f1a5431590701dd26e9c4f94180127e6L26-R26): Updated the link to Dragonfly 2.0 repository.
* [`CONTRIBUTING.md`](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L29-R29): Updated multiple links and repository references from `Dragonfly2` to `dragonfly` for forking, cloning, setting remote, and branch definitions. [[1]](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L29-R29) …

chore: rename repo from Dragonfly2 to dragonfly

---

manager/job/sync_peers.go

This pull request includes changes to the `manager/job/sync_peers.go` file to improve the synchronization of peers, specifically addressing compatibility with the Rust client. The most important changes include updating the `SyncPeers` interface documentation and adding a condition to handle scheduler clusters in the `mergePeers` function.
Documentation update:
* [`manager/job/sync_peers.go`](diffhunk://#diff-e9f785a9d48a7b2ad2641434fc567ca957fe98308c11fadc0e53d6e82df00debL42-R43): Updated the `SyncPeers` interface comment to specify that it is only supported in the Rust client.
Functionality improvement:
* [`manager/job/sync_peers.go`](diffhunk://#diff-e9f785a9d48a7b2ad2641434fc567ca957fe98308c11fadc0e53d6e82df00debR199-R205): Added a condition in the `mergePeers` function to skip sync …

fix: skip the sync peer that does not belong to the scheduler cluster

---

go.mod
go.sum
scheduler/resource/persistentcache/host_manager.go
scheduler/resource/persistentcache/host_manager_mock.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/peer_manager_mock.go
scheduler/resource/persistentcache/task.go
scheduler/resource/persistentcache/task_manager.go
scheduler/resource/persistentcache/task_manager_mock.go
scheduler/scheduling/evaluator/evaluator.go
scheduler/scheduling/evaluator/evaluator_base.go
scheduler/scheduling/evaluator/evaluator_base_test.go
scheduler/scheduling/evaluator/plugin_test.go
scheduler/scheduling/evaluator/testdata/main.go
scheduler/scheduling/evaluator/testdata/plugin/evaluator.go
scheduler/scheduling/mocks/scheduling_mock.go
scheduler/scheduling/scheduling.go
scheduler/service/service_v2.go

This pull request includes changes to the `scheduler/resource/persistentcache` package to add new functionalities and improve existing ones. The most important changes include adding a new method to load hosts randomly, modifying existing methods to use Redis transactions, and updating data types for task attributes.
* [`scheduler/resource/persistentcache/host_manager.go`](diffhunk://#diff-cab2c0c5532854f2dd2b4557cc339dd396bccb1ea3a66af3ffc13821da7e3a8dR56-R58): Added `LoadRandom` method to load hosts randomly through the set of Redis. [[1]](diffhunk://#diff-cab2c0c5532854f2dd2b4557cc339dd396bccb1ea3a66af3ffc13821da7e3a8dR56-R58) [[2]](diffhunk://#diff-cab2c0c5532854f2dd2b4557cc339dd396bccb1ea3a66af3ffc13821da7e3a8dR589-R623)
* [`scheduler/resource/persistentcache/peer_manager.go`](diffhun …

feat: replicate persistent cache task when task needs persistent replicas

---

go.mod
go.sum
scheduler/job/job.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/service/service_v2.go

This pull request includes various improvements and bug fixes across multiple files, primarily focusing on enhancing the `PeerManager` interface and related functionalities. The most important changes include adding new methods to the `PeerManager` interface, updating logging for better error tracking, and modifying the `DeletePersistentCacheTask` function to ensure proper cleanup.
Enhancements to `PeerManager` interface:
* Added `LoadAllIDsByTaskID` and `LoadAllIDsByHostID` methods to the `PeerManager` interface to retrieve peer IDs by task ID and host ID respectively. [[1]](diffhunk://#diff-243b8e8011a1eb5e57b015c90ddff263d31ea40d2123fe67763fd114a6486452R54-R56) [[2]](diffhunk://#diff-243b8e8011a1eb5e57b015c90ddff263d31ea40d2123fe67763fd114a6486452R66-R68)
Logging improvements:
* …

feat: delete persistent cache task from peer

---

go.mod
go.sum
pkg/rpc/dfdaemon/client/client_v2.go
pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go
scheduler/resource/persistentcache/peer.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/peer_manager_mock.go
scheduler/resource/standard/seed_peer_client_mock.go
scheduler/scheduling/mocks/scheduling_mock.go
scheduler/scheduling/scheduling.go
scheduler/service/service_v2.go

This pull request includes changes to the persistent cache task management and scheduling logic, as well as updates to mock implementations and dependency versions. The most important changes focus on adding new methods for updating persistent cache tasks, improving the handling of peer states, and refining the scheduling logic.
* Added `UpdatePersistentCacheTask` method to `V2` interface and its implementation in `client_v2.go` to update persistent cache task information. [[1]](diffhunk://#diff-4941d744e2734dadec552334f209d76d28196a136dc78a0fa26dceb837b45db2R143-R145) [[2]](diffhunk://#diff-4941d744e2734dadec552334f209d76d28196a136dc78a0fa26dceb837b45db2R218-R226)
* Modified `peer_manager.go` to correctly set task joint-set TTL and handle peer deletion more robustly by using the task ID …

feat: replicate the persistent cache task when delete host

---

client/config/peerhost.go
client/daemon/daemon.go
client/daemon/peer/peertask_conductor.go

feat: add option to cancel idle peer task

---

go.mod
go.sum
scheduler/resource/persistentcache/host_test.go
scheduler/resource/persistentcache/peer_test.go
scheduler/resource/persistentcache/task_test.go

This pull request includes several changes to the `scheduler/resource/persistentcache` package, adding new tests for the `Host`, `Peer`, and `Task` components, and updating dependencies in the `go.mod` file. The most important changes include the addition of comprehensive test cases for `Host`, `Peer`, and `Task` structs, as well as the inclusion of new dependencies for Redis and Redis mock.
* [`scheduler/resource/persistentcache/host_test.go`](diffhunk://#diff-afcb6469761c0aa8f6f005d609396d88981e640448633c881acd407ef38a3cf6R1-R273): Added new test cases for the `Host` struct, including mock data and a test for the `NewHost` function.
* [`scheduler/resource/persistentcache/peer_test.go`](diffhunk://#diff-108757ed502ebf22899acefce13ecacb501cb03b8cd600d70b7b3fcc3e3e4b50R1-R115): Added new …

test(scheduler/resource): add host, peer and task uint tests

---

scheduler/resource/persistentcache/host_manager.go
scheduler/resource/persistentcache/host_manager_test.go
scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/task_manager.go

This pull request includes changes to the `scheduler/resource/persistentcache` package to ensure that time intervals are stored in nanoseconds. The most important changes include updates to the `Store` methods in the `hostManager`, `peerManager`, and `taskManager` to convert time intervals to nanoseconds.
Time interval conversion to nanoseconds:
* [`scheduler/resource/persistentcache/host_manager.go`](diffhunk://#diff-cab2c0c5532854f2dd2b4557cc339dd396bccb1ea3a66af3ffc13821da7e3a8dL512-R512): Modified the `Store` method to convert `announce_interval` to nanoseconds.
* [`scheduler/resource/persistentcache/peer_manager.go`](diffhunk://#diff-243b8e8011a1eb5e57b015c90ddff263d31ea40d2123fe67763fd114a6486452L198-R198): Modified the `Store` method to convert `cost` to nanoseconds.
* …

test(scheduler/persistentcache): add uint test for host manager

---

scheduler/resource/persistentcache/peer_manager_test.go
scheduler/resource/persistentcache/task_manager_test.go

This pull request includes changes to the `scheduler/resource/persistentcache/task_manager_test.go` file to improve the consistency and reliability of the `TestTaskManager` functions. The most important changes involve updating the task state representation and ensuring mock Redis clients are always initialized.
Updates to task state representation:
* Changed the task state from a string to the `TaskStateSucceeded` constant in `TestTaskManager_Load` and `TestTaskManager_LoadAll` functions. [[1]](diffhunk://#diff-5a61ad647f10fda37745b66568f273cb946e897d8d2ca5319839b375f5020cecL130-R130) [[2]](diffhunk://#diff-5a61ad647f10fda37745b66568f273cb946e897d8d2ca5319839b375f5020cecL530-R525)
Improvements to mock Redis client initialization:
* Removed unnecessary nil checks before calling …

test(scheduler/resource/persistentcache): add unit tests for peer manager

---

scheduler/scheduling/evaluator/evaluator_base_test.go

This pull request focuses on updating the `scheduler/scheduling/evaluator/evaluator_base_test.go` file to standardize the usage of types from the `standard` package instead of the `resource` package. The key changes are as follows:
Standardization of types:
* Changed the import from `resource "d7y.io/dragonfly/v2/scheduler/resource/standard"` to `d7y.io/dragonfly/v2/scheduler/resource/standard` for consistency.
* Updated variable declarations to use types from the `standard` package instead of the `resource` package. This affects `Host`, `CPU`, `Memory`, `Network`, `Disk`, and `Build` types. [[1]](diffhunk://#diff-017b88edb7a2ecf9332269ba266867c153b1f69041c6f30d448a9c594b66dca6L57-R57) [[2]](diffhunk://#diff-017b88edb7a2ecf9332269ba266867c153b1f69041c6f30d448a9c594b66dca6L78-R83) …

test(scheduler/scheduling): rename resource to standard

---

test/e2e/v2/dfget_test.go

This pull request introduces new test contexts for downloading files using `dfget` with the `transfer-from-dfdaemon` option in the `test/e2e/v2/dfget_test.go` file. The changes include adding tests for 1MiB and 10MiB file downloads.
New test contexts for `dfget`:
* Added context for downloading a 1MiB file using `dfget` with `transfer-from-dfdaemon` option. This includes setup and teardown steps, as well as validation of the downloaded file's SHA256 checksum.
* Added context for downloading a 10MiB file using `dfget` with `transfer-from-dfdaemon` option. This includes setup and teardown steps, as well as validation of the downloaded file's SHA256 checksum.

test(e2e/v2): add transfer-from-dfdaemon option for dfget test case

---

.github/workflows/docker.yml

This pull request includes updates to the `.github/workflows/docker.yml` file to enhance security by integrating a vulnerability scanner and uploading the results to GitHub. The most important changes include adding steps to run the Trivy vulnerability scanner and upload the scan results to GitHub's Security tab.
Security enhancements:
* Added a step to run the Trivy vulnerability scanner in tarball mode, targeting critical and high severity vulnerabilities, and outputting the results in SARIF format.
* Added a step to upload the Trivy scan results to the GitHub Security tab using the `github/codeql-action/upload-sarif` action.
https://github.com/dragonflyoss/dragonfly/issues/3811

chore: add trivy action for vulnerability scanner

---

scheduler/service/service_v2.go

This pull request includes a change to the `scheduler/service/service_v2.go` file to improve the handling of download piece requests by making the request handling asynchronous.
Concurrency improvements:
* [`scheduler/service/service_v2.go`](diffhunk://#diff-53ba821b898fb629c0cdb43d491c544e6b4ffc93aebb1fb05725ede3551de75cL1749-R1762): Modified the `AnnouncePersistentCachePeer` function to handle `DownloadPieceFinishedRequest` and `DownloadPieceFailedRequest` asynchronously using goroutines. This change ensures that the main thread is not blocked while handling these requests.

feat(scheduler): handle DownloadPieceFinishedRequest and DownloadPieceFailedRequest asynchronously

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
cmd/manager/main.go
manager/handlers/application.go
manager/handlers/bucket.go
manager/handlers/cluster.go
manager/handlers/config.go
manager/handlers/job.go
manager/handlers/oauth.go
manager/handlers/peer.go
manager/handlers/permission.go
manager/handlers/personal_access_token.go
manager/handlers/role.go
manager/handlers/scheduler.go
manager/handlers/scheduler_cluster.go
manager/handlers/scheduler_feature.go
manager/handlers/seed_peer.go
manager/handlers/seed_peer_cluster.go
manager/handlers/user.go

Update swagger annotations to support multiple API route groups.
This PR fixes an issue in Swagger documentation generation where the Swagger annotation incorrectly defined the BasePath as `/api/v1`, while in reality the Dragonfly Manager service provides two sets of API routes: `/api/v1` and `/oapi/v1`.
Specifically, the changes include:
1. Changed the `@BasePath` in `cmd/manager/main.go` from `/api/v1` to `/`
2. Added `@tag.name` and `@tag.description` annotations to describe the two API route groups
3. Modified the `@Router` annotations in handler files to use absolute paths instead of relative paths
4. Added dual route path annotations for handlers used in both `/api/v1` and `/oapi/v1` route groups (such as job and cluster handlers)
close …

feat: add swagger annotations for open API router

---

.github/workflows/compatibility-e2e-v2.yml

This pull request includes updates to the image tags in the `.github/workflows/compatibility-e2e-v2.yml` file and updates the subproject commit reference in the `client-rs` file. The most important changes are:
Updates to image tags:
* [`.github/workflows/compatibility-e2e-v2.yml`](diffhunk://#diff-94b4b9fb9262094b9e7ac79907321114cc3b29bb1b77634989d64226d4c6e06bL34-R49): Updated the image tags for `manager`, `scheduler`, `client`, and `seed-client` modules to their respective new versions.
Subproject reference update:
* [`client-rs`](diffhunk://#diff-84558f39216002fac1c3d61169fea29ee720b962a90c14d2f81a13e0ee6742bfL1-R1): Updated the subproject commit reference to the latest commit.

chore: update client version to 0.2.18

---

manager/middlewares/personal_access_token.go

Enhance Personal Access Token middleware with scope validation.
This PR enhances the Personal Access Token middleware with comprehensive validation features:
- Add detailed error logging for security audit purposes
- Add token state validation to ensure only active tokens are accepted
- Implement token expiration checking to reject expired tokens
- Add scope-based authorization to restrict access based on resource types
close https://github.com/dragonflyoss/dragonfly/issues/3883
This change significantly improves the security of the API by ensuring that personal access tokens are properly validated before granting access. The previous implementation only verified token existence without checking its state, expiration, or permissions.
The scope-based validation ensures that tokens can only …

feat: enhance PAT validation in middleware

---

manager/job/preheat.go
manager/job/types.go
manager/middlewares/personal_access_token.go
manager/service/personal_access_token.go
manager/types/persional_access_token.go

This pull request includes several changes to improve the handling of personal access tokens, refactor regular expressions, and update submodule references. The most important changes include moving the regular expression for access URLs, refactoring the personal access token middleware for better permission handling, and setting default scopes for personal access tokens.
* [`manager/middlewares/personal_access_token.go`](diffhunk://#diff-95dbb8ce3388da41ed4e95157980238ab0caf637204862ab8a2a05ce21e5cf0aR36-R37): Refactored the middleware to introduce `hasPermission` and `requiredPermission` functions, improving the handling of token permissions and error logging. [[1]](diffhunk://#diff-95dbb8ce3388da41ed4e95157980238ab0caf637204862ab8a2a05ce21e5cf0aR36-R37) …

feat(manager): an empty permissions list grants all permissions

---

scheduler/resource/persistentcache/peer_manager.go
scheduler/resource/persistentcache/peer_manager_test.go
scheduler/resource/persistentcache/task_manager.go
scheduler/resource/persistentcache/task_manager_mock.go
scheduler/resource/persistentcache/task_manager_test.go
scheduler/service/service_v2.go

- Changed key formatting in LoadAll methods of peer and task managers to use a prefix with wildcard for scanning.
- Renamed LoadCorrentReplicaCount to LoadCurrentReplicaCount for consistency.
- Added test cases for handling invalid peer and task keys in respective test files.
https://github.com/dragonflyoss/dragonfly/issues/3892

fix: update peer and task manager methods to use correct key format

---

api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/handlers/job.go
manager/handlers/persistent_cache.go
manager/handlers/persistent_cache_test.go
manager/router/router.go
manager/service/mocks/service_mock.go
manager/service/persistent_cache.go
manager/service/service.go
manager/types/job.go
manager/types/persistent_cache.go
pkg/redis/redis.go

Add persistent cache API in Dragonfly Manager.
This PR adds new features to manage persistent cache in Dragonfly Manager:
1. Implementation of Redis-based persistent cache operations:
- Added `GetPersistentCaches` method to list multiple persistent cache tasks
- Added `GetPersistentCache` method to retrieve a single persistent cache task
- Added `DestroyPersistentCache` method to delete a persistent cache task
2. Enhanced data structures:
- Completed `GetPersistentCacheResponse` structure with all necessary task information fields
- Implemented `PersistentCachePeer` structure with detailed peer information
- Added `PersistentCachePeerHost` structure with comprehensive host information
- Created `PersistentCacheParams` for API parameter handling
3. Technical improvements:
- Used Scan …

Implement persistent cache service 

---

client/config/dynconfig_manager.go
client/config/dynconfig_manager_test.go

This pull request makes improvements to the `GetResolveSchedulerAddrs` function in the `dynconfig_manager.go` file by simplifying the health check logic and removing redundant code.
Codebase simplification:
* [`client/config/dynconfig_manager.go`](diffhunk://#diff-2c8daaddbf3bfc3cc93f6a9f39a0b6be67f648f95ea03422161c26c2e7469ae1L128-R130): Removed redundant checks for the scheduler's host address and simplified the logic to only check the scheduler's IP address. This change reduces the complexity and potential duplication in the health check process.

feat(client): removing hostname resolution fallback when the IP address check fails

---

manager/searcher/searcher.go
pkg/rpc/scheduler/server/server.go

This pull request includes several changes to improve error logging, optimize code, and adjust default settings. The most important changes are summarized below:
Enhancements to logging:
* [`manager/searcher/searcher.go`](diffhunk://#diff-c57b43f4b362cffd77ed7a2270b57f37a85ec0341b53f2a4ff3413de35d67cd6L97-R97): Updated the logging statement to use `logger.Warnf` instead of `logger.Info` when loading the searcher plugin fails, providing more context about the error.
Code optimization:
* [`manager/searcher/searcher.go`](diffhunk://#diff-c57b43f4b362cffd77ed7a2270b57f37a85ec0341b53f2a4ff3413de35d67cd6L260-R261): Simplified the `calculateMultiElementAffinityScore` function by replacing a conditional block with a single `min` function and modifying the loop to use `range`.
Adjustments to …

feat: add log for searcher plugin

---

.goreleaser.yml

This pull request includes changes to the `.goreleaser.yml` file to update the `nfpms` section by replacing the `builds` key with the `ids` key for specific entries. The most important changes are as follows:
* Changed `nfpms` entry for `dfget` to use `ids` instead of `builds`. (`.goreleaser.yml` [.goreleaser.ymlL142-R142](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689L142-R142))
* Changed `nfpms` entry for `dfcache` to use `ids` instead of `builds`. (`.goreleaser.yml` [.goreleaser.ymlL188-R187](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689L188-R187))
* Changed `nfpms` entry for `dfstore` to use `ids` instead of `builds`. (`.goreleaser.yml` [.goreleaser.ymlL232-R230](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699 …

fix: replace builds with ids in config

---

manager/service/mocks/service_mock.go
manager/service/persistent_cache_task.go
manager/service/service.go
manager/types/persistent_cache_task.go

This pull request includes several changes to the `manager/service/persistent_cache_task.go` and related files to improve the handling of persistent cache tasks. The primary focus is on changing the return types and updating the query parameters.
* Modified the return type of `GetPersistentCacheTask` to return `types.PersistentCacheTask` instead of a pointer. [[1]](diffhunk://#diff-7eb5cd37cfb63d6f46d2a691550f7a56fd11367e3ad6276fc49e9c974464f854L41-R62) [[2]](diffhunk://#diff-7eb5cd37cfb63d6f46d2a691550f7a56fd11367e3ad6276fc49e9c974464f854L129-R144)
* Modified the return type of `GetPersistentCacheTasks` to return a slice of `types.PersistentCacheTask` instead of a slice of pointers.
* Updated the `loadTask` and `loadAllTasks` functions to reflect these changes. …

feat: change PersistentCacheTask to value type and ensure empty slice response

---

manager/service/persistent_cache_task.go

This pull request includes a minor change to the `manager/service/persistent_cache_task.go` file. The change corrects the logging statement to use the correct variable for the peer ID.
* [`manager/service/persistent_cache_task.go`](diffhunk://#diff-7eb5cd37cfb63d6f46d2a691550f7a56fd11367e3ad6276fc49e9c974464f854L219-R219): Corrected the logging statement in the `loadAllPeersByTaskID` function to use `peerID` instead of `peer.ID`.

fix(manager): fix peer ID logging in loadAllPeersByTaskID

---

CHANGELOG.md
api/manager/docs.go
api/manager/swagger.json
api/manager/swagger.yaml
manager/database/database.go
manager/handlers/audit.go
manager/handlers/audit_test.go
manager/middlewares/audit.go
manager/middlewares/personal_access_token.go
manager/models/audit.go
manager/router/router.go
manager/service/audit.go
manager/service/mocks/service_mock.go
manager/service/service.go
manager/types/audit.go

This pull request introduces a new audit logging feature, updates dependencies, and makes configuration changes. The most important changes include the addition of audit logging functionality, updates to the API documentation, and dependency updates.
* [`api/manager/docs.go`](diffhunk://#diff-fb4b019c51d6ad6041c4c033ac7ab5be21fd94850c4012d5cf4d7d1f7d0f4704R244-R298): Added new endpoint `/api/v1/audits` to fetch audit logs.
* [`manager/handlers/audit.go`](diffhunk://#diff-4799190c048bdc15d61349f8f443ef2e270c9bc91cbb075eb3cba8f05fbf964aR1-R57): Implemented handler for fetching audit logs.
* [`manager/middlewares/audit.go`](diffhunk://#diff-a31eafc4807e74cf7f02b3eb8755879f2dd74cbdae251dccf0eedd0e9f8e51c2R1-R80): Added middleware to log audit information for each request.
* …

feat: adds the audit middleware to records the system audit events

---

manager/handlers/audit_test.go
manager/service/audit.go
manager/types/audit.go

This pull request enhances the audit functionality by introducing support for query parameters in the `GetAudits` endpoint, improving the filtering and sorting of audit records, and updating the corresponding test cases. Below are the key changes:
* Updated the `GetAuditsQuery` struct in `manager/types/audit.go` to include new fields (`ActorType`, `ActorName`, `EventType`, `Operation`, `State`, `Path`, and `StatusCode`) for filtering audit records. Each field has validation rules for allowed values and formats.
* Modified the `GetAudits` method in `manager/service/audit.go` to apply filtering based on the new query parameters and to sort results by `created_at` in descending order.
* Added a new test case in `manager/handlers/audit_test.go` to verify the `GetAudits` endpoint's behavior …

feat: support query parameters for list audit API

---

pkg/math/rand.go

* See the License for the specific language governing permissions and
rand.Seed is deprecated: As of Go 1.20 there is no reason to call Seed with
a random value. Programs that call Seed with a known value to get
a specific sequence of results should use New(NewSource(seed)) to
obtain a local random generator.

refactor(math/rand): remove init function for rand.Seed

---

cmd/dependency/dependency.go
cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go

This pull request refactors the monitoring initialization logic to improve clarity and maintainability. The key changes include replacing the use of `freeport` with a simplified configuration for statsview, renaming variables for better readability, and updating the shutdown handling mechanism.
* Removed the `freeport` dependency and replaced the dynamic port assignment with a direct configuration using `net.IPv4zero` for statsview. This simplifies the initialization process for monitoring. (`cmd/dependency/dependency.go`, [[1]](diffhunk://#diff-3950f049f495b4c8f37427cc77a764da5c5b4e9f33ac41ab45ced60bea085196L35) [[2]](diffhunk://#diff-3950f049f495b4c8f37427cc77a764da5c5b4e9f33ac41ab45ced60bea085196L96-R124)
* Renamed the `fc` channel to `shutdowns` for better semantic clarity, and …

feat: resolve statsview hanging issue by improving port handling and shutdown logic

---

manager/database/database.go
manager/models/config.go

This pull request introduces changes to support a default garbage collection (GC) configuration in the database layer. The most important updates include adding new constants and types for GC configuration, seeding the database with a default GC configuration, and importing necessary dependencies.
* [`manager/database/database.go`](diffhunk://#diff-ec3993c2c1033e912870893c0da883551c7c46171de1fc6ceefd5ba8762618cdR204-R231): Updated the `seed` function to create a default GC configuration in the database if it does not already exist. This involves defining default TTL values for audit and job configurations, serializing them to JSON, and storing them in the `Config` table.
* [`manager/models/config.go`](diffhunk://#diff-f801ef1a0b8c1315f1b86c72af575edbcb057eb11cd8e300317967204796eb86R19-R33) …

feat: add the default gc config

---

.github/workflows/release.yml

This pull request updates the `.github/workflows/release.yml` file to enhance the release workflow by modifying how the `tag_name` output is handled and ensuring consistency in the workflow configuration.
Key changes to the release workflow:
* **Addition of `tag_name` output in `goreleaser` job:**
- Added a new output `tag_name` to the `goreleaser` job to capture the tag name generated during the build process. (`[.github/workflows/release.ymlR19](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R19)`)
* **Update to `upload-tag-name` in `slsa-github-generator`:**
- Updated the `upload-tag-name` input to use the `tag_name` output from the `goreleaser` job instead of the `release` job, ensuring the correct tag name is passed for the release process. …

chore(.github/workflows/release.yml): update release workflow to correctly pass tag_name output to SLSA generator

---

manager/models/models.go

This pull request simplifies the `BaseModel` struct in `manager/models/models.go` by removing redundant GORM tags from the `CreatedAt` and `UpdatedAt` fields.
Code simplification:
* [`manager/models/models.go`](diffhunk://#diff-f0ba3380214024f46eceeacea13b1848d224da336ff53494564553b368a6566eL33-R34): Removed the `gorm` tags specifying column names, types, defaults, and comments for the `CreatedAt` and `UpdatedAt` fields in the `BaseModel` struct, leaving only the `json` tags.
https://github.com/dragonflyoss/dragonfly/issues/3989

fix: remove the gorm tag for CreatedAt and UpdatedAt

---

manager/config/config.go
manager/config/config_test.go
manager/config/constants.go

This pull request removes the `GCConfig` struct and its associated configuration, validation, and test cases from the `manager/config` package. The changes simplify the `JobConfig` structure by eliminating the GC-related fields and logic.
* Removed the `GCConfig` struct and its fields (`Interval`, `TTL`, `BatchSize`) from the `JobConfig` definition in `config.go`. This also includes removing the corresponding YAML and mapstructure tags.
* Deleted the initialization of default GC configuration values in the `New` function.
* Removed GC-related validation logic from the `Validate` method in the `Config` struct.
* Removed GC configuration initialization from the `TestConfig_Load` test case in `config_test.go`.
* Deleted test cases in `TestConfig_Validate` that were validating GC-specific …

refactor: remove legacy job gc config

---

.github/workflows/stale.yml

This pull request introduces a new GitHub Actions workflow to automatically manage stale issues and pull requests in the repository. The workflow is designed to identify and close inactive items based on configurable thresholds.
* [`.github/workflows/stale.yml`](diffhunk://#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894R1-R29): Added a workflow named "Close stale issues and PRs" that runs on a schedule and can be triggered manually. It uses the `actions/stale` action to mark issues and PRs as stale after 90 days of inactivity and close them after 60 additional days. It also exempts items with specific labels (`bug`, `wip`, `on-hold`) or milestones from being marked as stale.

chore(.github/workflows): add stale action

---

manager/gc/audit.go
manager/manager.go

This pull request introduces a new garbage collection (GC) task for cleaning up audit records in the Dragonfly Manager. The most important changes include adding the `audit` GC task implementation, registering it with the GC scheduler, and defining default configurations for this task.
* **Added `audit` GC task**: Implemented a new GC task in `manager/gc/audit.go` to periodically delete outdated audit records. The task includes configurations for batch size, interval, and timeout, and uses a `RunGC` method to perform the cleanup. It also integrates a job recorder to log GC results.
* **Registered the `audit` GC task**: Updated the `manager/manager.go` file to register the new `audit` GC task with the GC scheduler during server initialization. …

feat: add the audit gc

---

.github/workflows/release.yml

This pull request updates the GitHub Actions workflow in `.github/workflows/release.yml` to enhance the release process by adding a new job for uploading SLSA provenance attestations and reorganizing permissions for better clarity.
* **Reorganized permissions in the `provenance` job**: Adjusted the order of `id-token`, `contents`, and `actions` permissions for better readability.
* **Added a new `upload-provenance` job**: 
- Introduced a job that depends on `goreleaser` and `provenance` to upload SLSA provenance attestations to the release.
- Configured the job to use `actions/checkout` and `actions/download-artifact` for downloading artifacts and then uploading them to the release using the GitHub CLI.

chore(.github/workflows/release.yml): add custom SLSA provenance and SPDX file upload to release workflow

---

.github/auto_assign.yml

This pull request modifies the `.github/auto_assign.yml` configuration file to change how reviewers and assignees are handled. The key changes involve disabling automatic addition of reviewers, enabling automatic addition of assignees, and updating related configuration fields.
* Disabled the automatic addition of reviewers to pull requests by setting `addReviewers` to `false`.
* Enabled the automatic addition of assignees to pull requests by setting `addAssignees` to `true`.
* Replaced the `reviewers` list with an `assignees` list, specifying `gaius-qi`, `yxxhero`, and `chlins` as assignees.
* Renamed the `numberOfReviewers` field to `numberOfAssignees` to align with the new configuration, and set its value to `3`.

chore(.github/auto_assign.yml): add assignees for PR

---

manager/middlewares/personal_access_token.go

This pull request refactors the `PersonalAccessToken` middleware in `manager/middlewares/personal_access_token.go` to improve the handling of the personal access token within the request context. The key change involves moving the context-setting logic for the token to an earlier point in the function for better auditability.
* [`manager/middlewares/personal_access_token.go`](diffhunk://#diff-95dbb8ce3388da41ed4e95157980238ab0caf637204862ab8a2a05ce21e5cf0aR69-R71): Moved the `c.Set("pat", &token)` call to an earlier point in the `PersonalAccessToken` function, ensuring the personal access token is set in the context immediately after it is retrieved. This change supports better audit logging and context management. [[1]](diffhunk://#diff-95dbb8ce3388da41ed4e95157980238ab0caf637204862ab8a2a …

fix: set the pat to context for audit

---

.github/workflows/auto-assign.yml

fix(.github/workflows): detected GitHub workflow tokens with excessive permissions in auto-assign.yml

---

manager/handlers/persistent_cache_task_test.go

Add unit tests for persistent cache task handlers.
https://github.com/dragonflyoss/dragonfly/issues/3892

feat: add unit tests for persistent cache task handlers

---

.github/workflows/compatibility-e2e-v2.yml
pkg/digest/digest.go
pkg/digest/digest_test.go
pkg/idgen/task_id.go
pkg/idgen/task_id_test.go
test/e2e/v2/dfcache_test.go

This pull request introduces changes to enhance functionality, update dependencies, and improve test coverage. The most significant updates include the addition of a new `CRC32FromStrings` function for generating checksums, updates to compatibility tests, and modifications to e2e tests for persistent cache task ID generation.
* Added a new `CRC32FromStrings` function in `pkg/digest/digest.go` to compute CRC32 checksums from multiple strings. This function is used for generating persistent cache task IDs.
* Introduced a `PersistentCacheTaskIDByContent` function in `pkg/idgen/task_id.go` that utilizes `CRC32FromStrings` to generate task IDs for persistent caching.
* Updated the image tag for `client` and `seed-client` in `.github/workflows/compatibility-e2e-v2.yml` from `v0.2.18` to …

feat: bump client to v0.2.26 and add CRC32FromStrings func

---

.github/workflows/stale.yml

This pull request updates the configuration for the stale workflow in `.github/workflows/stale.yml`. The changes adjust the timing and messaging for marking issues and pull requests as stale or closed.
* Reduced the `days-before-close` for issues from 60 days to 7 days and added `days-before-pr-close` with the same 7-day threshold.
* Adjusted the `days-before-stale` for pull requests to 120 days and added specific stale and close messages for pull requests.

chore(.github/workflows): change rules of the stale actions

---

manager/gc/audit.go
manager/gc/job.go
manager/manager.go
pkg/gc/gc.go
pkg/gc/gc_mock.go
pkg/gc/gc_test.go
pkg/gc/runner_mock.go
pkg/gc/task.go
scheduler/resource/persistentcache/host_manager.go
scheduler/resource/persistentcache/host_manager_mock.go
scheduler/resource/persistentcache/host_manager_test.go
scheduler/resource/standard/host_manager.go
scheduler/resource/standard/host_manager_mock.go
scheduler/resource/standard/host_manager_test.go
scheduler/resource/standard/peer_manager.go
scheduler/resource/standard/peer_manager_mock.go
scheduler/resource/standard/peer_manager_test.go
scheduler/resource/standard/task_manager.go
scheduler/resource/standard/task_manager_mock.go
scheduler/resource/standard/task_manager_test.go
scheduler/scheduler.go

This pull request introduces changes to the garbage collection (GC) system across multiple files to add support for `context.Context`. The updates ensure that GC operations are context-aware, allowing for better control and cancellation of long-running tasks. Below are the most important changes grouped by theme.
* Updated the `GC` interface in `pkg/gc/gc.go` to include `context.Context` as a parameter for methods like `Run`, `RunAll`, `Start`, and their implementations. This ensures all GC operations are context-aware. [[1]](diffhunk://#diff-ab4510a5b43b75ecc8656c954f48b486a78fff7c141823159c63c256aa4df20cL33-R40) [[2]](diffhunk://#diff-ab4510a5b43b75ecc8656c954f48b486a78fff7c141823159c63c256aa4df20cL86-R109) [[3]](diffhunk://#diff-ab4510a5b43b75ecc8656c954f48b486a78fff7c141823159c63c256aa …

refactor: pass context to run gc task

---

manager/config/config.go

feat(manager/config): add RedisConfig with documentation

---

cmd/dependency/dependency.go

Correct error logging format in `InitMonitor` function.

Correct error logging format in InitMonitor function

---

manager/handlers/bucket.go

refactor(manager/handlers/bucket.go): Reorder imports for clarity

---

manager/router/router.go

This pull request refactors the routing logic for the `/configs` API endpoints in `manager/router/router.go` to simplify middleware handling. The most important change consolidates the `jwt.MiddlewareFunc()` and `rbac` middleware into the group definition, reducing redundancy in individual route declarations.
* Consolidated `jwt.MiddlewareFunc()` and `rbac` middleware into the group definition for `/configs` API endpoints, simplifying the route definitions. Individual routes no longer explicitly include these middleware calls. (`[manager/router/router.goL207-R211](diffhunk://#diff-accc11d77962a73f2df2837787ed0d45a6a0d5ca6a020c3eec7726f447db2d9cL207-R211)`)

fix: add the authorization for get configs API

---

go.mod
go.sum
internal/job/constants.go
internal/job/job.go
manager/job/preheat.go
manager/job/task.go

This pull request introduces updates to dependency versions, refines Redis configuration defaults, and modifies task group handling to improve performance and maintainability. The most notable changes include upgrading the `dragonflyoss/machinery` dependency, updating Redis-related constants, and adjusting task group timeout values.
* Updated `dragonflyoss/machinery` to version `v1.10.13` in `go.mod` for compatibility and bug fixes.
* Updated Redis-related constants in `internal/job/constants.go`:
- Set `DefaultRedisMaxIdle` to `0` and introduced `DefaultRedisMaxActive` with a value of `300`.
- Reduced `DefaultRedisIdleTimeout` to `30` seconds.
- Added polling periods for normal (`DefaultRedisNormalTasksPollPeriod = 2000`) and delayed tasks (`DefaultRedisDelayedTasksPollPeriod = 500`).
* …

feat: Update machinery to v1.10.13 and optimize Redis connection pool for weak network conditions

---

go.mod
go.sum
internal/job/constants.go

This pull request includes updates to dependencies and configuration constants to improve performance and compatibility. The most important changes involve upgrading the `dragonflyoss/machinery` dependency and adjusting Redis-related configuration defaults.
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L26-R26): Upgraded `github.com/dragonflyoss/machinery` from v1.10.13 to v1.10.14 for compatibility and potential bug fixes.
* `internal/job/constants.go`: Adjusted Redis configuration defaults:
- Increased `DefaultRedisMaxIdle` from 0 to 10 and reduced `DefaultRedisMaxActive` from 300 to 50 to optimize connection pooling.
- Increased `DefaultRedisNormalTasksPollPeriod` from 2000ms to 2500ms for better task polling efficiency.

feat: update machinery to v1.10.14 and adjust Redis config

---

internal/job/constants.go
manager/gc/audit.go
manager/gc/job.go
manager/gc/recorder.go
manager/handlers/job.go
manager/manager.go
manager/service/job.go
manager/service/mocks/service_mock.go
manager/service/service.go
manager/types/job.go
pkg/gc/gc.go

This pull request introduces a new Garbage Collection (GC) job functionality to the system, including its creation, execution, and management. The changes span across multiple files and involve updates to constants, context handling, service interfaces, and job creation logic. Below is a summary of the most important changes:
* Added a new constant `GCJob` to represent the GC job type in `internal/job/constants.go`.
* Introduced a `CreateGCJob` method in the `service` layer to handle the creation of GC jobs. This includes asynchronous execution and polling for job completion. [[1]](diffhunk://#diff-32eba326fa80fbb1d566d606bb6bf6d24c19b9dd24687c2a361c69d9f2c56aeaR23-R99) [[2]](diffhunk://#diff-9b0bb37ddc1e552a9ed9188c29fe5c1431ea05503aaedbca98ebb74a22b5e637R122)
* Added a new …

feat: add the API for trigger the GC manually

---

internal/job/constants.go
manager/config/constants.go
manager/database/database.go
pkg/redis/redis.go
scheduler/config/config.go
scheduler/config/config_test.go
scheduler/config/constants.go
scheduler/config/testdata/scheduler.yaml
scheduler/scheduler.go

feat: set poolSize and poolTimeout for manager

---

manager/gc/audit.go
manager/gc/job.go

This pull request adds a `type` field to the arguments passed to garbage collection (`GC`) tasks in both the `audit` and `job` managers. This change ensures that the GC tasks are properly identified by their respective types.
Changes to garbage collection tasks:
* [`manager/gc/audit.go`](diffhunk://#diff-f6991c9ca09a3884ff8508562a8f6b5400dbf2b88eddd3df6ac28ec404957dedR69): Added `"type": AuditGCTaskID` to the `args` map in the `RunGC` method to specify the type of the audit GC task.
* [`manager/gc/job.go`](diffhunk://#diff-f072844f925732f5f4176bbe063a9a4b83acbfd8bc34d011f4338f18d3a8c7a8R68): Added `"type": JobGCTaskID` to the `args` map in the `RunGC` method to specify the type of the job GC task.

feat: add the type in the gc job args

---

cmd/dependency/base/option.go
cmd/dependency/dependency.go

This pull request introduces support for custom headers in tracing requests by extending the tracing configuration and updating the tracer initialization logic. The most important changes include adding a new `Headers` field to the `TracingConfig` struct and utilizing this field in the Jaeger tracer setup.
* [`cmd/dependency/base/option.go`](diffhunk://#diff-fe8a3936e9c6af18d24c9ee30eceb0a250c0cd608014ccf890b90c226e10ba63R32-R33): Added a new `Headers` field to the `TracingConfig` struct to allow specifying additional headers for tracing requests.
* [`cmd/dependency/dependency.go`](diffhunk://#diff-3950f049f495b4c8f37427cc77a764da5c5b4e9f33ac41ab45ced60bea085196L153-R153): Modified the `initJaegerTracer` function to pass the custom headers from the `TracingConfig.Headers` field to the …

feat: add headers for tracing

---

build/package/nfpm/config/dfget.yaml
cmd/dependency/base/option.go
cmd/dependency/dependency.go
cmd/dfcache/cmd/root.go
cmd/dfget/cmd/daemon.go
cmd/dfget/cmd/root.go
cmd/manager/cmd/root.go
cmd/scheduler/cmd/root.go
deploy/docker-compose/template/manager.template.yaml
deploy/docker-compose/template/scheduler.template.yaml
internal/dflog/logcore.go
internal/dflog/loginit.go
pkg/log/log.go
scheduler/resource/standard/peer_manager.go

This change adds `--log-level` option for manager and scheduler, with empty string as default value, so it won't affect existing depoyments. When specify `--log-level` and `--verbose` at the same time, `--log-level` will take precedence.
Note that since cmd and log functionality use shared code, so dfcahe and dfget are also affected.
Config files containing `verbose: true` have been updated, but not those under `testdata/`.
https://github.com/dragonflyoss/dragonfly/issues/2670
We see a lot of logs in our environment, it would be nice to be able to control log level of manager and scheduler so we can ignore not important logs and reduce log storage cost.
Also, the `peer fsm event failed: event Leave inappropriate because previous transition did not complete` log is too frequent, better to …

feat: add --log-level support for manager and scheduler

---

manager/models/casbin_rule.go

This pull request modifies the `CasbinRule` model in `manager/models/casbin_rule.go` to remove the `uniqueIndex:uk_casbin_rule` constraint from several fields. This change simplifies the database schema by eliminating unique indexing on these fields.
Schema changes:
* [`manager/models/casbin_rule.go`](diffhunk://#diff-3ee2d1ebf3c2f39fc7042650d20fa347119dfb726b3198879b6e43bee4b64826L21-R27): Removed the `uniqueIndex:uk_casbin_rule` constraint from the `Ptype`, `V0`, `V1`, `V2`, `V3`, `V4`, and `V5` fields in the `CasbinRule` model.

feat: remove unique index uk_casbin_rule from CasbinRule model to resolve permission issue

---

cmd/dependency/base/option.go
cmd/dependency/dependency.go
deploy/docker-compose/template/client.template.yaml
deploy/docker-compose/template/manager.template.yaml
deploy/docker-compose/template/scheduler.template.yaml
deploy/docker-compose/template/seed-client.template.yaml
manager/config/config.go
scheduler/config/config.go

This pull request introduces updates to the tracing configuration across multiple components in the codebase. The key changes include adding a `Path` field to the `TracingConfig` struct, modifying the initialization logic for HTTP and HTTPS tracing exporters to support the new `Path` field, and removing outdated tracing configuration sections from various Docker Compose templates.
* **Added `Path` field to `TracingConfig`:** Introduced a new `Path` field in the `TracingConfig` struct to specify the URL path for the tracing server (e.g., `/v1/traces`). (`cmd/dependency/base/option.go`, [cmd/dependency/base/option.goR35-R37](diffhunk://#diff-fe8a3936e9c6af18d24c9ee30eceb0a250c0cd608014ccf890b90c226e10ba63R35-R37))
* **Updated tracing exporter initialization:** Modified the …

feat: support HTTPS protocol for otel

---

manager/gc/job.go

This pull request makes a small but important change to the `RunGC` method in `manager/gc/job.go`. The change updates the default task ID used in background periodic execution scenarios to ensure it aligns with the correct identifier.
* [`manager/gc/job.go`](diffhunk://#diff-f072844f925732f5f4176bbe063a9a4b83acbfd8bc34d011f4338f18d3a8c7a8L83-R83): Replaced `AuditGCTaskID` with `JobGCTaskID` as the default task ID in the `RunGC` method.

fix: correct the task id of job gc

---

.github/workflows/compatibility-e2e.yml
deploy/docker-compose/template/client.template.yaml
deploy/docker-compose/template/seed-client.template.yaml

This pull request includes updates to dependency versions for improved compatibility and functionality. The changes primarily focus on updating image tags in the workflow configuration and updating the `client-rs` submodule reference.
* [`.github/workflows/compatibility-e2e.yml`](diffhunk://#diff-62915ee251a22234e796dacb74a6371d13312594faf822c06da355b816b846e9L34-R49): Updated image tags for `manager`, `scheduler`, `client`, and `seed-client` modules to newer versions (`v2.3.0` for `manager` and `scheduler`, `v1.0.1` for `client` and `seed-client`) to reflect the latest releases.
* [`client-rs`](diffhunk://#diff-84558f39216002fac1c3d61169fea29ee720b962a90c14d2f81a13e0ee6742bfL1-R1): Updated the submodule reference to a newer commit (`1a60b934e2efb48b3bc6bcdb6f317803b07d4e50`) for improved …

chore: bump client-rs to v1.0.1

---

manager/gc/scheduler.go
manager/manager.go

This pull request introduces a new garbage collection (GC) task for cleaning up inactive schedulers in the `manager` module. It includes the implementation of the scheduler GC logic and its integration into the server initialization process.
* Added a new `scheduler` GC task in `manager/gc/scheduler.go`:
- Defined constants for default GC parameters, such as batch size, TTL, interval, and timeout.
- Implemented the `scheduler` struct and its `RunGC` method to delete inactive schedulers based on the TTL. The method uses a database query to identify and remove records in batches, logging the results.
- Integrated a `jobRecorder` to track and record the GC task's execution details.
* Registered the new scheduler GC task in the server initialization process (`manager/manager.go`) to ensure it …

feat: add the gc task to clean up the inactive schedulers

---

manager/gc/seed_peer.go
manager/manager.go

This pull request introduces a new garbage collection (GC) task for cleaning up inactive seed peers, refactors the GC task registration process for better maintainability, and updates a submodule reference. Below is a summary of the most important changes:
* Added a new GC task in `manager/gc/seed_peer.go` to clean up inactive seed peers. This includes constants for default configurations (e.g., TTL, batch size, interval) and a `RunGC` method to perform the cleanup using database operations.
* Refactored the GC task registration in `manager/manager.go` by introducing a new `registerGCTasks` function. This consolidates the registration logic for all GC tasks, including the new seed peer GC task. [[1]](diffhunk://#diff-f679b61276b44dc3f4712950536707c0389ee4c536fc29837c0202c6e81c1bbfL171-L185 …

feat: add gc task to clean up inactive seed peers

---

manager/models/models.go
manager/rpcserver/manager_server_v2.go

* use longtext to fit larger clusters
* fix scheduler and seed-client register logic
This change updates the manager peer & scheduler registration logic to use more stable fields, ie. host names as opposed to IPs which can change when a pod is rescheduled.
Also use longtext instead of just text so that warming jobs don't fail in large clusters. 
Maybe https://github.com/dragonflyoss/client/issues/1116
Pod IPs will change. Pods will be rescheduled to other nodes, etc. When manager returns list of schedulers, it grabs the list in order. Thus it will ALWAYS return a stale scheduler / seed client address. The scheduler/seed reregistration SHOULD over rid the OLD entries.
Additionally jobs may be larger in pieces. This won't fit in text. Fit it in longtext instead.
- [ x] Bug fix (non-breaking …

Tune dragonfly to Remove Old Entries & Use Longtext to fit larger warming jobs

---

manager/rpcserver/manager_server_v2.go

This pull request updates the `managerServerV2` RPC server to include additional fields (`IP` and `Port`) when querying for `SeedPeer` and `Scheduler` records. These changes ensure more precise matching of records in the database.
Enhancements to database queries:
* [`manager/rpcserver/manager_server_v2.go`](diffhunk://#diff-d6cc9560b22b902b815a8aabd758bb6f6127891f1ddb666f462088228a6a860cR241-R242): Updated the `UpdateSeedPeer` method to include `IP` and `Port` in the query criteria for retrieving `SeedPeer` records.
* [`manager/rpcserver/manager_server_v2.go`](diffhunk://#diff-d6cc9560b22b902b815a8aabd758bb6f6127891f1ddb666f462088228a6a860cR455-R456): Updated the `UpdateScheduler` method to include `IP` and `Port` in the query criteria for retrieving `Scheduler` records.

fix: revert the remove of ip and port in mamager rpc server

---

Makefile

…e quality
- Add `fmt` and `vet` targets to Makefile for code formatting and static analysis.
- Add `precheck` target to run fmt, vet, lint, and test in one command.
- Update help section to document new targets.
- This improves developer experience and CI code quality checks.
- These changes improve developer experience and make it easier to maintain code quality in CI.

Add fmt, vet, and precheck targets to Makefile for better CI and code quality

---

SECURITY-INSIGHTS.yml

This pull request updates the `SECURITY-INSIGHTS.yml` file to reflect changes in the repository name and structure for the Dragonfly project. The most important changes include updating repository URLs and notes to align with the new repository naming conventions.
Updates to repository references:
* [`SECURITY-INSIGHTS.yml`](diffhunk://#diff-cb650ef911579f6ff1e25b1b7ab7e70a96c1a7e609cf5598a0635bca1b6984acL12-R17): Changed the `repository` URL from `https://github.com/dragonflyoss/Dragonfly` to `https://github.com/dragonflyoss/dragonfly` to match the updated repository name.
* [`SECURITY-INSIGHTS.yml`](diffhunk://#diff-cb650ef911579f6ff1e25b1b7ab7e70a96c1a7e609cf5598a0635bca1b6984acL12-R17): Updated the `url` for the project's security policy to use `main` instead of `master` in the path, …

chore(SECURITY-INSIGHTS.yml): change the address of dragonfly repository

---

manager/manager.go
scheduler/scheduler.go

- Optimized error handling when IP formatting fails in the manager and scheduler modules
- Replaced errors.New with fmt.Errorf to improve readability of error messages
- Extracted IP address string into a separate variable to enhance code maintainability

refactor(manager/scheduler): optimize IP formatting error handling

---

.github/workflows/compatibility-e2e.yml
scheduler/job/job.go
test/testdata/charts/config.yaml

This pull request updates the configuration settings in the `test/testdata/charts/config.yaml` file to adjust caching and scheduling behavior.
* **Cache Configuration:**
- Added a `redis` section under `cache` with a `ttl` (time-to-live) value of 5 seconds. (`[test/testdata/charts/config.yamlR31](diffhunk://#diff-59638ce8a58cd511c9e74c1c823454ba680f03345f727393e4b139b3b237c036R31)`)
* **Seed Client Configuration:**
- Increased the `dynconfig.refreshInterval` from 1 second to 5 seconds. (`[test/testdata/charts/config.yamlL109-R112](diffhunk://#diff-59638ce8a58cd511c9e74c1c823454ba680f03345f727393e4b139b3b237c036L109-R112)`)
- Increased the `scheduler.announceInterval` from 1 second to 10 seconds. (`[test/testdata/charts/config.yamlL109-R112](diffhunk://#diff-59638ce8a58cd511c9e74c1c823454ba …

test(e2e): update config to fix the slow resolution of seed peer address

---

manager/service/job.go

This pull request introduces minor updates to the job management logic in `manager/service/job.go`, focusing on task job creation and polling behavior.
Job creation and polling updates:
* Added support for passing the `Timeout` parameter from the API request (`json.Args.Timeout`) into the job creation logic, allowing for more flexible control over job execution timeouts.
* Increased the polling interval for the `pollingJob` function when creating a synchronous get-task job, changing the last argument from 4 to 60, which likely extends the polling timeout or interval.

feat(job): add timeout parameter to job scheduling

---

MAINTAINERS.md
OWNERS.md

Update the URLs pointing to the community maintainers file to the correct path under roles/Maintainers.md in both MAINTAINERS.md and OWNERS.md. This ensures the links direct users to the accurate location for maintainer information.

docs: fix maintainer links in MAINTAINERS.md and OWNERS.md

---

OWNERS.md

- Revise links to community resources in CODE_OF_CONDUCT.md
- Update contributing guidelines link in CONTRIBUTING.md
- Correct governance reference in GOVERNANCE.md
- Enhance maintainer info with role details in MAINTAINERS.md
- Streamline owner information and links in OWNERS.md
https://github.com/dragonflyoss/community/issues/97
We need to clean up the governance documents because they contain redundant jumps and cross-references.

docs: update community links in project documentation
