dragonflyoss/dragonfly

scheduler/service/service.go, scheduler/storage/storage.go
=> feat: store parent information

client/daemon/announcer/announcer.go, go.mod, go.sum, pkg/rpc/scheduler/client/client.go
- Change announcer validation.
=> feat: change announcer validation

client/daemon/peer/peertask_conductor.go, client/daemon/peer/peertask_manager_test.go
=> feat: support reregister peer task in client

internal/dflog/logcore.go
=> feat: change log rotate size

scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/constants.go, scheduler/config/testdata/scheduler.yaml, scheduler/resource/host.go, scheduler/resource/host_test.go, scheduler/resource/peer.go, scheduler/resource/peer_manager.go, scheduler/resource/peer_manager_test.go, scheduler/resource/peer_test.go, scheduler/resource/seed_peer.go, scheduler/resource/task.go, scheduler/resource/task_test.go, scheduler/service/service.go, scheduler/storage/storage_test.go, scheduler/storage/types.go
- Add the timeout of downloading piece to scheduler.
=> feat: add the timeout of downloading piece to scheduler

deploy/docker-compose/template/scheduler.template.yaml
- Add pieceDownloadTimeout to docker compose template.
=> feat: add pieceDownloadTimeout to docker compose template

ADOPTERS.md
- Add `Baidu` to `ADOPTERS.md`.
=> chore: add Baidu to ADOPTERS.md

.github/workflows/release.yml, .goreleaser.yml
- Releaser action disable cgo.
=> chore: releaser action disable cgo

client/daemon/peer/peertask_conductor.go
=> chore: optimize reregister

scheduler/config/config.go
- Add backSourceCount validation.
=> feat: add backSourceCount validation

go.mod, go.sum
=> chore: update api package verison

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/model/application.go, manager/service/application.go, manager/types/application.go, scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/constants.go, scheduler/config/testdata/scheduler.yaml, scheduler/rpcserver/rpcserver_test.go, scheduler/scheduler/scheduler.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service.go, scheduler/service/service_test.go
- Refactor back-to-source configuration.
=> refactor: back-to-source configuration

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/model/application.go, manager/service/application.go, manager/service/scheduler_cluster.go, manager/service/seed_peer_cluster.go, manager/types/application.go, manager/types/config.go
- Add priority to application in manager
=> feat: add priority to application in manager

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/types/application.go
- Rename url priority struct and remove PriorityLevel constants.
=> feat: rename url priority struct and remove PriorityLevel constants

go.mod, go.sum, manager/cache/cache.go, manager/rpcserver/rpcserver.go, manager/service/mocks/service_mock.go, pkg/rpc/manager/client/client.go, pkg/rpc/manager/client/mocks/client_mock.go, scheduler/config/dynconfig.go, scheduler/config/dynconfig_test.go, scheduler/config/mocks/dynconfig_mock.go, scheduler/resource/resource_test.go, scheduler/resource/seed_peer_client.go, scheduler/resource/seed_peer_client_test.go, scheduler/scheduler/scheduler.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service.go, scheduler/service/service_test.go
- Dynconfig adds list application in scheduler.
=> feat: dynconfig adds list application in scheduler

go.mod, go.sum, internal/dflog/logger.go, scheduler/config/dynconfig_test.go, scheduler/resource/peer.go, scheduler/resource/peer_test.go, scheduler/resource/resource_test.go, scheduler/resource/seed_peer.go, scheduler/resource/task.go, scheduler/resource/task_test.go, scheduler/scheduler/scheduler.go, scheduler/service/service.go, scheduler/service/service_test.go
- Trigger task with priority.
https://github.com/dragonflyoss/Dragonfly2/issues/1883
=> feat: trigger task with priority

go.mod, go.sum, scheduler/config/dynconfig_test.go, scheduler/resource/peer.go, scheduler/resource/peer_test.go, scheduler/service/service.go, scheduler/service/service_test.go
- Priority of the register parameter is higher than parameter of the application.
=> feat: priority of the register parameter is higher than parameter of the application

.github/workflows/e2e-nydus.yml, test/testdata/charts/config-nydus.yaml, test/testdata/charts/config.yaml, test/testdata/containerd/config.toml, test/testdata/k8s/nydus.yaml, test/testdata/kind/config.yaml
Add a new GitHub actions that run dragonfly + nydus in e2e test.
=> chore: add e2e with nydus snapshotter

.github/workflows/nydus-e2e.yml
Signed-off-by: bin liu <liubin0329@gmail.com>
=> upload nydus e2e logs to artifact

go.mod, go.sum, manager/rpcserver/rpcserver.go, scheduler/config/dynconfig_test.go, scheduler/resource/peer.go, scheduler/resource/peer_test.go, scheduler/service/service.go, scheduler/service/service_test.go
=> feat: update priority api

internal/job/job.go
Fix redis ping err on machinery connect to redis
#1915
=> fix machinery redis broker address format err

build/package/docs/dfget.1, build/package/docs/dfget.1.md
=> chore: add priority to dfget man page

client/config/dfget.go, client/config/dfget_darwin.go, client/config/dfget_linux.go, client/config/headers.go, client/config/peerhost.go, client/daemon/proxy/proxy.go, client/daemon/proxy/proxy_manager.go, client/daemon/transport/transport.go, client/dfget/dfget.go, cmd/dfget/cmd/root.go, pkg/net/http/http.go, scheduler/service/service_test.go
=> feat: client support 'priority' parameter

client/daemon/metrics/metrics.go, manager/metrics/metrics.go, scheduler/metrics/metrics.go, version/version.go
- Update version guage metrics.
=> feat: update version guage metrics

pkg/balancer/consistent_hashing.go
-  Fix panic caused by hashring not being built.
=> fix: panic caused by hashring not being built

client/config/constants.go, client/config/peerhost.go, client/config/peerhost_darwin.go, client/config/peerhost_linux.go, client/config/peerhost_test.go, client/config/testdata/config/daemon.yaml, client/daemon/daemon.go, manager/config/config.go, manager/config/config_test.go, manager/config/constants.go, manager/config/testdata/manager.yaml, manager/manager.go, manager/rpcserver/cert.go, pkg/issuer/dragonfly.go, pkg/issuer/dragonfly_manager.go, scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/constants.go, scheduler/config/testdata/scheduler.yaml, scheduler/scheduler.go
- Add IPAddresses and DNSNames to sans of client.
Fixes #1887
=> feat: add IPAddresses and DNSNames to sans of the cert

client/daemon/announcer/announcer.go
- Fix peer keepalive with manager
=> fix: peer keepalive with manager

pkg/rpc/cdnsystem/server/server.go, pkg/rpc/dfdaemon/server/server.go, pkg/rpc/manager/server/server.go, pkg/rpc/scheduler/server/server.go
- Register reflection on grpc server.
=> feat: register reflection on grpc server

client/daemon/rpcserver/rpcserver.go
=> fix: download context cancelled

client/daemon/rpcserver/rpcserver.go, pkg/source/list_metadata.go
=> chore: optimize download log

client/daemon/peer/peertask_conductor.go, client/daemon/peer/peertask_piecetask_synchronizer.go, client/daemon/peer/peertask_piecetask_synchronizer_test.go
=> feat: create synchronizers concurrently

internal/dflog/logger.go, internal/dflog/loginit.go, test/e2e/e2e_test.go
=> chore: create log dir

codecov.yml
- Change codecov coverage range.
=> chore: change codecov coverage range

test/e2e/e2e_test.go
=> chore: print e2e exec output

.github/workflows/docker.yml, .github/workflows/lint.yml
=> chore: update actions

.goreleaser.yml
=> chore: goreleaser set rlcp field

scheduler/service/service.go
- Fix context of trigger seed peer.
Fixes #1970
=> fix: context of trigger seed peer

codecov.yml
- Remove codecov patch feature.
=> chore: remove codecov patch feature

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/handlers/model.go, manager/handlers/role.go, manager/handlers/user.go
=> docs: fix manager swag error

client/daemon/peer/peertask_bitmap.go
=> fix: client bitMap extend capacity

scheduler/metrics/metrics.go, scheduler/service/service.go
=> feat: add fail_code in scheduler's DownloadFailureCount metric

manager/handlers/handlers.go
- Fix count of total page in pagination.
=> fix: count of total page in pagination

client/daemon/peer/peertask_conductor.go
=> fix: daemon recognize Code_SchedForbidden

client/config/dynconfig_manager.go, client/config/dynconfig_manager_test.go
=> fix: manager typo

client/dfstore/dfstore.go, client/dfstore/mocks/dfstore_mock.go, cmd/dfstore/cmd/copy.go
=> fix: dfstore typo

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml
=> chore: generate manager swagger

manager/searcher/searcher_test.go, scheduler/resource/host.go, scheduler/resource/host_manager.go, scheduler/resource/host_manager_test.go, scheduler/resource/host_test.go, scheduler/resource/peer_manager.go, scheduler/resource/peer_manager_test.go, scheduler/resource/peer_test.go, scheduler/resource/seed_peer.go, scheduler/resource/seed_peer_client.go, scheduler/resource/task.go, scheduler/resource/task_manager.go, scheduler/resource/task_manager_test.go, scheduler/resource/task_test.go, scheduler/scheduler/scheduler.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Change ok to loaded in loading func.
=> feat: change ok to loaded in loading func

.github/workflows/ci.yml, .github/workflows/docker.yml, .github/workflows/release.yml
=> chore: fix workflows typo

client/config/peerhost.go, client/daemon/daemon.go, cmd/dependency/dependency.go, cmd/dfget/cmd/root.go, cmd/dfget/main.go, pkg/source/clients/example/dfs.go, pkg/source/clients/hdfsprotocol/hdfs_source_client.go, pkg/source/clients/httpprotocol/http_source_client.go, pkg/source/clients/httpprotocol/http_source_client_test.go, pkg/source/clients/orasprotocol/oras_source_client.go, pkg/source/clients/ossprotocol/oss_source_client.go, pkg/source/clients/s3protocol/s3_source_client.go, pkg/source/loader/oras.go, pkg/source/source_client_builder.go, pkg/source/transport_option.go
=> feat: support source client option

scheduler/resource/peer.go, scheduler/resource/piece.go, scheduler/resource/piece_test.go, scheduler/resource/seed_peer.go, scheduler/service/service_v1.go
- change peer's piece type in resource
=> feat: change peer's piece type in resource

client/config/constants.go, client/daemon/peer/peertask_conductor.go, client/daemon/peer/peertask_piecetask_synchronizer.go, client/daemon/peer/piece_dispatcher.go, client/daemon/peer/piece_dispatcher_test.go, client/daemon/peer/piece_downloader.go, client/daemon/peer/piece_manager.go
Refactor dfdaemon's piece dispatcher to improve download speed.
20 clients download a same 10GB file. Seedpeer don't have cache.
- seedPeer * 1: 4C4G
- scheduler *1 : 4C4G
- dfget(normal peer) * 20 : 1C1G
- scheduler configuration:
- Filter Parent Count:6 
- Load Limit: 50 
- Download Parallel Count: 4
- seedPeer configuration:
- Load Limit: 50 
- bandwith between peers: 200MB/s
Mainly uploaded by seedPeer，upload traffic peek is 481MB/s
But it not work as expectedly
So I refactor piece random dispatcher. The main difference: first randomly choose a peer, then choose it's piece.
More normal peers are uploading. Upload traffic peek is 1.09GB/s, which is a great improve.
But seedPeer is still the most heavy-load peer.
Upload traffic peak …
=> refactor: piece_dispatcher considering score of parent peer

README.md
- Change introduction in readem.
=> docs: change introduction in readem

CHANGELOG.md
Signed-off-by: 李龙峰 <lilongfeng@inspur.com>
Spelling mistakes
none
=> Spelling mistakes

.gitignore, deploy/docker-compose/config/.gitignore
- Ignore configs generate with docker compose.
=> chore: ignore configs generate with docker compose

MAINTAINERS.md
- Change maintainers informations.
=> chore: change maintainers informations

scheduler/resource/peer.go, scheduler/resource/peer_test.go, scheduler/resource/task.go, scheduler/resource/task_test.go, scheduler/scheduler/scheduler.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Refactor peer resource with v2 version of the grpc.
=> refactor: peer resource with v2 version of the grpc

scheduler/resource/peer.go, scheduler/resource/peer_test.go, scheduler/resource/task.go, scheduler/resource/task_test.go, scheduler/scheduler/scheduler.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Add AnnouncePeers to task in resource.
=> feat: add AnnouncePeers to task in resource

pkg/types/types.go, scheduler/resource/host.go, scheduler/resource/host_manager_test.go, scheduler/resource/host_test.go, scheduler/resource/peer_manager_test.go, scheduler/resource/peer_test.go, scheduler/resource/seed_peer_test.go, scheduler/resource/task.go, scheduler/resource/task_manager_test.go, scheduler/resource/task_test.go, scheduler/scheduler/evaluator/evaluator_base_test.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Update task type from v1 to v2.
=> feat: update task type from v1 to v2

ADOPTERS.md
- Add miHoYo to `ADOPTERS.md`.
=> chore: add miHoYo to ADOPTERS.md

scheduler/resource/task.go
- Change PeerCountLimitForTask to 1000
#2058
=> feat: change PeerCountLimitForTask to 1000

.github/workflows/compatibility-e2e.yml, .github/workflows/e2e.yml
=> chore: change e2e timeout

manager/database/mysql.go
=> feat: set gorm log level

scheduler/resource/peer.go, scheduler/resource/peer_test.go, scheduler/resource/piece.go, scheduler/resource/seed_peer.go, scheduler/resource/task.go, scheduler/resource/task_test.go, scheduler/scheduler/evaluator/evaluator_base_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Refactor task piece with v2 grpc.
=> refactor: task piece with v2 grpc

scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/testdata/scheduler.yaml
- Remove training configuration in scheduler.
=> feat: remove training configuration in scheduler

pkg/types/types.go, scheduler/resource/task.go, scheduler/resource/task_test.go, scheduler/service/service_v1.go
- Refactor task.SizeScope with v2 grpc in scheduler.
=> refactor: task.SizeScope with v2 grpc in scheduler

scheduler/resource/host_manager_test.go, scheduler/resource/host_test.go, scheduler/resource/peer_manager_test.go, scheduler/resource/peer_test.go, scheduler/resource/seed_peer.go, scheduler/resource/seed_peer_test.go, scheduler/resource/task.go, scheduler/resource/task_manager_test.go, scheduler/resource/task_test.go, scheduler/scheduler/evaluator/evaluator_base_test.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Refactor the type of digest in task.
=> refactor: type of digest in task

client/daemon/peer/piece_downloader.go, client/daemon/peer/piece_manager.go, client/daemon/peer/piece_manager_test.go, pkg/digest/digest.go, pkg/digest/digest_reader.go, pkg/digest/digest_reader_test.go, pkg/digest/digest_test.go
=> refactor: package digest

client/daemon/daemon.go, pkg/idgen/host_id.go, pkg/idgen/host_id_test.go, scheduler/resource/host_test.go, scheduler/resource/seed_peer_client.go, scheduler/resource/seed_peer_client_test.go, scheduler/scheduler/evaluator/evaluator_base_test.go, scheduler/scheduler/scheduler_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Use v2 version of host id and add Addrs func to seed peer.
=> feat: use v2 version of host id and add Addrs func to seed peer

deploy/docker-compose/template/scheduler.template.yaml, scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/constants.go, scheduler/config/testdata/scheduler.yaml, scheduler/resource/host_test.go, scheduler/resource/peer_manager.go, scheduler/resource/peer_manager_test.go, scheduler/resource/seed_peer.go, scheduler/scheduling/evaluator/evaluator_base_test.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
=> feat: add host gc to scheduler

client/daemon/storage/local_storage.go, client/daemon/storage/local_storage_test.go
=> feat: don't GC task if expire time is 0

client/daemon/peer/piece_dispatcher_test.go
=> test: remove random test in pieceDispatcherTest

client/config/dynconfig.go, client/config/dynconfig_local.go, client/config/dynconfig_local_test.go, client/config/dynconfig_manager.go, client/config/dynconfig_manager_test.go, client/config/dynconfig_test.go, client/config/mocks/dynconfig_mock.go, client/daemon/daemon.go, pkg/rpc/health/client/client.go, scheduler/config/dynconfig.go, scheduler/config/dynconfig_test.go
- Dynconfig resolves addresses with host.
=> feat: dynconfig resolves addresses with host

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, go.mod, go.sum, manager/model/security_group.go, manager/model/seed_peer_cluster.go, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, manager/service/seed_peer_cluster.go, manager/types/seed_peer_cluster.go
- Remove Scopes and SecurityGroup in seed peer cluster.
=> feat: remove Scopes and SecurityGroup in seed peer cluster

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, go.mod, go.sum, manager/searcher/mocks/searcher_mock.go, manager/searcher/plugin_test.go, manager/searcher/searcher.go, manager/searcher/searcher_test.go, manager/searcher/testdata/main.go, manager/types/scheduler_cluster.go
- Add CIDR affinity to searcher.
Fixes #2099
=> feat: add CIDR affinity to searcher

manager/job/preheat.go
=> refactor: preheat job

client/daemon/daemon.go, client/daemon/peer/peertask_dummy.go, pkg/rpc/manager/client/client_v1.go, pkg/rpc/manager/client/client_v2.go, pkg/rpc/scheduler/client/client_v1.go, pkg/rpc/scheduler/client/client_v2.go, pkg/rpc/scheduler/client/mocks/client_v1_mock.go, pkg/rpc/scheduler/client/mocks/client_v2_mock.go, scheduler/scheduler.go
- Add `SyncNetworkTopology` and `SyncProbes` to scheduler client.
=> feat: add SyncNetworkTopology and SyncProbes to scheduler client

client/config/peerhost_test.go
=> chore: add unit tests for DaemonConfig.Validate()

client/config/peerhost_test.go
- Refactor client validate test
=> test: refactor client validate ut

test/README.md
Fix a minor typo in test/README.md
=> Fix a minor typo

manager/config/config.go, manager/config/config_test.go
- Add Validate test to manager config.
=> test: add Validate test to manager config

client/config/peerhost_test.go, codecov.yml, manager/config/config.go, manager/config/config_test.go, scheduler/config/config.go, scheduler/config/config_test.go
- Add Validate test to scheduler config.
=> test: add Validate test to scheduler config

client/daemon/daemon.go, client/daemon/peer/peertask_manager_test.go, client/daemon/peer/peertask_stream_backsource_partial_test.go, client/daemon/peer/traffic_shaper_test.go, client/daemon/rpcserver/rpcserver.go, client/daemon/rpcserver/rpcserver_test.go, client/daemon/rpcserver/seeder_test.go, pkg/resolver/scheduler_resolver.go, pkg/rpc/dfdaemon/server/server.go
Add health check for schedulers.
=> feat: enhance daemon health check

go.mod, go.sum, pkg/idgen/task_id.go, pkg/idgen/task_id_test.go, scheduler/metrics/metrics.go, scheduler/resource/task_manager.go, scheduler/resource/task_manager_test.go, scheduler/resource/task_test.go, scheduler/rpcserver/scheduler_server_v2.go, scheduler/scheduling/evaluator/evaluator_base_test.go, scheduler/scheduling/mocks/scheduling_mock.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go
- Change ScheduleCandidateParentsForNormalPeer implement.
- Remove TaskStateLeave event in task GC.
- Implement AnnouncePeer in service v2.
=> feat: change ScheduleCandidateParentsForNormalPeer implement

MAINTAINERS.md
- Add Garen Wen to maintainers.
=> chore: add Garen Wen to maintainers

ADOPTERS.md
- Add public cloud providers `Adopters.md`.
=> docs: add public cloud providers Adopters.md

README.md
- Add OpenSSF badge to README.md.
=> docs: add OpenSSF badge to README.md

scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
- Add handleRegisterSeedPeerRequest to service v2 in scheduler.
=> feat: add handleRegisterSeedPeerRequest to service v2 in scheduler

go.mod, go.sum, scheduler/resource/peer.go, scheduler/resource/peer_test.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
- Add handleDownloadPeerStartedRequest, handleDownloadPeerBackToSourceStartedRequest, handleDownloadPeerFinishedRequest, handleDownloadPeerBackToSourceFinishedRequest, handleDownloadPeerFailedRequest, handleDownloadPeerBackToSourceFailedRequest, handleDownloadPieceFinishedRequest, handleDownloadPieceBackToSourceFinishedRequest, handleDownloadPieceFailedRequest and handleDownloadPieceBackToSourceFailedRequest, to AnnouncePeer service api.
=> feat: implement announce peer

manager/metrics/metrics.go, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go
=> feat: add SearchSchedulerClusterCount metric to manager

pkg/net/url/url_test.go
=> test: improve TestFilterQuery

pkg/net/http/range.go
=> fix: remove unnecessary fmt.Sprintf calls

pkg/net/http/range_test.go
=> test: add UT for MustParseRang

pkg/cache/certify.go
=> refactor: optimize certifyCache Get function

pkg/net/url/url.go
=> refactor: improve the performance of the code

pkg/math/math_test.go
Improve test coverage from 90% to 100%.
=> test: improve TestMin

ADOPTERS.md
- Add [Volcano Engine](https://www.volcengine.com/) to `ADOPTERS.md`
=> docs: add Volcano Engine to ADOPTERS.md

manager/database/database.go
- Add error log to database in manager.
=> feat: add error log to database in manager

pkg/unit/byte_test.go
=> test: add UT for byte String function

pkg/unit/byte_test.go
=> test: improve Test_parseByte

codecov.yml
=> chore: change codecov rules

manager/metrics/metrics.go
- Fix manager metrics Subsystem.
=> fix: manager metrics Subsystem

Makefile
- Add build-man-page to Makefile.
=> chore: add build-man-page to makefile

.github/workflows/compatibility-e2e.yml
=> chore: change the compatibility testing version of manager and scheduler to v2.0.9

manager/config/config.go, manager/config/config_test.go, manager/config/constants.go, manager/config/testdata/manager.yaml
- Add advertisePort to manager.
=> feat: add advertisePort to manager

manager/database/database.go, manager/models/model.go, manager/models/scheduler.go, manager/models/seed_peer.go
-  Add inference model table in database.
=> feat: add inference model table in database

manager/models/model.go
- Add index `uk_model` to model table.
=> feat: add index uk_model to model table

manager/database/database.go
=> feat: remove model migration

client/config/dynconfig_manager.go, client/config/dynconfig_manager_test.go, client/daemon/announcer/announcer.go, client/daemon/daemon.go, go.mod, go.sum, manager/database/database.go, manager/job/preheat.go, manager/models/scheduler.go, manager/models/seed_peer.go, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, manager/searcher/searcher_test.go, manager/service/scheduler.go, manager/service/seed_peer.go, manager/types/scheduler.go, manager/types/seed_peer.go, pkg/rpc/manager/client/client_v1.go, pkg/rpc/manager/client/client_v2.go, pkg/source/clients/hdfsprotocol/hdfs_source_client.go, scheduler/announcer/announcer.go, scheduler/config/dynconfig.go, scheduler/config/dynconfig_test.go, scheduler/resource/seed_peer_client.go, scheduler/resource/seed_peer_client_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go
- Rename HostName to Hostname.
=> feat: rename HostName to Hostname

go.mod, go.sum, manager/rpcserver/security_server_v1.go, pkg/rpc/manager/client/client_v1.go, pkg/rpc/manager/client/client_v2.go, pkg/rpc/manager/server/server.go, pkg/rpc/security/client/v1.go
- Rename SecurityService to Security.
=> feat: rename SecurityService to Security

go.mod, go.sum, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, pkg/rpc/manager/client/client_v1.go, pkg/rpc/manager/client/client_v2.go, pkg/rpc/manager/client/constants.go, pkg/rpc/manager/client/mocks/client_v1_mock.go, pkg/rpc/manager/client/mocks/client_v2_mock.go
- Add CreateModel func to manager grpc client.
=> feat: add CreateModel func to manager grpc client

MAINTAINERS.md
-  Add Mohammed Farooq to MAINTAINERS.
=> chore: add Mohammed Farooq to MAINTAINERS

client/daemon/metrics/metrics_test.go, manager/metrics/metrics_test.go, scheduler/metrics/metrics_test.go
- Add new metrics test to service.
=> test: add new metrics test to service

scheduler/service/service_v1.go
- Fix fsm events failed when register task.
Fixes #2224
=> fix: fsm events failed when register task

client/daemon/peer/traffic_shaper.go
=> fix: traffic shaper record task not found

client/daemon/peer/traffic_shaper.go
=> chore: update traffic shaper log

manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, manager/searcher/mocks/searcher_mock.go, manager/searcher/searcher.go, manager/searcher/searcher_test.go, manager/searcher/testdata/main.go, manager/searcher/testdata/plugin/searcher.go
=> feat: add log to searcher plugin

manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go
- When the cache is missing, change the error log to a warning log.
=> feat: when the cache is missing, change the error log to a warning log

go.mod, go.sum, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go
- Update d7y.io/api package and change cpu percent validation.
=> feat: update d7y.io/api package and change cpu percent validation

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml
- Add features swagger config.
=> chore: add features swagger config

README.md
- Optimize Community description in README.md.
=> docs: optimize Community description in README.md

.github/workflows/cr.yml
- Add `ChatGPT Code Review` to workflows.
=> chore: add ChatGPT Code Review to workflows

trainer/config/config.go, trainer/config/config_test.go, trainer/config/constants.go
- Rename trainer config package to config.
=> feat: rename trainer config package to config

pkg/source/clients/orasprotocol/oras_source_client.go
=> chore: update oras error format

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/database/database.go, manager/handlers/cluster.go, manager/models/seed_peer_cluster.go, manager/router/router.go, manager/service/cluster.go, manager/service/mocks/service_mock.go, manager/service/seed_peer_cluster.go, manager/service/service.go, manager/types/cluster.go, manager/types/seed_peer_cluster.go, pkg/structure/structure.go, pkg/structure/structure_test.go
=> feat: add cluster api in manager

scheduler/scheduler.go, scheduler/storage/mocks/storage_mock.go, scheduler/storage/storage.go, scheduler/storage/storage_test.go
Add network topology storage interface.
=> feat: add network topology storage interface

manager/cache/cache.go, manager/database/database.go, pkg/redis/redis.go, pkg/redis/redis_logger.go
- Move redis package to pkg dir.
=> feat: move redis package to pkg dir

client/daemon/peer/peertask_dummy.go, go.mod, go.sum, pkg/rpc/scheduler/client/client_v1.go, pkg/rpc/scheduler/client/client_v2.go, pkg/rpc/scheduler/client/mocks/client_v1_mock.go, pkg/rpc/scheduler/client/mocks/client_v2_mock.go, scheduler/rpcserver/scheduler_server_v1.go, scheduler/rpcserver/scheduler_server_v2.go
- Remove SyncNetworkTopology API.
=> feat: remove SyncNetworkTopology API

manager/router/router.go
- Add `Access-Control-Allow-Credentials` to rest api.
=> feat: add Access-Control-Allow-Credentials to rest api

manager/middlewares/cors.go, manager/router/router.go
- Add CORS middleware to manager.
=> feat: add CORS middleware to manager

.github/workflows/docker.yml
Arm64 support is missing at version 2.0.9 
Resolves #2307 
- [] Bug fix (non-breaking change which fixes an issue)
=> feat: add multiple aarch support

scheduler/service/service_v1.go
- Rename createRecord to createDownloadRecord.
=> feat: rename createRecord to createDownloadRecord

.github/workflows/ci.yml, .github/workflows/compatibility-e2e.yml, .github/workflows/cr.yml, .github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/nydus-e2e.yml, .github/workflows/release.yml
=> chore: update timeout in actions

cmd/dfcache/cmd/root.go, cmd/dfget/cmd/daemon.go, cmd/dfget/cmd/root.go, cmd/manager/cmd/root.go, cmd/scheduler/cmd/root.go
- Remove log of configuration.
Fixes https://github.com/dragonflyoss/Dragonfly2/issues/2321
=> feat: remove log of configuration

client/daemon/objectstorage/objectstorage.go
-  Fix object downloads failed by dfstore when dfdaemon enabled concurrent.
Fixes #2327
=> fix: object downloads failed by dfstore when dfdaemon enabled concurrent

internal/job/job.go
=> feat: optimize job new in internal

manager/config/config_test.go, manager/config/testdata/manager.yaml
=> feat: remove compatibility logic for manager config testing

manager/config/config.go, scheduler/config/config.go
- Remove deprecated field in manager and scheduler.
=> feat: remove deprecated field in manager and scheduler

.github/workflows/ci.yml
[setup-go](https://github.com/actions/setup-go) has built-in functionality for caching and restoring go modules and build outputs. The action defaults to search for the dependency file - go.sum in the repository root, and uses its hash as a part of the cache key. To use the cache, we should first checkout code. Otherwise setup-go can't find go.sum and use/restore cache.
Related: https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
Please see warnings in https://github.com/dragonflyoss/Dragonfly2/actions/runs/4955055861.
=>  chore: checkout code first in CI

CHANGELOG.md
=> misspelling

.github/workflows/compatibility-e2e.yml, .github/workflows/e2e.yml, test/e2e/constants.go, test/e2e/dfget_test.go
=> test: improve timeout in recursive download

scheduler/service/service_v1.go, scheduler/service/service_v2.go
- Hide sensitive information in log.
=> feat: hide sensitive information in log

pkg/dfpath/dfpath_test.go
Add test case "new dfpath by dataDir"
=> test: add test case "new dfpath by dataDir"

go.mod, go.sum, pkg/redis/redis.go, pkg/redis/redis_logger.go
=> fix: package declaration error

pkg/slices/slices.go
- Add Reverse function to slice.
=> feat: add Reverse function to slice

pkg/slices/slices_test.go
=> test: add slice packege tests

scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/constants.go, scheduler/config/testdata/scheduler.yaml
- Optimize field name of ProbeConfig.
=> feat: optimize field name of ProbeConfig

scheduler/resource/seed_peer.go, scheduler/service/service_v1.go
- Handle context in triggerSeedPeerTask.
=> feat: handle context in triggerSeedPeerTask

client/config/dfcache.go, client/config/dfget.go, scheduler/networktopology/mocks/probes_mock.go, scheduler/networktopology/probes.go, test/e2e/e2eutil/exec.go
- Implement Enqueue and AverageRTT in probes.go.
=> feat: implement Enqueue and AverageRTT in probes.go

internal/util/util_test.go
Add test case "new dfpath by dataDir"
=> test: add unit test for ComputePieceCount

scheduler/networktopology/mocks/network_topology_mock.go, scheduler/networktopology/mocks/probes_mock.go, scheduler/networktopology/network_topology.go, scheduler/networktopology/network_topology_test.go, scheduler/networktopology/probes.go, scheduler/networktopology/probes_test.go
- Refactor network topology package.
=> refactor: network topology package

scheduler/networktopology/network_topology.go, scheduler/networktopology/network_topology_test.go, scheduler/networktopology/probes_test.go
Add probes and network topology unit tests.
=> test: add probes and network topology unit tests

scheduler/networktopology/network_topology.go, scheduler/networktopology/probes.go
- Remove redis Pipelined in network topology.
=> feat: remove redis Pipelined in network topology

scheduler/networktopology/network_topology.go, scheduler/networktopology/network_topology_test.go
- Delete host in network topology.
=> fix: delete host in network topology

scheduler/networktopology/mocks/probes_mock.go, scheduler/networktopology/probes.go, scheduler/networktopology/probes_test.go
- Change Dequeue to private func.
=> feat: change Dequeue to private func

pkg/redis/redis_test.go
Add test case "new dfpath by dataDir"
=> test: add unit test for MakeProbedAtKeyInScheduler

pkg/unit/byte_test.go
Add test case "new dfpath by dataDir"
=> test: add unit test for Bytes.Set

scheduler/networktopology/network_topology.go, scheduler/networktopology/network_topology_test.go
=> test: add delete host unit tests

manager/models/scheduler.go, manager/models/seed_peer.go
- Add ip to uk_scheduler index and uk_seed_peer index in manager.
=> feat: add ip to uk_scheduler index and uk_seed_peer index in manager

scheduler/networktopology/network_topology.go, scheduler/networktopology/network_topology_test.go, scheduler/networktopology/probes_test.go
Optimize network topology and probes unit tests.
=> test: optimize network topology and probes unit tests

scheduler/config/constants.go
- Change DefaultProbeInterval to 20 minute.
=> feat: change DefaultProbeInterval to 20 minute

go.mod, go.sum
- Update grpc api definition to v1.9.0.
=> chore: update grpc api definition to v1.9.0

client/daemon/announcer/announcer.go, scheduler/announcer/announcer.go
- Optimize announcer in scheduler and client.
=> feat: optimize announcer in scheduler and client

scheduler/announcer/announcer_test.go
- Optimize announcer in scheduler.
=> test: optimize announcer in scheduler

scheduler/announcer/announcer.go, scheduler/announcer/mocks/announcer_mock.go, scheduler/announcer/{;w, scheduler/scheduler.go
=> fix: announcer in scheduler

cmd/dfget/cmd/daemon.go, pkg/dfpath/dfpath_darwin.go, pkg/dfpath/dfpath_test.go
=> feat: optimize dfpath format

client/dfget/dfget.go
=> chore: update dfget recursive log

go.mod, go.sum
=> chore: update grpc proto version

pkg/dfpath/mocks/dfpath_mock.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> fix: Interval in SyncProbesResponse

.github/workflows/compatibility-e2e.yml, .github/workflows/e2e.yml, .github/workflows/nydus-e2e.yml
E2E tests report warning: `Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: engineerd/setup-kind@v0.5.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`.
Replace `engineerd/setup-kind@v0.5.0` due to the outdated Node.js version.
=> feat: update kind action

.github/workflows/lint.yml
The cache of `actions/setup-go` and `golangci/golangci-lint-action` has conflict for cache, try to disable one cache of them.
=> feat: update lint action to solve cache conflict

client/daemon/storage/local_storage.go, client/daemon/storage/local_storage_subtask.go, go.mod, go.sum
=> feat: daemon store file exclusive

pkg/rpc/scheduler/client/client_v1.go, pkg/rpc/scheduler/client/client_v2.go
- Add context key to SyncProbes.
=> feat: add context key to SyncProbes

.github/workflows/docker.yml, .goreleaser.yml
- Build trainer binary and publish trainer docker image.
=> chore: build trainer binary and publish trainer docker image

cmd/dfget/cmd/daemon.go, cmd/scheduler/cmd/root.go, cmd/trainer/cmd/root.go, internal/dflog/loginit.go, manager/manager.go, pkg/dfpath/dfpath.go, pkg/dfpath/dfpath_test.go, scheduler/scheduler.go, trainer/rpcserver/rpcserver.go, trainer/rpcserver/trainer_server_v1.go, trainer/trainer.go
- Refactor trainer server module.
=> refactor: trainer server module

Makefile, build/images/trainer/Dockerfile, hack/build.sh, hack/docker-build.sh, hack/docker-push.sh, hack/gen-buildx.sh, hack/install.sh, hack/kind-load.sh
=> chore: add trainer to Makefile and shell

client/daemon/networktopology/network_topology_test.go
Add client daemon network topology unit tests.
=> test: add client daemon network topology unit tests

manager/config/config.go, manager/config/config_test.go, manager/config/constants.go, manager/config/testdata/manager.yaml
Manager adds trainer configuration
=> feat: manager adds trainer config

scheduler/networktopology/network_topology.go
=> feat: set scan count for redis client

scheduler/config/config_test.go
Add a test case for config test to improve UT coverage.
=> test: optimize config in scheduler

scheduler/storage/storage_test.go
Add unit tests for DownloadCount and NetworkTopologyCount
=> test: add unit tests for DownloadCount and NetworkTopologyCount

pkg/digest/digest_test.go
=> test: optimize TestDigest_HashFile

pkg/slices/slices_test.go, scheduler/networktopology/network_topology.go, scheduler/networktopology/network_topology_test.go, scheduler/resource/host_manager_test.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2_test.go
Add unit tests of FindProbedHosts and LoadRandomHosts in host manager.
=> test: add unit tests of FindProbedHosts and LoadRandomHosts in host manager  

MAINTAINERS.md
=> chore: add fcgxz2003 to maintainer

deploy/docker-compose/template/scheduler.template.yaml
Fix scheduler.template.yaml comments.
=> fix: scheduler.template.yaml comments

manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, manager/types/model.go
manager adds createModel function
=> feat: manager adds createModel function

manager/manager.go, manager/models/model.go, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, manager/rpcserver/rpcserver.go, manager/service/model.go
=> fix: change model state in the same scheduler id

manager/types/model.go, manager/types/model_test.go, pkg/digest/digest_test.go
add unit test for model and digest
=> test: add unit test for model and digest

scheduler/service/service_v1.go
=> refactor: store pieceRecords in download record

scheduler/announcer/announcer_test.go, scheduler/storage/storage_test.go
Fix storage and announcer unit tests.
=> fix: storage and announcer unit tests

go.mod, go.sum, scheduler/service/service_v2.go
=> feat: update api verison to v1.9.7 and compatible with tiny task response

pkg/source/header_test.go
=> test: add unit test for Header.has

go.mod, go.sum, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, scheduler/announcer/announcer.go, scheduler/announcer/announcer_test.go, scheduler/config/dynconfig_test.go, scheduler/resource/seed_peer_client.go, scheduler/resource/seed_peer_client_test.go
=> feat: update api version to v2.0.7

go.mod, go.sum, scheduler/rpcserver/scheduler_server_v2.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: update api version to 2.0.8

build/images/trainer/Dockerfile
=> chore: change trainer expose port from 8002 to 9090 in Dockerfile

pkg/source/header_test.go
=> test: add unit test for Header.get

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/models/config.go, manager/models/job.go, manager/models/model.go, manager/models/models.go, manager/models/scheduler.go, manager/models/scheduler_cluster.go, manager/models/seed_peer.go, manager/models/seed_peer_cluster.go, manager/models/user.go, manager/service/cluster.go, manager/types/cluster.go
=> fix: response of cluster rest api

manager/types/application.go, manager/types/cluster.go, manager/types/config.go, manager/types/job.go, manager/types/oauth.go, manager/types/scheduler.go, manager/types/scheduler_cluster.go, manager/types/seed_peer.go, manager/types/seed_peer_cluster.go, manager/types/user.go
=> feat: change per_page to 1000

client/dfget/dfget.go
Fix: `os.Remove(target.Name())` is always fail when work directory is not same with output directory.
=> chore: clean temporary file when backsource error

go.mod, go.sum
=> feat: update api version

client/config/headers.go, client/daemon/objectstorage/objectstorage.go, client/daemon/objectstorage/types.go, client/dfstore/dfstore.go, pkg/objectstorage/objectstorage.go, pkg/objectstorage/obs.go, pkg/objectstorage/oss.go, pkg/objectstorage/s3.go
To implement Dragonfly-based object storage in JuiceFS, several functions were added to the `dfstore Client`, `daemon`, and `objectstorage` components as detailed below:
1. **dfstore Client:**
- Added the following functions:
- `CreateBucketWithContext`
- `CreateBucketRequestWithContext`
- `ListObjectMetadatasWithContext`
- `ListObjectMetadatasRequestWithContext`
- `CopyObjectWithContext`
- `CopyObjectRequestWithContext`
- The return value of `GetObjectMetadataWithContext` was extended to include `LastModifiedTime` and `StorageClass`.
2. **daemon:**
- Added handlers:
- `listObjectMetadatas`
- `createBucket`
- `copyObject`
- The return value of `HeadObject` was extended to include `LastModifiedTime` and `StorageClass`.
3. **objectstorage:**
- Added `copyObject` function for `s3`, `oss`, …
=> feat: provide support for JuiceFS objectStorage implementation

client/daemon/objectstorage/objectstorage.go, client/daemon/objectstorage/types.go, client/dfstore/dfstore.go, client/dfstore/mocks/dfstore_mock.go, pkg/objectstorage/constants.go, pkg/objectstorage/mocks/objectstorage_mock.go, pkg/objectstorage/objectstorage.go, pkg/objectstorage/obs.go, pkg/objectstorage/oss.go, pkg/objectstorage/s3.go
=> refactor: support for JuiceFS objectStorage implementation

manager/config/config.go, manager/config/config_test.go, manager/config/testdata/manager.yaml, manager/manager.go
=> feat: support tls in manager rest server

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/database/database.go, manager/handlers/personal_access_token.go, manager/models/personal_access_token.go, manager/router/router.go, manager/service/application.go, manager/service/mocks/service_mock.go, manager/service/personal_access_token.go, manager/service/service.go, manager/types/persional_access_token.go
=> feat: add personal access tokens api to rest server

scheduler/resource/seed_peer_client_test.go
Add unit test for seedPeerClient.Addrs
=> test: add unit test for seedPeerClient.Addrs

manager/manager.go, manager/middlewares/personal_access_token.go, manager/models/personal_access_token.go, manager/router/router.go
=> feat: add personal access token middleware to open api

manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go
=> feat: change seed peer state to active in UpdateSeedPeer api

manager/rpcserver/manager_server_v2.go
=> feat: create seed peer with active state in manager

manager/service/application.go, manager/service/cluster.go, manager/service/config.go, manager/service/job.go, manager/service/oauth.go, manager/service/personal_access_token.go, manager/service/scheduler.go, manager/service/scheduler_cluster.go, manager/service/seed_peer.go, manager/service/seed_peer_cluster.go
=> feat: use unscoped delete for resource in manager

manager/database/database.go
=> feat: change default cluster name to cluster-1

client/daemon/proxy/proxy.go
=> chore: use subtle compare to verify proxy auth

client/daemon/peer/peertask_manager.go, client/daemon/rpcserver/rpcserver.go
=> fix: potential nil panic

client/daemon/objectstorage/objectstorage.go, client/daemon/peer/piece_manager.go, client/daemon/storage/local_storage.go, client/daemon/storage/local_storage_subtask.go, client/dfget/dfget.go, scheduler/storage/storage.go, trainer/storage/storage.go
=> chore: optimize unhandled file close error

manager/config/config.go, manager/config/config_test.go, manager/config/testdata/manager.yaml, manager/job/job.go, manager/job/preheat.go
=> feat: add tls client config for preheat in manager

pkg/graph/dag/dag.go, pkg/graph/dag/vertex.go, scheduler/resource/task.go
=> feat: add lock to dag vertex and replace rand.Seed with rand.New

go.mod, go.sum
Add message required validation to url_meta and
optimize regex for the download digest.
=> chore: update d7y.io/api version to v2.0.18

scheduler/service/service_v1.go
=> fix: usage of architecture-dependent int type in the scheduler

scheduler/service/service_v1.go
=> fix: incorrect log message in the scheduler

manager/config/config.go, manager/config/config_test.go, manager/config/constants.go, manager/config/testdata/manager.yaml, manager/job/job.go, manager/job/preheat.go, scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/constants.go, scheduler/config/testdata/scheduler.yaml, scheduler/resource/host_manager_test.go, scheduler/resource/host_test.go, scheduler/resource/peer.go, scheduler/resource/peer_manager_test.go, scheduler/resource/peer_test.go, scheduler/resource/resource.go, scheduler/resource/seed_peer.go, scheduler/resource/seed_peer_test.go, scheduler/resource/task_manager_test.go, scheduler/resource/task_test.go, scheduler/scheduling/evaluator/evaluator_base_test.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: download tiny file with https scheme

client/config/dfstore.go
=> feat: net.JoinHostPort replace fmt.Sprintf

manager/config/constants.go
=> feat: change cache size in manager

manager/service/personal_access_token.go, manager/types/persional_access_token.go
=> fix: list personal access token with query string

manager/searcher/searcher.go, manager/searcher/searcher_test.go, scheduler/scheduling/evaluator/evaluator_base.go
=> feat: case insensitive string comparison in evaluater package of the manager

client/daemon/peer/piece_manager.go
=> fix: add traffic

client/daemon/peer/piece_downloader.go, scheduler/resource/peer.go
=> chore: check task id

client/daemon/rpcserver/rpcserver.go
=> chore: skip export to exist file

client/config/dfstore_test.go
=> test: add unit tests for dfstore

client/config/dfstore_test.go
=> test: rename Test_Validate to TestDfstoreConfig_Validate

pkg/unit/byte_test.go
=> test: add unit tests for byte

pkg/source/request_test.go
Add unit test for request.WithContext.
=> test: add unit test for request.WithContext

manager/types/application.go, manager/types/cluster.go, manager/types/config.go, manager/types/job.go, manager/types/model.go, manager/types/oauth.go, manager/types/persional_access_token.go, manager/types/scheduler.go, manager/types/scheduler_cluster.go, manager/types/seed_peer.go, manager/types/seed_peer_cluster.go, manager/types/user.go
=> feat: change max PerPage to 10000000

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/config/config.go, manager/config/config_test.go, manager/config/testdata/manager.yaml, manager/database/database.go, manager/handlers/peer.go, manager/metrics/metrics.go, manager/models/peer.go, manager/models/scheduler_cluster.go, manager/router/router.go, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, manager/rpcserver/rpcserver.go, manager/service/peer.go, manager/service/service.go, manager/types/peer.go
1. Add peer table in mysql in manager.
2. Add peer query api in manager.
3. Remove peer total metrics in manager.
=> feat: peer information is changed from being stored in metrics to being stored in mysql

manager/config/config.go, manager/job/job.go, manager/job/preheat.go, manager/job/sync_peers.go, manager/manager.go
=> feat: add createSyncPeers to async job in manager

client/dfget/dfget_test.go
Add unit test for Dfget.parseHeader.
=> test: add unit test for Dfget.parseHeader

client/daemon/announcer/announcer.go, client/daemon/daemon.go, go.mod, go.sum, internal/dflog/logger.go, internal/job/job.go, internal/job/job_test.go, internal/job/queue_test.go, manager/config/config.go, manager/config/config_test.go, manager/config/constants.go, manager/config/testdata/manager.yaml, manager/job/mocks/sync_peers_mock.go, manager/job/sync_peers.go, manager/manager.go, pkg/digest/digest_reader_test.go, scheduler/job/job.go, scheduler/resource/host.go, scheduler/resource/host_test.go, scheduler/service/service_v1.go, scheduler/service/service_v2.go
=> feat: merge sync peer with peer table in manager

client/config/dfget_test.go
Add unit test for DfgetConfig.Validate.
=> test: add unit test for DfgetConfig.Validate

client/daemon/peer/piece_downloader_test.go
Add unit test for PieceDownloader.Error.
=> test: add unit test for PieceDownloader.Error

GOVERNANCE.md
=> docs: add GOVERNANCE.md to dragonfly project

ADOPTERS.md, MAINTAINERS.md, OWNERS.md
=> docs: add OWNERS.md to project

pkg/net/http/http.go
=> feat: remove IsPrivate from safeSocketControl

MAINTAINERS.md
=> docs: add Akash HR to maintainers

go.mod, go.sum, manager/rpcserver/manager_server_v2.go
=> feat: add idc and location to ListSchedulers in manager

internal/job/job_test.go
Add unit test for MarshalResponse.
=> test: add unit test for MarshalResponse

pkg/net/http/http_test.go
Add unit test for safeSocketControl.
=> test: add unit test for safeSocketControl

go.mod, go.sum
=> chore: update api verison to v2.0.25

MAINTAINERS.md, OWNERS.md
=> chore: maintainer in alphabetical order of the company

client/dfstore/dfstore.go, client/dfstore/mocks/dfstore_mock.go, pkg/objectstorage/constants.go, pkg/objectstorage/objectstorage.go, pkg/objectstorage/obs.go, pkg/objectstorage/oss.go, pkg/objectstorage/s3.go
- Optimize GetObjectMetadatasInput validate in dfstore.
- Add convert to GetObjectMetadatasInput.
=> feat: optimize GetObjectMetadatasInput validate in dfstore

ADOPTERS.md
=> docs: remove china mobile in ADOPTERS.md

client/daemon/rpcserver/rpcserver.go
=> feat: change file mode when export task from local in dfcache

pkg/cache/cache_test.go
=> test: add unit test for Items

manager/router/router.go
=> feat: add cluster rest api to open api

manager/service/personal_access_token.go, manager/types/persional_access_token.go
=> feat: remove DefaultPersonalAccessTokenScopes in personalAccessToken

pkg/dfpath/dfpath_darwin.go, pkg/dfpath/dfpath_linux.go
=> fix(pkg/dfpath): can't build in darwin

build/images/manager/Dockerfile, hack/build.sh
=> chore: update console submodule to v1.0.11

build/images/manager/Dockerfile, hack/build.sh
=> feat: add network timout to yarn install

.github/workflows/docker.yml
=> chore: change timeout-minutes to 120 in docker actions

client/config/dfget_test.go
=> test: add unit test for Convert

scheduler/service/service_v1.go, scheduler/service/service_v2.go
=> fix: if network topology is nil, LeaveHost panic in scheduler

client/dfstore/dfstore.go
=> feat: convert limit in dfstore

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/handlers/peer.go, manager/router/router.go, manager/service/peer.go, manager/service/service.go, manager/types/model.go, manager/types/peer.go
=> feat: add CreatePeer to manager rest api

client/config/dynconfig_local_test.go
=> test: add unit test for Notify

pkg/source/clients/httpprotocol/http_source_client_test.go
Add unit test for GetLastModified.
=> test: add unit test for GetLastModified

client/daemon/storage/storage_manager.go
=> fix: overhead gc when DiskGCThreshold not set

go.mod, go.sum, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: update api to v2.0.29 with optional

.github/workflows/check-size.yml, .github/workflows/lint.yml, .github/workflows/nydus-e2e.yml, build/images/base/Dockerfile, build/images/dfdaemon/Dockerfile, build/images/manager/Dockerfile, build/images/scheduler/Dockerfile, build/images/trainer/Dockerfile, build/plugin-builder/Dockerfile, build/plugin-builder/images/dfdaemon/Dockerfile, build/plugin-builder/images/manager/Dockerfile, build/plugin-builder/images/scheduler/Dockerfile, go.mod, go.sum, hack/build.sh, hack/docker-build.sh, test/tools/no-content-length/Dockerfile
=> chore: update golang version to v1.21

client/daemon/rpcserver/rpcserver_test.go, cmd/dependency/dependency.go, pkg/rpc/mux_test.go, scheduler/storage/storage.go, scheduler/storage/storage_test.go, trainer/storage/storage_test.go
=> chore: remove refs to deprecated io/ioutil

client/daemon/transport/transport.go
Set download header log level debug
https://github.com/dragonflyoss/Dragonfly2/issues/2769
Authorization tokens are included in the log
=> fix: set download header log level debug

.github/workflows/compatibility-e2e.yml, .github/workflows/e2e.yml, Makefile, hack/install-e2e-test.sh
=> chore: update ginkgo version

client/daemon/objectstorage/objectstorage.go
=> feat: change error handle in object storage

client/daemon/objectstorage/objectstorage.go
=> fixed close file twice issue  when using dfstore upload large file

client/daemon/rpcserver/rpcserver.go
=> chore: optimize recursive download log

client/daemon/objectstorage/objectstorage.go
=> fix: task length did not match range length

cmd/dependency/dependency.go
=> chore(cmd/dependency): use errors.As for check not found error

client/daemon/objectstorage/objectstorage.go
=> feat: add comment about not checking object storage close

client/config/peerhost.go, cmd/dfget/cmd/root.go, pkg/rpc/interceptor.go, pkg/source/clients/orasprotocol/oras_source_client.go, pkg/source/source_client_builder.go, scheduler/networktopology/network_topology_test.go
=> chore: gofmt -w -r 'interface{} -> any' .

scheduler/metrics/metrics.go, scheduler/service/service_v1.go, scheduler/service/service_v2.go
=> feat: change DownloadPeerDuration metric type to summary

manager/auth/oauth/github.go, manager/auth/oauth/google.go, manager/auth/oauth/oauth.go
=> chore(manager/auth/oauth): rm unused args and struct

manager/database/database.go, manager/database/mysql.go, manager/database/postgres.go
=> chore(manager/database): rm unused cfg

manager/job/sync_peers.go
=> fix: sync peer with unknow relation

.github/workflows/compatibility-e2e.yml, .github/workflows/e2e.yml
=> chore: add free disk space in e2e actions

manager/job/sync_peers.go
=> feat: add sync peers log

hack/build.sh
=> fix: console build failed

scheduler/job/job.go
=> feat: print headers with debug log

manager/service/job.go
=> feat: list jobs order by created_at

scheduler/service/service_v1.go, scheduler/service/service_v2.go
=> feat: use scheduler's cluster id in host resource

client/daemon/peer/peertask_conductor.go, client/daemon/peer/piece_manager.go, client/daemon/storage/local_storage.go, client/daemon/storage/local_storage_subtask.go, client/daemon/storage/local_storage_test.go, client/daemon/storage/metadata.go
Split concurrentDownloadSource, prepare for piece group.
=> chore: split concurrentDownloadSource

go.mod, go.sum
=> chore: update console and api verison

manager/job/preheat.go
=> feat: if no matching manifest, then the log printing platform string

internal/dynconfig/dynconfig.go
=> feat: avoid hot reload when dynconfig refresh data

client/daemon/objectstorage/objectstorage.go, pkg/objectstorage/mocks/objectstorage_mock.go, pkg/objectstorage/objectstorage.go, pkg/objectstorage/obs.go, pkg/objectstorage/oss.go, pkg/objectstorage/s3.go
=> feat: add getObjectStorageMetadata to dfstore

pkg/objectstorage/oss.go, pkg/objectstorage/s3.go
=>  Fix dfstore getMetadata.

pkg/rpc/cdnsystem/server/server.go, pkg/rpc/dfdaemon/server/server.go, pkg/rpc/manager/server/server.go, pkg/rpc/scheduler/server/server.go, pkg/rpc/trainer/server/server.go
=> feat: change ratelimit's DefaultQPS and DefaultBurst

go.mod, go.sum, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: add reschedule handler for schduler v2

scheduler/scheduling/evaluator/evaluator.go, scheduler/scheduling/evaluator/evaluator_base.go, scheduler/scheduling/evaluator/evaluator_base_test.go, scheduler/scheduling/evaluator/testdata/main.go, scheduler/scheduling/evaluator/testdata/plugin/evaluator.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go
Implement batch calculation of candidate parents scores.
=> feat: implement batch calculation of candidate parents scores

scheduler/service/service_v2.go
=> fix: digest and range validation in v2

internal/job/job.go
CANNOT connet to Redis with special password #2893
=> fix: CANNOT connet to Redis with special password #2893

client/config/peerhost_darwin.go, client/config/peerhost_linux.go
=> feat: enable watch dog by default

scheduler/config/dynconfig.go
=> fix: log parse error

client/config/constants.go
=> fix the wrong word

scheduler/service/service_v2.go
=> feat: optimize service v2 log print

go.mod, go.sum, pkg/rpc/dfdaemon/client/client_v2.go, pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go
=> chore: update api version to v2.0.59

go.mod, go.sum, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go
=> feat: add prefetch to trigger seed peer downloads entire task

scheduler/config/constants.go, scheduler/resource/task.go
=> feat: change DefaultSchedulerFilterParentLimit to 15

.goreleaser.yml
=> fix: goreleaser config in v2.0.10

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, client/daemon/peer/peertask_conductor.go, client/daemon/peer/peertask_manager_test.go, client/daemon/peer/peertask_stream_backsource_partial_test.go, client/daemon/peer/traffic_shaper_test.go, go.mod, go.sum, manager/database/database.go, manager/types/scheduler_cluster.go, scheduler/config/constants.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go
=> feat: remove concurrent_piece_count in scheduler

pkg/rpc/health/client/client.go
=> fix: add context timeout to health check

internal/dynconfig/dynconfig.go, pkg/resolver/scheduler_resolver.go, pkg/resolver/seed_peer_resolver.go, pkg/rpc/interceptor.go, scheduler/config/dynconfig.go
=> feat: add log for resolver and dynconfig

pkg/rpc/cdnsystem/client/client.go, pkg/rpc/cdnsystem/server/server.go, pkg/rpc/dfdaemon/client/client_v1.go, pkg/rpc/dfdaemon/client/client_v2.go, pkg/rpc/dfdaemon/server/server.go, pkg/rpc/health/client/client.go, pkg/rpc/inference/client/client_v1.go, pkg/rpc/interceptor.go, pkg/rpc/manager/client/client_v1.go, pkg/rpc/manager/client/client_v2.go, pkg/rpc/manager/server/server.go, pkg/rpc/scheduler/client/client_v1.go, pkg/rpc/scheduler/client/client_v2.go, pkg/rpc/scheduler/server/server.go, pkg/rpc/security/client/client_v1.go, pkg/rpc/trainer/client/client_v1.go, pkg/rpc/trainer/server/server.go
=> feat: add WithStatsHandler and StatsHandler replace deprecated func

build/images/dfdaemon/Dockerfile, build/images/manager/Dockerfile, build/images/scheduler/Dockerfile, build/images/trainer/Dockerfile
=> chore: grpc_health_probe supports different architectures in dockerfile

scheduler/service/service_v2.go
=> feat: support logging the range and header when registering a task

go.mod, go.sum, pkg/rpc/health/client/client.go
=> chore: grpc reverts to v1.60.0-dev version

pkg/rpc/dfdaemon/client/client_v2.go, pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go, scheduler/resource/seed_peer.go, scheduler/resource/seed_peer_client_mock.go, scheduler/resource/seed_peer_mock.go, scheduler/resource/seed_peer_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: trigger download by task id

go.mod, go.sum, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: remove register seed peer in announce peer

scheduler/service/service_v2.go
=> feat: if trigger peer is seed peer, set NeedBackToSource flag true

scheduler/scheduling/mocks/scheduling_mock.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go
=> fix: peer events state failed when register task

scheduler/config/constants.go, scheduler/service/service_v2.go
=> feat: if seed peer download task, return NeedBackToSource directly

.goreleaser.yml
=> chore: add draft in goreleaser

pkg/slices/slices_test.go
=> test: add slice unit test

go.mod, go.sum, manager/rpcserver/manager_server_v2.go, manager/rpcserver/rpcserver.go, pkg/rpc/manager/client/client_v2.go, pkg/rpc/manager/client/mocks/client_v2_mock.go, scheduler/service/service_v2.go
=> feat: remove object storage and model message

.github/workflows/docker.yml
=> chore: add cache docker layers action to docker.yaml

deploy/docker-compose/README.md, deploy/docker-compose/run.sh
Update the docker compose document for local development.
=> Update docker compose document

scheduler/resource/task.go, scheduler/resource/task_test.go, scheduler/scheduling/scheduling.go, scheduler/service/service_v2.go
=> feat: change state set when trigger seed peer

go.mod, go.sum, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: report bad parents and add bad parents to block parent set

go.mod, go.sum, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: add block parent to peer if peer reschedule in downloading

manager/config/config.go, manager/config/config_test.go, manager/config/constants.go, manager/config/testdata/manager.yaml, manager/rpcserver/manager_server_v2.go, scheduler/config/config.go
=> feat: update scheduler and seed peer by ip and port

go.mod, go.sum
=> chore: update api verison to v2.0.76

scheduler/config/constants.go, scheduler/scheduling/scheduling.go, scheduler/service/service_v2.go
=> feat: prevent concurrent request to cause state switch failed

scheduler/service/service_v2_test.go
=> test: remove failed case in handleDownloadPeerStartedRequest

MAINTAINERS.md, OWNERS.md
=> chore: add yyzai384 to maintainers

go.mod, go.sum, scheduler/service/service_v2.go
=> feat: output path should be empty, prevent seed peer copy file to output path

client/dfget/dfget.go, cmd/dfget/cmd/root.go
=> chore: optimize dfget progressbar

scheduler/networktopology/network_topology.go, scheduler/networktopology/network_topology_test.go
revise findProbedHosts function
=> feat: revise findProbedHosts function

scheduler/scheduling/scheduling.go
=> feat: CanAddPeerEdge is moved to the end of filter

go.mod, go.sum, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: change request header in response

go.mod, go.sum, internal/job/types.go, manager/job/preheat.go, manager/service/preheat.go, manager/types/job.go, manager/types/preheat.go, pkg/idgen/task_id.go, pkg/net/url/url.go, pkg/net/url/url_test.go, scheduler/job/job.go, scheduler/resource/host_manager_test.go, scheduler/resource/host_test.go, scheduler/resource/peer_manager_test.go, scheduler/resource/peer_test.go, scheduler/resource/seed_peer.go, scheduler/resource/seed_peer_test.go, scheduler/resource/task.go, scheduler/resource/task_manager_test.go, scheduler/resource/task_test.go, scheduler/scheduling/evaluator/evaluator_base_test.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v1.go, scheduler/service/service_v1_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: replace filters with filteredQueryParams

scheduler/scheduling/scheduling.go
=> feat: optimize scheduling log when exceeded RetryBackToSourceLimit

scheduler/scheduler.go, scheduler/scheduling/evaluator/evaluator.go, scheduler/scheduling/evaluator/evaluator_base.go, scheduler/scheduling/evaluator/evaluator_base_test.go, scheduler/scheduling/evaluator/evaluator_network_topology.go, scheduler/scheduling/evaluator/evaluator_network_topology_test.go, scheduler/scheduling/evaluator/evaluator_test.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go
=> feat: optimize network topology in evaluator

go.mod, go.sum
=> chore: update api version and console version

client/config/dfcache.go, cmd/dfcache/cmd/root.go
=> feat: dfcache support customize socket path

client/config/dfcache.go, cmd/dfcache/cmd/root.go
=> fix: dfcache daemon sock

manager/searcher/searcher.go, manager/searcher/searcher_test.go, manager/types/scheduler_cluster.go
=> feat: cluster scopes add hostname regexes for client matchs cluster by hostname

client/daemon/peer/peertask_bitmap.go
Replace bitmap with bitset.
#1974
=> feat: replace bitmap with bitset

manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go
=> feat: add ip to keepalive's params

scheduler/config/config.go
=> fix: typo in scheduler config

go.mod, go.sum
=> chore: update api version

manager/middlewares/error.go, manager/router/router.go
=> fix: erorr middleware set error message return headers were already written

scheduler/resource/task.go
=> feat: change peer count limit for task

.github/workflows/check-size.yml
=> chore: add check-size to actions

.github/workflows/check-size.yml, .github/workflows/docker.yml
=> chore: move cache for buildx in docker actions

.github/workflows/compatibility-e2e.yml, .github/workflows/docker.yml, .github/workflows/e2e.yml
=> chore: remove tips in actions

.github/workflows/e2e-with-client-go.yml, client/config/peerhost.go, client/daemon/daemon.go, client/daemon/storage/local_storage.go, client/daemon/storage/local_storage_subtask.go, client/daemon/storage/storage_manager.go, test/testdata/charts/config-write-buffer-size.yaml
Support set WriteBufferSize for writing from source.
For some resource plugins, bigger buffer size with better performance.
=> feat: storage write buffer size

go.mod, go.sum
=> chore: update api verison to v2.0.106

client/daemon/storage/storage_manager.go
=> fix: storage buffer size

.github/workflows/compatibility-e2e-with-client-go.yml, .github/workflows/e2e-with-client-go.yml, .github/workflows/e2e-with-client-rs.yml
=> chore: rename test actions

hack/install-e2e-test.sh
Fix: `make e2e-test` error:
```
Error from server (NotFound): pods "file-server-no-content-length-0" not found
```
=> fix: make e2e-test

client/daemon/peer/peertask_conductor.go, scheduler/resource/seed_peer_client.go
=> chore: optimize log

client/daemon/peer/peertask_conductor.go, client/daemon/peer/peertask_manager.go
=> fix: parent peertask conductor race condition

client/daemon/peer/peertask_conductor.go, client/daemon/peer/peertask_manager_test.go
=> fix: tiny piece digest reader

client/daemon/peer/peertask_conductor.go, client/daemon/rpcserver/rpcserver.go
=> chore: update single piece storage

client/daemon/storage/mocks/stroage_manager_mock.go, go.mod, go.sum, pkg/rpc/dfdaemon/client/client_v2.go, pkg/rpc/dfdaemon/client/mocks/client_v1_mock.go, pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go, scheduler/resource/seed_peer.go, scheduler/resource/seed_peer_client_mock.go, scheduler/resource/seed_peer_mock.go, scheduler/resource/seed_peer_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: trigger download task by stream

client/daemon/storage/mocks/stroage_manager_mock.go, go.mod, go.sum, internal/job/types.go, manager/job/preheat.go, manager/service/job.go, manager/service/preheat.go, manager/types/job.go, pkg/rpc/dfdaemon/client/client_v2.go, pkg/rpc/dfdaemon/client/mocks/client_v1_mock.go, pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go, scheduler/config/dynconfig.go, scheduler/job/job.go, scheduler/resource/seed_peer.go, scheduler/resource/seed_peer_client_mock.go, scheduler/resource/seed_peer_mock.go, scheduler/resource/seed_peer_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: support preheating by v2 grpc protocol

test/e2e/v2/dfget_test.go
=> test: add piece lenght, tag, application test cases for dfget downloading

.github/workflows/e2e-v2.yml, test/e2e/v2/dfget_test.go, test/e2e/v2/proxy_test.go, test/testdata/charts/config-v2.yaml
=> test: add range download testings by prefetch proxy

build/images/manager/Dockerfile, build/images/scheduler/Dockerfile, test/e2e/v2/e2e_test.go, test/e2e/v2/manager/preheat.go, test/e2e/v2/util/exec.go
=> test: add preheat e2e testing for v2

.github/workflows/compatibility-e2e-v2.yml
https://github.com/dragonflyoss/client/issues/398
=> test: add compatibility e2e testing for v2

.gitignore
=> chore: change gitignore for vendor

manager/handlers/handlers_test.go
=> test: add unit test for manager handler

.github/workflows/compatibility-e2e-v2.yml, .github/workflows/e2e-v2.yml, test/e2e/v2/containerd_test.go, test/e2e/v2/dfget_test.go, test/e2e/v2/e2e_test.go, test/e2e/v2/proxy_test.go
=> test: delayed checking Seed Peer download content

client/config/peerhost_darwin.go, client/config/peerhost_linux.go, client/config/peerhost_test.go, client/config/testdata/config/daemon.yaml
… downloading large files
https://github.com/dragonflyoss/Dragonfly2/issues/3233
=> feat: set calculateDigest to false in dfdaemon, because it has bug in large files

test/e2e/v2/concurrency_test.go
=> test: change number of the concurrent in e2e testing

ADOPTERS.md
=> docs: add iQIYI to ADOPTERS.md

client/daemon/peer/peertask_conductor.go
=> chore: release failed running piece

scheduler/service/service_v2.go
=> fix: DownloadPeerDuration observe cost by milliseconds

.github/workflows/compatibility-e2e-v2.yml, go.mod, go.sum, pkg/digest/digest.go
=> chore: update api verison to v2.0.112

client/config/peerhost.go
=> fix: peer exchange option

client/daemon/pex/peer_exchange.go
=> chore: update pex initial backoff

client/daemon/transport/transport.go, go.mod, go.sum
=> chore: transport proxy ttl cache

scheduler/config/dynconfig.go
There are two repetitions of word "the" in some comments.
=> chore: fix typo in scheduler config

client/daemon/storage/local_storage.go
=> BUGFIX: hardlink

README.md, go.mod, go.sum, internal/dflog/logger.go, pkg/rpc/scheduler/client/client_v2.go, pkg/rpc/scheduler/client/mocks/client_v2_mock.go, scheduler/metrics/metrics.go, scheduler/rpcserver/scheduler_server_v2.go, scheduler/service/service_v2.go
=> chore: update client version

client/daemon/peer/peertask_conductor.go
=> fix: clean running piece done

client/daemon/objectstorage/objectstorage.go
Corrected spelling errors in Dragonfly2/client/daemon/objectstorage/objectstorage.go file, specifically in constant names and variable names.
No related issue. 
This change ensures consistency and accuracy in the codebase by fixing minor spelling errors.
=> fix: correct spelling typos

go.mod, go.sum
=> chore: update client and console verison

scheduler/config/constants.go, scheduler/resource/seed_peer_client.go, scheduler/resource/task.go, scheduler/scheduling/scheduling.go, scheduler/service/service_v2.go
=> feat: if host is seed client, set concurrentUploadLimit when dynconfig refreshes

manager/types/seed_peer_cluster.go, scheduler/config/constants.go
=> feat: change loadLimit validation to 50000

.github/workflows/release.yml
=> fix: release action unknown flag

go.mod, go.sum, pkg/rpc/dfdaemon/client/client_v2.go, pkg/rpc/dfdaemon/client/mocks/client_v2_mock.go, pkg/rpc/scheduler/client/client_v2.go, pkg/rpc/scheduler/client/mocks/client_v2_mock.go, scheduler/job/job.go, scheduler/resource/seed_peer_client_mock.go, scheduler/rpcserver/scheduler_server_v2.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: update api protoc version to v2.0.118

go.mod, go.sum, pkg/rpc/scheduler/client/client_v2.go, scheduler/rpcserver/scheduler_server_v2.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: add cache peer to grpc api

pkg/rpc/cdnsystem/client/client.go, pkg/rpc/cdnsystem/server/server.go, pkg/rpc/dfdaemon/client/client_v1.go, pkg/rpc/dfdaemon/client/client_v2.go, pkg/rpc/dfdaemon/server/server.go, pkg/rpc/health/client/client.go, pkg/rpc/inference/client/client_v1.go, pkg/rpc/manager/client/client_v1.go, pkg/rpc/manager/client/client_v2.go, pkg/rpc/manager/server/server.go, pkg/rpc/scheduler/client/client_v1.go, pkg/rpc/scheduler/client/client_v2.go, pkg/rpc/scheduler/server/server.go, pkg/rpc/security/client/client_v1.go, pkg/rpc/trainer/client/client_v1.go, pkg/rpc/trainer/server/server.go
=> feat: increase revice msg size and send msg size in grpc

deploy/docker-compose/docker-compose.yaml
Make the container name in the docker-compose.yml file corresponds to the container name in the run.sh script; otherwise, the run.sh script will be unable to remove the container. :alien:
=> rename container in compose config

client/daemon/proxy/proxy.go, client/daemon/proxy/proxy_manager.go
=> chore: avoid use default mux

scheduler/metrics/metrics.go
1. Align the comments of the scheduler metrics
2. Define uniform size constants for better human readability
=> refactor: update comments and define size constant for human readable

.github/workflows/compatibility-e2e-v1.yml, .github/workflows/e2e-v1-nydus.yml, .github/workflows/e2e-v1.yml
=> chore: update chart version for rust client

scheduler/service/service_v2.go
=> feat: use content.Background() to avoid stream cancel by dfdaemon

internal/job/job.go
=> chore: update rust client version

.github/workflows/ci.yml, .github/workflows/docker.yml
=> chore: add self-hosted runner for ci

.github/workflows/compatibility-e2e-v2.yml, go.mod, go.sum, pkg/digest/digest.go, pkg/objectstorage/mocks/objectstorage_mock.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: remove unused context and update api version

.github/workflows/compatibility-e2e-v2.yml, pkg/redis/redis_test.go
=> chore: update client verison to v0.1.96

CHANGELOG.md, client/config/dynconfig_local.go, client/config/dynconfig_manager.go, client/daemon/metrics/metrics.go, client/daemon/upload/types.go, client/daemon/upload/upload_manager.go, client/dfstore/dfstore.go, internal/dynconfig/dynconfig_test.go, manager/job/preheat.go, manager/rpcserver/manager_server_v1.go, manager/rpcserver/manager_server_v2.go, manager/service/service.go, pkg/gc/gc.go, pkg/issuer/dragonfly.go, pkg/issuer/dragonfly_manager.go, pkg/rpc/manager/client/client_v1.go, pkg/rpc/manager/client/client_v2.go, pkg/source/response.go, pkg/types/constants.go, scheduler/config/dynconfig.go, scheduler/resource/resource.go, scheduler/resource/seed_peer.go, scheduler/rpcserver/scheduler_server_v1.go, scheduler/service/service_v1.go, trainer/training/training.go
Scheduelr/Scheudler -> Scheduler
scehdule -> schedule
serivce  -> service
matedata -> metadata
instence  -> instance
indecates -> indicates
Downalod -> Download
clent -> client
prase -> parse
acitve -> active
featrue -> feature
=> chore: fix typo

client/daemon/peer/peertask_reuse.go, client/daemon/transport/transport.go
For library like opencv, it depends on AcceptRanges, otherwise it will complain "partial file" error.
=> feat: add accept ranges header

client/daemon/transport/transport.go, pkg/source/clients/httpprotocol/header.go
=> chore: export content range in http source

.github/workflows/scorecards.yml, README.md
PR to add the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action) and its [badge](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/) in the README file.
#3362 
Enhances the security posture, increasing user trust and reducing the risk of security exploits.
N/A
=> feat: added the scorecard github action and its badge

go.mod, go.sum
Fixed vulnerability which is reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/dragonflyoss/dragonfly2).
Part of #3441
=> vulnerability fix

scheduler/metrics/metrics.go, scheduler/resource/seed_peer.go, scheduler/rpcserver/scheduler_server_v1.go, scheduler/service/service_v1.go, scheduler/service/service_v2.go
=> feat: add ScheduleDuration for recording duration of the scheduling

build/images/dfdaemon/Dockerfile, build/images/manager/Dockerfile, build/images/scheduler/Dockerfile, build/images/trainer/Dockerfile, test/tools/no-content-length/Dockerfile
=> chore: fix 'as' keyword should match the case of the 'from' keyword

build/images/dfdaemon/Dockerfile, build/images/manager/Dockerfile, build/images/scheduler/Dockerfile
=> fix: key/value format with whitespace separator should not be used

client/daemon/metrics/metrics.go, client/daemon/peer/piece_manager.go
=> feat: daemon add back source metric

client/daemon/storage/local_storage.go, client/daemon/storage/storage_manager.go
=> chore: mute some reclaim check log

client/daemon/metrics/metrics.go, client/daemon/transport/transport.go
=> feat: add proxy error metric

manager/config/config.go, manager/config/config_test.go, manager/config/constants.go, manager/config/testdata/manager.yaml, manager/middlewares/rate_limit.go
=> feat: add ratelimit for job in manager

manager/config/constants.go, manager/router/router.go
=> feat: add rate limit middlewares for job

api/manager/docs.go, api/manager/swagger.json, api/manager/swagger.yaml, manager/handlers/scheduler_feature.go, manager/router/router.go, manager/service/mocks/service_mock.go, manager/service/scheduler_feature.go, manager/service/service.go, manager/types/scheduler.go, manager/types/scheduler_feature.go
=> feat: add scheduler features api for manager

go.mod, go.sum, manager/rpcserver/manager_server_v2.go, scheduler/announcer/announcer.go, scheduler/announcer/announcer_test.go, scheduler/scheduler.go
=> feat: add job feature for scheduler's announcer

manager/middlewares/server.go, manager/router/router.go
=> feat: response server real ip in X-Server-IP header

manager/service/job.go
=> feat: remove order by created_at for selecting job

go.mod, go.sum, scheduler/resource/host.go, scheduler/resource/peer_manager.go, scheduler/resource/peer_manager_test.go, scheduler/scheduling/scheduling.go, scheduler/scheduling/scheduling_test.go, scheduler/service/service_v2.go, scheduler/service/service_v2_test.go
=> feat: when peer disabled shared, scheduler will skip peer in filterCandidateParents

manager/config/constants.go, manager/service/job.go
=> feat: change gc config for manager job

.github/workflows/check-size.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/compatibility-e2e-v1.yml, .github/workflows/compatibility-e2e-v2.yml, .github/workflows/docker.yml, .github/workflows/e2e-v1-nydus.yml, .github/workflows/e2e-v1.yml, .github/workflows/e2e-v2-nydus.yml, .github/workflows/e2e-v2.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/scorecards.yml
=> fix: fixed the token-permission and pinned dependencies

.github/workflows/codeql-analysis.yml, .github/workflows/docker.yml, .github/workflows/scorecards.yml
=> chore: signed release for container image

.github/workflows/docker.yml
=> chore: add GITHUB_TOKEN for ghcr to login

README.md
=> docs: fixed the badge uri of the OpenSSF Scorecard

client/dfget/dfget.go
=> fix(dfget): Change file path

manager/handlers/job_test.go, manager/job/task_test.go, test/e2e/v2/manager/task.go
=> test: generate mode task id for testings

go.mod, go.sum, scheduler/metrics/metrics.go, scheduler/rpcserver/scheduler_server_v2.go, scheduler/service/service_v2.go
=> feat: add metrics for grpc api of the cache task

manager/router/router.go, manager/service/job.go, test/testdata/charts/config-cache-list-metadata.yaml, test/testdata/charts/config-compatibility.yaml, test/testdata/charts/config-concurent-back-source.yaml, test/testdata/charts/config-disable-seed-peer.yaml, test/testdata/charts/config-grpc-tls-ipv6.yaml, test/testdata/charts/config-grpc-tls.yaml, test/testdata/charts/config-ipv6.yaml, test/testdata/charts/config-split-running-tasks.yaml, test/testdata/charts/config-v2.yaml, test/testdata/charts/config-write-buffer-size.yaml, test/testdata/charts/config.yaml
=> feat: increase interval of the preheat polling

.github/workflows/compatibility-e2e-v2.yml
=> chore: update client-rs version

.github/workflows/check-size.yml, .github/workflows/e2e-v1-nydus.yml, .github/workflows/e2e-v2-nydus.yml, .github/workflows/lint.yml, build/images/base/Dockerfile, build/images/dfdaemon/Dockerfile, build/images/manager/Dockerfile, build/images/scheduler/Dockerfile, build/plugin-builder/Dockerfile, codecov.yml, go.mod, test/tools/no-content-length/Dockerfile
=> chore: update go version to v1.22.4

.github/workflows/docker.yml, .goreleaser.yml
=> chore: generate SBOM for release artifacts

.github/workflows/docker.yml, .goreleaser.yml
Reverts dragonflyoss/Dragonfly2#3585
=> Revert "chore: generate SBOM for release artifacts"

manager/config/constants.go
=> feat: change job gc interval in manager

.github/workflows/compatibility-e2e-v2.yml, test/e2e/v2/util/task.go
=> chore: update client version to v0.1.113

scheduler/service/service_v2_test.go, test/e2e/v2/host_test.go
=> test: refactor the tests for the list hosts and delete host

go.mod, go.sum, scheduler/resource/persistentcache/peer.go, scheduler/resource/persistentcache/peer_manager.go, scheduler/resource/persistentcache/task.go, scheduler/resource/persistentcache/task_manager.go, scheduler/resource/standard/peer.go, scheduler/resource/standard/task.go, scheduler/service/service_v2.go
=> feat: implement upload persistent cache task

scheduler/resource/persistentcache/host_manager.go, scheduler/resource/persistentcache/host_manager_mock.go, scheduler/resource/persistentcache/peer_manager.go, scheduler/resource/persistentcache/peer_manager_mock.go, scheduler/resource/persistentcache/resource.go, scheduler/resource/persistentcache/task_manager_mock.go, scheduler/scheduler.go
=> feat: add garbage collection for persistent cache host

deploy/docker-compose/README.md, deploy/docker-compose/run.sh
=> feat: remove deploy without docker compose

SECURITY.md
This pull request includes significant updates to the `SECURITY.md` file to enhance the security policy documentation. The changes introduce new sections for reporting vulnerabilities, the review process, and guidelines for joining the security announce mailing list.
Key updates to the security policy documentation:
* **Reporting a Vulnerability**: Added detailed steps for reporting a Dragonfly vulnerability through GitHub's security features and outlined the expected response time.
* **Review Process**: Described the process for handling reported vulnerabilities, including the creation of a draft security advisory and the involvement of security advisors and reporters in the discussion.
* **Supported Versions**: Updated the section to refer users to the Dragonfly releases page for …
=> docs: update SECURITY.md for Dragonfly

.github/workflows/compatibility-e2e-v2.yml
=> chore: update client version to v0.1.125

README.md
This pull request includes a minor change to the `README.md` file. The change repositions the Twitter badge to ensure it is correctly displayed.
Changes in `README.md`:
* Repositioned the Twitter badge to ensure it is correctly displayed.
=> docs: change the order of the badges

MAINTAINERS.md, OWNERS.md
Add CormickKneey as maintainer and 
- Add [CormickKneey](https://github.com/CormickKneey) as maintainer.
- Add [Garen Wen](https://github.com/garenwen) as emeritus maintainer.
=> Add CormickKneey as maintainer

manager/config/constants.go
This pull request includes a small change to the `manager/config/constants.go` file. The change reduces the default size for the LFU cache.
* [`manager/config/constants.go`](diffhunk://#diff-2cba7d0d032cd2e3a3842ed4df38cab999b1e1cf93f1cdf8b1ea3109f4acaaaeL78-R78): Reduced the `DefaultLFUCacheSize` from `100 * 1000` to `50 * 1000`.
=> feat: reduce the cache size of the lfu in manager

.github/workflows/compatibility-e2e-v2.yml, test/e2e/v2/containerd_test.go, test/e2e/v2/manager/preheat.go, test/testdata/charts/config-v2.yaml
This pull request includes updates to image tags and log levels in configuration files. The most important changes include updating the image tags for the `client` and `seed-client` modules and changing the log level from `info` to `debug` for both the `client` and `seedClient` configurations.
Updates to image tags:
* [`.github/workflows/compatibility-e2e-v2.yml`](diffhunk://#diff-94b4b9fb9262094b9e7ac79907321114cc3b29bb1b77634989d64226d4c6e06bL42-R46): Updated the `image-tag` for the `client` and `seed-client` modules from `v0.1.125` to `v0.2.2`.
Changes to log levels:
* [`test/testdata/charts/config-v2.yaml`](diffhunk://#diff-c996b5e76282d69b515fbf10a99cdccf4324298e307273c60801697170c9f175L101-R101): Changed the log level from `info` to `debug` for the `seedClient` configuration.
* …
=> fix: update client version in e2e testing

.github/workflows/compatibility-e2e-v2.yml, .github/workflows/e2e-v2-rate-limit.yml, test/e2e/v2/rate_limit_test.go, test/testdata/charts/config-v2-rate-limit.yaml
This pull request introduces a new end-to-end (E2E) testing workflow with rate limiting and updates existing workflows and configurations to support this feature. The most important changes include the addition of a new E2E test workflow, updates to existing workflows to skip rate limit tests, and the creation of new test files and configurations for rate limiting.
* [`.github/workflows/e2e-v2-rate-limit.yml`](diffhunk://#diff-5d616b4aa7c1f6aa5d0ec26ebd48b73bfecbcb9dcbb66c0ccfc132725d03649dR1-R153): Added a new E2E test workflow for testing with rate limits, including job definitions, environment variables, and steps for setting up and running tests.
* [`.github/workflows/compatibility-e2e-v2.yml`](diffhunk://#diff-94b4b9fb9262094b9e7ac79907321114cc3b29bb1b77634989d64226d4c6e06bR36-R51): …
=> test: add the e2e test cases for download & prefetch rate limit

README.md
This pull request includes an addition to the `README.md` file to include a new section about the project license.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R86-R89): Added a "License" section with a FOSSA status badge to provide information about the project's license.
=> docs: add FOSSA embed status badge

README.md
This pull request includes a small change to the `README.md` file. The change adds an OpenSSF Scorecard badge to the list of badges in the file.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R7): Added the OpenSSF Scorecard badge to the list of badges.
=> docs: add OpenSSF Scorecard badge

scheduler/resource/persistentcache/task_manager_test.go
=> test(scheduler/resource/persistentcache): add uint testings for task manager

.github/workflows/compatibility-e2e-v2.yml, .goreleaser.yml
This pull request includes updates to image tags in the `.github/workflows/compatibility-e2e-v2.yml` file and a minor change in the `.goreleaser.yml` file. The most important changes are:
* Updated image tags for `manager`, `scheduler`, `client`, and `seed-client` modules to new versions in the `.github/workflows/compatibility-e2e-v2.yml` file.
* Changed the `format` field to `formats` in the `.goreleaser.yml` file to support an array of formats.
=> chore: remove archives.format in goreleaser

README.md
This pull request involves a minor change to the `README.md` file. The change removes the License section and the associated FOSSA status badge.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L87-L90): Removed the License section and the FOSSA status badge.
=> docs: remove FOSSA in README.md

.github/workflows/compatibility-e2e-v2.yml
This pull request includes updates to the `client` and `seed-client` image tags and a submodule update.
Updates to image tags:
* [`.github/workflows/compatibility-e2e-v2.yml`](diffhunk://#diff-94b4b9fb9262094b9e7ac79907321114cc3b29bb1b77634989d64226d4c6e06bL44-R49): Updated `image-tag` for `client` and `seed-client` from `v0.2.8` to `v0.2.11`.
Submodule update:
* [`client-rs`](diffhunk://#diff-84558f39216002fac1c3d61169fea29ee720b962a90c14d2f81a13e0ee6742bfL1-R1): Updated submodule commit from `4407ecd2fdd236c451c175df245e06b4b6eab137` to `3339d5ca2feac41a63f0472811cb38205e5fbaf2`.
=> chore(client-rs): update client rs submodule to v0.2.11

test/e2e/v2/dfcache_test.go, test/e2e/v2/util/task.go
This pull request introduces a new function to calculate the SHA-256 checksum for a task by accessing a persistent cache. The most important change is the addition of the new function `CalculateSha256ByPersistentCacheTaskID`.
New functionality:
* [`test/e2e/v2/util/task.go`](diffhunk://#diff-c4b36c73952c9a5025721b3d69281abc5d2df38925951093f5f9534e0ce54458R76-R103): Added `CalculateSha256ByPersistentCacheTaskID` function to calculate the SHA-256 checksum for a task by accessing a persistent cache path. This function iterates over the provided pods, checks if the content path exists, and computes the SHA-256 checksum if the path is found.
=> test(e2e/v2): add test cases for dfcache

.github/workflows/compatibility-e2e-v2.yml, scheduler/service/service_v2.go
=> feat(scheduler/service): print error log when announce peer failed

scheduler/config/config.go, scheduler/config/config_test.go, scheduler/config/constants.go, scheduler/config/testdata/scheduler.yaml
This pull request focuses on removing the storage configuration from the scheduler configuration files and related tests. The most important changes include the removal of the `StorageConfig` struct and its references throughout the codebase.
Configuration changes:
* [`scheduler/config/config.go`](diffhunk://#diff-0c784f71367ad0e2181f892a3fe4ba3529290443b5f3573bfdbd1b231de96a5eL61-L63): Removed the `StorageConfig` struct and its related fields and validation checks from the `Config` struct. [[1]](diffhunk://#diff-0c784f71367ad0e2181f892a3fe4ba3529290443b5f3573bfdbd1b231de96a5eL61-L63) [[2]](diffhunk://#diff-0c784f71367ad0e2181f892a3fe4ba3529290443b5f3573bfdbd1b231de96a5eL264-L275) [[3]](diffhunk://#diff-0c784f71367ad0e2181f892a3fe4ba3529290443b5f3573bfdbd1b231de96a5eL376-L380) …
=> feat: update helm charts and remove storage config in scheduler

manager/middlewares/personal_access_token.go
This pull request includes changes to the `manager/middlewares/personal_access_token.go` file to optimize the code by using the `slices` package for checking permissions.
Code optimization:
* [`manager/middlewares/personal_access_token.go`](diffhunk://#diff-95dbb8ce3388da41ed4e95157980238ab0caf637204862ab8a2a05ce21e5cf0aR23): Added import for the `slices` package.
* [`manager/middlewares/personal_access_token.go`](diffhunk://#diff-95dbb8ce3388da41ed4e95157980238ab0caf637204862ab8a2a05ce21e5cf0aL130-R131): Simplified the `hasPermission` function by replacing the loop with a call to `slices.Contains`.
=> refactor: use slices.Contains to check the permission

cmd/dependency/plugin_cmd.go, internal/dfplugin/dfplugin.go, test/e2e/v2/concurrency_test.go, test/e2e/v2/containerd_test.go, test/e2e/v2/dfget_test.go, test/e2e/v2/e2e_test.go, test/e2e/v2/manager/preheat.go, test/e2e/v2/manager/task.go, test/e2e/v2/proxy_test.go
This pull request includes several changes to improve the codebase by fixing a loop iteration issue and renaming a regular expression variable. The most important changes include modifying the loop iteration syntax across multiple test files and renaming a variable for consistency.
Loop iteration improvements:
* Changed the loop iteration syntax from `for i := 0; i < 3; i++` to `for i := range 3` in multiple test files to improve code readability and consistency. (`test/e2e/v2/concurrency_test.go` [[1]](diffhunk://#diff-dce1855eca0445dc4acb26e3857926af19650a79516bba294e9f9ba6d4fdd973L110-R110) [[2]](diffhunk://#diff-dce1855eca0445dc4acb26e3857926af19650a79516bba294e9f9ba6d4fdd973L135-R135); `test/e2e/v2/containerd_test.go` [[3]](diffhunk://#diff-0c79287e4d37c3a9724260486bbe2a5719fd0ed7c8e9 …
=> test(e2e): optimize testing for preheating in cache

client/daemon/daemon.go
=> fix(client/daemon): update type hint for resource clients option

README.md
This pull request includes a small change to the `README.md` file. The change updates the URL for the OpenSSF Best Practices badge to reflect the new project ID.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L11-R11): Updated the OpenSSF Best Practices badge URL to `https://www.bestpractices.dev/projects/10432/badge` and its corresponding link to `https://www.bestpractices.dev/projects/10432`.
=> chore(README.md): change OpenSSF badge

cmd/dfget/cmd/root.go
=> build(client-rs): update subproject commit and add comment in dfget

cmd/dfget/cmd/root.go
=> refactor(root.go): simplify error handling in checkAndSpawnDaemon

client/daemon/rpcserver/rpcserver.go
=> comments(rpcserver): add Stop method to gracefully stop servers

manager/models/audit.go, manager/models/models.go
This pull request introduces a minor yet impactful change to the `Audit` struct in `manager/models/audit.go` to enhance database default behavior. The most important change is as follows:
* Modified the `OperatedAt` field in the `Audit` struct to include a default value of the current timestamp (`default:current_timestamp`). This ensures that the `operated_at` column will automatically be populated with the current timestamp if no value is provided during record creation. (`[manager/models/audit.goL63-R63](diffhunk://#diff-bb3605e12ccfd26986f947daf49f4966b4f34288a17a2999f37888ea2e0e3d79L63-R63)`)
=> feat(manager): add default value for operated_at

cmd/dependency/doc_cmd.go
=> comments(genDocCommand): add runDoc method to generate markdown docs

internal/util/util.go
=> style: Fix spacing in ComputePieceSize comment

cmd/manager/cmd/root.go
=> comments: add initDfpath function to initialize dfpath

cmd/dependency/doc_cmd.go
=> fix(genDocCommand): handle directory creation error in runDoc

scheduler/resource/standard/peer_manager.go
=> refactor(peer_manager): remove unnecessary log in RunGC

scheduler/resource/standard/task_manager.go
=> refactor(task_manager): Remove unnecessary error log in RunGC

manager/database/postgres.go
=> style(database/postgres.go): Capitalize DSN in comment

manager/database/postgres.go
=> refactor(database/postgres): update migration comment for clarity

manager/auth/oauth/oauth.go
=> comments(auth/oauth): add default timeout comments for oauth

manager/gc/audit.go
=> comments(manager/gc): add NewAuditGCTask function

manager/middlewares/ratelimiter.go
=> feat(middlewares): add CreateJobRateLimiter middleware

manager/database/database.go, pkg/redis/proxy.go, pkg/redis/redis.go
This pull request introduces enhancements to the Redis proxy functionality by adding protocol validation, improving error logging, and refactoring data copying mechanisms. Additionally, it improves error handling in the Redis client initialization.
* Added a new `isRedisProtocol` method to validate whether incoming connections use the Redis protocol by inspecting the first byte of the connection. If invalid, the connection is rejected with an error log. (`pkg/redis/proxy.go`, [[1]](diffhunk://#diff-9d450daf6620950174474735e2789d06043df44f84bb860acb7bdff14a8f9bf7R83-R89) [[2]](diffhunk://#diff-9d450daf6620950174474735e2789d06043df44f84bb860acb7bdff14a8f9bf7L104-R152)
* Introduced a `copyReader` method to handle data copying from a `bufio.Reader` to a connection, replacing the previous …
=> refactor(manager): redis proxy to use bufio.Reader for protocol detection

.github/workflows/compatibility-e2e-v2.yml, pkg/idgen/task_id.go, pkg/idgen/task_id_test.go, test/e2e/v2/containerd_test.go, test/e2e/v2/manager/preheat.go
=> feat: add task type to ID generation for Standard and PersistentCache tasks

internal/job/types.go, manager/job/preheat.go, manager/types/job.go, scheduler/job/job.go
=> feat: support preheat by peer count

pkg/idgen/task_id.go, pkg/storage/piece.go, pkg/storage/piece_test.go, pkg/storage/stat_task.go, pkg/storage/stat_task_test.go
This pull request introduces functionality for calculating and managing piece lengths for storage tasks, along with utilities for validating and retrieving task information. It includes new implementations, constants, helper functions, and comprehensive unit tests.
* Added `CalculatePieceLength` function in `pkg/storage/piece.go` to compute optimal piece lengths based on content length, constrained by minimum and maximum thresholds. This function uses a helper, `nextPowerOfTwo`, to align lengths to powers of two.
* Defined constants `MIN_PIECE_LENGTH`, `MAX_PIECE_LENGTH`, and `MAX_PIECE_COUNT` to standardize piece length constraints.
* Introduced `StatTask` in `pkg/storage/stat_task.go` to retrieve task information based on parameters like path, URL, content length, and filtered query …
=> feat: add the storage pkg for stat task

manager/gc/job.go
=> feat(manager): add cleanup of associated tables in job garbage collection

manager/router/router.go
=> comments(router): add Init function to initialize gin engine

MAINTAINERS.md
Add [Chlins Zhang](https://github.com/chlins) as maintainer.
=> Add Chlins Zhang as maintainer

scheduler/resource/persistentcache/host.go
=> docs(host.go): Update NewHost comment for clarity

manager/handlers/job.go
This pull request updates the validation logic in the `CreateJob` handler to include a new parameter, `ContentForCalculatingTaskID`, as an acceptable input for job creation. The changes ensure that at least one of `task_id`, `url`, or `content_for_calculating_task_id` is provided.
Validation logic update:
* [`manager/handlers/job.go`](diffhunk://#diff-0211307ac5f6ce619a07ddd29c6ebf19171a7aa6aba54675f6e0afe5806e7869L90-R91): Modified the conditional checks in the `CreateJob` handler to include `ContentForCalculatingTaskID` as a required parameter option, alongside `task_id` and `url`. This change was applied in two places within the function. [[1]](diffhunk://#diff-0211307ac5f6ce619a07ddd29c6ebf19171a7aa6aba54675f6e0afe5806e7869L90-R91) …
=> feat: update validate for job's handler

OWNERS.md
This pull request adds a new section to the `OWNERS.md` file to include information about Community Managers.
Community Managers section added:
* [`OWNERS.md`](diffhunk://#diff-403b96de276ed29c25c2559e38f07721a79bbffffeedaa6cb3b78364b2af58a4R29-R38): Introduced a new section titled "Community Managers," listing GitHub IDs, names, emails, and company affiliations for community managers.
=> docs: Add Cheng Ming to Community Managers

OWNERS.md
This pull request updates the `OWNERS.md` file to replace the emeritus maintainers table with a reference to an external YAML file, simplifying the document and centralizing information management.
Key change:
* [`OWNERS.md`](diffhunk://#diff-403b96de276ed29c25c2559e38f07721a79bbffffeedaa6cb3b78364b2af58a4L15-R15): Removed the emeritus maintainers table and added a link to `emeritus_members.yaml` in the DragonflyOSS community repository for centralized information.
https://github.com/dragonflyoss/community/issues/27
=> docs: Update OWNERS.md to reference emeritus_members.yaml for emeritus maintainers

README.md
This pull request introduces a small change to the `README.md` file. It adds a new badge to display the FOSSA status for license compliance.
https://github.com/dragonflyoss/community/issues/43
=> docs(README.md): add FOSSA Status badge

README.md, SECURITY-INSIGHTS.yml
- Add SECURITY-INSIGHTS.yml with detailed security policy and project information.
- Update README.md with security insights reference and minor community section edits.
- Include software bill of materials badge in README.md.
=> docs: add security insights and update community details 📚

README.md
- Add LFX Health Score badge to indicate project health status.
- Include CLOMonitor badge for additional project metrics visibility.
=> docs: update README with project health badges 📚

manager/gc/audit.go, manager/gc/scheduler.go, manager/gc/seed_peer.go
This pull request introduces improvements to the garbage collection (GC) logic across multiple components (`audit`, `scheduler`, and `seed peer`) in the codebase. The changes include the addition of a new "mark and sweep" GC phase for schedulers, improved logging, and minor formatting updates.
* Introduced a new "mark and sweep" GC process for schedulers. The `runMark` method identifies inactive schedulers based on their last keep-alive time and marks them as inactive, while the `runSweep` method cleans up these inactive schedulers. This improves the efficiency and reliability of the scheduler GC process. (`manager/gc/scheduler.go`, [manager/gc/scheduler.goR65-R130](diffhunk://#diff-cbcdc15b2acbe6c754221a159f33428e7cdec57d27a79a56b1f4b8c4f10b779fR65-R130))
* Updated log messages across …
=> feat: support mark inactive schedulers in the scheduler gc

scheduler/job/job.go
This pull request introduces enhanced error logging and fixes a logical issue in peer selection within the `scheduler/job/job.go` file. The changes improve debugging capabilities and ensure correct behavior during peer selection.
* Added detailed error logs in the `preheat` method to capture failures for single seed peers, all seed peers, all peers, and invalid scopes. This ensures better traceability in case of errors. [[1]](diffhunk://#diff-d9c3b15511ab73786700fed2b761b4e8ef1b73b60183deaab4f8aa5a8130cf8cR186) [[2]](diffhunk://#diff-d9c3b15511ab73786700fed2b761b4e8ef1b73b60183deaab4f8aa5a8130cf8cR196) [[3]](diffhunk://#diff-d9c3b15511ab73786700fed2b761b4e8ef1b73b60183deaab4f8aa5a8130cf8cR206) [[4]](diffhunk://#diff-d9c3b15511ab73786700fed2b761b4e8ef1b73b60183deaab4f8aa5a8130cf8cR216)
* …
=> feat: add error logging for preheat failures and fix peer selection logic

internal/job/constants.go, internal/job/job.go
=> refactor(job): use goroutine to unmarshal task result

.github/workflows/compatibility-e2e.yml, test/testdata/charts/config.yaml
This pull request updates several components to use newer versions and introduces a minor configuration change to improve compatibility and cluster identification. The most important changes are grouped below:
**Version Updates:**
* Updated Docker image tags for `manager`, `scheduler`, `client`, and `seed-client` modules in `.github/workflows/compatibility-e2e.yml` to newer release candidates and client versions.
* Updated the submodule reference for `client-rs` to the latest commit.
* Updated the submodule reference for `deploy/helm-charts` to the latest commit.
**Configuration Improvements:**
* Added the `schedulerClusterID: 1` configuration under `host` for both `seedClient` and `client` sections in `test/testdata/charts/config.yaml` to ensure proper cluster identification. …
=> chore: bump version to v2.3.1-rc.4

.github/workflows/compatibility-e2e.yml, pkg/idgen/task_id.go, pkg/idgen/task_id_test.go
refer to https://github.com/dragonflyoss/client/pull/1316
=> fix: use sha256 generate persistent cache task id

README.md
This pull request significantly revises the `README.md` to provide clearer, more concise project information and improve organization. The changes modernize the introduction, streamline community and security sections, and clarify contribution guidelines.
**Project description and introduction:**
* Updated the project overview to emphasize efficient, stable, and secure data distribution for various artifact types, and improved clarity for cloud-native use cases.
**Community and contribution information:**
* Reworded and reorganized the community section for clarity, including improved instructions for joining and participating in the community. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L18-R31) …
=> docs(README): update project description and structure

scheduler/resource/standard/host_manager.go, scheduler/resource/standard/host_manager_mock.go
This pull request refactors the `hostManager` implementation in `scheduler/resource/standard/host_manager.go` to improve how hosts are managed and accessed based on their type. Instead of storing all hosts in a single map, the code now maintains separate maps for normal hosts and seed hosts, resulting in clearer separation and more efficient operations. All methods have been updated to use the new structure.
* Split the single `sync.Map` into two distinct maps: `normal` for normal hosts and `seed` for seed hosts, updating the struct definition and constructor accordingly.
* Modified all host access methods (`Load`, `Store`, `LoadOrStore`, `Delete`, `Range`) to operate on the appropriate map based on host type, ensuring correct categorization and lookup.
* Updated methods for loading all …
=> refactor(host_manager): separate normal and seed host maps
