- build/supernode/Dockerfile
#28 
更新dockerfile中 tomcat url地址，解决通过dockerfile构建镜像失败的问题。
> update tomcat url.

- src/daemon/src/df-daemon/handler/transport.go
> 修改正则，匹配更多的镜像地址

- build/supernode/Dockerfile
- the jdk8's download link is broken
- discard wget's annoying ans useless outputs
- reduce mvn installation's outputs
BTW, is it necessary to minimize the number of layers?
> chore: fix broken link & reduce build outputs

- docs/en/README.md
- docs/en/install_client.md
- docs/zh/README.md
- docs/zh/api.md
- docs/zh/architecture.md
- docs/zh/install_client.md
- docs/zh/install_server.md
- docs/zh/usage.md
translate README.md/install_clinet.md
see issue #53
> docs: add documents written in Chinese

- README.md
**1.Describe what this PR did**
It updates a single paragraph in `./README.md`
**2.Does this pull request fix one issue?**
No
**3.Describe how you did it**
n/a
**4.Describe how to verify it**
n/a
**5.Special notes for reviews**
n/a
> docs: fix grammer in README.md

- dfget/cli/cli.go
- dfget/cli/cli_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/downloader/downloader.go
- dfget/downloader/downloader_test.go
- dfget/exception/exception.go
- dfget/exception/exception_test.go
- dfget/types/types.go
- dfget/types/types_test.go
- dfget/uploader/uploader.go
- dfget/uploader/uploader_test.go
- dfget/util/util.go
- dfget/util/util_test.go
> refactor: defines the base structure of dfget(GoLang)

- dfget/errors/errors.go
- dfget/errors/errors_test.go
- dfget/types/base_response.go
- dfget/types/pull_piece_task_request.go
- dfget/types/register_request.go
- dfget/types/register_response.go
- dfget/types/report_piece_request.go
- dfget/types/types_test.go
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/rest/controller/PeerController.java
> refactor: defines config and communication data structures

- dfget/cli/cli.go
- dfget/cli/cli_parameters.go
- dfget/cli/cli_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/config/constants.go
- dfget/util/util.go
- dfget/util/util_test.go
> refactor(dfget): define constants and refactor cli

- README.md
- ROADMAP.md
- docs/README.md
> docs: update Pouch to PouchContainer

- README.md
I put * number to a couple of claims. There claims need to have support evidence. Please add them as references and put a link from the * number.
> rewrite the intro part

- dfdaemon/handler/transport.go
- dfdaemon/util/netutil.go
refactor: use return fast to reduce ident to be more readable
With the original way, the code was so hard to read. This pull request tries to change this situation.
> refactor: use return fast to reduce ident to be more readable

- ROADMAP.md
> docs: make readmap in English

- dfget/util/file_util.go
- dfget/util/file_util_test.go
implement some of file util functions in file_util.go.
> refactor: add file util functions in file_util.go

- ROADMAP.md
> docs: fix spelling errors in roadmap

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> doc: add issue and pr template for project

- ROADMAP.md
> docs: complete the roadmap.md

- docs/zh/usage.md
should be df-daemon.
no
no need. Just a few typo.
NA
NA
> should be df-daemon

- docs/en/quick_start.md
change df-daemon to dfdaemon for new version 0.2.0
> docs: update quick_start.md 

- MAINTAINERS.md
@chenchaobing is a founder maintainer of project Dragonfly. Now he is in new career of Meitu, and he and his team is also trying to adopt Dragonfly as an essential tool for container image distribution.
Chaobing will commit more of his time in the project building. 
Welcome his back. 
Also cc @lowzj @zhouhaibing089 @garfield009
none
no need
none
none
> docs: add chenchaobing as a maintainer

- docs/zh/install_client.md
This is a testing PR. As the technical writer, I need to make sure everything works before I migrate the docs for Dragonfly.
NONE
No test needed. For documentation only. 
N/A
N/A
> docs: [test] revising doc Installing Client

- dfdaemon/util/netutil.go
remove the code that will never happen
None.
nothing to do with existing logic.
> rafactor: remove the code that will never happen

- dfget/util/queue.go
Signed-off-by: zou sheng <zouyu12344444@126.com>
Fix typos
NONE
No.
> comments: fix some typos in queue.go

- .github/ISSUE_TEMPLATE/any-questions-on-dragonfly.md
- .github/ISSUE_TEMPLATE/bug-report-for-dragonfly.md
- .github/ISSUE_TEMPLATE/feature-request-of-dragonfly.md
The github have already support different issue template. I added three:
* bug report
* feature request
* questions about Dragonfly
> docs: Update issue templates

- .circleci/config.yml
- build/build.sh
- build/client/env.sh
- build/client/run.sh
- build/supernode/supernode-build.sh
add shellcheck to validate shell scripts, this is integrated into circleCI.
the execution command is `find ./ -name "*.sh" | grep -v vendor | xargs shellcheck`.
fix https://github.com/alibaba/Dragonfly/issues/187
no need
none
none
> docs: add shellcheck to validate shell scripts

- .circleci/config.yml
reduce MD002 MD007 MD026 rule for markdownlint
These three rules are affecting pr https://github.com/alibaba/Dragonfly/pull/192.
With the rule update, hugo rules will be perfect within this project.
none
no need.
none
none
> docs: reduce MD002 MD007 MD026 rule for markdownlint

- cmd/dfdaemon/main.go
- cmd/dfdaemon/options/options.go
- cmd/dfdaemon/options/options_test.go
- dfdaemon/handler/dfgetter.go
- dfdaemon/handler/root_handler.go
- dfdaemon/handler/transport.go
At present, there are some unreasonable code with `dfdaemon`. So I make a few adjustments.
None.
Just structural adjustment.
> refactor: some changes about the code of dfdaemon

- .circleci/config.yml
- dfdaemon/util/netutil.go
- dfget/core/core.go
- dfget/core/core_test.go
- dfget/util/file_util_test.go
This is a pull request to strict the code type of Dragonfly.
We use [gometalinter](https://github.com/alecthomas/gometalinter) to make it.
For the detailed rules, I add:
* gofmt
* goimports
* golint
* misspell
* vet
* deadcode
* goconst 
* interfacer 
* megacheck 
* maligned
If we need to add other validation rules, it is quite easy to edit this .circle/config.yml to add it.
none
no need
none
none
> lint: make gocode validated by gometalinter

- apis/swagger.yml
add preheat list API endpoint in swagger.yml
none
no need 
none
none
> docs: add preheat list API endpoint in swagger.yml

- README.md
- docs/_index.md
remove commercial support part in README.md.
Since Dragonfly will try to be neutral, we need to remove some legacy part of document.
No commercial support for Dragonfly now.
none
no need, just doc update.
none
none
> docs: remove commercial support part in README.md

- wercker.yml
use custom git-pages domain, setting: https://app.wercker.com/lowzj/Dragonfly/workflows/pipelines/5bef53f1655e0d0700cf390c
> docs: use custom git-pages domain

- MAINTAINERS.md
I'm working from eBay in San Jose right now. :)
Signed-off-by: zhouhaibing089 <zhouhaibing089@gmail.com>
> docs: update company name for zhouhaibing089

- Dockerfile
As title described.
fixes part of #206
I have tested on my VM.
1. enter the root directory of project
2. docker build image
```
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM golang:1.10
---> 3c65b5659316
Step 2/7 : WORKDIR /go/src/github.com/alibaba
---> Running in 7de52b261ba8
Removing intermediate container 7de52b261ba8
---> 3923ed8d67b9
Step 3/7 : RUN git clone https://github.com/alibaba/Dragonfly.git     && cd Dragonfly && ./build/build.sh client
---> Running in 0643415dbad9
Cloning into 'Dragonfly'...
=====================================================================
BUILD(dfdaemon&dfget): compiling dfdaemon and dfget...
install home: /root/.dragonfly
link /tmp/dragonfly/build/src/github.com/alibaba/Dragonfly -> …
```
> feature: add Dockerfile of dfclient

- docs/quick_start/_index.md
> fix: bad link of dfget example

- docs/.build/prepare.sh
> fix: don't replace '../images' in code block

- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/BaseWorker.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/FilePreheater.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/ImagePreheater.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/preheat/PreheatServiceImpl.java
> fix: remove unused code and polish log

- .gitignore
- dfget/cli/cli.go
- dfget/core/downloader/p2p_downloader.go
- dfget/core/downloader/power_client.go
Currently, `dfget` cannot download a file as expected which means that it's not a complete application to be used. So I complete the key part that are not yet implemented to make the p2p download function available. In the meantime, update something that doesn't make sense.
None.
None.
1. get the source code
2. make 
```
=====================================================================
BUILD(dfdaemon&dfget): compiling dfdaemon and dfget...
install home: /opt/dragonfly
link /tmp/dragonfly/build/src/github.com/dragonflyoss/Dragonfly -> /vagrant/gopath/src/github.com/dragonflyoss/Dragonfly
PRE: clean and create /tmp/dragonfly/build/bin
CHECK: gofmt, check code formats
CHECK: install golint
CHECK: golint, check code style
CHECK: go vet, check code …
```
> feature: implement powerClient and finishTask to implement the basic functions of dfget

- src/supernode/src/main/docker/sources/nginx.conf
> chore: update nginx.conf to serve all apis of supernode

- apis/swagger.yml
- apis/types/error.go
- apis/types/error_response.go
- apis/types/peer_create_request.go
- apis/types/peer_create_response.go
- apis/types/peer_info.go
- apis/types/piece_info.go
- apis/types/piece_update_request.go
- apis/types/preheat_create_request.go
- apis/types/preheat_create_response.go
- apis/types/preheat_info.go
- apis/types/task_create_request.go
- apis/types/task_create_response.go
- apis/types/task_info.go
- apis/types/task_update_request.go
Before refactoring Dragonfly in Golang, We should define the API very well. This pull request tries to polish the API.
The original way combines peer registry and task creation into a single API, while this pr tries to split them into two.
And all the new APIs is like below:
|Index|Endpoint|Usage|
|:--:|:---:|:---:|
|1|GET /_ping | ge a ping response|
|2|POST /peers|register dfget in Supernode as a peer node|
|3|GET /peers/{id}|get a peer in supernode|
|4|DELETE /peers/{id}| delete a peer in supernode|
|5|POST /tasks|create a task|
|6|GET /tasks/{id}|get a task|
|7|PUT /tasks/{id}|update a task|
|8|GET /tasks/{id}/pieces|Get pieces in task|
|9|GET /pieces/{id}|get a piece|
|10|PUT /pieces/{id}|update a piece|
|11|POST …
> feature: polish API definition in swagger

- docs/quick_start/README.md
- docs/user_guide/install_client.md
- docs/user_guide/install_server.md
* Update the building and installing documents due to the PR: #276 
* Add installing client with image to QuickStart
> docs: update installing documents and quick-start

- docs/zh/install_server.md
fix markdown format
NA
No.
NA
NA
> fix markdown format for this document

- MAINTAINERS.md
@wangj998 is a great guy for project Dragonfly. When Dragonfly is not a CNCF project, he contributed a lot to spread the technology to the whole industry in Alibaba. Without him, Dragonfly cannot be a wide-spread software project at all. While currently he is not able to maintain Dragonfly any more, and he is doing great work in other field. We are going to remove @wangj998 from the maintainers list, while in the following days we still wish @wangj998 to care this project.
@Starnop is now making quite many efforts in bring success to project Dragonfly. He is very active contributor in maintaining the original Java-based supernode, and now mainly focuses on refactoring the Golang version of the whole project. In addition, he starts up …
> docs: remove wangj998 and add Starnop in MAINTAINER.md

- cmd/dfdaemon/app/root.go
- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/core/core.go
- dfget/core/core_test.go
- dfget/core/downloader/back_downloader.go
- dfget/core/downloader/back_downloader_test.go
- dfget/core/downloader/downloader.go
- dfget/core/downloader/p2p_downloader.go
- dfget/core/downloader/power_client.go
- dfget/core/helper/test_helper.go
- dfget/core/regist/register.go
- dfget/core/regist/register_test.go
- dfget/core/uploader/uploader.go
In general, we use ctx as the variable name of package `context` of golang, in the meantime, we don't have to create a global variable for config, passing it by argument is enough. So this pull request has dong two things as follows:
1. update the name `ctx` -> `cfg`
2. delete the global variable of `Context`
None.
updated.
After merged, we can use go `context` as normal.
> refactor: update context to config in dfget

- CONTRIBUTING.md
add README in vendor dir to illustrate the vendor policy
This is a very good guide for developers to manage vendoring. Most of the added file is from project PouchContainer.
none
no need, just doc related.
none
cc @zhouhaibing089 @Starnop
> docs: add README in vendor dir to illustrate the vendor policy

- FAQ.md
- docs/cli_reference/dfget.md
Update the FAQ.md for some questions about the sequence of Dragonfly. I hope that after this PR is merged, users will have a better understanding of Dragonfly.
fixes #296 #315
No needed.
If you have any questions, please let me know.
> doc: add some FAQs about sequence

- docs/user_guide/download_files.md
- docs/zh/usage.md
Signed-off-by: silenceshell <me@ieevee.com>
Add description about authentication for private docker registry.
fixes #17 
No. just document.
NA
None
> docs: support private image which needs user/passwd for remote registries

- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- dfget/config/config.go
- dfget/config/constants.go
- dfget/config/metadata.go
- dfget/config/metadata_test.go
- dfget/core/core.go
- dfget/core/downloader/p2p_downloader.go
- dfget/core/helper/file_helper.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_util.go
- dfget/core/uploader/uploader_util_test.go
- dfget/util/http_util.go
* client launches an independent peer server when downloading files in p2p pattern
* add `server` command to `dfget`
> refactor: client launches an independent peer server when downloading files in p2p pattern

- FAQ.md
update FAQ to add private image supporting way. And it is added in doc via #310 by @silenceshell 
Thank you.
none
no need
none
none
> docs: update FAQ to add private image supporting way

- docs/design/design.md
> docs: delete no-ascii char in design.md

- cmd/dfget/app/root.go
> fix: output whole cmd's args

- docs/design/design.md
```bash
FILE: ./docs/design/design.md
[✖] https://github.com/dragonflyoss/Dragonfly/blob/master/docs/apis.md
ERROR: dead links found!
```
> docs: fix dead link in design.md

- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/core/core_test.go
- dfget/core/helper/test_helper.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_util_test.go
Previously, CI will looks good even if the unit test did not pass.  So there were a lot of tests that didn't actually pass before. And update them in this pull request. As for fix the bug of CI, please refer to #340 
None.
> fix failed unit tests

- Makefile
- hack/build-client-local.sh
- hack/check-client.sh
- hack/unit-test.sh
The building scripts always return `0` even though they executes failed.
related: #255
> fix: ci passed but code checks and unit-test failed in actual

- dfget/core/uploader/uploader.go
* execute go routine `monitorAlive` when the server is launched successfully.
* polish the code of `LaunchPeerServer`
> fix: execute monitorAlive after server starting successfully

- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/Downloader.java
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/SuperWriter.java
Dragonfly cannot download an empty file because that supernode don't write and cache data if the file length less and equals zero.
merge to branch: `0.2.x`
related: #44
> fix: [0.2.x] cannot use dragonfly to download an empty file

- dfget/config/constants.go
- dfget/core/api/download_api.go
- dfget/core/api/uploader_api.go
- dfget/core/api/uploader_api_types.go
- dfget/core/downloader/back_downloader.go
- dfget/core/downloader/downloader.go
- dfget/core/downloader/p2p_downloader.go
- dfget/core/downloader/power_client.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_util.go
- dfget/util/http_util.go
The uploader provides a few http APIs. we splice the url directly where it needed to be called previously. This is a very rough approach, we should define it uniformly.
None.
Help wanted.
> refactor: untify the api of uploader

- cmd/dfdaemon/app/gen_doc.go
- cmd/dfdaemon/app/options/options.go
- cmd/dfdaemon/app/root.go
- cmd/dfdaemon/main.go
- cmd/dfget/app/gen_doc.go
- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- cmd/dfget/app/version.go
- dfdaemon/constant/code.go
- dfdaemon/downloader/dfget/dfget.go
- dfdaemon/downloader/downloader.go
- dfdaemon/exception/errors.go
- dfdaemon/global/global.go
- dfdaemon/handler/debug_handler.go
- dfdaemon/handler/env_handler.go
- dfdaemon/handler/param_handler.go
- dfdaemon/handler/root_handler.go
- dfdaemon/handler/transport.go
- dfdaemon/initializer/atime_darwin_amd64.go
- dfdaemon/initializer/atime_linux_amd64.go
- dfdaemon/initializer/initializer.go
- dfdaemon/muxconf/muxconf.go
- dfdaemon/util/netutil.go
- dfdaemon/util/urlutil.go
Update copyright from `Alibaba Group` to `Dragonfly Authors`.
> fix: update copyright to Dragonfly Authors

- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- dfget/config/constants.go
- dfget/core/api/download_api.go
- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/back_downloader/back_downloader_test.go
- dfget/core/downloader/downloader_test.go
- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/downloader/p2p_downloader/target_writer.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_helper_test.go
- dfget/core/uploader/uploader_test.go
- dfget/core/uploader/uploader_util.go
- dfget/core/uploader/uploader_util_test.go
- dfget/errors/errors.go
- dfget/util/limit_reader.go
- dfget/util/log.go
- dfget/util/log_test.go
* report the downloaded piece's status to supernode, then other peers can download from this peer
* fix the incorrect `dataDir` of downloading task in dfget server
> feature: report downloaded piece's status to supernode

- apis/swagger.yml
- docs/api_reference/apis.md
fix: correct typo and remove basepath
none
no need
none
none
> fix: correct typo and remove basepath

- FAQ.md
docs: add more questions in FAQ.md
* What is the usage of configuring `registry-mirrors` and `HTTP_PTOXY`
* How to check if block piece is distributed among dfgets nodes
none
no need, just doc related.
none
none
> docs: add more questions in FAQ.md

- client/peer_create.go
- client/peer_delete.go
- client/peer_info.go
- client/peer_list.go
add peers implementation in sdk：
POST /peers
GET /peers
GET /peers/{id}
DELETE /peers/{id}
none
none
> feature: add peers actions in client pkg of golang sdk

- dfget/core/api/uploader_api.go
- dfget/core/api/uploader_api_types.go
- dfget/core/uploader/peer_server.go
- dfget/core/uploader/peer_server_test.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_helper_test.go
- dfget/core/uploader/uploader_test.go
- dfget/core/uploader/uploader_util.go
- dfget/core/uploader/uploader_util_test.go
- dfget/util/http_util_test.go
* add unit-test for module uploader of dfget
* fix data race in `uploader.uploader`
one task of #352 : unit test of module `uploader`
> test: add unit-test for module uploader of dfget

- dfget/config/config.go
- dfget/config/metadata.go
- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/piece.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/downloader/p2p_downloader/target_writer.go
We need to add more description for every fields in struct definition. And this PR try to do that.
#161 
None.
> comments: add comments for struct fields

- apis/README.md
"Drgaonfly porject" to "Dragonfly project" in line 28.
> Fix typo in README.md

- dfget/core/api/download_api.go
- dfget/core/downloader/back_downloader/back_downloader_test.go
- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/client_writer_test.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/p2p_downloader_test.go
- dfget/core/downloader/p2p_downloader/piece_test.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/downloader/p2p_downloader/power_client_test.go
- dfget/core/downloader/p2p_downloader/target_writer.go
As title described, this PR add partial unit tests for the p2p downloader module.
fixes part of #352 
exactly
> test: add unit tests for p2p downloader

- dfdaemon/constant/code.go
- dfdaemon/downloader/dfget/dfget.go
- dfdaemon/initializer/initializer.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
Dfdaemon exit directly when load config file failed.
> fix: dfdaemon exit when load properties failed

- apis/swagger.yml
- apis/types/peer_info.go
- docs/api_reference/apis.md
> Fix some misspells

- .circleci/config.yml
- dfget/core/downloader/p2p_downloader/power_client.go
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/ClusterMember.java
- test/README.md
- test/cli_dfget_p2p_test.go
- test/command/cmd.go
test/command package makes it easier for integration testing.
`test/cli_dfget_p2p_test.go` is an example for testing downloading by using Dragonfly with p2p pattern.
related: #352
> test: implements test/command package of integration testing

- common/util/assert.go
- common/util/assert_test.go
- common/util/digest_util.go
- common/util/file_util.go
- common/util/net_util.go
- common/util/net_util_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/core/core.go
- dfget/core/core_test.go
- supernode/util/range_util.go
- supernode/util/range_util_test.go
Before developing the supernode, some of the necessary tools and methods can help improve the development efficiency. And I wrote it based on the java version of supernode.
None.
Added.
> feature: add some utils that supernode will use

- docs/quick_start/README.md
- docs/user_guide/download_files.md
- docs/user_guide/install_client.md
We have released version v0.3.0 and the related package files have also been uploaded to the server. So we should update the docs in a timely manner.
> doc: update the version of dfclient to v0.3.0

- docs/user_guide/supernode_configuration.md
fix supernode default port doc
this is doc
> fix supernode default port doc

- dfdaemon/downloader/dfget/dfget.go
- dfget/core/api/download_api.go
- dfget/core/api/supernode_api.go
- dfget/core/api/uploader_api.go
- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/regist/register.go
- dfget/core/uploader/peer_server_executor.go
- dfget/util/http_util.go
- dfget/util/queue.go
Add code to ensure Go interface satisfaction at compile-time.
NONE
NA
Just build the golang code.
> ensuring Go interface satisfaction at compile-time

- docs/quick_start/README.md
> added docker run desc

- .circleci/config.yml
- cmd/supernode/app/options.go
- cmd/supernode/app/root.go
- cmd/supernode/app/root_test.go
- common/util/file_util.go
- common/util/file_util_test.go
- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- supernode/config/config.go
- supernode/config/config_test.go
- supernode/config/constants.go
- supernode/config/plugin_type.go
- supernode/daemon/daemon.go
- supernode/plugins/plugin_manager.go
- supernode/plugins/plugins.go
- supernode/plugins/plugins_test.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
- supernode/store/store.go
- supernode/store/store_mgr.go
- test/environment/env.go
> feature: implement plugin framework of Dragonfly

- supernode/config/config.go
> fix: fix the default download path of supernode

- supernode/daemon/mgr/cdn_mgr.go
Add an empty implementation of the CDN manager for task manager.
fixes part of #348
None.
> feature: Add an empty implementation of the CDN manager

- README.md
Minor grammar/typo fixes in README
> Minor grammar/typo fixes in README

- supernode/daemon/mgr/scheduler/manager.go
- supernode/daemon/mgr/scheduler_mgr.go
> feature: implement an empty scheduler and update the interface

- supernode/daemon/mgr/progress/progress_manager.go
> bugfix: no need to return error if the result is nil when get pieces

- supernode/daemon/mgr/task_mgr.go
> feature: add setter/getter about pieces MD5 for task interface

- common/util/http_util_test.go
- dfget/core/core.go
- dfget/core/uploader/peer_server_executor.go
- dfget/util/http_util.go
- supernode/daemon/mgr/dfgettask/manager_test.go
- supernode/daemon/mgr/peer/manager_test.go
- supernode/daemon/mgr/scheduler/manager.go
Fix ineffectual assignments. As follows:
- dfget/core/core.go
Line 118: warning: ineffectual assignment to port (ineffassign)  
- dfget/util/http_util.go
Line 140: warning: ineffectual assignment to err (ineffassign)
- supernode/daemon/mgr/dfgettask/manager_test.go
Line 88: warning: ineffectual assignment to dt (ineffassign)
- supernode/daemon/mgr/scheduler/manager.go
Line 196: warning: ineffectual assignment to err (ineffassign)
- supernode/daemon/mgr/peer/manager_test.go
Line 131: warning: ineffectual assignment to err (ineffassign)
Line 133: warning: ineffectual assignment to err (ineffassign)
Line 142: warning: ineffectual assignment to err (ineffassign)
Line 144: warning: ineffectual assignment to err (ineffassign)
- dfget/core/uploader/peer_server_executor.go
Line 106: warning: …
> fix: fix ineffectual assignments

- FAQ.md
by default and in default have totally different meaning. Here in Dragonfly should we use by default.
docs: correct some abused phrase
> docs: correct some abused phrase

- FAQ.md
- docs/user_guide/proxy.md
Update documentation for the new proxy mode
fixes #478
> Update documentation for the new transparent proxy

- cmd/supernode/app/root.go
- common/util/net_util.go
- supernode/config/config.go
Add `AdvertiseIP` flag for the rootCmd of supernode.
None.
None.
> feature: add AdvertiseIP flag for supernode

- common/util/http_util.go
> feature: add a function to determine whether the resource has expired

- supernode/config/config.go
- supernode/daemon/mgr/progress/progress_manager.go
- supernode/daemon/mgr/progress/progress_util.go
- supernode/daemon/mgr/progress/progress_util_test.go
> feature: implement function of IsSuperCID and IsSuperPID

- cmd/supernode/app/root.go
> bugfix: use advertise-ip as the supernode ip when specified

- common/util/sync_map_util.go
> feature: add function GetAsString for SyncMap

- cmd/dfdaemon/app/options/options.go
- cmd/dfget/app/root.go
- docs/cli_reference/dfdaemon.md
- docs/cli_reference/dfget.md
Fixed typos ("supnernode" to "supernode")
N/A
N/A
N/A
N/A
N/A
> Fixed typos

- Dockerfile
Adjust Dockerfile for better caching
> Update Dockerfile for better caching

- supernode/daemon/mgr/progress/progress_manager.go
- supernode/daemon/mgr/progress/progress_util.go
> logs: add some debug logs with progress mgr for better debug

- supernode/daemon/mgr/peer/manager.go
- supernode/daemon/mgr/peer/manager_test.go
- supernode/daemon/mgr/scheduler/manager.go
- supernode/daemon/mgr/scheduler/manager_test.go
- supernode/daemon/mgr/scheduler_mgr.go
1. Implement the function getSupernodePID which get result from the config.
2. Add some logs for better debug.
None.
> feature: update scheduler manager GetSuperPID

- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/cdn_mgr.go
- supernode/daemon/mgr/mock/mock_cdn_mgr.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
> feature: add GetHTTPPath function for cdn mgr

- dfget/core/downloader/p2p_downloader/power_client.go
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/exception/UrlNotReachableException.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/HttpClientUtil.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/impl/PeerRegistryServiceImpl.java
at most follow 20 redirections
merge to  branch `master` and `0.3.x`
> fix: handle redirect at most 20 times

- supernode/daemon/mgr/cdn/file_meta_data.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/util/count_rw_mutex.go
- supernode/util/locker.go
> bugfix: add locker util and fix thread-unsafe problems for cdn

- common/constants/dfget_super_code.go
- dfget/core/api/supernode_api.go
- dfget/core/api/supernode_api_test.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/downloader/p2p_downloader/power_client_test.go
- dfget/core/helper/test_helper.go
- dfget/types/client_error_request.go
related pr: #582 
> merge into branch `master` and `0.3.x`
#545 #311 #68
> feature: dfget reports client error to supernode

- cmd/dfget/app/root.go
- common/util/net_util.go
- common/util/net_util_test.go
- dfget/config/constants.go
- dfget/core/api/supernode_api.go
- dfget/core/core.go
- dfget/core/regist/register.go
- test/cli_dfget_p2p_test.go
- test/environment/env.go
fixes #543 
fixes part of #473
Added
This PR do the same job with #542 #553. And thanks for the job by @xq2248
>merge into branch master and 0.3.x
> feature: parse the port of supernode from --node flag of dfget

- docs/user_guide/README.md
- docs/user_guide/download_files.md
- docs/user_guide/install_server.md
- docs/user_guide/supernode_configuration.md
> docs: remove useless contents

- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/SupernodeProperties.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/impl/PeerRegistryServiceImpl.java
supernode(java): -Dsupernode.downloadPort=xxx
the default value is 8001
> feature: make the download port configurable

- supernode/daemon/mgr/task/manager_util.go
> bugfix: do not use -1 as the basis for successful conversion

- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/cdn/super_writer.go
- supernode/daemon/mgr/cdn/super_writer_util.go
- supernode/daemon/mgr/task/manager.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
> bugfix: return http file length as the file length of register resp

- supernode/daemon/mgr/cdn/cdn_util.go
- supernode/daemon/mgr/cdn/super_reader.go
- supernode/daemon/mgr/cdn/super_writer_util.go
> feature: add piece length for task md5 file

- supernode/daemon/mgr/progress/progress_util.go
> bugfix: do not add the superPID to pieceState

- docs/user_guide/install_server_go.md
> doc: add a doc about how to install golang supernode

- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
Signed-off-by: inoc603 <inoc603@gmail.com>
Add unit tests for dfdaemon/config
go test -v ./dfdaemon/config -cover
> test: add unit tests for dfdaemon/config

- supernode/daemon/util/filter.go
Fix the third failure described in #631
#631 
make unit-test
> bugfix: fix unit test failure

- FAQ.md
modify  the spelling errors in the docs
fixes：#628
>  docs:modify some spelling mistakes in the doc

- .circleci/config.yml
- CONTRIBUTING.md
- Dockerfile
- Dockerfile.supernode
- docs/user_guide/install_server_go.md
- hack/build.sh
- test/README.md
update to Go 1.12.6
fix part of #634
> upgrade: bump to Go 1.12.6

- docs/user_guide/install_server_go.md
i have modify a mistake in the doc
> docs:modify a mistake in the doc

- common/util/file_util_test.go
> fix: unit-test failed in file_util_test.go caused by user permission

- .circleci/config.yml
- CONTRIBUTING.md
- common/util/net_util_test.go
- hack/generate-swagger-models.sh
update pouchlinter image. It uses Golang 1.12.6 and use go-swagger 0.19.0. 
@allencloud  Can you give a review please?
NONE
> chore: update pouchlinter

- Dockerfile.supernode
- hack/start-supernode.sh
> bugfix: update Dockerfile of supernode

- Dockerfile.supernode
- docs/quick_start/README.md
> bugfix: update supernode Dockerfile

- docs/user_guide/docker_proxy.md
- docs/user_guide/proxy.md
**WIP**
Add a document to describe how to use dfdaemon as http proxy for docker. 
Address one of the tasks in #596
Really sorry for the delay. I've been very busy recently and didn't have much time to work on this. I'll try find time to finish it. Feel free to comment on the work in progress.
> doc: user guide to use dfdaemon as http proxy for docker

- FAQ.md
fix type "questiones" -> "questions"
None
> fix type "questiones" -> "questions"

- README.md
docs: update readme about version information
Now we have rewritten Dragonfly in Golang version, and this will be the long term support one. We suggest that end users would adopt Golang version rather than Java version.
none
no need.
none
none
> docs: update readme about version information

- docs/user_guide/install_client.md
improve docs install_client.md
improve docs install_client.md
NONE
> improve docs install_client.md

- docs/user_guide/download_files.md
docs: improve docs download_files.md
docs: improve docs download_files.md
NONE
> docs: improve docs download_files.md

- docs/README.md
fix type "furthure" -> "further"
fix type "furthure" -> "further"
NONE
> fix type "furthure" -> "further"

- hack/check.sh
> chore: fix script to check code format

- dfdaemon/proxy/proxy.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/task/manager_util.go
We should use rawURL which contains some queries or parameter to interact with source web server.
None.
None.
> bugfix: use rawUrl to interact with source server

- hack/after-install.sh
- hack/before-remove.sh
- hack/build.sh
- hack/check-docker.sh
- hack/check.sh
- hack/docker-build.sh
- hack/env.sh
- hack/generate-contributors.sh
- hack/generate-docs.sh
- hack/generate-super-mock-mgr.sh
- hack/generate-swagger-models.sh
- hack/install.sh
- hack/package.sh
- hack/start-supernode.sh
- hack/unit-test.sh
Add options to bash scripts:
```
set -o nounset
set -o errexit
```
Otherwise the `build.sh` will continue when some steps failed. The final result is build a image with missing artifacts.
> Add options for bash scripts

- apis/swagger.yml
- apis/types/df_get_task.go
- apis/types/task_create_request.go
- apis/types/task_info.go
- apis/types/task_register_request.go
- supernode/daemon/mgr/dfgettask/manager_test.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/daemon/mgr/task/manager_util_test.go
- supernode/server/0.3_bridge.go
Add callSystem to taskRegisterRequest struct. Later we can add this information in metrics.
NONE
> feature: add callsystem when task create

- apis/swagger.yml
- cmd/dfdaemon/app/version.go
- cmd/dfget/app/version.go
- cmd/supernode/app/version.go
- common/util/metrics_util.go
- docs/user_guide/monitoring.md
- supernode/config/constants.go
- supernode/server/metrics.go
- test/util_api.go
- version/version.go
- add a doc about how to add metrics
- move NewMetrics logic to package common
NONE
> docs: add a doc about how to add metrics

- FAQ.md
docs: improve docs FAQ.md
NONE
none
none
none
> docs: improve docs FAQ.md

- Makefile
- test/cli_dfget_p2p_test.go
- test/command/cmd.go
- test/environment/env.go
> bugfix: Use a local file instead of a remote file as the url to be downloaded

- client/task_delete.go
feature: add tasks delete actions in client pkg of golang sdk
none
none
> feature: add tasks delete actions in client pkg of golang sdk

- client/request.go
- client/task_update.go
feature: add task update actions in client pkg of golang sdk
none
none
> feature: add task update actions in client pkg of golang sdk

- dfget/core/uploader/peer_server_executor.go
optimize error description
Signed-off-by: BingGuanqi <guanqi.bing@daocloud.io>
> optimize error description

- dfget/core/regist/register.go
- pkg/timeutils/time_util.go
- supernode/config/config.go
- supernode/daemon/mgr/cdn/cdn_util.go
- supernode/daemon/mgr/task/manager.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/daemon/mgr/task/manager_util_test.go
- supernode/server/result_info.go
The supernode will success to register the task even though when dfget try to download an 404 URL. It‘s not make sense. 
None.
> bugfix: return error when the url is unreachable

- supernode/server/router.go
- supernode/server/router_test.go
Caused by #654, it will return `unknown profile` if you try to do some profiling.
NONE
supernode -D then checkout browser at /debug/pprof/profile
> bugfix: fix bug unknown profile

- dfget/core/uploader/peer_server.go
cleanup: log message typo fix
NONE
NONE
NONE
NONE
> cleanup: log message typo fix

- docs/README.md
clean spell error, make it more understandable.
> docs/readme.md: cleanup typo in dcos

- supernode/store/storage_driver.go
just correct code typos in comments :)
> storage_driver.go: property name be "offset"

- cmd/dfget/app/server.go
fix typo in flag message
maybe not
no need test ;)
> cleanup: server.go flag help massage typo fix

- dfdaemon/constant/constant.go
- dfdaemon/handler/root_handler.go
- dfdaemon/server.go
- docs/user_guide/metrics.md
- docs/user_guide/monitoring.md
- go.mod
- go.sum
- pkg/metricsutils/metrics_util.go
- pkg/timeutils/time_util.go
- supernode/config/constants.go
- supernode/daemon/daemon.go
- supernode/daemon/mgr/dfgettask/manager.go
- supernode/daemon/mgr/dfgettask/manager_test.go
- supernode/daemon/mgr/peer/manager.go
- supernode/daemon/mgr/peer/manager_test.go
- supernode/daemon/mgr/task/manager.go
- supernode/daemon/mgr/task/manager_test.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/daemon/mgr/task/manager_util_test.go
- supernode/server/metrics.go
- supernode/server/router.go
- supernode/server/router_test.go
- supernode/server/server.go
- test/api_metrics_test.go
- test/util_api.go
- version/version.go
1. Add some internal metrics of supernode. The metrics I add are put in https://github.com/dragonflyoss/Dragonfly/pull/759/files#diff-da2f8a75b36b591f3f12425d653389ad.
2. Refact common metrics part. Add a register param to make registering metrics more flexible, especially in tests. 
NONE
I have added some unit tests. As for integration test, I will put it later.
> feature: add some supernode metrics

- cmd/dfget/app/root.go
- docs/cli_reference/dfget.md
cleanup misspelled words
no need
> cleanup: fix typos in root.go and dfget.md

- supernode/daemon/mgr/task/manager_util.go
update dfget task to success
fixes #792 
Already verified in Prometheus
We can see the dfget task metrics with status "success" now
> bugfix: update dfgettask status to success

- test/README.md
Make the document more readable
None
> fix mis-spelling in README.md

- client/httputils.go
Signed-off-by: xichengliudui <1693291525@qq.com>
Use constant blocks to define constants instead of discrete definitions.
NONE
/integration test
> Use constant blocks to define constants instead of discrete definitions.

- docs/quick_start/README.md
- docs/user_guide/install_client.md
- docs/user_guide/install_server.md
- docs/user_guide/monitoring.md
- docs/user_guide/multi_machines_deployment.md
Welcome to the release 0.4.3 of Dragonfly.
> docs: update docs for release 0.4.3

- ROADMAP.md
Adjust the doc of `ROADMAP` to make it look more reasonable.
None.
Just docs.
> docs: update the roadmap doc

- apis/swagger.yml
- apis/types/df_get_task.go
fix typos in docs, make it more smooth.
NONE
no, it's very simple change.
> apis/swagger.yml: cleanup by fix some typos

- supernode/daemon/mgr/dfgettask/manager.go
Add a check before deleting supernode dfget tasks
fixes #853 
No
> bugfix: prevent dfgettask metrics < 0

- .golangci.yml
- client/request.go
- dfget/core/api/supernode_api_test.go
- dfget/core/uploader/peer_server_test.go
- dfget/core/uploader/uploader.go
- supernode/daemon/mgr/dfgettask/manager_test.go
feature: add staticcheck
fixes: #848
> feature: enable staticcheck

- supernode/daemon/mgr/scheduler/manager.go
As title described.
None.
None.
> refactor: update some code and output logs for supernode

- pkg/httputils/mock_http_util.go
Delete extra slash
NONE
Don't need
> delete extra slash

- .github/ISSUE_TEMPLATE/feature-request-of-dragonfly.md
- CONTRIBUTING.md
Delete ertra spaces
NONE
Don't need
> delete ertra spaces

- client/task_create.go
feature: add tasks create actions in client pkg of golang sdk
add peers implementation in sdk：
POST /tasks
none
none
> feature: add tasks create actions in client pkg of golang sdk

- CONTRIBUTING.md
- cmd/supernode/app/version.go
- docs/quick_start/README.md
- docs/user_guide/multi_machines_deployment.md
- test/README.md
Modify the Chinese punctuation mark to the English punctuation mark.
NONE
Don't need.
> Modify the Chinese punctuation mark to the English punctuation mark

- supernode/daemon/mgr/gc/gc_peer.go
modify  gc logic err,if in previous logic,when download time is long,the peer will be delete during download 
fixes #844
> bugfix: modify gc logic err

- dfget/core/core.go
> bugfix:fix dfget panic

- dfget/core/uploader/uploader.go
fix typo in /dfget/core/uploader/
> fix typo in /dfget/core/uploader/

- pkg/dflog/log.go
- pkg/fileutils/fileutils.go
- pkg/httputils/http_util.go
> fix-up-document-format

- pkg/errortypes/errortypes.go
- pkg/errortypes/supernode_errors.go
- pkg/printer/printer.go
- pkg/syncmap/syncmap.go
modify the document 
None
No Need
> improve standard of  the document

- supernode/config/config.go
- supernode/daemon/daemon.go
- supernode/daemon/mgr/cdn/cache_detector.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/cdn/piece_md5_mgr.go
- supernode/daemon/mgr/dfgettask/manager.go
- supernode/daemon/util/filter.go
Signed-off-by: chentanjun <2799194073@qq.com>
modify document
None
No Need
> perfect the document

- docs/user_guide/install_server.md
> docs: fix wrong command.

- supernode/daemon/mgr/cdn_mgr.go
- supernode/daemon/mgr/dfget_task_mgr.go
- supernode/daemon/mgr/gc/gc_manager.go
- supernode/daemon/mgr/peer/manager.go
- supernode/daemon/mgr/progress/progress_util.go
- supernode/httpclient/origin_http_client.go
- supernode/plugins/plugin_manager.go
- supernode/plugins/plugins.go
- supernode/server/result_info.go
- supernode/store/errors.go
- supernode/store/local_storage.go
- supernode/store/storage_driver.go
- supernode/store/store.go
- supernode/store/store_mgr.go
- test/command/cmd.go
- test/request/request.go
Signed-off-by: chentanjun <2799194073@qq.com>
modify document
None
No Need
> modify document

- cmd/dfdaemon/app/init.go
- cmd/dfdaemon/app/root.go
- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- cmd/supernode/app/root.go
- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
- dfdaemon/proxy/proxy.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/config/constants.go
- dfget/core/core_test.go
- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/uploader/peer_server.go
- dfget/core/uploader/peer_server_executor.go
- go.sum
- pkg/limitreader/limit_reader.go
- pkg/netutils/netutils.go
- pkg/netutils/netutils_test.go
- pkg/rate/rate.go
- pkg/rate/rate_test.go
- pkg/ratelimiter/ratelimiter.go
- supernode/config/config.go
- supernode/daemon/mgr/cdn/manager.go
1. Add model.Rate type to represent rate type, includes GB, MB, KB and B.
fixes #879 #836 
Added some tests already.
> feature: support rate type

- client/client.go
- client/preheat_info.go
- cmd/dfdaemon/app/gen_doc.go
- cmd/dfdaemon/app/init.go
- cmd/dfdaemon/app/root.go
- cmd/dfget/app/gen_doc.go
- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- cmd/supernode/app/root.go
> perfect document

- cmd/dfdaemon/app/root_test.go
- cmd/dfget/app/server.go
- cmd/supernode/app/root.go
add error handling in cmd
NONE
> cmd: add err handling

- supernode/daemon/mgr/gc/gc_task.go
Signed-off-by: SataQiu <qiushida@beyondcent.com>
Remove useless return value of gc task function
#845
> Remove useless return value of gc task function

- client/client.go
- dfdaemon/proxy/proxy.go
- dfget/config/config.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/power_client.go
Grammatical correction.
NONE
Don't need.
> Grammatical correction

- dfget/config/config_test.go
- dfget/config/metadata_test.go
- dfget/core/downloader/p2p_downloader/client_writer.go
> dfget: add err handling

- client/peer_delete.go
- client/request.go
- client/task_delete.go
- client/task_update.go
- client/utils.go
add error handling in client
NONE
may be need test
> fix(client): add error handling in client

- docs/user_guide/metrics.md
- supernode/daemon/mgr/gc/gc_manager.go
- supernode/daemon/mgr/gc/gc_peer.go
- supernode/daemon/mgr/gc/gc_task.go
- supernode/server/server.go
Signed-off-by: SataQiu <qiushida@beyondcent.com>
feature: add gc metrics
Ref: #840
> feature: add gc metrics

- cmd/supernode/app/root.go
- go.mod
- go.sum
- pkg/errortypes/errortypes.go
- pkg/fileutils/filesize.go
- pkg/fileutils/filesize_test.go
- pkg/fileutils/fileutils.go
- supernode/config/config.go
- supernode/config/constants.go
- supernode/daemon/mgr/cdn/cache_detector.go
- supernode/daemon/mgr/cdn/cdn_gc.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/cdn/path_util.go
- supernode/daemon/mgr/cdn_mgr.go
- supernode/daemon/mgr/gc/gc_disk.go
- supernode/daemon/mgr/gc/gc_manager.go
- supernode/daemon/mgr/mock/mock_cdn_mgr.go
- supernode/daemon/mgr/task/manager.go
- supernode/store/local_storage.go
- supernode/store/storage_driver.go
- supernode/store/store.go
With supernode downloading more and more tasks, and it will take up more and more disk space. So we need  a gc mechanism to clean up the disk space occupied by the supenrode when necessary. And that's what this PR does.
#867
> feature: add supernode disk gc feature

- docs/user_guide/monitoring.md
Add docs about other exporters.
NONE
> Add docs about other exporters

- CONTRIBUTING.md
- FAQ.md
It is also welcomed to join Dragonfly team if you are willing to participate in Dragonfly community continuously and keep active.
And this PR will help you to find how to join the `dragonflyoss org` and what should you prepare for that.
NONE.
> doc: add instructions how to join Dragonfly as a meber

- Makefile
feature: add 'help' target to Makefile and make it the default
make
make help
> feature: add 'help' target to Makefile and make it the default

- client/request.go
- dfget/core/core.go
- dfget/core/uploader/peer_server.go
- dfget/core/uploader/uploader.go
- supernode/server/router.go
cleanup some code, fix some staticcheck warnings
NONE
no big changes
> cleanup code base: reformat some code based on staticcheck

- supernode/server/0.3_bridge.go
- supernode/server/router_test.go
- supernode/server/system_bridge.go
add error handling in test and version folder
Ref: #952
> fix(supernode/server): add error handling

- cmd/dfdaemon/app/root.go
- dfget/core/uploader/uploader.go
Perfect annotations.
NONE
Don't need.
> Improve the comments: modify the words spelling mistakes

- docs/user_guide/metrics.md
Some metrics labels are stale, and this PR update them.
NONE
> docs: update stale metrics docs

- dfget/core/uploader/peer_server_test.go
- dfget/core/uploader/uploader_helper_test.go
- dfget/core/uploader/uploader_util_test.go
- supernode/daemon/mgr/progress/state_sync_map.go
cleanup code based on staticcheck warnings
> clinte, dfget, supernode: delete unused functions based on static check

- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/config/constants.go
- dfget/core/core.go
- dfget/core/core_test.go
- dfget/core/regist/register.go
- dfget/core/regist/register_test.go
remove  the repeat struct Properties 
Ref #933
> make the struct Properties embedded into config Ref#933

- dfdaemon/handler/env_handler.go
- dfdaemon/handler/param_handler.go
- dfdaemon/proxy/proxy.go
- dfdaemon/server.go
Add error handling in supernode/httpclient
Ref: #952
>  fix(dfdaemon): add error handling 

- dfget/core/api/supernode_api_test.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/uploader/peer_server.go
- supernode/daemon/mgr/pieceerror/manager.go
dfget&&supernode: cleanup code based on staticcheck warnings
> dfget&&supernode: cleanup code based on staticcheck warnings

- .circleci/config.yml
- CONTRIBUTING.md
- Dockerfile
- Dockerfile.supernode
- cmd/dfdaemon/app/version.go
- cmd/dfget/app/version.go
- cmd/supernode/app/version.go
- docs/cli_reference/dfdaemon_version.md
- docs/cli_reference/dfget_version.md
- hack/build.sh
- test/README.md
Signed-off-by: fengzixu <hnustphoenix@gmail.com>
Due to the golang vulnerability, we need to upgrade golang version
#989 
I run `make build` and `make unit-test` to verify
> feature: upgrade golang version to 1.12.10

- version/version.go
> version: add error handling

- dfget/core/downloader/p2p_downloader/power_client.go
- supernode/daemon/mgr/gc/gc_peer.go
- supernode/daemon/mgr/gc/gc_task.go
Signed-off-by: SataQiu <qiushida@beyondcent.com>
feature: add a warn log for long gc duration
/cc @Starnop @yeya24
> feature: add a warn log for long gc duration

- Makefile
- hack/env.sh
Using GOPROXY environment variables if set instead of default value
> Using GOPROXY environment variables if set instead of default value

- docs/config/README.md
- docs/config/dfdaemon_config_template.yml
- docs/config/dfdaemon_properties.md
- docs/config/dfget_config_template.yml
- docs/config/dfget_properties.md
- docs/config/supernode_config_template.yml
- docs/config/supernode_properties.md
> doc: add a doc about how to configure  supernode,dfget,dfdaemon

- supernode/daemon/mgr/gc/gc_task.go
- supernode/server/0.3_bridge.go
- supernode/server/router.go
fixes #1007
related PR #582 #583 #587 #794
> feature: add piece error handler API for supernode

- cmd/dfdaemon/app/init.go
- cmd/dfdaemon/app/root.go
- cmd/dfget/app/root.go
- dfdaemon/config/config.go
- dfget/config/config.go
- dfget/core/uploader/peer_server_executor.go
Dfget server uses current user's home directory as root workdir, and it is not configurable now.
I wish that I can change the dfget work dir by dfget's config file.
None
> feature: support set home dir in dfget config file.

- adopters.md
docs: delete Yum China as a Dragonfly adopter
> docs: delete Yum China as a Dragonfly adopter

- supernode/store/local_storage.go
> fix comment for localStorage

- supernode/config/config.go
the comment for PeerDownLimit's default value is wrong.
> bugfix:modify the comment

- .circleci/config.yml
Update circle ci to 2.1 to use go orb.
Add cache for go mods.
NONE
> chore: Add go mod cache in circleci

- pkg/netutils/netutils.go
> feature: prohibit the IPv6 addr for supernode peer IP

- supernode/daemon/mgr/progress/progress_util.go
> bugfix: fix running piece concurrent update wrong

- cmd/dfdaemon/app/init.go
- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- cmd/supernode/app/root.go
- dfdaemon/config/config.go
- dfget/config/config.go
- pkg/dflog/log.go
- pkg/dflog/log_test.go
- supernode/config/config.go
> feature: make the log related parameter can be configured

- .circleci/config.yml
- .goreleaser.yml
1. Auto build tarballs in each release
2. publish images to docker hub in each release
fixes #1072
> add goreleaser in circleci

- docs/user_guide/dragonfly.json
> fix broken grafana dashboard

- apis/swagger.yml
201means success create
but this request just want to get all peers
> bugfix:fix api response  status code 

- client/interface.go
- client/peer_create.go
- client/peer_delete.go
- client/peer_info.go
- client/peer_list.go
- client/preheat_create.go
- client/preheat_info.go
- client/task_create.go
- client/task_info.go
in this pr,
I do these things:
1. make dfget request url int the format `api/v1/*`
2. modify `config` to `request`
3. and make client interface be the sub-interface of `CommonAPIClient`  
refrence #1082 #1065
> feature:modify client api

- FAQ.md
Fixes CI in #1125
See https://circleci.com/gh/dragonflyoss/Dragonfly/12939?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
NONE
> [chore] fix bad link

- pkg/ratelimiter/ratelimiter_test.go
Add unit test case for func TransRate
NONE
go test github.com/dragonflyoss/Dragonfly/pkg/ratelimiter -run Test -v
> test: add unit test case for func TransRate

- pkg/printer/printer.go
Fix comment for function Print in pkg/printer/printer.go, 'Println' -> 'Print'
NONE
> fix typo: fix comment for func Print

- CONTRIBUTING.md
Insert steps for updating working directory, create
a new branch for contributing.
Signed-off-by: Nguyen Hai Truong <truongnh@fujitsu.com>
Add more detail steps in workspace preparation
This PR for docs
> docs: add more detail steps in workspace preparation

- CODE_OF_CONDUCT.md
Fix http link to https link for security, modify many link
http to https in the project.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> Securing many http links to https links

- docs/user_guide/download_files.md
- docs/user_guide/install_client.md
- docs/user_guide/install_server.md
> docs: update docs about deploy with Physical Machines

- pkg/syncmap/syncmap_test.go
> test: add unit test case for func GetAsBool

- supernode/daemon/mgr/cdn/downloader.go
- supernode/daemon/mgr/cdn/downloader_test.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/daemon/mgr/task/manager_util_test.go
- supernode/httpclient/mock/mock_origin_http_client.go
- supernode/httpclient/origin_http_client.go
generate task by for one file by http range
> feat: generate task per http range

- pkg/syncmap/syncmap_test.go
> test: add unit test case for func GetAsMap

- pkg/digest/digest_test.go
> Add digest util test

- docs/ecosystem/Harbor-with-Dragonfly.md
Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> docs: trivial fix some typos

- docs/user_guide/multi_machines_deployment.md
Although it is small mistake, it might make an affect while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
> Fix markdown syntax in documentation

- pkg/constants/dfget_super_code_test.go
Complete tests in other situations.
> pkg/constants: improve GetMsgByCode test

- supernode/config/constants.go
Fix comment for const var in supernode/config/constants.go, 'DefaultFailCountLimit' -> 'DefaultFailureCountLimit'
NONE
> fix typo: fix comment for const var DefaultFailureCountLimit

- pkg/fileutils/fileutils_test.go
> pkg/fileutils: add unit test for IsRegularFile

- pkg/fileutils/fileutils.go
According to [the suggestions given by Allen](https://github.com/dragonflyoss/Dragonfly/pull/1223#discussion_r379912052), reconstruct all errors in pkg/fileutils following conventions.
> Construct errors following conventions

- README.md
This PR removed gitter from realtime chatting tools, since I think we are no longer at the gitter tools.
While we suggest that github issue and dingtalk is the direct way we could use to communicate in real time.
none
no need
none
none
> docs: remove gitter from realtime chatting tools

- docs/design/data_integrity.md
docs: add data integrity theory of distributing files and blocks
https://github.com/dragonflyoss/Dragonfly/issues/1205 asked the data integrity of Dragonfly, we think it should be a document to present all the details.
fix https://github.com/dragonflyoss/Dragonfly/issues/1205
no need, just docs.
none
none
> docs: add data integrity theory of distributing files and blocks

- dfdaemon/server.go
Fix bug
Issue: #1231 
Need integration testing
Don't config docker mirrors，pull the images from a non-local address（eg：docker pull 192.168.1.100:8443/alpine:3.9）
> Fix an issue where HTTPS is not supported

- pkg/dflog/log_test.go
Add unit test case for func WithMaxSizeMB
NONE
go test github.com/dragonflyoss/Dragonfly/pkg/dflog -run Test -v
> test: add unit test case for func WithMaxSizeMB

- pkg/httputils/http_util.go
- pkg/httputils/http_util_test.go
See as https://github.com/dragonflyoss/Dragonfly/issues/1245.
fix https://github.com/dragonflyoss/Dragonfly/issues/1245.
add it.
by unit test.
> fix the concurrent race of reuse of fasthttp resp body

- pkg/httputils/http_util_test.go
> test: add unit test case for func ConstructRangeStr

- client/httpuils_test.go
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
add unit test for client/httputils.go
NONE
> add unit test for client/httputils.go

- supernode/config/config_test.go
> test: add unit test case for func GetSuperCID

- dfget/core/helper/helper_test.go
- dfget/core/helper/test_helper.go
- pkg/queue/lru_queue.go
- pkg/queue/lru_queue_test.go
Add the lru queue and mock file server. It may be used in some test.
NONE.
Already add it.
> add lru queue and mockFileServer

- docs/user_guide/install_client.md
> docs: fix typo

- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/power_client.go
Signed-off-by: frank.hx <1543087373@qq.com>
typo: fix typo cdnDource to cdnSource
> typo: fix typo cdnDource to cdnSource

- dfdaemon/proxy/proxy.go
proxy: do not log error messages when http Server is closed
Since it is an expected error, we don't have to log it.
Fixes: #1273
> Proxy: do not log error messages when http Server is closed

- Dockerfile
- Dockerfile.supernode
- hack/docker-build.sh
> fix: pass GOPROXY to docker build

- supernode/config/config_test.go
> supernode/config: add some unit tests

- .travis.yml
fix error when execute `git describe`:
```bash
./hack/build.sh dfget
fatal: No names found, cannot describe anything.
```
> fix(ci): disable shadow clone in travis-ci

- dfget/corev2/basic/types.go
Add schedule peer info.
NONE.
NONE.
> add schedule peer info

- dfget/config/supernode_value_test.go
Add unit test case for supernode_value.go
NONE
> test: add unit test case for supernode_value.go

- pkg/protocol/http/http.go
- pkg/protocol/url.go
add functional options as arguments for NewProtocolClient.
NONE.
no need.
> add functional options for new protocol client

- pkg/fileutils/fileutils.go
- pkg/fileutils/fileutils_test.go
- supernode/daemon/mgr/cdn/path_util.go
- supernode/store/local_storage.go
It's to prevent the `inode` from being exhausted.
> fix: delete empty directory in local storage

- pkg/errortypes/errortypes_test.go
> test: add unit test case for func NewHTTPError

- README.md
> doc(README): change "Sandbox" to "Incubating"

- dfget/core/downloader/p2p_downloader/p2p_downloader.go
feature: compare the local md5 and the md5 returned by supernode after downloaded.
#1459 
N/A
N/A
> feature: compare md5 after downloaded

- MAINTAINERS.md
Signed-off-by: garfield009 zuozheng.hzz@alibaba-inc.com
@jim3ma  has made outstanding contributions to the dfget and supernode of Dragonfly. He mainly made the following contributions：
+ support stream mode and  seed mode of dfget
+ support custom protocal
+ very active in dragonfly dev group. help a lot of people resolve deployment issue, address problems, and bug fix. take an active part in community issue discussion
+ multiple container runtimes images distribution support and many other minimum update
He is still willing to contribute more to the maintenance of the community and the future development.
With the trust @jim3ma  built in the community, I proposed to add @jim3ma  as a maintainer in Dragonfly project.
Also cc @lowzj @allencloud @zhouhaibing089 @chenchaobing @inoc603 …
> add jim3ma as a maintainer

- supernode/daemon/mgr/preheat/file_preaheater.go
bugfix(supernode) Change the default log level to info to prevent the disk from being full
NONE
N/A
N/A
> bugfix(supernode) the log level default debug

- dfget/local/seed/downloader.go
- dfget/local/seed/downloader_generator.go
- dfget/local/seed/manager.go
- dfget/local/seed/manager_test.go
- dfget/local/seed/seed.go
- dfget/local/seed/seed_test.go
- dfget/local/seed/types.go
Seed support prefetch data from other peers.
> peer to peer downloader for seed prefetch

- dfget/locator/manager_test.go
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
Unit test
NONE
> test: Add unit test for dfget/locator/manager.go

- dfget/core/downloader/p2p_downloader/p2p_downloader.go
finishTask **should** return error, otherwise p2pdownloader would consider download success.
NONE
N/A
N/A
####dfget log:
2020-09-29 17:31:12.862 INFO sign:7978-1601371750.211 : move src:/root/.small-dragonfly/data/inventory-20200805160005-shard_2-segment530.idx-7978-1601371750.211 to dst:/usr/tmp/4694/10881659/inventory-20200805160005-shard_2-segment530.idx result:false cost:0.000
2020-09-29 17:31:12.862 WARN sign:7978-1601371750.211 : post run error: failed to move /root/.small-dragonfly/data/inventory-20200805160005-shard_2-segment530.idx-7978-1601371750.211 to /usr/tmp/4694/10881659/inventory-20200805160005-shard_2-segment530.idx: **src is not a regular file**
####high level service log:
time="2020-09-29T17:31:12+08:00" level=debug msg="DownloadFile dfcmd output:--2020-09-29 17:29:10-- …
> bugfix(dfget) finishTask should return error

- docs/design/dfget_supernode.puml
When I study the dragonfly, I find something that need to be revised. Because the timing diagram is not matched with the master branch code.
NONE
NO
You can find the relation API, in the file : dragonfly/supernode/server/router.go
None
> timing diagram is inaccurate

- cmd/dfdaemon/app/init.go
> Add dfget cmd version args
