- src/daemon/src/df-daemon/df-daemon.go
- src/daemon/src/df-daemon/global/global.go
- src/daemon/src/df-daemon/handler/debug_handler.go
- src/daemon/src/df-daemon/handler/dfgetter.go
- src/daemon/src/df-daemon/handler/env_handler.go
- src/daemon/src/df-daemon/handler/param_handler.go
- src/daemon/src/df-daemon/handler/root_handler.go
- src/daemon/src/df-daemon/handler/transport.go
- src/daemon/src/df-daemon/initializer/initializer.go
- src/daemon/src/df-daemon/muxconf/muxconf.go
- src/daemon/src/df-daemon/util/netutil.go
basically, as a go project, it should be discoverable by go tools,
thus I makde a change to update its import path to be:
github.com/alibaba/Dragonfly/src/daemon/src/df-daemon
with this change, you can run:
go get github.com/alibaba/Dragonfly/src/daemon/src/df-daemon
and get a compiled binary in your $GOPATH/bin.
> df-daemon: change the import path

- build/supernode/supernode-build.sh
#90 
When building the supernode container image, if the docker is not installed or docker daemon is not started, the build scripts will show an error message: **Please install docker and start docker daemon first.**;
> chore: check environment before building supernode image

- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/rest/controller/PeerController.java
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/rest/request/ReportPieceRequest.java
dfget query supernode's api `/peer/piece/suc` always gets an error: `some param is empty`. The error is caused by inconsistent parameter name `range` between supernode and dfget.
And this pull request will do:
* bugfix: inconsistent parameter name "range" of report piece success request between supernode and dfget
* log: add debug logs for PeerController
Please merge to branch `master` and `0.1.x`.
> bugfix: report successful piece always gets an error

- dfdaemon/handler/dfgetter.go
#125  [df-daemon] discard HTTP host header for backing to source successfully
> bugfix: fix back source failed

- cmd/dfdaemon/options/options.go
Start dfdaemon failed because of the invalid default value of options.DFRepo: `$HOME.small-dragonfly/dfdaemon/data/`. The expected value is: `$HOME/.small-dragonfly/dfdaemon/data/`.
Missed a `/` between `$HOME` and `.small-dragonfly`.
> fix(dfdaemon): fix default value of options.DFRepo

- dfget/types/pull_piece_task_response.go
- dfget/types/types_test.go
> bugfix: correct the type of response when the task's status is CONTINUE

- dfget/util/queue.go
- dfget/util/queue_test.go
Add a general implementation of blocking queue to use easily instead of directly using buffered channels.
The buffered channels can only implement blocking queue with a fixed capacity and there're many redundant codes when we directly use it.
So this pull request defines a general blocking queue interface and implements 2 kinds of blocking queue:
* `infiniteQueue`: we can use it when we don't care about the capacity of queue beforehand. It uses `List` to store elements, uses a `unsafe.Pointer(point to a chan)` and `sync.Mutex` for concurrency controlling.
```go
// create a blocking queue with an infinite capacity
q := NewQueue(0)
```
* `finiteQueue`: we can use it when we want a fixed capacity queue. It's implemented by buffered channels.
```go
// create a blocking queue with fixed …
```
> feature: add blocking queue

- docs/quick_start/_index.md
add install dfclient commands to QuickStart
> docs: add install dfclient commands to QuickStart

- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/common/domain/FileMetaData.java
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/common/util/HttpClientUtil.java
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/CacheDetectorImpl.java
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/Downloader.java
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/cdn/FileMetaDataService.java
- src/supernode/src/main/java/com/alibaba/dragonfly/supernode/service/impl/FileMetaDataServiceImpl.java
I used harbor as our docker registry, with Dragonfly as a p2p proxy, and I found that supernode has never hit the cache in `./repo/download`. 
It seems that supernode always downloads the blob file again from harbor, even the same file has exist in the `./repo/download/{taskid}/files`
In the method `CacheDetectorImpl.parseBreakNum`, supernode only uses the `Last-Modified` to check whether the cache has expired.
However, Harbor only returns the `ETag` header in the response message. The `ETag` is the sha256 digest of the blob. 
This PR adds support for ETag identifier with http cache. `parseBreakNum` will return 0 when both `Last-Modified` and `Etag` check failed.
NA
NA
1. use Harbor as docker registry(I don't think harbor is nessary, however I have not tried), and Dragonfly as a p2p …
> fix http cache miss for servers which supports etag only

- build/client/run.sh
- build/supernode/supernode-build.sh
> go vet "${packages}" 2>&1
The `"${packages}"` will be treated as one whole string parameter by `go vet`. Actually we want `go vet` receives all files not one file. A workaround is:
```bash
echo "${packages}" | xargs go vet 2>&1
```
> chore: fix go vet check failure and misspell of shell scripts

- build/build.sh
- build/client/env.sh
- build/client/run.sh
Create links `dfdaemon` and `dfget` in `/usr/local/bin`. It's convenient for users to use dragonfly client directly after installing.
> chore: create links to clients in /usr/local/bin

- client/client.go
- client/httputils.go
- client/interface.go
- client/preheat_create.go
- client/preheat_info.go
- client/preheat_list.go
- client/request.go
- client/utils.go
When we expose API side of supernode in Dragonfly, caller should have a sdk to call API.
This pr adds preheat related golang sdk for client.
The API endpoints is:
* GET /preheats/{id}
* GET /preheats
* POST /preheats
none
Will add in a follow-up
none
none
> feature: add preheat client sdk for supernode

- docs/.build/prepare.sh
Relative path of image in markdown files are not suitable for generated hugo html pages.
This pull request replaces all the relative path with absolute path.
> fix: dead image link in hugo pages

- Dockerfile
- dfdaemon/initializer/initializer.go
It used to take a long time to download the image because it was so big. As title described, to make the image smaller built by the Dockerfile, I rewrite the Dockerfile using multi-stage builds. Now 
```
REPOSITORY                                                 TAG                 IMAGE ID            CREATED             SIZE
dfclient                                                   latest              b1a01a3df1a9        12 minutes ago      28.5MB
dragonflyoss/dfclient                                      v0.3.0_dev          79cf3514b9dc        3 weeks ago         842MB
```
Finally, the program also runs normally and the mirror size is significantly reduced
None.
just Dockerfile
```
CONTAINER ID        IMAGE …
```
> Rewrite dockerfile to make the image smaller

- cmd/dfget/app/root.go
- dfget/config/config.go
- dfget/core/core.go
- dfget/core/downloader/p2p_downloader.go
The `dfget` will output twice result message and the downloaded file's length is not correct.
```bash
--2018-12-26 19:51:37--  https://www.taobao.com
dfget version:0.3.0
workspace:/Users/zj/.small-dragonfly sign:51733-1545825097.015
client:127.0.0.1 connected to node:127.0.0.1
start download by dragonfly
download SUCCESS(0) cost:0.052s length:-1 reason:0
download SUCCESS(0) cost:0.052s length:-1 reason:0
```
> fix: remove redundant log and output correct file length

- cmd/dfget/app/root.go
- dfget/core/downloader/p2p_downloader.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_util.go
- dfget/core/uploader/uploader_util_test.go
- dfget/util/http_util.go
implement the basic handler of uploader, at present, the http server of uploader exposes  four apis currently as follows:
1. /peer/file/{taskFileName},  trans the piece content  that dfget wants to get;
2. /rate/{taskFileName}, update the read rate limit; 
3. /check/{taskFileName}, check the server status to decide whether to restart a new server;
4. /client/finish, when a dfget downloaded a piece from uploader server, update the status of finished.
None.
added.
not now.
We still have something to do as follows:
1. limit read rate
2. check alive and sever gc
3. start the server with a new process
> feature: implement dfget uploader server

- FAQ.md
FAQ is very important for end-users or developers to understand the project much better.
We have not sufficient question&answer in Dragonfly before. 
Now I try to add more question&answer in FAQ.md.
If any reviewers or readers find that there should be more concrete questions there in FAQ.md, please do not hesitate to add question&answer in the file within a pull request, or in issue to request maintainers to add.
fix https://github.com/dragonflyoss/Dragonfly/issues/212
fix https://github.com/dragonflyoss/Dragonfly/issues/301 via question ## What is the policy of bandwidth limit in peer network
no need.
none
none
> docs: add more questions in FAQ.md

- .circleci/config.yml
Project Dragonfly pays lots of attention on the cyclomatic complexities of functions in Go source code. Reasonable cyclomatic complexities could be able to make the code much more readable. We must support this at the very beginning of the golang refactoring. Then it could be a fundamental feature of Dragonfly.
Here we take advantages of [gocyclo](https://github.com/alecthomas/gocyclo) in [gometalinter](https://github.com/alecthomas/gometalinter). Please see the code update about the circle CI config file.
Currently we set the gocyclo limit is 20. Any functions which have more than 20 cyclos will trigger the CI failure.
none
no need.
none
none
> ci: add gocyclo support in circle CI test

- cmd/dfget/app/root.go
In fact, we should use `Flags()` instead of `PersistentFlags()`. A 'persistent flag' means that this flag will be available to the command it's assigned to as well as every command under that command. For more info about `PersistentFlags`, please refer to https://github.com/spf13/cobra#persistent-flags
None.
not needed.
> bugfix: update rootCmd of dfget from PersistentFlags to Flags

- .gitignore
- Makefile
- hack/build-client-local.sh
Signed-off-by: fengzixu <hnustphoenix@gmail.com>
1. add the script to build the client in the local env other than docker
2. add the build option in the Makefile
fixed https://github.com/dragonflyoss/Dragonfly/issues/313
Just makefile and a script of building the client
Run two commands:
1. cd hack && ./build-client-local.sh
2. make build-client-local
> feature: add the build option of the client in the local environment

- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/config/constants.go
- dfget/core/core.go
- dfget/core/core_test.go
- dfget/core/uploader/uploader.go
- dfget/errors/errors.go
- dfget/util/log.go
- dfget/util/log_test.go
- dfget/util/util.go
- dfget/util/util_test.go
- vendor/github.com/pkg/errors/LICENSE
- vendor/github.com/pkg/errors/Makefile
- vendor/github.com/pkg/errors/README.md
- vendor/github.com/pkg/errors/appveyor.yml
- vendor/github.com/pkg/errors/errors.go
- vendor/github.com/pkg/errors/stack.go
- vendor/vendor.json
I submitted this pull request for the following reasons: 
+ For a project with `Golang`, it's not suitable to use a lot of `panic` . 
+ In the mean time, it's not user-friendly to print the `Stack information` when something goes wrong.
+ For error handling, we should normalize that.
+ By the way, refactor the code which is not reasonable.
fixes  #193
updated.
> refator: use error instead of panic

- dfget/core/downloader/power_client.go
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/cdn/Downloader.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/cdn/SuperWriter.java
Dragonfly cannot download an empty file because that supernode don't write and cache data if the file length less and equals zero.
fix `0.2.x`: #351 
fixes: #44 
Prepare an empty file, start supernode, and use dfget to download it, here is the repaired logs:
**supernode**
```
2019-01-24 17:41:07.959  INFO 28083 --- [http-nio-8080-exec-1] c.d.d.s.repository.TaskRepository        : get file length:0 from http client about taskId:5b1c283943dc1c8da0865907038b0401ce7f5f50b4a7bb2b8f8b7bcf7dda5d00
2019-01-24 17:41:07.961  INFO 28083 --- [http-nio-8080-exec-1] c.d.d.s.service.impl.CdnManagerImpl      : do trigger cdn start for taskId:5b1c283943dc1c8da0865907038b0401ce7f5f50b4a7bb2b8f8b7bcf7dda5d00,httpLen:0
2019-01-24 17:41:07.970  INFO 28083 --- …
```
> fix: cannot use dragonfly to download an empty file

- dfget/core/core.go
- dfget/core/downloader/p2p_downloader.go
- dfget/core/downloader/power_client.go
- dfget/core/helper/helper_test.go
- dfget/core/helper/util_helper.go
When downloading pattern is not `p2p`, `dfget` should not write service file for uploading, because they're useless.
This pull request makes `dfget` only write downloading data to target directory. It will reduce write disk times.
> fix: don't write service file if downloading pattern isn't p2p

- dfget/core/downloader/back_downloader.go
- dfget/core/downloader/p2p_downloader.go
- dfget/core/downloader/power_client.go
- dfget/core/helper/test_helper.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_test.go
- dfget/core/uploader/uploader_util.go
- dfget/core/uploader/uploader_util_test.go
- dfget/errors/errors.go
- dfget/types/pull_piece_task_response.go
- dfget/util/http_util.go
- dfget/util/limit_reader.go
- dfget/util/rate_limiter.go
It's  an important feature to limit the download/upload speed for Dragonfly. More info about the advanced features about Dragonfly, please refer to [features](https://github.com/dragonflyoss/Dragonfly#features).
As you can see, dfget limits the speed with two parameters:
+ locallimit: rate limit about a single download task
+ totallimit: rate limit about the whole host
You can get more info about that [here](https://github.com/dragonflyoss/Dragonfly/blob/master/docs/cli_reference/dfget.md#options).
As for a download task, dfget will calculate the rate limit dynamically before download a piece from other peers **through the native uploader server**. Proceed as follows:
1. get locallimit
2. send a request to the **native uploader server** with: 
+ …
> feature: implement the rate limit feature

- dfget/core/downloader/p2p_downloader.go
- dfget/core/downloader/power_client.go
- dfget/types/pull_piece_task_response.go
- dfget/types/types_test.go
- dfget/util/log.go
- dfget/util/log_test.go
- src/supernode/src/main/resources/logback.xml
This pull request makes the log clearer and more readable.
**log of client**: only output first 4 chars of all log levels
* before
```
2019-01-29 17:23:57.693 WARNING sign:32351-1548753817.127 : has not available pieceTask,maybe resource lack
2019-01-29 17:23:57.695 INFO sign:32351-1548753817.127 : pull piece task result:{"code":602,"msg":"client sucCount:28,cdn status:RUNNING,cdn sucCount:28"} and sleep 1.313s
2019-01-29 17:23:58.019 ERROR sign:32351-1548753817.127 : download timeout(20.000s)
```
* after
```
2019-01-29 17:23:57.693 WARN sign:32351-1548753817.127 : has not available pieceTask,maybe resource lack
2019-01-29 17:23:57.695 INFO sign:32351-1548753817.127 : pull piece task result:{"code":602,"msg":"client sucCount:28,cdn …
```
> style: make log's output more clear and readable

- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/HttpClientUtil.java
* increase read timeout to 2 seconds
* not expire if get response from remote server timeout
> fix: optimize the judgment of local cache expiration

- dfdaemon/initializer/initializer.go
When the size of dfdaemon.log file large than 20M, the size of log file will continuous growth up.
Use Mmap to copy the file which need be truncated.
fix https://github.com/dragonflyoss/Dragonfly/issues/364
Run this pr in my local machine, when dfdaemon.log large than 20M, truncated it into 10M successfully.
/cc @lowzj 
/cc @allencloud
> bugfix: fix rotating log makes dfdaemon.log file huge size

- client/client_mock_test.go
- client/preheat_info_test.go
- hack/env.sh
- hack/unit-test.sh
Unit test for API client is very essential for dragonfly. We should guarantee the quality of golang SDK.
This PR adds : 
* mock test for api client
* preheat API mock test
And Dragonfly community encourages everyone to finish the golang SDK of dragonfly's supernode's API and finish the mock test for client as well.
This fixes one part of https://github.com/dragonflyoss/Dragonfly/issues/366.
added
```
Running tool: /usr/local/go/bin/go test -timeout 30s github.com/dragonflyoss/Dragonfly/client -run ^(TestSystemInfoError)$
ok  	github.com/dragonflyoss/Dragonfly/client	0.103s
Success: Tests passed.
```
and 
```
Running tool: /usr/local/go/bin/go test -timeout 30s github.com/dragonflyoss/Dragonfly/client -run ^(TestPreheatInfo)$
ok …
```
> test: add mock test for api client and preheat API mock test

- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- cmd/dfget/app/server.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/core/core.go
- dfget/core/core_test.go
- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/downloader.go
- dfget/core/downloader/downloader_test.go
- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/downloader/p2p_downloader/target_writer.go
- dfget/core/helper/test_helper.go
- dfget/core/regist/register.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_util.go
- dfget/util/log.go
In the component of dfget, the Logger is regarded one field of the configuration, and it will be transferred to other places where logger recording is needed.
Since when dfget process is started to the status of its exit, the log configuration will not change, then I think we can directly use the default `logrus.Logger` in pkg `logrus`. And we only need to configure the default logger's LogLevel, Formatter and Output via:
* logrus.SetOutput()
* logrus.SetLevel()
* logrus.SetFormatter()
no, just refactoring
no 
no
none
> refactor: directly config logrus' default Logger rather than create a new one

- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- dfget/config/config.go
When user uses dragonfly, no matter dfget, dfdaemon or supernode, I think the readability of command line instruction is very important.
In this PR, I make cli of dfget more readable
none
no need
no need
none
> feature: make cli of dfget more readable

- client/ping.go
- client/ping_test.go
add ping impelmentation in sdk and add mock test
this fixes one part of https://github.com/dragonflyoss/Dragonfly/issues/366
added mock test
```
Running tool: /usr/local/go/bin/go test -timeout 30s github.com/dragonflyoss/Dragonfly/client -run ^(TestPing)$
ok  	github.com/dragonflyoss/Dragonfly/client	0.063s
Success: Tests passed.
```
none
> feature: add ping impelmentation in sdk and add mock test

- dfget/core/api/uploader_api.go
- dfget/core/helper/test_helper.go
- dfget/core/uploader/peer_server.go
- dfget/core/uploader/peer_server_test.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_helper_test.go
- dfget/core/uploader/uploader_test.go
- dfget/core/uploader/uploader_util.go
- dfget/core/uploader/uploader_util_test.go
- dfget/util/limit_reader.go
When peer server passively exists, such as killed by people or other processes, it doesn't tell supernode that it has been down. So `supernode` will also schedules the down peer to other `dfget` who is downloading the same file. This will cause that downloading `dfget` failed to download from the down peer and retries to other peers serval times.
Here is some logs:
```
2019-02-03 13:57:52.228 DEBU sign:4456-1549173472.085 : pieces to be processed:[{"range":"0-4194303","pieceNum":0,"pieceSize":4194304,"pieceMd5":"6f4783b83c95b697da36ff912a6fa7bf:25681","cid":"127.0.0.1-3895-1549172876.386","peerIp":"127.0.0.1","peerPort":1234,"path":"/peer/file/b.test-3895-1549172876.386","downLink":20480}]
2019-02-03 13:57:52.229 DEBU sign:4456-1549173472.085 : …
```
> feature: report peer server down when it passively exits

- Makefile
- hack/build-client.sh
- hack/generate-docs.sh
Signed-off-by: fengzixu <hnustphoenix@gmail.com>
1. add 'docs' target in Makefile to generate API/CLI docs easily.
fixed: #375 
just makefile
I run the command as below:
```
make build
cd hack
./generate_docs.sh cli
./generate_docs.sh
```
```
make build
make docs
```
Thoes commands can help us generate CLI docs successfully.
> feature: add 'docs' target in Makefile to generate API/CLI docs easily

- cmd/dfget/app/root.go
update dfget commandline description to rm trailing spaces
I try to make every line of document are less than 80 chars.
none
no need
none
none
> docs: update dfget commandline description to rm trailing spaces

- dfget/core/core_test.go
- dfget/core/helper/test_helper.go
- dfget/core/uploader/peer_server_executor.go
- dfget/core/uploader/peer_server_executor_test.go
- dfget/core/uploader/uploader.go
- dfget/core/uploader/uploader_helper_test.go
- dfget/core/uploader/uploader_util_test.go
refactor `uploader.StartPeerServerProcess`:
* add interface `PeerServerExecutor` and an default implementation
* add unit-test for `peer_server_executor.go`
* fix: data race of function `readPort`
* fix: previous unit-test of `core` creates a temporary directory `dfget-CoreTestSuite-xxx` and don't delete it after testing.
one task of #352 : unit test of module uploader
> refactor: refactor and add unit-test for peer_server_executor.go

- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- cmd/dfget/app/version.go
- dfdaemon/initializer/initializer.go
- dflog/log.go
- dflog/log_test.go
move the file `log.go` from `dfget` to root path, all modules in Dragonfly use it to initialize log.
> log: unify project logs

- dfget/core/uploader/uploader_test.go
When submitting a new pull request, the unit-test-golang CI flow is always failed caused by `TestLaunchPeerServer`, following are error messages:
```bash
==================
WARNING: DATA RACE
Write at 0x00c4200ec500 by goroutine 119:
github.com/dragonflyoss/Dragonfly/dfget/core/helper.CreateConfig()
/go/src/github.com/dragonflyoss/Dragonfly/dfget/core/helper/test_helper.go:45 +0x32a
github.com/dragonflyoss/Dragonfly/dfget/core/uploader.createConfig()
/go/src/github.com/dragonflyoss/Dragonfly/dfget/core/uploader/uploader_test.go:258 +0x4e
github.com/dragonflyoss/Dragonfly/dfget/core/uploader.(*UploaderLaunchTestSuite).TestLaunchPeerServer()
/go/src/github.com/dragonflyoss/Dragonfly/dfget/core/uploader/uploader_test.go:94 +0x2c5
runtime.call32() …
```
> test: fix data race caused by TestLaunchPeerServer

- cmd/dfget/app/root.go
- dfget/config/config.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
The field of `ClientQueueSize` controls the number of pieces that can be processed simultaneously.
And this PR makes it to be configured either as a command line or as a configuration file and be passed to the p2p downloader.
None.
Add it in the integration test later.
Eg:
```
dfget -u "https://github.com/dragonflyoss/Dragonfly/releases/download/v0.2.1/df-client_0.2.1_linux_amd64.tar.gz" --clientqueue=6  -o /tmp/dfclient.tar.gz
```
> feature: make client queue size configurable

- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/uploader/peer_server.go
- dfget/core/uploader/peer_server_test.go
…cuted consecutively on the same machine
Bugfix: the speed will be slower and slower when multiple dfgets are executed consecutively on the same machine.
> fix:  the speed will be slower and slower when multiple dfgets are executed consecutively on the same machine

- cmd/dfdaemon/app/options/options.go
- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
- dfdaemon/global/global.go
- dfdaemon/handler/root_handler.go
- dfdaemon/handler/transport.go
- dfdaemon/initializer/initializer.go
- dfdaemon/muxconf/muxconf.go
- dfget/config/config.go
- dfget/config/constants.go
---
This pull request implements a way to support registries which use `https` schema in `dfdaemon`'s proxy pattern:
* configure docker daemon
* set `dfdaemon` host as `http_proxy`
* set your registry hosts as `insecure-registries`
* bypass proxy for your registry auth hosts
* `dfdaemon` get the http requests, change them to `https` schema and send https request to the real registries
fixes #205 
related #347 
Here's a example to pull images from a https registry(`registry.cn-hangzhou.aliyuncs.com`) by using proxy pattern:
* create dfdaemon's config file: `/etc/dragonfly/dfdaemon.yml`, and start `dfdaemon`
```yaml
registries:
- regx: "^registry.cn-hangzhou.aliyuncs.com$"
schema: https
host: registry.cn-hangzhou.aliyuncs.com
```
* change your …
> feature: dfdaemon supports proxing https registries

- hack/build-client.sh
- version/version.go
1. the version can be dynamically retrieved with git.
2. the previous BUILD ldflags seems not used.
> build: populate version with ldflags

- cmd/dfdaemon/app/options/options.go
- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
- dfdaemon/constant/constant.go
- dfdaemon/initializer/initializer.go
Dfdaemon doesn't exit when the default config file is not exist,  make it friendly for user.
> fix: don't exit when default config file is not exist

- docs/quick_start/README.md
- src/supernode/src/main/docker/Dockerfile
- src/supernode/src/main/docker/sources/start.sh
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/SupernodeProperties.java
Make it possible for users to set the supernode's ip that we advertiese to other peers in the p2p-network, the property is: `advertieseIp`
```bash
java -Dsupernode.advertieseIp=10.1.1.1 -jar supernode.jar
```
By default, the first non-loop address of the host is advertied.
fixes: #252
> fix: unreachable supernode ip in p2p-network

- common/constants/dfget_super_code.go
- dfget/config/constants.go
- dfget/core/api/supernode_api_test.go
- dfget/core/core.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/piece.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/helper/test_helper.go
- dfget/core/regist/register.go
- dfget/core/regist/register_test.go
- dfget/types/pull_piece_task_response.go
- dfget/types/types_test.go
In the process of dfget interacting with supernode, and both parties reached an agreement on the return code in order to better understand each other. So we should make codes as a public part.
For supernode, there are three kinds of status codes: 
+ the code from dfget: PeerTaskRequestResult, PeerTaskRequestStatus
+ the result code  returned to the dfget：ResultCode
+ the status information maintained in memory：PeerPieceStatus, PeerTaskStatus, CdnStatus, PreheatTaskStatus
And the code of `PeerTaskRequestResult` and `PeerTaskRequestStatus` from dfget will converted to the status of `PeerPieceStatus` and `PeerTaskStatus` by supernode.
<image width="480" height="550" src="https://user-images.githubusercontent.com/31209634/54409805-9aea8900-4723-11e9-9cc …
> refactor: extract the common const code to the common folder

- common/util/file_util.go
- common/util/stat_darwin_amd64.go
- common/util/stat_linux_amd64.go
- dfdaemon/initializer/initializer.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
- supernode/store/storage_driver.go
- supernode/store/store.go
- supernode/store/store_mgr.go
The supernode will use cdn to cache the files which downloaded from the source  web server. However, using local storage is not a one-size-fits-all approach. So we define an interface `StorageDriver` that defines all the storage  driver behavior to support different storage drivers.
In addition,  we may use multiple storage drivers for different contents at the same time. So there is a `Manager` to manage multiple storage drivers.
You can understand it easily according to the follow image:
And I have implement a local driver as a demo.
#139 
Added.
> feature: add storage driver for supernode

- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
- supernode/store/storage_driver.go
- supernode/store/store.go
1. Add a `context` parameter for the interface of storage driver which carries deadlines, cancelation signals, and other request-scoped values across API boundaries and between processes.
2. update the local storage implementation.
None.
None.
> bugfix: add context for the interface of storage driver

- apis/swagger.yml
- apis/types/peer_info.go
- common/util/assert.go
- common/util/assert_test.go
- supernode/daemon/daemon.go
- supernode/daemon/mgr/filter.go
- supernode/daemon/mgr/filter_test.go
- supernode/daemon/mgr/peer_mgr.go
- supernode/daemon/mgr/peer_mgr_test.go
- supernode/daemon/mgr/store.go
- supernode/daemon/mgr/store_test.go
- supernode/errors/errors.go
- supernode/result/result_info.go
- supernode/server/peer_bridge.go
- supernode/server/router.go
- supernode/server/server.go
1. Implement the interface of `PeerMgr` with `PeerManager`.
2. Add peer-related routers and implement the `peer_bridge`.
fixes part of  #348
Added.
```
go build -o supernode
./supernode --port 8005
{"ID":"starnop-192.168.11.11-1553516098232891068"}
{"ID":"starnop11-192.168.11.11-1553516102853466652"}
[{"ID":"starnop-192.168.11.11-1553516098232891068","IP":"192.168.11.11","created":"2019-03-25T12:14:58.232Z","hostName":"starnop","port":16345,"version":"v0.3.0"},{"ID":"starnop11-192.168.11.11-1553516102853466652","IP":"192.168.11.11","created":"2019-03-25T12:15:02.853Z","hostName":"starnop11","port":16345,"version":"v0.3.0"}]
{"ID":"starnop11-192.168.11.11-1553516102853466652","IP":"192.168.11.11","created":"2019-03-25T12:15:02.853Z","hostName":"starn …
```
> feature: implement the peer mgr

- cmd/dfdaemon/app/options/options.go
- dfdaemon/downloader/dfget/dfget.go
- dfdaemon/global/global.go
- dfdaemon/handler/transport.go
- dfdaemon/initializer/initializer.go
Add a `super-nodes` flag for dfdaemon.
The reason to do this is that we can only configure the supernode which used by dfget through the configuration file(`/etc/dragonfly.conf` in default). It may be more convenient  in the test environment or the scenario that someone who just want to have a try with dragonfly quickly.
None.
None.
1. Start dfdaemon with `dfdaemon --super-nodes 127.0.0.1,192.168.33.12 --registry https://index.docker.io`.
NOTE: set your own supernode IP.
2. Configure Docker Daemon.
3. Use docker client to pull a test image: `docker pull busybox:latest`.
4. Check the logs with `grep "do register to" ~/.small-dragonfly/logs/dfclient.log`
If the output of command above has content like
```
2019-04-03 08:44:01.377 INFO …
```
> feature: make supernode configurable for dfget with dfdaemon

- dfget/config/config.go
fix the comments mistake of the filed `ConfigFiles` of dfget.
None.
None.
> comments: update the comments of ConfigFiles of dfget

- cmd/dfget/app/root.go
- dfget/config/config.go
- dfget/config/constants.go
- docs/quick_start/README.md
- docs/user_guide/install_client.md
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/Constants.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/config/SupernodeProperties.java
add config and cli parameter `disableCDN` to make supernode's CDN feature optional.
related: #356
> feature: add config to disable cdn feature

- dfget/config/config.go
- dfget/core/downloader/p2p_downloader/client_writer.go
> dfget/config/config.go: Fix typo in comment

- common/errors/errors.go
- common/errors/supernode_errors.go
- supernode/daemon/mgr/progress/progress_manager.go
- supernode/daemon/mgr/progress/progress_manager_test.go
- supernode/daemon/mgr/progress/progress_state.go
- supernode/daemon/mgr/progress/progress_util.go
- supernode/daemon/mgr/progress/progress_util_test.go
- supernode/daemon/mgr/progress_mgr.go
For `ProgreeMgr`, it will maintain the correspondence between the peers and pieces as follows:
+ ClientID->PieceNums
+ PieceNum->PeerIDs
**NOTE:**
+ A `ClientID` corresponds to a unique peer and task.
+ A `PieceNum`  corresponds to a unique piece.
+ A `PeerID` corresponds to a unique peer node.
And the information should be readable and writable. So I updated the get and delete interfaces as follows:
```
// GetPieceProgressByCID get all pieces progress with specified clientID.
// And the pieceStatus should be one of the `PieceRunning`,`PieceSuccess` and `PieceAvailable`.
GetPieceProgressByCID(ctx context.Context, taskID, clientID, pieceStatus string) (pieceNums []int, err error)
// DeletePieceProgressByCID delete the pieces progress with specified …
```
> feature: implement the progress mgr for get/delete info

- common/errors/errors.go
- common/errors/supernode_errors.go
- supernode/config/constants.go
- supernode/daemon/mgr/scheduler/manager.go
- supernode/daemon/mgr/scheduler/manager_test.go
Implement the interface of `scheduler_mgr`. For the default implementation of `scheduler_mgr`, and `dragonfly` use the following scheduling steps:
1. get available pieces which except that have been downloaded or being downloaded.
2. sort the pieces by distributedCount in the p2p network.
3. sort the pieces by the distance to the pieces that are running.
4. select an appropriate peer node for each piece in order until the PeerDownLimit(in default 4) is reached 
+ use supernode directly when the src peer node has failed to download from other peer nodes for multiple times which up to FailCountLimit(in default 5)
+ exclude the peer nodes that have been offline
+ exclude the peer nodes that have failed to provide services for EliminationLimit(in …
> feature: implement the scheculer mgr

- apis/swagger.yml
- apis/types/task_info.go
A task not only maintains the source file size,  but also maintains a total file size after handled into pieces. 
In fact, The existing field `fileLength` indicates that the total file size after handled into pieces. So I add a filed named `httpFileLength` to maintain the source file size.
None.
None.
> feature: add httpFileLength field for taskInfo

- README.md
The Linux Foundation (LF) Core Infrastructure Initiative (CII) Best Practices badge is a way for Free/Libre and Open Source Software (FLOSS) projects to show that they follow best practices. Projects can voluntarily self-certify, at no cost, by using this web application to explain how they follow each best practice. The CII Best Practices Badge is inspired by the many badges available to projects on GitHub. Consumers of the badge can quickly assess which FLOSS projects are following best practices and as a result are more likely to produce higher-quality secure software.
CNCF tries to add CII for hosted project to guarantee the qualify of it. This PR adds CII badge support for Dragonfly. And we need to make it polished as the time …
> docs: add CII for project to add CII Best Practices Badge

- supernode/store/errors.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
- supernode/store/storage_driver.go
- supernode/store/store.go
This pull request fixes the following problems:
1. Return an `io.Reader` instead of passing in an `io.Writer` for the `Get` interface of `StorageDriver`.
2. Unify the type of error.
3. Add a global lock for the operation of remove file.
4. Return directly when the `Raw` is nil. Otherwise it will trigger panic.
For the first item in the list, I need to make some explanations.
If we passing a `io.Writer`, the storage will copy the data from the storage to the writer whether the data in the writer has been taken out. And if not, it will take up a lot of physical memory. I try to use `io.Pipe` to solve this problem. 
According to the docs, the `io.Pipe` creates a synchronous in-memory pipe.  And each Write to the PipeWriter blocks until it has …
> bugfix: update the implementation of local storage

- cmd/supernode/app/root.go
- supernode/config/config.go
- supernode/daemon/daemon.go
Add supernode info as the config of supernode daemon, and register the supernode as a peer before starting the daemon server.
None.
None.
> feature: register the supernode as a peer before starting the server

- supernode/store/errors.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
- supernode/store/store.go
For the local storage driver, there are three variables that determine the path to the storage file.
+ baseDir: the root dir of the storage
+ bucket: the sub dir of one file
+ key: the file name
When the caller put something to the storage, and the storage should create the dir If the parent directory of the file isn't exist,
None.
Updated.
> feature: use bucket as the parent sub dir of key

- .gitignore
- Makefile
- cmd/dfdaemon/app/root.go
- dfdaemon/config/config.go
- dfdaemon/handler/transport.go
- dfdaemon/proxy/proxy.go
- dfdaemon/proxy/proxy_test.go
Signed-off-by: inoc603 <inoc603@gmail.com>
Hijack https requests with self-signed certificates to enable the proxy to speed up https requests with dfget.
Users have to explicitly configure a registry in `insecure-registries` as well as in the new `hijack_https` configuration field introduced in this pr, to make this work. Other https requests will be tunneled directly as before.
I'll add some mock tests for https later
We can verify it with any docker mirror from aliyun like `xxx.mirror.aliyuncs.com` (replace this with a valid one).
`/etc/dragonfly/dfdaemon.yml`:
```yaml
proxies:
- regx: blobs/sha256
hijack_https:
cert: df.crt
key: df.key
hosts:
- regx: mirror.aliyuncs.com
```
Start dfdaemon with verbose logging:
```
dfdaemon --verbose
```
Then start or restart docker with these settings: …
> [feature] hijack https requests with self-signed certificates

- dfdaemon/config/config.go
- dfdaemon/proxy/proxy.go
- docs/user_guide/proxy.md
Signed-off-by: cd1989 <chende@caicloud.io>
- InsecureSkipVerify when no certs configured for HTTPS proxied host
- Update docs for example regex `blob/sha256/.*` --> `blobs/sha256:.*`
> Configure InsecureSkipVerify for proxied https host

- supernode/daemon/mgr/dfget_task_mgr.go
- supernode/daemon/mgr/dfgettask/manager.go
- supernode/daemon/mgr/mock/mock_dfget_task_mgr.go
In the go version, we introduce a peerID field which identifies a peer node and use cid identifies a downloading task. The relationship between them is as follows:
+ a cid one-to-one the combination of peerID and taskID
+ a peerID one-to-one the combination of cID and taskID
And this PR is submitted in order to get a unique cid via peerID and taskID.
None
None.
> feaeture: add function GetCIDByPeerIDAndTaskID for dfgetTask

- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/back_downloader/back_downloader_test.go
When the response code is greater or equals 400, it means that there's something wrong, so `BackDownloader` shouldn't download the file.
merge to branch `master` and `0.3.x`.
fixes: #544
> fix: BackDownloader only download file when response is less than 400

- common/constants/dfget_super_code.go
> bugfix: update the response code number

- supernode/store/local_storage_test.go
- supernode/store/store_mgr.go
* the manager of every plugin module has the responsibility to return the default implementation
* store manager returns the `localStorage` as its default implementation
> feature: store mgr return localStorage as default StorageDriver

- cmd/supernode/app/root.go
- supernode/config/config.go
- supernode/daemon/daemon.go
Supernode will listen on two ports:
+ The register port (default: 8002) 
+ The download port (default: 8001)
The register port is used for clients to register their own information into supernode.
The download port is used for clients to download pieces from supernode.
And we currently lack of the download port flag.
None.
None.
> feature: add download port flag

- common/util/limit_reader.go
- supernode/daemon/mgr/cdn/downloader_test.go
- supernode/daemon/mgr/cdn/manager.go
> bugfix: use a public limiter for cdn manager

- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/cdn/super_writer.go
- supernode/daemon/mgr/cdn/super_writer_test.go
- supernode/daemon/mgr/progress/progress_util.go
Now the writer will calculate the file Length dynamically which includes the piece header and piece tailer. However, we will use httpFileLength which is the length of the file contents to check whether file length matches the expected.
None.
None.
> bugfix: calculate realHTTPFileLength which is different realFileLength

- docs/design/design.md
fix typo: suernode -> supernode
> fix typo: suernode -> supernode

- supernode/store/local_storage.go
> feature: use util.LockerPool instead of local storage locker

- supernode/daemon/mgr/cdn/cdn_util.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/cdn/reporter.go
The `cdn_manger` should update the cdn status to failed when it  failed to get resources from url. Otherwise, `supernode` will keep returning peer_wait error until timeout.
> feature: return updateTaskInfo with cdnStatusFailed when http download gets errors

- supernode/config/global_variable.go
The store mgr set baseDir with prefix “repo” as the baseDir of local storage. In fact, it should be configured by the user. So I delete the prefix "repo".
> feature: delete the repo prefix for download home path

- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/Constants.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/domain/ClientErrorInfo.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/enumeration/ClientErrorType.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/ExecutorsUtil.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/common/util/RangeParseUtil.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/rest/controller/PeerController.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/cdn/util/PathUtil.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/impl/PeerRegistryServiceImpl.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/lock/LockService.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/BaseClientErrorHandler.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/ClientErrorHandleService.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/ClientErrorHandleServiceImpl.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/ClientErrorHandler.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/FileMd5NotMatchHandler.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/repair/FileNotExistHandler.java
- src/supernode/src/main/java/com/dragonflyoss/dragonfly/supernode/service/timer/DataGcService.java
dfget reports downloading errors to supernode, supernode checks and repairs local data automatically, currently repair these client errors:
* `FILE_NOT_EXIST`
* `FILE_MD5_NOT_MATCH`
add a new api into supernode to delete the task's data manually if any error occurred
```
DELETE /peer/tasks/{taskId}
```
client-side pr: #583 
> merge into branch `master` and `0.3.x`
fixes #545 
fixes #311 
fixes #68
> feature: handle client error and repair

- cmd/dfget/app/root.go
- dfget/config/constants.go
- dfget/core/api/supernode_api.go
- dfget/core/core.go
- dfget/core/regist/register.go
- dfget/util/net_util.go
- dfget/util/net_util_test.go
- test/cli_dfget_p2p_test.go
- test/command/cmd.go
- test/environment/env.go
related pr: #586 
backport to branch `0.3.x`
> feature: parse the port of supernode from --node flag of dfget

- apis/swagger.yml
- apis/types/task_register_request.go
- common/util/net_util.go
- common/util/net_util_test.go
- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/downloader.go
- dfget/core/downloader/downloader_test.go
- supernode/server/0.3_bridge.go
> feature: update task register header to slice not map

- supernode/daemon/mgr/cdn/cache_detector.go
- supernode/daemon/mgr/cdn/super_writer.go
- supernode/daemon/mgr/cdn_mgr.go
- supernode/daemon/mgr/dfgettask/manager.go
- supernode/daemon/mgr/peer/manager.go
- supernode/daemon/mgr/scheduler/manager.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/daemon/util/store.go
- supernode/util/range_util.go
> fix some typos

- dfget/core/uploader/peer_server.go
- dfget/core/uploader/uploader.go
> feature: uploader will not automically exit when alivetime is set to <=0

- Dockerfile
- Dockerfile.supernode
- Makefile
- hack/docker-build.sh
- hack/install.sh
- hack/supernode-nginx.conf
- supernode/server/0.3_bridge.go
Add Dockerfile for supernode and use `make build && make install` instead of `go build` for either dfclient and supernode.
Update the `Makefile` and add a shell `docker-build.sh` , and then you can
+ use `make docker-build-dfclient DF_VERSION=$tag` to get a dfclient image
+ use `make docker-build-supernode DF_VERSION=$tag` to get a supernode image 
+ use `make docker-build DF_VERSION=$tag` to get them all
After you get a supernode image, then you can use docker run to start your supernode server
```
make docker-build-supernode DF_VERSION=0.4
docker run -d --name dfsupernode -p 8001:8001 -p 8002:8002 -v /home/admin/supernode:/home/admin/supernode supernode:0.4 --advertise-ip=127.0.0.1 --download-port=8001
```
fixes part of #206
> feature: add supernode Dockerfile

- supernode/daemon/mgr/cdn/file_meta_data.go
- supernode/daemon/mgr/cdn/file_meta_data_test.go
We store the piece md5s with json.Marsal(slice), and we will get piece md5 files like this
```
["803d361428809167be0719fec41e571b","4027139d441a8f58b5279148ce7d5edc","8451dcbc3e8b544049d911273d9fb22b","573fcda3bd0ead944600af51fb9fa756","7c927626b0c8f05afd07fd7f20b5cd27","f1fe2699daea7d24964794988b219181","43047f23461e00855695ceb159bdfa99","d37ce5323a523c5527df58748ae54d4f","497830f85e8a165bb85ef87a6be61f6d","bc4da60219956919de9bb06ab8b999d1","697611243967318765324df47e926ea1","1b06b3a3926741d2f85f8dd9542076bc","82975171731b83d9c82f491dffc5fd31ee40348a"]
```
It's unfriendly to read and most importantly, it's not compatible with the Java version which looks like this
```
b91e1c4ea54d7a0a4e91f8ed46e28fc6:4194304 …
```
> feature: store piece md5s with native bytes

- common/util/http_util.go
- common/util/net_util.go
- common/util/net_util_test.go
- supernode/daemon/mgr/cdn/cache_detector.go
- supernode/daemon/mgr/cdn/manager.go
> bugfix: parse the lastmodified header to timestamp

- common/util/http_util.go
- supernode/daemon/mgr/cdn/cache_detector.go
- supernode/daemon/mgr/cdn/downloader.go
- supernode/daemon/mgr/cdn/file_meta_data.go
- supernode/daemon/mgr/cdn/reporter.go
- supernode/daemon/mgr/cdn/super_reader.go
- supernode/daemon/mgr/progress/progress_manager.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/server/0.3_bridge.go
> log: reduce info logs of supernode

- common/util/http_util.go
- dfget/core/api/download_api.go
- dfget/core/downloader/back_downloader/back_downloader.go
- supernode/daemon/mgr/cdn/downloader.go
* change connection timeout from `30 seconds` to `3 seconds`
* use `GET` method instead of `HEAD` method to get `content-length`, check expiration and whether support range request. It's because that some servers may not support `HEAD` method.
* set the whole operation's timeout as `4 seconds`(including connection timeout)
> fix: send http request with timeout

- supernode/daemon/mgr/mock/mock_progress_mgr.go
- supernode/daemon/mgr/progress/progress_manager.go
- supernode/daemon/mgr/progress/progress_util.go
- supernode/daemon/mgr/progress_mgr.go
- supernode/daemon/mgr/scheduler/manager.go
> bugfix: update the client progress after success to schedule

- supernode/daemon/mgr/progress/progress_manager.go
- supernode/daemon/mgr/progress/progress_util.go
- supernode/daemon/mgr/progress_mgr.go
- supernode/daemon/mgr/scheduler/manager.go
> bugfix: increase load of the peer serving for others

- FAQ.md
- docs/user_guide/download_files.md
- docs/user_guide/install_client.md
> doc: update doc because update 0.3 to 0.4

- CONTRIBUTING.md
- README.md
Fix some typos and grammar issues after I passed through README and CONTRIBUTING doc.
> docs: fix some typos and grammar issue

- docs/design/design.md
I have modify some spell mistakes in the document
> docs:modify some spell mistakes in the document

- dfdaemon/proxy/proxy.go
- docs/user_guide/proxy.md
- dfclient set InsecureSkipVerify for https proxy.
- update docs for deprecated 65002 port
> Dfclient set InsecureSkipVerify for https proxy

- cmd/dfget/app/root.go
- dfget/config/config.go
- dfget/config/constants.go
- dfget/core/core.go
Signed-off-by: yizheng <yizheng@cs.unc.edu>
Implement minrate option for dfget when downloading a file. Use "-x" to specify minrate.
Re-implement func calculateTimeout() to use minrate.
> feature: implement minrate option for dfget when downloading a file

- FAQ.md
add a question and answer about the log's time
> docs:add a question and answer about the log's time

- docs/quick_start/README.md
Specify --node to make sure that dfget can access supernode container.
fix #643
> docs: add --node when starting dfclient container in quick_start docs

- cmd/dfget/app/root.go
- dfget/core/core.go
- dfget/core/uploader/peer_server_executor.go
At present, we can specify the uploader server port with command `dfget server --port`. However, you have to run `dfget server` to start a uploader server before using `dfget` to download. If you don't want to do that, and this PR will help you.
In the meantime, you can't specify the IP address of the uploader server as a peer and `dfget` will use the IP address which can success to connect to `supernode`  automatically before this PR. In fact, the address that can be connected to a supernode is not necessarily the address that can be accessed by other peer nodes.
And now, you can use command as follows to specify the ip and port of uploader server when you want to download a file with `dfget`:
`dfget -u  https://www.taobao.com --ip 192.168.33.21 …
> feature: enable uploader server ip and port to be specified

- cmd/dfget/app/root.go
- dfget/core/core.go
NOTE: The `rate-related-params` below means the  params `localLimit`, `minRate`,`totalLimit` and so on.
At present, we can configure `rate-related-params`  by cmd or config files. And we should try to trans the param value firstly which from cmd. If not, try to imagine a scene.
If you not specify the `rate-related-params` values , and then they will get the default values when init config. Immediately after that, we will try to parse the `rate-related-params` values specified by cmd. And then you will use the empty value to override the default value.
> bugfix: initProperties after trans the param

- dfdaemon/config/config.go
- dfdaemon/downloader/dfget/dfget.go
As title described.
None.
None.
Run dfdaemon with `--verbose` and you will get more logs.
> feature: pass the value of dfdaemon verbose flag to dfget

- cmd/supernode/app/root.go
- hack/build.sh
We have updated the go version to 1.12.6 and use go mod to manage the dependency. So we should set the `GO111MODULE` env to `on` when building with docker. Otherwise we would get errors like this：
```
apis/types/df_get_task.go:11:2: cannot find package "github.com/go-openapi/errors" in any of:
/usr/local/go/src/github.com/go-openapi/errors (from $GOROOT)
/go/src/github.com/go-openapi/errors (from $GOPATH)
apis/types/df_get_task.go:12:2: cannot find package "github.com/go-openapi/strfmt" in any of:
/usr/local/go/src/github.com/go-openapi/strfmt (from $GOROOT)
/go/src/github.com/go-openapi/strfmt (from $GOPATH)
apis/types/df_get_task.go:13:2: cannot find package "github.com/go-openapi/swag" in any of:
/usr/local/go/src/github.com/go-openapi/swag …
```
> bugfix: set GO111MODULE to on when use docker build

- common/util/stat_linux_arm.go
Add support for arm32. Recently, we can not build binary for arm32 unless we implement function `Atime`, `Ctime`, `AtimeSec` and `CtimeSec` for arm32.
NONE
No test needed because I only add support for a special architecture.
```shell
for i in dfdaemon dfget supernode; do
cd cmd/$i
GOOS=linux GOARCH=arm GOARM=7 go build
cd ../..
done
```
> Add support for arm32

- supernode/daemon/mgr/task/manager_util.go
fix typo "caculate" -> "calculate"
Signed-off-by: alan <zg.zhu@daocloud.io>
fix typo "caculate" -> "calculate"
NONE
> fix typo "caculate" -> "calculate"

- cmd/dfget/app/root.go
print help message when check parameter error
NONE
> print help message when check parameter error

- .circleci/config.yml
```bash
FILE: README.md
[✖] https://twitter.com/dragonfly_oss → Status: 0 Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://twitter.com/dragonfly_oss
ERROR: dead links found!
```
The failure is caused by some reason that we don't known(maybe a bug of `markdown-link-check`), but we can confirm that this link is ok and can be accessed successfully. So we ignore checking the urls of `twitter.com`.
> fix: markdown-link-check ignore twitter.com

- apis/swagger.yml
- apis/types/df_get_task.go
- apis/types/task_create_request.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/server/0.3_bridge.go
We must specify the supernode IP which can be connected by the peer node when we use dfget to download a file. However, the different peers have different network environments. And they will use different addresses to connect to the same supernode.  And for now, supernode will always return the IP address that will not change according to the peer node. That's not reasonable. 
So this PR will store the supernode IP which carried by dfget. When a peer download something from supernode, and the supernode will return the IP address that it specifies.
None.
None.
```
make build && make install
supernode 
https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/install_server_go.md#procedure---when-deploying-with-physical-machines
dfget -u …
```
> feature: return supernode ip according to the value specified by peer

- docs/README.md
fix typo 'deisgn' -> 'design'
Signed-off-by: alan <zg.zhu@daocloud.io>
fix typo 'deisgn' -> 'design'
NONE
> fix typo 'deisgn' -> 'design'

- common/util/file_util.go
Signed-off-by: dzzg <zhengguang.zhu@daocloud.io>
fix wrong spells in file_util.go
NONE
> fix wrong spells in file_util.go

- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/uploader/peer_server.go
- dfget/core/uploader/peer_server_test.go
- dfget/core/uploader/uploader_test.go
- supernode/daemon/mgr/cdn/cache_detector.go
- supernode/daemon/mgr/task/manager_util.go
Now we use file.ModTime() to determine whether the file is expired. However, we just read the file when we upload pieces to other files. And the `modTime` has not changed. So the file will be marked expired and will be deleted after expire time even though it is providing the server for the other peers.
So I added a `accessTime` field which should be updated when doing anything with the file.
None.
None.
> bugfix: use access time to determine whether the file is expired

- common/util/assert.go
- common/util/assert_test.go
- common/util/limit_reader.go
- common/util/rate_limiter.go
- common/util/rate_limiter_test.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/power_client_test.go
- dfget/core/uploader/peer_server.go
- dfget/core/uploader/uploader_helper_test.go
fix the overflow for rate limit
when use the function `createTokens` it may return negative number because of the overflow
The problem code is here `diff/(rl.window*time.Millisecond.Nanoseconds()) * rl.ratePerWindow`.
When `createTokens` return negative number it may cause sleep and it will make p2p download failed.
use int64 instead of int32 can solve this problem
> bugfix: fix overflow for rate limit

- FAQ.md
- apis/swagger.yml
- apis/types/task_register_request.go
- cmd/dfdaemon/app/root.go
- cmd/dfget/app/root.go
- hack/build.sh
- hack/install.sh
- hack/package.sh
- supernode/server/0.3_bridge.go
Make it work normally when specifies non-ipv4 format node address for dfclient.
#679
None.
BTW. update the shell scripts.
> feature: support non-ipv4 format node address for Dragonfly dfclient

- client/task_info.go
feature: add tasks info actions in client pkg of golang sdk
none
none
> feature: add tasks info actions in client pkg of golang sdk

- common/constants/dfget_super_code.go
- dfget/core/api/supernode_api.go
- dfget/core/api/supernode_api_test.go
- supernode/server/0.3_bridge.go
- First bug:when supernode send  response to dfget's reportpiece and servicedown request,it will return a nil response.So when the dfget do with the response with `json.Unmarshal(body, resp)` ,it will produce an `err unexpected end of JSON input` err.I add a status code info to the supernode's response to resolve these bugs and do with the err and status code
- Second bug:when dfget send pulltask request to supernode.if the supernode is off,the dfget will crash instead of find another supernode to finish its work.because the pulltask will retuen a `{}` instead of `nil`,the coder use `nil` to check the res,so it will happen `a invalid memory address or nil pointer dereference ` err .i make the return be nil when the supernode is off …
> bugfix: modify two supernode api's bug

- dfget/core/uploader/peer_server_executor.go
fix initiliazed => initialized
Signed-off-by: Guanqi Bing <guanqi.bing@daocloud.io>
> fix initiliazed => initialized

- supernode/server/0.3_bridge.go
Signed-off-by: wybzju <552044481@qq.com>
1 there have two supernode A and B
2 dfget registers to A and download some piece from A
3 suddenly, the A down
4 dfget will get error when pull piece task from A, then dfget register to node B
5 it will pull piece task again, but the item has dstCID. However, B doesn't have the task, and can't get dfgettask by dstCID and taskID. Then B will return err. Finally, dfget will receive error again
> bugfix: the dfget will always receive fail result when change supernode

- docs/design/design.md
Make the document more readable
None
> fix word `managered` to `managed`

- client/client.go
- common/errors/supernode_errors.go
- supernode/daemon/mgr/scheduler/manager.go
- test/main_test.go
fi a to an
Signed-off-by: sakura longfei.shang@daocloud.io
> fix a to an in annotation

- .gitignore
- common/util/sys_util.go
- supernode/daemon/mgr/cdn/cdn_util.go
- supernode/daemon/mgr/task/manager.go
- supernode/daemon/mgr/task_mgr.go
Add a accessTime for taskID to make it possible for GC. 
None.
None.
> feature: add access time for taskID

- common/util/net_util.go
- common/util/sync_map_util.go
- dfget/core/downloader/p2p_downloader/power_client_test.go
- dfget/core/regist/register.go
- supernode/config/config.go
Signed-off-by: Sakura <longf_shang@163.com>
fix some typos in comment
fix some typos
> fix some typos in comment

- cmd/dfdaemon/app/init.go
- supernode/server/0.3_bridge.go
Change some logs level from info to debug.
It is not user-friendly and is unreadable to output these for info-level logs.
``` bash
2019-08-02 00:10:11.530 INFO sign:2289 : success to register task &{CID:127.0.0.1-2335-1564675809.912 CallSystem:com_ops_dragonfly Dfdaemon:true Filter:[] Headers:map[Authorization:Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK2pDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXpzeVYwNVpPbFZMUzFJNlJFMUVVanBTU1U5Rk9reEhOa0U2UTFWWVZEcE5SbFZNT2tZelNFVTZOVkF5VlRwTFNqTkdPa05CTmxrNlNrbEVVVEFlRncweE9UQXhNVEl3TURJeU5EVmFGdzB5TURBeE1USXdNREl5TkRWYU1FWXhSREJDQmdOVkJBTVRPMUpMTkZNNlMwRkxVVHBEV0RWRk9rRTJSMVE2VTBwTVR6cFFNbEpMT2tOWlZVUTZTMEpEU0RwWFNVeE1Pa3hUU2xrNldscFFVVHBaVWxsRU1JSUJJakFOQmdrcWhraUc5dzB …
```
> move some log level to debug

- cmd/dfdaemon/app/root.go
- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
- dfdaemon/downloader/dfget/dfget.go
fixes part of #687
TODO.
```
cat /etc/dragonfly/dfdaemon.yml
global_dfget_params: ["--node","192.168.33.21","--verbose","--ip","192.168.33.22","--port","15001","--alivetime","0s","--expiretime","5m0s"]
......
```
In my opition,  I think it's not a good way to use CLI args to pass values to the dfget compared to the config file. So I have not added a flag for dfget params. @lowzj @yeya24 WDYT?
In this PR, I only add a `globalDfgetParams` through the dfdaemon config file firstly. And we can add a `dfgetParam` for every proxy later.
In addition, there is one more thing we need to pay attention to: how should we verify the correctness of the dfget params? Do you have any good ideas?
> feature: add golbal dfget params to the dfdaemon config

- FAQ.md
- docs/user_guide/download_files.md
modify the spelling errors in the docs
None
> docs: improve docs

- pkg/httputils/http_util.go
> http_util.go: fix word in error message

- docs/user_guide/multi_machines_deployment.md
Make the document more readable
None
> fix mis-spelling in multi_machines_deployment.md

- MAINTAINERS.md
@inoc603 has made outstanding contributions to the dfdaemon of Dragonfly. He almost refactored dfdaemon proxy scheme which make dfdaemon not only a proxy for docker, but also a proxy service for more services. And perfected the lack of dfdaemon in https proxy by the way.  
Now he is in new career of ByteDance. And he is still willing to contribute more to the maintenance of the community and the future development. 
With the trust @inoc603 built in the community, I proposed to add @inoc603 as a maintainer in Dragonfly project.
Also cc @lowzj @allencloud @zhouhaibing089 @garfield009 @chenchaobing 
NONE
NONE
NONE
NONE
> docs: add EddieHuang as a maintainer

- dfget/config/config.go
Make the document more readable
None
> fix wrong spells in config.go

- supernode/daemon/mgr/task/manager_util.go
When supernode failed to get file length from source which is slow to be accessed due to `context deadline exceeded`, we should not return error directly and tell the client failed to register the task.  Instead, we should make it success unless something goes wrong with 404, 401,407, etc.
None.
None.
> feature: not return error directly when failed to get http file Length

- test/README.md
Update indentation of comments, for ocd, especially awkward!
NONE
> Update indentation of comments

- dfget/core/downloader/p2p_downloader/p2p_downloader.go
Signed-off-by: wybzju <552044481@qq.com>
the case is:
1 the dfget pull piece task from supernode(for example, the total piece is two, pieceA, pieceB)
2 the dfget get two pieces and start to run download tasks
3 pieceB download successfully and put it into queue. pieceA is running 
4 so the function p2p.getItem can get one Item. Then try to pull task again
5 because the supernode have sent all pieces to dfget， dfget will receive waiting code, then sleep a moment and try to pull task again.
6 the pieceA download failed, and put it into queue, but it will never be dealt. And the step5 will run forever until timeout.
so if dfget receive the code waiting, it should judge the length of the queue. If the length is large than 0, it should break the cycle. Then the failed piece in the queue can be …
> bugfix: the dfget will wait forever when the final piece failed

- ROADMAP.md
The `Dragonfly` was written with a unified programming language now and it has entered a new stage. So we need to redefine the roadmap to do some new plan for Dragonfly.
None.
None.
> feature: update the roadmap for a new stage

- .circleci/config.yml
- .golangci.yml
- Makefile
- dfget/core/api/supernode_api.go
- dfget/core/api/supernode_api_test.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- hack/build.sh
- hack/golangci-lint.sh
Since gometaliner is deprecated, we need to migrate golangci-lint.
Ref: https://github.com/alecthomas/gometalinter
> feature: replace gometalinter with golangci-lint

- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/config/config_test.go
Dfget config field `help` and `version` is unused now, so remove them.
NONE
> cleanup some unused dfget config fields

- .circleci/config.yml
- Makefile
- hack/boilerplate-check.sh
- hack/boilerplate/check-boilerplate.go
- hack/check.sh
- supernode/daemon/mgr/gc/gc_dfget_task.go
- supernode/daemon/mgr/gc/gc_manager.go
- supernode/daemon/mgr/gc/gc_peer.go
- supernode/daemon/mgr/gc/gc_task.go
- supernode/daemon/mgr/gc_mgr.go
- supernode/daemon/mgr/progress/progress_delete.go
Feature: add code format check into circleci
1. add code boilerplate check as a circleci job
2. make `check-boilerplate.go` always exit with 0, so we can catch the output
3. fix gofmt check bug (ignore vendor)
make boilerplate-check
> Feature: add code boilerplate check into circleci

- cmd/dfdaemon/app/root.go
I config `supernodes` in /etc/dragonfly/dfdaemon.yml , but it does not work.
```
supernodes: 
- "172.16.38.93:8002"
```
I use `node` instead of `supernodes` , and it works.
In fact, `RegisterAlias` after reading config from file may solve this problem?
None
> bugfix: dfdaemon's config supernodes as an alias do not work.

- cmd/dfdaemon/app/version.go
- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- cmd/dfget/app/server.go
- cmd/dfget/app/version.go
- cmd/supernode/app/version.go
- dfget/core/core.go
- dfget/core/downloader/back_downloader/back_downloader.go
make dfget output clear
fixes #817 
now the out  put is
```
--2019-08-22 19:28:46--  https://dl.google.com/go/go1.12.7.src.tar.gz
dfget version:
workspace:10156-1566473326.503
sign:10156-1566473326.503
client:127.0.0.1 connected to node:127.0.1.0:8002
start download by dragonfly...
download SUCCESS !
cost:3.333s length:21976647
--2019-08-22 19:28:08--  https://dl.google.com/go/go1.12.7.src.tar.gz
dfget version:
workspace:7650-1566473288.932
sign:7650-1566473288.932
download FAIL(1104)
cost:0.142s length:-1
reason:1001
error:{"Code":1104,"Msg":"download fail and not back source: 1001"}
exit status 80
```
> bugfix:modify dfget output

- cmd/dfget/app/root.go
See PR https://github.com/dragonflyoss/Dragonfly/pull/859 and its ci https://circleci.com/gh/dragonflyoss/Dragonfly/10456?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link failed because of the example has trailing space here. So remove it.
NONE
> chore: remove trailing spaces in dfget example

- supernode/config/config.go
- supernode/daemon/mgr/mock/mock_progress_mgr.go
- supernode/daemon/mgr/progress/progress_delete.go
- supernode/daemon/mgr/progress/progress_manager.go
- supernode/daemon/mgr/progress/progress_state.go
- supernode/daemon/mgr/progress/state_sync_map.go
- supernode/daemon/mgr/progress/superload_manager.go
- supernode/daemon/mgr/progress_mgr.go
- supernode/daemon/mgr/scheduler/manager.go
- supernode/daemon/mgr/task/manager.go
- supernode/daemon/mgr/task/manager_util.go
When dragonfly begin to distribute a new file, a large number of download requests will be dispatched to the supernode node because there are no nodes in the current P2P network owns the file. Then the load of supernode will become heavier and heavier. According to the test, sometimes one peer will cost almost 2 minutes to download a piece which is only 4M from supernode(NOTE: the network bandwidth is enough).  In order to avoid this, we should add a limit which only allows a limited number of downloads from supernode for one task at the same time. And then the others will download the piece form the peers which have downloaded from the supernode. 
This will greatly reduce the load of the supernode.
None.
None.
> feature: limit the number which download from supernode for one task

- supernode/store/local_storage.go
I found that if set OpenFile flag `os.O_SYNC`, supernode writes piece files to local disk with low efficiency.
I removed this flag, then writing process was obviously speed up.
None
I download a 300+M size image layer in the same machine,  and compare the efficiency when set and unset 
`os.O_SYNC` flag. 
I filter the critical logs with timestamp as below:
set `os.O_SYNC`
```
2019-09-05 20:24:01.102 DEBU sign:12542 : send the protocolContent taskID: d577b0c6f739dabcf101dd6733a16916126f1cef89418f0b72c10b48c18dcdf3 pieceNum: 0
2019-09-05 20:24:01.226 DEBU sign:12542 : send the protocolContent taskID: d577b0c6f739dabcf101dd6733a16916126f1cef89418f0b72c10b48c18dcdf3 pieceNum: 1
2019-09-05 20:24:01.371 DEBU sign:12542 : send the …
```
> delete os.O_SYNC flag when supernode write piece to local

- docs/user_guide/metrics.md
- supernode/daemon/mgr/cdn/downloader_test.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/task/manager.go
- supernode/server/server.go
We already have a metric call `dragonfly_supernode_trigger_cdn_total` to represent the total times of cdn triggering. However this metric cannot represent the total times of downloading by cdn because supernode cdn has cache. So add three metrics in this PR to represent the downloading process and cache hit times.
NONE
> feature: add some cdn metrics

- cmd/supernode/app/root.go
add gc cli config
fixes #884 
```
Usage:
Dragonfly Supernode [flags]
Dragonfly [command]
Available Commands:
help        Help about any command
version     Show the current version of supernode
Flags:
--advertise-ip string             the supernode ip that we advertise to other peer in the p2p-network
--config string                   the path of supernode's configuration file (default "/etc/dragonfly/supernode.yml")
-D, --debug                           Switch daemon log level to DEBUG mode
--down-limit int                  download limit for supernode to serve download tasks (default 5)
--download-path string            specifies the path where to store downloaded filed from source address (default …
```
> feature: add gc cli config

- docs/user_guide/metrics.md
- supernode/server/0.3_bridge.go
- supernode/server/metrics.go
- supernode/util/range_util.go
- supernode/util/range_util_test.go
Add a counter type metric to count total size of pieces downloaded from supernode by dfget.
NONE
> feature: add supernode piece downloaded size metrics

- supernode/daemon/mgr/gc/gc_peer.go
fixes:#904
run supernode and dfget
take some minutes gc over
```
2019-09-14 13:35:55.942 DEBU sign:6860 : start to update progress taskID (9f5a8cf450054274c79a485a0fdc75fbc2ec8bfef743620109c464754ab42660) srcCID (127.0.0.1-7560-1568439354.843) srcPID (buaa-127.0.0.1-1568439354844787684) dstPID (buaa-127.0.0.1-1568439352517033339) pieceNum (2) pieceStatus (-3)
2019-09-14 13:35:55.942 DEBU sign:6860 : success to update ClientProgress taskID(9f5a8cf450054274c79a485a0fdc75fbc2ec8bfef743620109c464754ab42660) srcCID(127.0.0.1-7560-1568439354.843) dstPID(buaa-127.0.0.1-1568439352517033339) pieceNum(2) pieceStatus(-3) with result: false
2019-09-14 13:35:55.942 DEBU sign:6860 : taskID(9f5a8cf450054274c79a485a0fdc75fbc2ec8bfef743620109c464754ab4 …
```
> bugfix:fix the gc time 

- go.mod
- go.sum
- supernode/server/0.3_bridge.go
We have refactored the dragonfly with golang. And we should make supernode compatible with  every version of dfget to make it possible to seamlessly migrate dragonfly to the latest version.
Recommended migration plan:
1. upgrade your supernode to the latest version
2. upgrade the dfclient constantly and supernode can support both old and new versions of dfclient
None.
None.
> feature: make supernode compatible with the 0.2.x dfget

- cmd/dfdaemon/app/init.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- pkg/dflog/log.go
> log: not rotate log file when startup

- test/cli_dfget_p2p_test.go
add err handling in test
NONE
maybe need test
> test: add err handling in test

- supernode/config/config.go
- supernode/config/constants.go
- supernode/daemon/mgr/scheduler/manager.go
Replace literal values when initial supernode's base properties.
`FailureCountLimit` config item does not work now, fix it in this pr.
> feature: use constant value to replace literals in supernode config.

- supernode/daemon/mgr/gc/gc_dfget_task.go
- supernode/daemon/mgr/gc/gc_peer.go
fixes #886 
set  
```
func (s *Server) reportServiceDown(ctx context.Context, rw http.ResponseWriter, req *http.Request) (err error) {
return nil
params := req.URL.Query()
taskID := params.Get("taskId")
cID := params.Get("cid")
// get peerID according to the CID and taskID
dfgetTask, err := s.DfgetTaskMgr.Get(ctx, cID, taskID)
if err != nil {
return err
}
s.ProgressMgr.UpdatePeerServiceDown(ctx, dfgetTask.PeerID)
return EncodeResponse(rw, http.StatusOK, &types.ResultInfo{
Code: constants.CodeGetPeerDown,
})
}
```
to make server down fail,and start some dfgets.wait some minutes and long  at the supernode log to see gc result
```
dstPID(buaa-127.0.0.1-1568789107329775876) pieceNum(0) pieceStatus(1)
2019-09-18 14:45:23.087 DEBU …
```
> bugfix:gc peer failing to server down

- cmd/supernode/app/options.go
- dfdaemon/config/config.go
- dfdaemon/constant/constant.go
- dfdaemon/proxy/proxy.go
- dfdaemon/server.go
- dfdaemon/transport/transport.go
Adjust the word order of comments.
NONE
Don't need.
> Adjust the word order of comments

- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
The tls config in registry_mirror should save to dfget config.Otherwise, it doesn't work.
#928
> bugfix: paas registry mirror tls config into dfget config.

- cmd/dfdaemon/app/root.go
- cmd/dfdaemon/app/root_test.go
Signed-off-by: inoc603 <inoc603@gmail.com>
Remove `viper.RegisterAlias("supernodes", "node")`, and set the value by hand.
fixes #900 
create a simple `dfdaemon.yml`:
```yaml
supernodes:
- 127.0.0.1:6666
```
First use the config file only:
```bash
dfdaemon --config dfdaemon.yml
```
Look for this line in log:
```
use supernodes: 127.0.0.1:6666
```
Then use the `--node` flag
```bash
dfdaemon --config dfdaemon.yml --node 127.0.0.1:7777 --node 127.0.0.1:7778
```
And check the cli flag overrides the config file:
```
use supernodes: 127.0.0.1:7777,127.0.0.1:7778
```
> fix: ineffective viper alias

- docs/user_guide/metrics.md
Signed-off-by: SataQiu <qiushida@beyondcent.com>
docs: update the metrics as a table
> docs: update the metrics as a table

- .gitignore
- version/version.go
add some punctuation in version and .gitignore
NONE
> fix(version) : add some punctuation

- docs/user_guide/metrics.md
- supernode/config/config.go
- supernode/daemon/mgr/gc/gc_disk.go
- supernode/daemon/mgr/gc/gc_manager.go
Add metrics about disk gc
Fixes #958 
I think we should consider opening a new PR for the whole tests of supernode gc.
> feature: add gc disks metrics

- supernode/daemon/mgr/cdn/cache_detector.go
- supernode/daemon/mgr/cdn/cdn_gc.go
- supernode/store/local_storage.go
…me dir not exist
At present, gc disk will produce error logs continuously when download home dir not exist. And in this case, there is no need to do the gc job. So just return  directly in this PR.
NONE.
> bugfix: reduce error logs when download home dir not exist

- pkg/util/assert.go
- supernode/daemon/mgr/cdn/cdn_gc.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/cdn/reporter.go
cleanup code based on static check warning
NONE
> pkg, supernode: cleanup code based on static check warning

- supernode/config/config_test.go
fix(supernode/config): add error handling
Ref: #952
> fix(supernode/config): add error handling

- FAQ.md
too many questions about this in dingding group
> docs:add FAQ.md abot how dfget connect to supernodes in mul-supernode mode

- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- cmd/supernode/app/root.go
- cmd/supernode/app/root_test.go
fixes #908 
supernode:
```
yunfeiyang@buaa:~/go/src/github.com/dragonflyoss/Dragonfly/cmd/supernode$ sudo go run main.go -h
Usage:
Dragonfly Supernode [flags]
Dragonfly [command]
Available Commands:
help        Help about any command
version     Show the current version of supernode
Flags:
--advertise-ip string             the supernode ip is the ip we advertise to other peers in the p2p-network
--config string                   the path of supernode's configuration file (default "/etc/dragonfly/supernode.yml")
-D, --debug                           switch daemon log level to DEBUG mode
--down-limit int                  download limit for supernode to serve download tasks (default 5)
--download-path string            download path …
```
> feature:make cli better

- .circleci/config.yml
- .travis.yml
> update pouchlinter to 0.2.4

- cmd/supernode/app/root.go
we can't config debug mod and homedir in yaml file because init config after init log and use option to config the log instead of cfg
the yaml file is 
```
base:
listenPort: 9002
downloadPort: 9001
advertiseIP: 102.168.50.156
failAccessInterval: 2m0s
gcInitialDelay: 3s
gcMetaInterval: 10m0s
taskExpireTime: 2m0s
peerGCDelay: 100m0s
gcDiskInterval: 120s
debug: true
```
the command is 
`sudo go run main.go  --config  /home/yunfeiyang/yml/supernode.yml  --port  8090  --advertise-ip 127.0.0.2`
the config result is 
```
2019-10-10 15:35:44.417 DEBU sign:16151 : get supernode config: base:
listenPort: 8090
downloadPort: 9001
homeDir: /home/admin/supernode
schedulerCorePoolSize: 10
downloadPath: /home/admin/supernode/repo/download …
```
> bugfix:fix debug mod and homedir config in yaml

- cmd/dfdaemon/app/root.go
- cmd/dfdaemon/app/root_test.go
- dfdaemon/downloader/dfget/dfget.go
Somebody will define the dfget configuration by using dfget config file which locates at `/etc/dragonfly/dfget.yml`. And then they will feel confused about why dfget don't use the supernodes that I defined in the dfget config file. In fact, dfdaemon will specify a default value for supernodes and dfdaemon call the dfget by using cmd flags. So the default value defined by dfdaemon will override the dfget config. So I think we should delete the default value for supernode specified by dfdaemon.
NONE.
No need.
1. config the nodes in the dfget config file and neither define the nodes through the configuration file nor through cli flags for dfdaemon
2. start to pull a file by dfdaemon
> bugfix: delete the default value for supernodes from dfdaemon

- dfget/core/core.go
bug fix dfget client timeout set error when fileLength is 0
bug fix dfget client timeout set error when fileLength is 0
use dfget and set timeout
> bug fix dfget client timeout set error when fileLength is 0

- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/config/constants.go
- dfget/config/supernode_value.go
- dfget/config/supernode_value_test.go
- docs/config/dfget_config_template.yml
- docs/config/dfget_properties.md
- pkg/algorithm/algorithm.go
- pkg/algorithm/algorithm_test.go
Now we choose the supernodes randomly and fairly. In the actual scenario, the service capabilities of multiple supernodes may be different. And we hope that the machine with good serviceability will be selected more times. So I add a weight configuration for supernode which defined by dfget. 
For now, users can specify the supernode with weight like format: `host:port/weight`. For example:
Using cli flag`dfget  --node 192.168.33.21/2 --node 127.0.0.1/1`
or using config file
```
nodes:
- 192.168.33.21/2
- 127.0.0.1/1 
```
And then the supernode with `192.168.33.21` and the supernode with `127.0.0.1` will be selected in a `2:1` ratio.
NONE.
The host is necessary,  port and weight is optional
Added
Take a look at dfclient.log file and search `do …
> feature: add weight for node config

- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- cmd/supernode/app/root.go
- dfget/config/config_test.go
- dfget/core/core.go
- dfget/core/core_test.go
- dfget/core/downloader/back_downloader/back_downloader.go
- dfget/core/downloader/back_downloader/back_downloader_test.go
- dfget/core/downloader/downloader_test.go
- dfget/core/downloader/p2p_downloader/client_writer_test.go
- dfget/core/helper/test_helper.go
- dfget/core/uploader/peer_server_executor_test.go
- dfget/core/uploader/uploader_util_test.go
- pkg/fileutils/fileutils_test.go
- supernode/config/config_test.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
- supernode/store/store_mgr.go
Signed-off-by: SataQiu <1527062125@qq.com>
Using `path/filepath` instead of `path` for file operations.
fixes #1051
> Using path/filepath instead of path for file operations

- dfdaemon/downloader/dfget/dfget.go
- dfdaemon/downloader/downloader.go
- dfdaemon/transport/transport.go
This change is meant to fix #997. The dfget process is supposed to
be terminated when client closes the connection.
> dfdaemon: specify context when invokes dfget

- pkg/httputils/http_util.go
- pkg/httputils/http_util_test.go
Signed-off-by: fengzixu <hnustphoenix@gmail.com>
For prohibiting the IPv6, we have two methods
1. validate the IP addr which was passed by parameters in dfclient side
2. validate the IP addr in supernode side
Both methods will throw an error when users use the IPv6 address as the IP of dfget.
Before we support the IPv6 in Dragonfly, we can prohibit using IPv6 in dfclient.
> feature: prohibit the IPv6 to communicate with supernode

- supernode/daemon/mgr/cdn/file_meta_data.go
- supernode/daemon/mgr/cdn/path_util.go
- supernode/daemon/mgr/cdn/reporter.go
- supernode/store/local_storage.go
- supernode/store/local_storage_test.go
- supernode/store/storage_driver.go
When we put data to the storage driver, it should be possible to choose whether it's erased firstly if it already exists. So I add a `trunc bool` field in this PR. And for the issue #1055, we should make  `trunc` as true.
fixes #1055
> bugfix: support truncate the file when put

- dfget/core/core.go
- dfget/core/downloader/downloader.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
There is a probability that it will fail when dfget use `p2p` pattern to download the file from supernode. So the `dfget` should try to download from the source station again if the value of the `notbs` flag is false even if failed to download timeout with dragonfly.
NONE.
> feature: try to download from back source even if download timeout with dragonfly

- dfdaemon/config/config.go
- dfdaemon/proxy/proxy.go
- dfdaemon/proxy/proxy_test.go
- dfdaemon/transport/transport.go
I find that there is no config item `direct=true` in `registry_mirror` just like in `proxy`.
It is necessary for us to support this config, because in some cases we want to make some nodes pull image from remote registry directly.
> feature:registry mirror support direct param.

- cmd/dfdaemon/app/root.go
- cmd/dfdaemon/app/root_test.go
- cmd/supernode/app/root.go
- cmd/supernode/app/root_test.go
feature: support init from environment variables for dfdaemon and supernode
Ref:  #959
/cc @Starnop
> feature: support init from environment variables for dfdaemon and supernode

- dfget/core/uploader/peer_server_executor.go
- pkg/fileutils/filelock.go
- pkg/fileutils/filelock_test.go
Add a file lock (lock meta dir) to make sure dfget server process would not be recreated many times by dfget process before the dfserver start up.
#997
> bugfix: avoid creating dup-process of dfget server.

- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
- dfdaemon/proxy/proxy.go
- dfdaemon/proxy/proxy_test.go
Signed-off-by: inoc603 <inoc603@gmail.com>
Allow dfdaemon to redirect proxy request to another host.
fixes #1046 
Start dfdaemon with the following config:
```yaml
proxies:
- regx: google.com
redirect: github.com
```
Use `curl` to verify that the redirect
```
http_proxy=127.0.0.1:65001 curl -v http://google.com
```
> feat(dfdaemon): add redirect to proxy rule

- dfget/core/core.go
- supernode/daemon/mgr/gc/gc_task.go
- supernode/daemon/mgr/mock/mock_progress_mgr.go
- supernode/daemon/mgr/progress/progress_delete.go
- supernode/daemon/mgr/progress_mgr.go
- supernode/daemon/mgr/scheduler/manager.go
> refactor: handle errors gracefully

- dfget/core/uploader/peer_server_executor.go
Meta dir should be locked before `checkPeerServerExist`. Otherwise, any processes that wait for the lock will execute dfget server command again.
fixes #1086
> bugfix: lock file before check server port

- dfget/config/constants.go
- dfget/core/core.go
- dfget/core/downloader/downloader.go
> bugfix: the timeout specified by user should be used firstly

- dfget/core/uploader/peer_server_executor.go
- dfget/core/uploader/uploader.go
> optimize: reduce the waiting time for starting dfget server

- cmd/supernode/app/root.go
The generated doc of supernode by spf13/cobra will display auto-generation tag in cli docs which like this
> ###### Auto generated by spf13/cobra on 29-Nov-2019
We should disable it.
> bugfix: disable displaying auto generation tag in cli docs for supernode

- pkg/netutils/netutils.go
fix the "index out of range" error when the length of speed is 0.
dfdaemon -h
ERRO[0000] parse default net limit error:runtime error: index out of range
panic: value method github.com/dragonflyoss/Dragonfly/pkg/rate.Rate.String called using nil *Rate pointer
goroutine 1 [running]:
github.com/dragonflyoss/Dragonfly/pkg/rate.(*Rate).String(0x0, 0x253, 0x0)
:1 +0x5f
github.com/spf13/pflag.(*FlagSet).VarPF(0xc0001a6600, 0xbd4160, 0x0, 0xae7ace, 0x9, 0x0, 0x0, 0xaeba0c, 0xf, 0xa)
/go/pkg/mod/github.com/spf13/pflag@v1.0.3/flag.go:817 +0x35
github.com/spf13/pflag.(*FlagSet).VarP(...)
/go/pkg/mod/github.com/spf13/pflag@v1.0.3/flag.go:825
github.com/spf13/pflag.(*FlagSet).Var(...)
/go/pkg/mod/github.com/spf13/pflag@v1.0.3/flag.go:806
github.com/dragonflyoss/Dragonfly/cmd/dfdaemon/app.init.1() …
> fix the "index out of range" error when the length of speed is 0.

- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/config/constants.go
The total limit of `dfget` is used to limit downloading speed of all the tasks on the same host. It's designed to be set by user explicitly, it should not be set by default. Otherwise it doesn't work if users only set flag `locallimit` but not set `totallimit`.
> fix: unset the default value of totallimit

- .circleci/config.yml
- .golangci.yml
- .goreleaser.yml
- .travis.yml
- apis/swagger.yml
- docs/config/dfdaemon_config_template.yml
- docs/config/dfget_config_template.yml
- docs/config/supernode_config_template.yml
Sign-off-by: fengzixu  <hnustphoenix@gmail.com>
I add the yamllint tool to check yaml files in Dragonfly, so that we can ensure that their format is legal.
fix https://github.com/dragonflyoss/Dragonfly/issues/1112
> feature: add the yamlint tool to check check all yaml files

- cmd/dfdaemon/app/root.go
- cmd/supernode/app/root.go
- pkg/cmd/config.go
- pkg/printer/printer.go
feature: add 'config default' command to print the default configuration of components
ref: #1069
```sh
dfdaemon config default
dfget config default
supernode config default
```
/cc @Starnop
> feature: add 'config default' command to print the default configuration of components

- apis/swagger.yml
- supernode/server/router.go
- supernode/server/task_bridge.go
modify the v1.0 bridge,We now use the 0.3 bridge and we will use the v1.0 bridge in the future.the v1.0 bridge hasn't been finished,I modify it in this pr
I do the following things:
1. make supernode url in the format `api/v1.*`
2. add some supernode v1.0 bridge 
3. modify previous  supernode v1.0 bridge
refrence #1082 #1114
> feature:modify supernode 1.0 bridge

- dfget/config/supernode_value.go
Fix a typo 'the the' -> 'the' in dfget/config/supernode_value.go
NONE
> fix typo: 'the the' -> 'the'

- supernode/util/range_util_test.go
Add unit test case for func ParsePieceIndex
NONE
go test github.com/dragonflyoss/Dragonfly/supernode/util -run Test -v
> test: add unit test case for func ParsePieceIndex

- dfget/config/supernode_value.go
Fix comment for func ParseNodesString, 'ParseNodesString' -> 'ParseNodesSlice'
NONE
> fix typo: fix comment for func ParseNodesString

- pkg/syncmap/syncmap_test.go
> test: add unit test case for func Remove

- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
StringSliceVar will separated by comma, which is not suitable for field
like Date:Mon, 30 Dec 2019, use StringArrayVar instead
> fix: use StringArrayVar to parse http header

- pkg/syncmap/syncmap_test.go
> test: add unit test case for func GetAsInt

- supernode/daemon/util/filter_test.go
This unit test missed the case of "err pageSize", so add it.
NONE
go test -cover -v github.com/dragonflyoss/Dragonfly/supernode/daemon/util
> test: add test case in unit test TestParseFilter

- pkg/syncmap/syncmap_test.go
> test: add unit test case for func GetAsString

- docs/ecosystem/Harbor-with-Dragonfly.md
> docs: add a doc about using dragonfly with harbor registry

- docs/config/dfdaemon_properties.md
- docs/config/dfget_config_template.yml
- docs/config/dfget_properties.md
- docs/config/supernode_config_template.yml
- docs/config/supernode_properties.md
ref #1094 
I delete the configurations that unused for now.
> docs: optimize the config documents

- dfget/core/core.go
- dfget/core/regist/register.go
- dfget/core/regist/register_test.go
- supernode/daemon/mgr/cdn/manager.go
If supernode is writing to the CDN cache and the source server goes down, the cdn status of task will not be updated failed for now. This PR will fix it.
In addition, if dfget failed to download from `supernode xxx`, it will migrate to other supenodes in the node list of dfget. It's unreasonable to register to the supernode  that just failed, and it will bring a few questions:
+ It doesn't make much sense to try again for the same supernode.
+ The cid of dfgetTask will not change. So two dfgetTask with same cid will be registered on the same supernode, which will cause some data confusion.
fixes #1150
**Attention**
In the meantime, another problem has also been found.
```
dragonfly_supernode_dfgettasks{callsystem="",status="RUNNING"} 1 …
```
> bugfix: update cdn fail when the content is being read and the source server is down

- pkg/constants/dfget_super_code_test.go
> add unit test for GetMsgByCode

- pkg/atomiccount/atomiccount_test.go
Add util test for atomiccount,go.
```
➜  atomiccount git:(add-util-test) go test -v atomiccount_test.go atomiccount.go
=== RUN   Test
OK: 2 passed
--- PASS: Test (0.00s)
PASS
ok      command-line-arguments  (cached)
```
> test: add util test for atomiccount

- cmd/dfdaemon/app/init.go
- cmd/dfget/app/root.go
- cmd/dfget/app/server.go
- docs/config/dfdaemon_config_template.yml
- docs/config/dfdaemon_properties.md
- pkg/dflog/log.go
Signed-off-by: YanzheL lee.yanzhe@yanzhe.org
Currently, there is no option for user to customize the log file path, which causes inconvenience while using `dfclient` in container.
For a typical use case, it is expected that the dfclient container logs to stdout so we can inspect the logs via `docker logs -f <dfclient>` instead of checking the log file in default location `~/.small-dragonfly/logs/dfdaemon.log`
This PR enables user to configure the log file path via configuration property `logConfig.path`.
For example
```yaml
logConfig:
path: /dev/stdout
```
NONE
Already tested in container.
1. Build the dockerfile
2. Add this property in dfclient configuration file
```yaml
logConfig:
path: /dev/stdout
```
3. You will see the log in `stdout` instead of the default location …
> Configure dfclient/dfdaemon/dfget log file path via 'logConfig.path' property

- dfget/core/api/supernode_api.go
- dfget/core/api/supernode_api_test.go
- dfget/core/downloader/p2p_downloader/client_writer.go
Sometimes dfget will fail to report pieces to supernode for some reason, such as supernode cannot handle it. And then supernode will mark that this task has not been completed forever. That's not expected. So we should add a retry mechanism to reduce the chance of errors.
> bugfix: retry multi times if failed to report pieces

- pkg/syncmap/syncmap_test.go
> test: add unit test case for func GetAsBitset

- pkg/syncmap/syncmap_test.go
> test: add unit test case for func GetAsInt64

- pkg/syncmap/syncmap_test.go
Add unit test case for func GetAsTime
NONE
go test github.com/dragonflyoss/Dragonfly/pkg/syncmap -run Test -v
> test: add unit test case for func GetAsTime

- dfdaemon/proxy/cert.go
- dfdaemon/proxy/proxy.go
- go.mod
- go.sum
Signed-off-by: YanzheL <lee.yanzhe@yanzhe.org>
The current implementation of HTTPS hijacking is simple but not correct.
It uses user provided TLS server cert `df.crt` and `df.key` to decrypt HTTPS connection. However, this cert cannot be a CA, which means every TLS connection is encrypted by the same cert from user point of view.
This is not a standard behavior of a HTTPS Man-In-The-Middle proxy, and will cause various issues.
1. The cert used by HTTPS hijacking cannot be automatically verified by applications because the Common Name (or Server-Alternative-Names) is always same and it doesn't match the host of every connection. So user have to configure their applications manually to force-ignore the TLS verification.
This prevents `dfclient` be used as a general system-level HTTPS proxy …
> feature: Hijack HTTPS by generating leaf TLS certs on the fly issued by user provided CA.

- pkg/syncmap/syncmap_test.go
> pkg/syncmap: add unit test for GetAsAtomicInt

- supernode/daemon/mgr/peer/manager_test.go
Add unit test case for func GetAllPeerIDs
NONE
go test github.com/dragonflyoss/Dragonfly/supernode/daemon/mgr/peer -run Test -v
> test: add unit test case for func GetAllPeerIDs

- pkg/errortypes/supernode_errors_test.go
Fix untested unit test case due to prefix missing. The check.Suite requires any method to start with the "Test" prefix. So fix this.
> bugfix: fix untested case due to prefix missing

- pkg/fileutils/fileutils.go
- pkg/fileutils/fileutils_test.go
> pkg/fileutils: add verifications and unit test for SymboliLlink

- cmd/dfget/app/root.go
- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/config/config_test.go
- dfget/config/supernode_value.go
- dfget/config/supernode_value_test.go
> add unit test for NodeWightSlice2StringSlice

- dfdaemon/proxy/proxy.go
cConn should close immediately
> cConn should close immediately

- cmd/dfdaemon/app/cert.go
- cmd/dfdaemon/app/root.go
- pkg/certutils/cert_util.go
- pkg/certutils/cert_util_test.go
feature: add dfdaemon sub command 'gen-ca' for CA generation
Fix : #1207
```sh
dfdaemon gen-ca --common-name dragonflyoss --expire-duration 100h --key-output /tmp/ca.key --cert-output /tmp/ca.crt --overwrite
```
> feature: add dfdaemon sub command 'gen-ca' for CA generation

- dfget/core/core_test.go
Add unit test case for func calculateTimeout in core.go
NONE
go test github.com/dragonflyoss/Dragonfly/dfget/core -run Test -v
> test: add unit test case for core.go

- dfget/core/api/supernode_api_test.go
Add unit test case for func ReportMetrics in supernode_api.go
NONE
go test github.com/dragonflyoss/Dragonfly/dfget/core/api -run Test -v
> test: add unit test case for func ReportMetrics

- ROADMAP.md
- cmd/dfdaemon/app/init.go
- cmd/dfdaemon/app/root.go
- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
- dfdaemon/downloader/downloader.go
- dfdaemon/downloader/p2p/dfclient.go
- dfdaemon/proxy/proxy.go
- dfdaemon/server.go
- dfdaemon/transport/transport.go
In the past, if request the file, dfdaemon should boot the dfget as a progress to register and pull file from peer node. To speed up the p2p download rate, we extract dfget lib as the inner progress in dfdaemon progress.
NONE.
Add test.
> add stream mode which do not up dfget progress.

- dfget/core/api/download_api.go
- dfget/core/api/download_api_test.go
- pkg/rangeutils/range_util.go
- pkg/rangeutils/range_util_test.go
- supernode/daemon/mgr/cdn/downloader.go
- supernode/daemon/mgr/cdn/manager.go
- supernode/daemon/mgr/pieceerror/md5_not_match.go
- supernode/daemon/mgr/task/manager.go
- supernode/daemon/mgr/task/manager_util.go
- supernode/server/0.3_bridge.go
#1213 has support `cdn source` pattern. The download behavior is different when user wants to download a part of the source file, just like:
```bash
dfget -u $url -o /tmp/a.test --header "Range:bytes=1-9000000"
```
1. **download piece from source**: the range of piece get from `supernode` is not the real range of the source file, so `dfget` should correct it based on the _Range_ header passed by user.
2. **download from peer**: the range of piece get from `supernode` is the range of file stored on the other peers, so `dfget` can directly use it.
> fix: cdn-source pattern supports range task

- pkg/dflog/log_test.go
Add unit test case for func WithConsole 
NONE
go test github.com/dragonflyoss/Dragonfly/pkg/dflog -run Test -v
> test: add unit test case for func WithConsole

- apis/swagger.yml
- apis/types/heart_beat_request.go
Update the api of /peer/heartbeat and /peer/network. 
NONE.
no.
> update api definition of /peer/heartbeat and /peer/network

- dfget/types/register_response.go
- dfget/types/report_piece_request.go
- supernode/server/0.3_bridge.go
In seed pattern, add response for seed.
NONE.
> add seed response in seed pattern.

- supernode/daemon/mgr/cdn/super_reader_test.go
Add unit test case for super_reader.go
NONE
> test: add unit test case for super_reader.go

- dfdaemon/seed/manager.go
- dfdaemon/seed/seed.go
- dfdaemon/seed/types.go
define the seed interface. See https://github.com/dragonflyoss/Dragonfly/issues/1284.
NONE.
No need.
> define the interface of seed

- dfdaemon/config/config.go
- dfdaemon/config/config_test.go
modify dfdaemon port validate method, allow to expose more port to listen.
NONE
test case 
dfdaemon/config/config_test.go
Here is a case:
We have a private docker registry, named https://docker.pt.komey.com.
and we want to make our user to None care about the registry address,
So we'd like to config our DNS（docker.pt.komey.com） record for a specific region to 127.0.0.1 and expose dfdaemon on 443 port. Which may make our users have No feeling about the difference between the regions which didn't deploy dragonfly.
> feature: allow dfdaemon to listen port on 0~65535

- dfdaemon/seed/downloader.go
- dfdaemon/seed/downloader_test.go
- dfdaemon/seed/utils.go
- dfdaemon/seed/utils_test.go
- pkg/errortypes/errortypes.go
Add downloader for seed file. Please see refer https://github.com/dragonflyoss/Dragonfly/issues/1284.
NONE.
Add ut.
> add seed downloader

- dfget/config/supernode_value.go
- pkg/algorithm/algorithm.go
- pkg/algorithm/algorithm_test.go
The `GCDSlice` does not consider the situation when the giving slice is nil or empty.
This pr makes it returns 1 when s is empty because that any number divided by 1 is still
itself.
> fix: GCDSlice returns 1 when slice is empty

- pkg/algorithm/algorithm.go
improving algorithm, no recursion, it improves search efficiency without using recursion. 
ref:https://github.com/dragonflyoss/Dragonfly/issues/1306
see issue
> enhancement: improve GCDSlice performance

- dfget/core/downloader/p2p_downloader/client_stream_writer.go
- dfget/core/downloader/p2p_downloader/client_stream_writer_test.go
- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
fixes #1307 
should be merged into branch: `master`, `1.0.x`
> bugfix: notify p2p downloader to pull next piece after reporting

- dfget/config/constants.go
- dfget/locator/locator.go
- dfget/locator/static_locator.go
- dfget/locator/static_locator_test.go
issues: #1293 
This pull request just defines the `SupernodeLocator` interface, I will open another pull request to refactor the dfclient to use this interface to get supernode.
> feature: define the interface SupernodeLocator

- dfget/config/config.go
- dfget/config/config_test.go
> bugfix: infinite loop in dfget/config/config.go#checkOutput

- dfget/config/constants.go
- dfget/config/supernode_value.go
- dfget/core/core.go
- dfget/locator/locator.go
- dfget/locator/static_locator.go
- dfget/locator/static_locator_test.go
* redefine the behavior of method Get: It should return nil before first calling the Next method.
* add method Size to return the number of supernodes
* fix the implementation of StaticLocator
> refactor: redefine the behavior of SupernodeLocator

- client/httpuils_test.go
- dfget/core/api/download_api_test.go
- pkg/atomiccount/atomiccount_test.go
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
Add unit test case
NONE
NONE
NONE
NONE
> Add unit test cases for download_api_test.go&algorithm_test.go&atomiccount_test.go&httpuils_test.go 

- cmd/dfget/app/root_test.go
- dfget/config/config.go
- dfget/core/core.go
- dfget/core/core_test.go
- dfget/core/regist/register.go
- dfget/core/regist/register_test.go
- dfget/locator/locator.go
- dfget/locator/locator_test.go
- dfget/locator/manager.go
- dfget/locator/static_locator.go
- dfget/locator/static_locator_test.go
This pull request uses interface `SupernodeLocator` to refactor the `dfget/core` to get supernode list instead of configurations. 
It also provides a way for users to customized their own `SupernodeLocator` to replace the default implementation, for example:
```golang
package main
import (
"github.com/dragonflyoss/Dragonfly/cmd/dfget/app"
"github.com/dragonflyoss/Dragonfly/dfget/config"
"github.com/dragonflyoss/Dragonfly/dfget/locator"
)
func init() {
// use customized implementation to replace default one
// execute it in the `init` function
// or move it into `main` function, before `app.Execute()`
locator.RegisterLocator(func(cfg *config.Config) locator.SupernodeLocator {
return NewDynamicLocator(cfg)
})
}
// customized implementation of …
```
> refactor: refactor dfget/core with SupernodeLocator

- dfdaemon/seed/cache.go
- dfdaemon/seed/cache_test.go
- pkg/bitmap/bitmap.go
Add implementation for seed cache. Please see refer #1284.
NONE.
Add unit test.
> define cache for seed file in seed pattern

- dfget/locator/locator.go
- dfget/locator/static_locator.go
Providing a way for users to chooses a supernode based on the giving `key`.
> feature: add Select api into SupernodeLocator

- pkg/httputils/http_util.go
- pkg/httputils/http_util_test.go
…ort and add timeout in request context to share the http client.
Optimize the HTTPWithHeaders. When do a http request, share the transport and add timeout in request context to share the http client.
In the early version, if we do a request with HTTPWithHeaders, new transport will be generated every request, which cases a lot of goroutines for cached conn in transport. 
In my unit test, it causes error:
```
go test -race -v
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
```
NONE.
Add ut.
> optimize the HTTPWithHeaders

- supernode/daemon/mgr/cdn/path_util.go
Don't delete the parent directory of the task file, it may delete all the files in the same directory.
For example, there're 2 tasks in the same directory `5cb`:
```
./download
└── 5cb
├── 5cb71a86d65802a16c6bbb03037404b8d745d911157a449ba277dfa927df281f
└── 5cbc448ab2b3b86b4bce66ca0f7994fd01db68c1f487cd3b85e64ff21a37625c
```
The `GC` mechanism or other procedure to delete task `5cb71a86d65802a16c6bbb03037404b8d745d911157a449ba277dfa927df281f`, it will also delete all the files in directory `5cb`.
fixes: #1015 #1011 #970
Issue #810 maybe caused by this,  but not sure according to the logs provided.
> fix: don't delete the parent directory of the task file

- dfget/corev2/basic/types.go
- dfget/corev2/datascheduler/data_scheduler.go
Update types to basic package.
NONE.
No need.
> move some types to basic package

- supernode/server/api/api.go
- supernode/server/api/api_test.go
- supernode/server/api/handler.go
- supernode/server/api/utils.go
- supernode/server/api/utils_test.go
- supernode/server/router.go
define and expose the api register of supernode to make it possible to add APIs outside.
> refactor: define api register of supernode

- dfget/corev2/basic/interface.go
- dfget/corev2/clientwriter/client_writer.go
- dfget/corev2/common/notify.go
Update interface of ClientWriter, add method of Run(). 
NONE.
no need.
> update interface of ClientWriter

- dfget/config/constants.go
- dfget/core/api/supernode_api.go
- dfget/core/helper/test_helper.go
- dfget/types/heartbeat_response.go
Add supernode api for  seed pattern.
NONE.
none.
> add supernode api for seed pattern

- dfget/locator/hashcircler_locator.go
- dfget/locator/hashcircler_locator_test.go
- go.mod
- go.sum
- pkg/algorithm/algorithm.go
- pkg/algorithm/algorithm_test.go
- pkg/hashcircler/hash_circler.go
- pkg/hashcircler/hash_circler_test.go
Add an implementation of SuperNodeLocator. HashCirclerLocator allow Add/Delete supernode, and the deleted supernode will not be selected.
NONE.
add ut.
> add hash circler locator

- Dockerfile
- docs/config/dfdaemon_config_template.yml
fix: remove default registry definition in Dockerfile.
fix: change dfpath default value in dfdaemon config template.
1. CLI的参数优先级大于配置文件的，官方镜像带了--registry参数， 导致使用的时候 必须手动覆盖掉
2. 修改配置文件的文档错误
> fix: remove default registry definition in Dockerfile.

- supernode/daemon/mgr/cdn/downloader.go
- supernode/daemon/mgr/cdn/downloader_test.go
- supernode/httpclient/origin_http_client.go
- supernode/httpclient/origin_http_client_test.go
> bugfix: cdn cannot re-download uncompleted task with header param

- dfget/locator/static_locator_test.go
Add unit test case for static_locator.go
NONE
> test: add unit test case for static_locator.go

- dfget/locator/static_locator.go
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>
> Fix go-lint warning: "exported method ... should have comment or be unexported"

- FAQ.md
- docs/config/README.md
- docs/quick_start/README.md
- docs/user_guide/multi_machines_deployment.md
Update docs and images version
N/A
N/A
N/A
N/A
> Update docs and example image version

- dfget/core/downloader/p2p_downloader/client_stream_writer_test.go
- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/client_writer_test.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
- dfget/core/downloader/p2p_downloader/piece.go
- dfget/core/downloader/p2p_downloader/piece_test.go
- dfget/core/downloader/p2p_downloader/power_client.go
- dfget/core/downloader/p2p_downloader/power_client_test.go
- pkg/pool/buffer_pool.go
- pkg/pool/buffer_pool_test.go
- pkg/pool/writer_pool.go
- pkg/pool/writer_pool_test.go
This pull request uses `sync.Pool` to manager the `bytes.Buffer` and `bufio.Writer` to minimizing the memory allocation and usage.
Here is a comparison when downloading a 10GB file.
before:
```bash
Type: alloc_space
Time: Jul 1, 2020 at 12:53am (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 14.44GB, 99.94% of 14.45GB total
Dropped 74 nodes (cum <= 0.07GB)
Showing top 10 nodes out of 11
flat  flat%   sum%        cum   cum%
12.85GB 88.94% 88.94%    12.85GB 88.94%  bytes.makeSlice
1.59GB 11.00% 99.94%     1.59GB 11.00%  bufio.NewWriterSize (inline)
0     0% 99.94%    12.85GB 88.94%  bytes.(*Buffer).ReadFrom
0     0% 99.94%    12.85GB 88.94%  bytes.(*Buffer).grow
0     0% 99.94% …
```
> optimize: release allocated ByteBuffer explicitly

- docs/user_guide/install_server.md
fix markdown format and make it read easier
> fix format

- cmd/dfdaemon/app/init.go
- docs/user_guide/install_client.md
Signed-off-by: YesterdayxD <1144650984@qq.com>
fix : spelling mistake
> fix : spelling mistake

- pkg/pool/buffer_pool_test.go
- pkg/pool/writer_pool_test.go
Callers should not assume any relation between values passed to `Put` and the values returned by `Get`.
Ref: https://github.com/golang/go/blob/master/src/sync/pool.go#L116-L151
```go
// Get selects an arbitrary item from the Pool, removes it from the
// Pool, and returns it to the caller.
// Get may choose to ignore the pool and treat it as empty.
// Callers should not assume any relation between values passed to Put and
// the values returned by Get.
//
// If Get would otherwise return nil and p.New is non-nil, Get returns
// the result of calling p.New.
func (p *Pool) Get() interface{} {
```
Ref: https://github.com/golang/go/blob/master/src/sync/pool_test.go#L28-L42
```go
// Make sure that the goroutine doesn't migrate to another P
// between Put and Get calls.
Runtime_procPin() …
```
> Fix the bug in unit tests about sync.Pool

- dfget/core/downloader/p2p_downloader/client_stream_writer.go
- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/piece.go
- dfget/core/downloader/p2p_downloader/piece_test.go
when  dfget's `--output` and `--home`  directories are mounted under different disk device, it makes the hard link between them fails to create. At that time, `crossWrite` will be true.
And the same piece will be written to different files twice. Currently the `autoreset` field in piece is always true, so the piece buffer will reset after the first written, then the second written will trigger panic.
fixes #1410
> bugfix: fix dfget panic when crossWrite is true

- dfget/core/downloader/p2p_downloader/client_writer.go
dfget should notify supernode to mark client piece task success after the piece has been download by it.
fixes #1434 
fixes #1392
> bugfix: notify supernode client piece task success under cdn pattern

- docs/user_guide/install_server.md
In the [Start Supernode](https://github.com/qhb1001/Dragonfly/blob/master/docs/user_guide/install_server.md#start-supernode) section of server installation user guide, the environment variable `${supernodeDockerImageId}` is not added into the command below. 
If the default command is executed, the user-defined docker container will not be run. Rather, the official supernode would be started. And I correct the container to be run.
None
docs
> docs: modify the container id to be run in user guide

- .circleci/config.yml
- Dockerfile
- Dockerfile.supernode
- apis/types/preheat_info.go
- hack/build.sh
- supernode/daemon/mgr/preheat/base_preaheater.go
- supernode/daemon/mgr/preheat/base_worker.go
- supernode/daemon/mgr/preheat/file_preaheater.go
- supernode/daemon/mgr/preheat/image_preaheater.go
- supernode/daemon/mgr/preheat/image_preheater_test.go
- supernode/daemon/mgr/preheat/manager.go
- supernode/daemon/mgr/preheat/preheat_progress.go
- supernode/daemon/mgr/preheat/preheat_service.go
- supernode/daemon/mgr/preheat/preheat_task_repository.go
- supernode/daemon/mgr/preheat/preheater.go
- supernode/server/preheat_bridge.go
> add preheat implements

- dfdaemon/exception/errors.go
- dfdaemon/transport/transport.go
bugfix: dfdaemon does not back to source when download failed by dfget
no
N/A
N/A
> bugfix: dfdaemon does not back to source when download failed by dfget

- dfget/core/downloader/p2p_downloader/client_writer.go
bugfix(dfget) fix panic for slice bounds out of range when sendSuccessPiece
NONE
N/A
N/A
panic log:
--2020-09-27 13:58:52--  http://xxx:10086/v1/filecontent?path=/home/yunwei/papapa/1072116196/inventory-20200805160005-shard_2-segment858.idx
dfget version:1.0.4
workspace:/root/.small-dragonfly
sign:18761-1601186332.332
client:xxx connected to node:xxx:8002
start download by dragonfly...
migrated to node:xxx:8002
panic: runtime error: slice bounds out of range
goroutine 68 [running]:
github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader.sendSuccessPiece(0xbbbec0, 0xc000458030, 0xc00009e060, 0x22, 0xc0000e0600, 0x12916dce5, 0xbba4c0, 0xc0000ae548)
\t/go/src/github.com/dragonflyoss/Dragonfly/dfget/core/downloader/p2p_downloader/client_writer.go:294 +0x5f8
created by …
>  bugfix(dfget) fix panic for slice bounds out of range when sendSuccessPiece

- dfget/locator/hashcircler_locator_test.go
Add unit test cases for hashcircler_locator.go
NONE
> test: add unit test case for hashcircler_locator.go

- supernode/httpclient/origin_http_client.go
When CDN is triggered, the supernode will send http request to the sourceUrl to download the file.
If the http response status code is not 200 or 206(e.g. 403), the transport will not be closed.
This PR fixes this bug. 
yes.
Obviously, resp.Body.Close() is always needed.
Providing an file download url which needs authentication (for example, a s3 share link), use dfget to download that file for hundreds of  times.
Then `watch "lsof | grep socket | wc -l"` on the supernode server, lots of sockets will be open even if the dfget tasks are already failed.
none
> bugfix: fix connection leak when statuscode check is not passed

- .goreleaser.yml
- .travis.yml
- Dockerfile.supernode
- Updated the .goreleaser.yml file to generate linux/arm64 binaries.
- Added arm64 job in Travis-CI.
- Replaced dragonflyoss/nginx:apline with nginx:1.19.2-alpine image for supernode image.
Resolves #1486.
> Add ARM64 in goreleaser and Travis-CI

- dfget/core/downloader/p2p_downloader/client_writer.go
- dfget/core/downloader/p2p_downloader/p2p_downloader.go
修复bug或优化，对已经下载完成的片，客户端再次获得supernode调度后，上报当前片成功的状态。
无
下载大文件>=2G，首次下载中（该文件supernode不具备cdn资源，dfclent不具备p2p资源，即客户端与服务端都没有该文件），在dfclent使用p2p下载过程中的某个时刻（此时supernode cdn已填充完毕或者填充过程中），删除supernode的cdn资源，因为资源被删除，此时会引发dfclent下载片http 404，dfclient会上报该片的错误信息，supernode收到错误信息后，会将此文件对应task信息全部清除，清除后，dfclient请求supernode失败后触发迁移（即更换其他supernode再次下载），触发迁移逻辑后，由于结构P2PDownloader的pieceSet未被重新初始化，再次请求调度后，某些片信息被认为是（already downloaded piece）已存在的状态，已存在逻辑中直接跳过了对片的处理，导致某些已存在的片未得到重新汇报success的状态，但其实该文件在客户端已经是完整的，但是supernode没有收到dfclient汇报成功状态导致一直被调度，而调度的片dfclient认为已存在又被跳过，所以陷入了一种死循环的状态，简单理解为 dfclient 认为piece 0 已存在，supernode 认为在dfclient piece 0不存在，当dfclient请求调度后，supernode将 piece 0再次调度。
此问题在，dragonfly 1.01中已稳定复现，在新版本中，由于bug已修复 4bbbc80 fix: delete empty directory in local storage，触发概率将大大降低。
> 修复bug或优化，对已经下载完成的片，客户端再次获得supernode调度后，上报当前片成功的状态。
